### ISSUE TITLE
Improve the Discord.JS docs 

### ISSUE THREAD

**Issue by DoNotSpamPls** [hydrabolt/discord.js#100]
Hello,
This is an enhancement request for discord.js. As the title says, I think the docs need a little bit more improvment, mostly on how to start writing your bot and fixing common errors (I know most of you will say that everyone can do that, but most people are noobs at programming, but they may want to create their own bot too. Try to help them)

**Comment by meew0** [comment]
Regarding the P.S., the [unofficial Discord API server](https://discord.gg/0SBTUU1wZTVPwy6b) is effectively the support server for all APIs, discord.js included.

**Comment by khionu** [comment]
I would like to also point out that people should learn to program before trying to program. If by "noobs" you mean people who have no experience in programming, they need to learn how to before attempting a project meant to be live and used.

Also, the docs are very good, even if lacking in a few areas. Hydra puts a lot of effort into Discord.JS, as we see from the discussions on their channel in the aforementioned Discord Server.

**Comment by TehSeph** [comment]
The docs definitely could use an upgrade, and I agree with the OP in that it would be nice to see the process made easier for people just starting to use the library. A detailed walk-through of the simple ping-pong example would be a great way to explain how the library is designed to be used, while still requiring basic understanding of the core javascript concepts.

**Comment by khionu** [comment]
I think a Ping Pong tutorial would only serve as a streamlined way to learn Discord.JS. I was extremely rusty at programming when I started using it, and I was past that quickly.

**Comment by TehSeph** [comment]
Exactly my point. It would let those who understand javascript know how the library is used, while letting anyone who doesn't understand javascript know that they should start elsewhere before using the library (or more likely send them to the api channel where we will most likely tell them that lol.)

**Comment by khionu** [comment]
Or give them the false hope that they can understand it without prior knowledge :/

**Comment by khionu** [comment]
Technic has robbed me of my eagerness to see the best in people.

**Comment by abalabahaha** [comment]
Looking at the chat for this library's channel in Discord API (Unofficial) has made me lose my faith in people.

From what I've seen, most common errors are actually common Javascript mistakes (easily corrected by Google + StackOverflow), troubles with installation (opus/ffmpeg/node), and the wrong version of NodeJS.

**Comment by khionu** [comment]
Same with Technic, but 64-Bit Java, needing patience, and "you just don't have a good enough computer".

**Comment by macdja38** [comment]
additional voice documentation would be nice.

**Comment by abalabahaha** [comment]
That's implied by "improve docs"

**Comment by meew0** [comment]
Voice documentation has been done in commits https://github.com/hydrabolt/discord.js/commit/5a5316dc66cecfd1dcd6fac021c21ffd6fcf85c7 to 7c0476a.

**Comment by meew0** [comment]
As discussed on Discord, we're going to unlink this issue from the milestone, as the voice docs are done, and keep it open for future doc improvements.

**Comment by noisypixy** [comment]
The only gotcha I've found so far is that the bot isn't ready when the `login` callback is called. I was like 30 minutes trying to figure out why a certain channel couldn't be resolved.

In my case, the bot is a web hook for WordPress. It goes like:

1. There's a new blog entry.
2. WordPress sends a HTTP request to the bot (hosted at Heroku).
3. The bot logs in to Discord, sends a message, and then logs out.

As you can see, it isn't a long-running process. It would be ideal to be able to do this:

```javascript
bot.login(email, pass, function(err) {
  if (err) {
    throw err;
  }

  // Send message.

  bot.logout();
});
```

That's how I was trying to do it at first. It's easier to read, and it looks like it *might* work, but it doesn't. Instead, I had to change it to something like this:

```javascript
bot.once('ready', function() {
  // Send message.

  bot.logout();
});

bot.login(email, pass, function(err) {
  if (err) {
    throw err;
  }
});
```

Although I admit it was *my* mistake for assuming it worked in a certain way, it would be nice if you could add a note about this in the docs for the `login` function. It would have saved me some time.

Thanks.

**Comment by khionu** [comment]
I actually have to agree with Pixy. A number of people don't wait for the onReady event, and it throws them off. Personally, I think it should be implemented into the Library that the events that are related to the Discord Platform itself should wait for the onReady. It's someone everyone should be doing to prevent issues, and there's no reason why they would need to *not* wait.

I mentioned this in chat before, to have onMessage, onPresence, etc, wait for onReady before firing.

**Comment by hydrabolt** [comment]
Do you mean to queue actions until ready is emitted? If so, that's a pretty bad idea in general because it would just bloat up the internals even more. Also, docs are being updated as we speak

**Comment by khionu** [comment]
No, no queue. Just a basic `if(!ready){ return }`, if it's not ready, it should ignore.

**Comment by hydrabolt** [comment]
But that would still bloat up functions, every single "action" function would need a check that just unnecessarily rejects.

**Comment by noisypixy** [comment]
FTR, I have no problem with using the current pattern. I just want a note to be added to the docs, since it wasn't obvious for me at first.

@khionu, you can perfectly do that in your code.

**Comment by khionu** [comment]
..... I'm well aware that I can do that in my own code, I already do it....

**Comment by developerCodex** [comment]
The documentation link is still being rewritten to the newest verison, as people have to do other things in life they can not always get it done right that minute/second.

**Comment by DoNotSpamPls** [comment]
Oh, yeah. I didn't close this.
