### ISSUE TITLE
Collection.reduce is not identical to Array.reduce

### ISSUE THREAD

**Issue by appellation** [hydrabolt/discord.js#1006]
Docs say `Collection.reduce` is identical to `Array.reduce`, but omitting the second parameter in `Collection.reduce` does not start the reduction at the second value with the accumulator set to the first value.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce):

> Note: If initialValue isn't provided, reduce will execute the callback function starting at index 1, skipping the first index. If initialValue is provided, it will start at index 0.

**Comment by Gawdl3y** [comment]
Added in 28ca83011c5775ce0f1c643a261b4138b42a416d.
