### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ekmartin** [hydrabolt/discord.js#102]
Would really help with a `CHANGELOG.md` in the root of the project for future versions, makes it much easier upgrading! More information: http://keepachangelog.com/

**Comment by hydrabolt** [comment]
Yep I'll definitely do this for the next release haha! Thanks!

**Comment by hydrabolt** [comment]
Will add soon, can't this week

**Comment by hydrabolt** [comment]
Added 5.3.0 docs https://github.com/hydrabolt/discord.js/wiki/Changelog

**Comment by TehSeph** [comment]
lol Hydra did you even click his link? :p

**Comment by hydrabolt** [comment]
? I didn't want to make a MD file, I thought it'd be easier to maintain on a wiki

**Comment by ekmartin** [comment]
Looks good! Still think a committed markdown file would be smarter though, as most people who are using your library won't know to look to the wiki to find the changelog when upgrading (plus it can't be edited by anyone, at any time).
