### ISSUE TITLE
Some users in guild return a very incorrect join date

### ISSUE THREAD

**Issue by Doctah** [hydrabolt/discord.js#1022]
This specifically happens when using either `<Member>.joinedAt` or `<Member>.joinedTimestamp`. Sometimes a member will actually have a date that is at epoch, and I'm unsure of why this happens. Before I blamed it on a cache issue but even if I brought the user into cache, it failed to correct itself.

**Comment by hydrabolt** [comment]
Sometimes we are not given the join date of a member, which we can't circumvent. In some cases, the join date will not be accessible.
