### ISSUE TITLE
Choose which port to run.

### ISSUE THREAD

**Issue by igormp** [hydrabolt/discord.js#1029]
When ran, the app just seems to pick a random port to start, and it'd be nice for be to be able to pick a specific port to listen.
It would be useful for something like Heroku, where you need to pass the port as an env var.
I couldn't find any info in the docs nor after skimming trough the code quickly.
Can someone hand a light about this?

**Comment by GusCaplan** [comment]
uhm, everything in discord.js should be using 80 (http) and 443 (https), since all our stuff runs over rest and websockets.

**Comment by igormp** [comment]
Well, a simple lsof shows that it is bound to a port other than 80 or 443, ex:
`lsof -Pan -p 13773 -i`
`COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME`
`node    13773 igor   11u  IPv4 15259991      0t0  TCP 192.168.1.4:51502->104.16.59.37:443 (ESTABLISHED)`
And after every run, it binds to a new port.
So, any idea how can I specify this port?

**Comment by GusCaplan** [comment]
http://lmgtfy.com/?q=how+tcp+works

**Comment by igormp** [comment]
That wasn't really useful...
Anyway, even if it uses 80 or 443 by default, is there a way to change it somewhere?

**Comment by GusCaplan** [comment]
it uses 80 and 443 because that is how http works. you cannot change it.

**Comment by Gawdl3y** [comment]
To change the port, you'd have to ask Hammer & Chisel to change the port Discord's servers run on.
