### ISSUE TITLE
StreamDispatcher Ends before starting.

### ISSUE THREAD

**Issue by TShadowpt** [hydrabolt/discord.js#1033]
Hello, i know this isnt an program issue, its just me but i need help!
I am using the discord js to make a music player and he is saying that the stream is over without even starting :/
here is the code:
```js
if(currStream == undefined){
    const streamOptions = { seek: 0, volume: currVol };
    const stream = ytdl("https://www.youtube.com/watch?v="+videoID, {filter : 'audioonly'});
    currStream = voiceConnection.playStream(stream, streamOptions);
		
   currStream.once("end", () => {
    consoleLog("Music has ended.");
    currStream= undefined;
   });
}
```

**Comment by TShadowpt** [comment]
I discovered that if i end the connection and then rejoin, i can play another music, but this is not a good solution :/

**Comment by iCrawl** [comment]
There's not nearly enough information to even try to replicate that.
We'd need like more of your code than just your dispatcher.

For now all I can tell you is: can't reproduce.

**Comment by hydrabolt** [comment]
We can't reproduce this issue unfortunately.

We're currently working on a lot of voice fixes which might help you, you can test them out using `npm install hydrabolt/discord.js#indev-prism` and then seeing if the update helps you :)

**Comment by TShadowpt** [comment]
@hydrabolt @iCrawl 
I did the update and the bug still continues, its not a problem form my code, i think. If the bot is already connect in a voice channel he cant reproduce more streams he has to reconnect here is a full code for to test
`
const music= new Discord.Client({ fetchAllMembers: false, apiRequestMethod: 'sequential' });
music.login(token);

var currentStream;
var currState= -1;
var queue= ["","",""];

music.on('message', message => {
   
   if(message.content.toUpperCase() === "PLAY"){
      if(currentStream == undefined){
          currState=0;
          playMusic(message.member.voiceChannel;);
      }
   }
}

function playMusic(channel){
     channel.join().then(connection => {
          const streamOptions = { seek: 0, volume: currVol };
          const stream = ytdl(queue[currState], {filter : 'audioonly'});
          currStream = voiceConnection.playStream(stream, streamOptions);
          currStream.once("end", () => {
              consoleLog("Music has ended.");
              currStream= undefined;
              currState++;
           });
     }
}
`

**Comment by GlitchMasta47** [comment]
@TShadowpt As I was reading your code, I did notice a few mistakes that I have laid out in this easy-to-understand box.
> Line 24: consoleLog() is missing the period between "console" and "Log"
> Line 23: currStream.once() should be currStream.on() if music.on() is like it is
> Line 13: Hey, now, what is that ";" doing there before the line ends?

There's probably more stuff wrong with the code, but that's all I have for now.

**Comment by TShadowpt** [comment]
This is not my code this is for you to test,  its just similar to mine. Its not a bug problem form my code... I have it running. Its just a problem of connection. I have to disconnect the bot and connect it again to the channel so i can reproduce another stream! 
English is not my native language but I am trying to be extremely specific :/ sorry

**Comment by qurgh** [comment]
I'm experiencing this same issue. The StreamDispatcher appears to trigger "end" right away. My code:
```
         dispatcher = voiceConnection[msg.channel.guild.name].playFile("./audio/" + rows[0].file);
         if (shuffle["running"] == true) {
             dispatcher.on('end', (reason) => {
                 console.log(reason);
                 updateShuffle(msg);
             });
         }
```

If shuffle["running"] is false, then the file is played correctly. However, if it's true then the song is never played and updateShuffle(msg) is called right away. That function simply picks a new song from a list and then calls the playSong() function that contains the above code. In the console I just see it picking song after song (I have a console.log in updateShuffle()). The "reason" var contains the word "stream", but only after 'end' happens for a second time. The first time it's triggered it will be blank.

Any thoughts as to what is causing this or places to check that could give me more information?

**Comment by GusCaplan** [comment]
`shuffle['running']` can be `shuffle.running`

**Comment by qurgh** [comment]
I changed that, but it didn't make a difference. Any other ideas?
