### ISSUE TITLE
<TextChannel>.sendCode no longer codeblocks

### ISSUE THREAD

**Issue by CyberiumShadow** [hydrabolt/discord.js#1037]
Referring to https://github.com/hydrabolt/discord.js/blob/indev/src/structures/interface/TextBasedChannel.js#L146

and

https://github.com/hydrabolt/discord.js/blob/indev/src/structures/interface/TextBasedChannel.js#L67

and https://github.com/hydrabolt/discord.js/blob/indev/src/client/rest/RESTMethods.js#L49-L53

It appears the grave ticks aren't appended/prepended to the message before being sent to Discord

Whenever the <TextChannel>.sendCode is invoked. It behaves like a regular .send() or .sendMessage()

**Comment by CyberiumShadow** [comment]
Fixed in https://github.com/hydrabolt/discord.js/commit/75d45bd587c1d68039c999d12bc928f3df696f34

**Comment by hydrabolt** [comment]
Came around due to https://github.com/hydrabolt/discord.js/pull/1026
