### ISSUE TITLE
Using User.displayAvatarURL or User.defaultAvatarURL TypeErrors

### ISSUE THREAD

**Issue by Visate** [hydrabolt/discord.js#1044]
[Stacktrace](https://puu.sh/t5vAr/51074e991c.png)

```js
bot.on("message", message => {
  message.channel.sendMessage(message.author.displayAvatarURL);
});
```

**Comment by iCrawl** [comment]
Make sure you are on the latest release.

**Comment by Visate** [comment]
Stable or master?

**Comment by iCrawl** [comment]
Stable should be fine if you use github to pull your updates.
Otherwise the npm version is fine too.

**Comment by Visate** [comment]
I'm pretty sure I'm using stable, just did a npm install and got discord.js@11.0.0

**Comment by iCrawl** [comment]
What Node version do you have? Object.values() is behind the --harmony flag in Node 6.
Its stable in Node 7.

**Comment by Visate** [comment]
OH. Okay that would explain it then. Thanks!

**Comment by iCrawl** [comment]
Fixed in f0adf8f1223101b537548e5b60e70d85a7b9327f

**Comment by MeLlamoPablo** [comment]
@iCrawl any ideas about when will this be published to npm? Typescript is giving an "Cannot find module error" for modules installed through GitHub; the npm version works fine.

**Comment by Gawdl3y** [comment]
Try it without specifying the branch. (`npm i -S hydrabolt/discord.js`)
