### ISSUE TITLE
clientUser#setAvatar no loner work with a buffer

### ISSUE THREAD

**Issue by markni** [hydrabolt/discord.js#1047]
[new changes](https://github.com/hydrabolt/discord.js/blob/indev-prism/src/structures/ClientUser.js#L119) in #819 in clientUser#setAvatar assume parameter `avatar` is a string with string method `startsWith`,  this result in `TypeError: avatar.startsWith is not a function` when pass in a buffer. 

The doc still say support buffer as a parameter: https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setAvatar

**Comment by GusCaplan** [comment]
fixed in #1048
