### ISSUE TITLE
TypeError: Discord.RichEmbed is not a constructor

### ISSUE THREAD

**Issue by dayxhep** [hydrabolt/discord.js#1050]
Hi there,

I'm using Discord.js 11.0.0,

```js
var client  = new Discord.Client();
console.log(new Discord.RichEmbed({}));
```
Is returning me an error 
```
console.log(new Discord.RichEmbed({}));
            ^
TypeError: Discord.RichEmbed is not a constructor
    at Object.<anonymous> (/root/workspace/bots/lycana/index.js:19:13)
```
The client is succesfully created bot not the RichEmbed
refering to the doc
```js
new Discord.RichEmbed(data);
```
Should work : https://discord.js.org/#/docs/main/11.0.0/class/RichEmbed

Edit:
Same problem with
```js
var client  = new Discord.Client();
var emb = new Discord.RichEmbed();
```

**Comment by dayxhep** [comment]
Re-updating Discord.js throught `npm install` worked

**Comment by Slamakans** [comment]
https://discord.gg/bRCvFy9
You should join the Discord.js Official server if you encounter any further problems, or actually, do it even if you don't ¯\_(ツ)_/¯

**Comment by Andrew-9** [comment]
I'm having the same problem. what do I do?

**Comment by Papaia** [comment]
What???
You just replied to a three year old issue.
Also, please move to the Discord server, I think I know what caused this.
