### ISSUE TITLE
Positioning for embed fields?

### ISSUE THREAD

**Issue by GlitchMasta47** [hydrabolt/discord.js#1051]
Normally, discord.js embeds with multiple fields go straight up and down like this:
![image](https://cloud.githubusercontent.com/assets/17860556/21574343/14e85da0-ceb7-11e6-9f7d-ae8b456204e9.png)
However, I have seen some bots do them in different positions like these:
![image](https://cloud.githubusercontent.com/assets/17860556/21574351/32cc92fa-ceb7-11e6-8562-f3f8f8b78775.png)
![image](https://cloud.githubusercontent.com/assets/17860556/21574428/3935a752-ceb8-11e6-98b3-e1a04a16f332.png)

Is there some kind of position property available to fields, or are these only possible with other platforms? Thanks for your reply.

**Comment by hkwu** [comment]
Set the `inline` property of your fields to false.

**Comment by GlitchMasta47** [comment]
Thanks.
