### ISSUE TITLE
Discord.js.org website is now down

### ISSUE THREAD

**Issue by GlitchMasta47** [hydrabolt/discord.js#1052]
This isn't much of an issue, but just to let the devs know that the CNAME was removed from the `gh-pages`  branch. It is not located at the default `hydrabolt.com/discord.js/` or `hydrabolt.discord.io/discord.js/`

**Comment by iCrawl** [comment]
We are very well aware. And its getting moved into its own repository.

A PR already exists on the js.org repo too.

https://github.com/hydrabolt/discord.js-site
https://github.com/js-org/dns.js.org/pull/983

**Comment by GlitchMasta47** [comment]
Thanks for your confirmation. This will stay open for the remainder of maintenance time for people also wondering. As soon as relocation is over, I will go ahead and close the issue.

**Comment by FNCxPro** [comment]
@GlitchMasta47 it appears to work now.

**Comment by PgBiel** [comment]
It's up, someone should close this
