### ISSUE TITLE
Cannot set avatar for bot using setAvatar()

### ISSUE THREAD

**Issue by CharlotteDunois** [hydrabolt/discord.js#1054]
Hello

I am facing an issue with the `client.user.setAvatar` command. I am using discord.js v11.0.0 and I've crawled through some already existing issues on this topic here (#446, #284, #260). Also I applied the patch [`258e4b9`](https://github.com/hydrabolt/discord.js/commit/258e4b90859dc8daff12457d25ba09892d3c37ff) manually.

Everytime I try to set an avatar, my bot just gets an empty "placeholder", instead of the image I try to set. No errors are thrown or shown in console.

With empty placeholder, I mean this:
![empty placeholder](https://i.imgur.com/TJudRso.png)

The current code looks like this:

    if(message.content.indexOf(prefix+'setavatar') === 0) {
        request.get(message.content.substr(11)).pipe(fs.createWriteStream('./setavatar.png'));
        client.user.setAvatar(fs.readFileSync('./setavatar.png')).then(user => { message.channel.send('✔ Operation successful'); console.log('New Avatar set!'); })
            .catch((error) => { message.channel.send('× Operation failed'); console.log('Error on setavatar command:', error); });
        
        return;
    }

I also tried to update the avatar using the `base64`-encoded string representation, but this doesn't change the outcome. For reference, this was code for it:

    var bl = new BufferList();
    request({ uri: message.content.substr(11), responseBodyStream: bl}, function (error, response, body) {
        if (error === null && response.statusCode == 200) {
            var data_uri_prefix = "data:" + response.headers['content-type'] + ";base64,";
            var image = new Buffer(bl.toString(), 'binary').toString('base64');                                                                                                                                                                 
            image = data_uri_prefix + image;
            client.user.setAvatar(image).then(user => { message.channel.send('✔ Operation successful'); console.log('New Avatar set!'); })
            .catch((err) => { message.channel.send('× Operation failed'); console.log('Error on setavatar command:', err); });
        } else {
            message.channel.send('× Operation failed');
            console.log('Error on setavatar command:', error);
        }
    });

I see the image in the folder without any issues, so it's not the image. Also using a different image does not change the outcome.

Is there something wrong with the library or do I do something wrong?

Thanks for your help.

**Comment by ItsJordan** [comment]
`client.user.setAvatar('imageurl');`

**Comment by ItsJordan** [comment]
Also `client.user.setAvatar('local file path')`

**Comment by CharlotteDunois** [comment]
Issue was resolved with using `imageurl`. Though I'm still curious why it didn't work with `fs.readFileSync`, maybe someone has a lead.

**Comment by barbarbar338** [comment]
if (message.content === "botavatar") client.user.setAvatar('./avatar.png');
