### ISSUE TITLE
Email and Password bot.login()

### ISSUE THREAD

**Issue by Monochromefx** [hydrabolt/discord.js#1055]
I don't know if, I'm the only one experiencing this but. The `bot.login()` function, doesn't work
when I pass my email and password for the bot, however. It only takes the token parameter, Is this a possible problem or is it just me?
I have the latest version of Discord.js 11.0.0
And the latest version of Node v7.3.0

**Comment by iCrawl** [comment]
Email and password as a login method is not valid anymore.

Use a token to login at all times.
