### ISSUE TITLE
Unable to react to message "Unknown Emoji"

### ISSUE THREAD

**Issue by SquirrelsMcGee** [hydrabolt/discord.js#1057]
Tried using both raw emoji like 🍰, as well as emoji codes such as "alien" and :regional_indicator_l:, does not work for any.
Tested on Windows 10 and Ubuntu 14.04.5 LTS, same result each time

**Comment by GusCaplan** [comment]
unable to reproduce, here is a screenshot of it working ![](https://i.gus.host/9LqYpk)

**Comment by SquirrelsMcGee** [comment]
Found the issue, default encoding when saving files using Visual Studio 2017 is not unicode, and so emoji characters aren't saved properly. Not a bug with Discord.js
