### ISSUE TITLE
Listing users currently in a voice channel.

### ISSUE THREAD

**Issue by cpancake** [hydrabolt/discord.js#106]
I'm trying to get a list of users that are currently in a voice channel, but there doesn't seem to be a way to do this. For text channels you can get a list of members of the server and check the permissions of each one, but this doesn't work for voice channels.

**Comment by TehSeph** [comment]
This is not a feature yet, no, and I 100% agree it should be! +1

**Comment by hydrabolt** [comment]
Added in a6a9f085655237fb668af642907d519ded14b5ff, very sorry not to accept your PR howver!
