### ISSUE TITLE
presenceUpdate event - old and new presences are always identical 

### ISSUE THREAD

**Issue by FluxMonkey92** [hydrabolt/discord.js#1067]
Both old and new presences always appear to be identical.
```javascript
bot.on('presenceUpdate', (oldMember, newMember) => {
  console.log('old:');
  console.log(oldMember.user.presence);
  console.log('new:');
  console.log(newMember.user.presence);
});
```
gives this:
![image](https://cloud.githubusercontent.com/assets/14254955/21738375/bb6721ba-d47b-11e6-985f-d9688364fd74.png)

**Comment by hydrabolt** [comment]
You need `oldMember.presence`, not `oldMember.user.presence`
