### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined on Message.edit after messageReactionAdd

### ISSUE THREAD

**Issue by JSeed** [hydrabolt/discord.js#1071]
When using Message.edit on a message passed from the 'messageReactionAdd' event I catch the following error: 
```
Error: TypeError: Cannot read property 'name' of undefined
    at new MessageReaction (D:\Projects\Polly\node_modules\discord.js\src\structures\MessageReaction.js:34:48)
    at Message.patch (D:\Projects\Polly\node_modules\discord.js\src\structures\Message.js:231:34)
    at MessageUpdateAction.handle (D:\Projects\Polly\node_modules\discord.js\src\client\actions\MessageUpdate.js:14:17)
    at rest.makeRequest.then.data (D:\Projects\Polly\node_modules\discord.js\src\client\rest\RESTMethods.js:96:55)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
The reactions still appear as expected in the discord ui, but on following invocations of the same event, the MessageReaction.count field is incorrect.

**Comment by iCrawl** [comment]
What is `name` and where do you apply that property to?

**Comment by JSeed** [comment]
`name` isnt mine.  Judging by the call stack I'd say it's a property of the Emoji belonging to MessageReaction.
My calling code is 
```message.edit(newPoll).catch(console.error);```
Where `newPoll` is a string and `message` is the Message object passed by the `messageReactionAdd` event. Most of the rest of the handler code is string manipulation and has nothing to do with the library.

I threw a few simple logging statements in some of the functions referenced in the call stack, it seems that when I was calling `Message.edit` it was running `MessageUpdateAction.handle`, `Message.patch`, and the `MessageReaction` constructor twice, once with valid reactions, and once with reactions set to undefined.

**Comment by PgBiel** [comment]
`messageReactionAdd` does not have `message` as parameter, it has the reaction and the emoji. I'm assuming you are using `reaction.message`, though?

**Comment by PgBiel** [comment]
(P.S. Ik the names don't matter I'm just saying that it has no Message object)

**Comment by JSeed** [comment]
Yes my apologies, it is `MessageReaction.message`,  I have updated my previous comment for future clarity.
