### ISSUE TITLE
Repeated unhandled promise rejection(Forbidden) after bot leaves server

### ISSUE THREAD

**Issue by JMTK** [hydrabolt/discord.js#1076]
Hi all,

Running indev-prism as of January 8th on node 6.6. 

I can't reliably reproduce this but I noticed when the bot sometimes leaves a guild, I get an infinite list of unhandled promise rejections(it eventually got a SIGSEG fault). These happen every 3 seconds or so. I don't have any unhandled promises as far as I know(grepped and scanned my code to make sure). My event handler for my leave server is just a couple of logs, no Discord API actions.

Here's a screenshot from my logs:
[http://puu.sh/tfsCg/ced82839c3.png](http://puu.sh/tfsCg/ced82839c3.png)

I can say it seems to mitigate the issue temporarily once the bot joins another server again. My bot is in a large amount of servers (>1000) if it makes a difference. It happens on all node 6/7 versions. It keeps trying to run whatever it is constantly after this, but it doesn't seem to inhibit normal bot actions until it seg faulted on me after a couple hours of doing this.

I asked around but most in the DiscordJS server seemed to think it was on my end. I'll keep looking.

**Comment by Programmix** [comment]
Is it possible that you're repeatedly trying to execute some action on the server after the bot leaves a guild? I more or less doubt that the library itself would try to execute any actions on the guild that would land it forbidden errors. This seems like more of a user error, but it could very well be a library issue.

**Comment by JMTK** [comment]
I am not, I didn't even have a guildDelete event handler before I tried debugging this issue. I grepped a setInterval/setTimeout and I saw a couple places for "heartbeat". I also double checked to make sure all of my promises were being handled properly. I'm going to see if it happens while there's a voice connection.

**Comment by hydrabolt** [comment]
I have noticed a similar issue running my own test script, however my bot will only produce one Forbidden error so I assumed it was another part of my test script. I'll check this out, thanks for making us aware!

**Comment by Gawdl3y** [comment]
```js
process.on('unhandledRejection', console.error);
```

This will give you more useful info.

**Comment by bgsteiner** [comment]
I can confirm the same issue on my server running node v7.4.0 it appears to be a depreciation of some of the promise methods used in the api.
`(node:7336) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Forbidden
(node:7336) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by PgBiel** [comment]
No promise methods are deprecated, that warning is that unhandled promise rejections that are deprecated, not the methods. Like, promises without `.catch()`.

**Comment by Gawdl3y** [comment]
Please reproduce the issue with [this](https://github.com/hydrabolt/discord.js/issues/1076#issuecomment-271183802), so that we can get more information.

**Comment by JMTK** [comment]
I got latest indev-prism from today(1/14)

The unhandled promise promise was
```
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Not Found
    at Request.callback (/home/jam/discordbot/node_modules/superagent/lib/node/index.js:649:11)
    at /home/jam/discordbot/node_modules/superagent/lib/node/index.js:856:18
    at IncomingMessage.<anonymous> (/home/jam/discordbot/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The Discord API response error was this at the end of the full response.
```     error:$
      { Error: cannot POST /api/v6/channels/269744122842054656/typing (404)
          at Response.toError (/home/jam/discordbot/node_modules/superagent/lib/node/response.js:95:13)
          at ResponseBase._setStatusProperties (/home/jam/discordbot/node_modules/superagent/lib/response-base.js:122:16)
          at new Response (/home/jam/discordbot/node_modules/superagent/lib/node/response.js:41:8)
          at Request._emitResponse (/home/jam/discordbot/node_modules/superagent/lib/node/index.js:711:20)
          at /home/jam/discordbot/node_modules/superagent/lib/node/index.js:856:38
          at IncomingMessage.<anonymous> (/home/jam/discordbot/node_modules/superagent/lib/node/parsers/json.js:16:7)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        status: 404,
        text: '{"code": 10003, "message": "Unknown Channel"}',
        method: 'POST',
        path: '/api/v6/channels/269744122842054656/typing' },
```

Sorry I wasn't able to get it sooner, I have to switch my bot over to it and let it run for a while. So is it a typing issue on my end? Do I need to force stopTyping somewhere? I can say it only happens after leaving a server, that part seems consistent. But when I test it on my test bot that only has 1 server, it doesn't do it. Not sure what causes it.

**Comment by GusCaplan** [comment]
we do not ever post to typing automatically. If typing is being run, that is on you.

**Comment by JMTK** [comment]
Yeah it seems that was the issue. I just had to loop through all the text channels to make sure it wasn't typing anymore. I have a feeling others might run into this issue at some point because if you fail to handle this in the `guildDelete` event, it never stops.

I'm not sure if this still constitutes as a bug. Feel free to close it if the final say is that it's on the developer not the library.

**Comment by GusCaplan** [comment]
handled in #1096
