### ISSUE TITLE
Error with const stream = ytdl();

### ISSUE THREAD

**Issue by generalmd2** [hydrabolt/discord.js#1082]
Hello, 

 I discovered a bug here : https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=playStream

The worry is that the music stops at 10 seconds. An error with ytdl.

Original code : 

`const stream = ytdl('https://www.youtube.com/watch?v=XAWgeLF9EVQ', {filter : 'audioonly'});`

New Code (test with Discord.js 11.0) :

 `const stream = ytdl(URLyoutube);`

A problem with the filter who bug and stop the music. 

Cordially.

**Comment by vzwGrey** [comment]
Uhm, that's not how you specify the filters for ytdl-core.
You'll want to use `{ audioonly: true }` to set the `audioonly` filter.
The `filter` property seems to be for custom filter functions, which you're not using.

**Comment by meew0** [comment]
[ytdl's documentation](https://github.com/fent/node-ytdl-core#ytdlurl-options) suggests that the code from the docs (with `filter: 'audioonly'`) is actually correct.
