### ISSUE TITLE
 Write new members in a text room

### ISSUE THREAD

**Issue by generalmd2** [hydrabolt/discord.js#1084]
Hello
I would like to know how to put this: `console.log(`${m.user.username} a rejoins le serveur ${m.guild.name}`);` in the default room.

I found : https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=defaultChannel
but I do not know how to achieve this (my bot is on several servers and administrator rights).

Help pls :'(

**Comment by Sowce** [comment]
bot.on('guildMemberAdd', member => {
  member.guild.defaultChannel.sendMessage(`${member} a rejoint le serveur ${member.guild.name}`);
}

**Comment by generalmd2** [comment]
verry thanks :)
