### ISSUE TITLE
code wont work

### ISSUE THREAD

**Issue by towe102** [hydrabolt/discord.js#1085]
// You need this line to authorize a bot to join your channel.
// https://discordapp.com/oauth2/authorize?&client_id=174554870668328960&scope=bot&permissions=0

// implement lodash merge.

console.log('Let\'s get this party started!');

// Websocket Settings & Connection
var Client = require('wsabi-client-bacon');
var client = new Client('wss://realtime.beam.pro');

// Custom Events
var events = require('events');
var eventEmitter = new events.EventEmitter();
eventEmitter.on('online', onlineMessage);

// Discord Settings
var Discord = require("discord.js");
var firebot = new Discord.Client();
var firebotToken = require("./config.json").firebotToken;

// Build the Team Array
// Takes all team members and builds a json object then throws it in an array.
function teamArray() {
    var teamID = require("./config.json").beamTeamID;
    var teamURL = "/api/v1/teams/" + teamID + "/users";
    client.get(teamURL).then(function (response) {
        // Build the team array
        teamArray = [];
        for (var i = 0; i < response.length; i++) {
            var element = response[i];
            var cID = element.channel.id;
            var cName = element.username;
            var cOnline = element.channel.online;
            var cCurrentViewers = element.channel.viewersCurrent;
            var cViewersTotal = element.channel.viewersTotal;
            var cFollowers = element.channel.numFollowers;
            var date = 0;
            var streamer = {
                "id": cID,
                "name": cName,
                "slug": "channel:" + cID + ":update",
                "online": cOnline,
                "lastOnline": date,
                "currentViewers": cCurrentViewers,
                "viewersTotal": cViewersTotal,
                "numFollowers": cFollowers,
                "maxViewers": 0
            };
            teamArray.push(streamer);
        }
        // After array is build, start getting updates via websocket.
        beamUpdates(teamArray);
    });
}

// Beam Channel Online Status
// Loops through array and subs to websocket for channel updates.
function beamUpdates(teamArray) {
    for (var i = 0; i < teamArray.length; i++) {
        (function (i) {
            setTimeout(function () {
                var cID = teamArray[i].id;
                var cName = teamArray[i].name;
                var updateSlug = teamArray[i].slug;
                console.log(cName + '#' + cID + ' has jacked into the matrix.');
                client.live(updateSlug).then(function (response) {
                    response.onValue(function (data) {
                        //console.log(cName, data);
                        arrayUpdater(cName, data, teamArray);
                    });
                });
            }, 250 * i);
        }(i));
    }
}

// Array Update Handler
// Handles all of the websocket info and updating the streamer array.
// Emits events when certain things need to trigger such as online messages.
function arrayUpdater(cName, data, teamArray) {

    // Find the correct person and set them as variable streamer.
    for (var i = 0; i < teamArray.length; i++) {
        if (teamArray[i].name == cName) {
            var streamer = teamArray[i];
        }
    }

    // Update viewer counts.
    if (data.viewersCurrent !== undefined) {
        streamer.viewersCurrent = data.viewersCurrent;
        // Update Max Viewers
        if (data.viewersCurrent > streamer.maxViewers) {
            streamer.maxViewers = data.viewersCurrent;
        }
    }

    // Update online status
    if (data.online !== undefined && data.online !== streamer.online) {
        streamer.online = data.online;
        eventEmitter.emit('online', cName, streamer.online);
        //console.log('Emitting online event for '+cName+'.');
    }

    // Update Viewer Totals
    if (data.viewersTotal !== undefined) {
        streamer.viewersTotal = data.viewersTotal;

    }

    // Update Follower Totals
    if (data.numFollowers !== undefined) {
        streamer.numFollowers = data.numFollowers;
    }
}

// Channel Online Broadcast
// Grab game and title info when a channel goes online then post a message to a discord channel.
function onlineMessage(cName, onlineStatus) {
    // Find the correct person and set them as variable streamer.
    for (var i = 0; i < teamArray.length; i++) {
        if (teamArray[i].name == cName) {
            var streamer = teamArray[i];
        }
    }

    //console.log(streamer)

    var lastOnline = streamer.lastOnline;
    var date = new Date().getTime();

    // If the streamer is going online and the last online message was sent more than 5 hours ago...
    if (onlineStatus === true && Math.floor((date - lastOnline)) > 18000000) {
        // Get channel info to use in message.
        var streamURL = '/api/v1/channels/' + cName + '?fields=id,token,name,type';
        client.get(streamURL).then(function (response) {
            var channelID = response.id;
            var cName = response.token;
            var cTitle = response.name;
            if (response.type !== null || response.type !== undefined) {
                var cGame = response.type.name;
            } else {
                var cGame = "No Game Set";
            }

            console.log('Sending online status message for ' + cName + '.');
            var aChannel = require("./config.json").discordOnlineChannel;
            for (var i = 0; i < aChannel.length; i++) {
                var channel = aChannel[i];
                firebot.sendMessage(channel, cName + ' is live with ' + cGame + ' -> ' + cTitle + ' -> https://beam.pro/' + cName, function () {
                    console.log('Message sent.');
                });
            }

            streamer.lastOnline = date;
        });
    } else if (onlineStatus === true && Math.floor((date - lastOnline)) < 18000000) {
        console.log(cName + ' was online too recently. No message sent.');
    } else if (onlineStatus === false) {
        console.log(cName + ' has gone offline.');
    }
}

// Chat Command Functions
firebot.on("message", function (message) {
    var messageSender = message.author.username;
    var messageCmd = message.content.split(" ")[0].substring(1).toLowerCase();
    var messageParam = message.content.substring(messageCmd.length + 2);
    if (message.content[0] === "!" && message.author.id != firebot.user.id) {
        if (message.author.equals(firebot.user)) {
            return;
        } else {
            // Commands go here and look like this...
            if (messageCmd == "testsend") {

            } else {

            }
        }
    }
});

// When the bot is ready...
firebot.on("ready", function () {
    teamArray();
});

// On error, wait 5 minutes and try again.
client.socket.on("error", function (err) {
    console.log('Error! Trying to reconnect in 5 minutes.');
    console.log(err);
    setTimeout(function () {
        var client = new Client('wss://realtime.beam.pro');
    }, 300000);
});

// Login
// Make sure this is after everything else.
client.login(firebotToken);
    if (error !== null) {
        console.log('Error: ' + error);
        console.log('Token: ' + token);
    } else {
        console.log('Logged in and ready to kick ass.');
    }
// When websocket drops, login to discord again.
client.socket.on("reopen", function () {
    client.login(firebotToken, (error, token));
    if (error !== null) {
        console.log('Error: ' + error);
        console.log('Token: ' + token);
    } else {
        console.log('Reconnected to websocket.');
    }
});

**Comment by hydrabolt** [comment]
Not the place

**Comment by motiond3v** [comment]
you put 'client' in a few places, instead of firebot.
