### ISSUE TITLE
<Client>.presences doesn't seem to return the Presences of all of the user's friends

### ISSUE THREAD

**Issue by flaw600** [hydrabolt/discord.js#1092]
I noticed when developing my bot that `<Client>.presences` doesn't seem to return the Presences of all of my friends, but instead merely a subset of them. I raised this question in the Discord.JS Discord server. I was advised to set fetchAllMembers to true as an option, but that was not able to resolve the issue. I noticed the error by running `console.log(bot.user.friends)` and `console.log(bot.preseces)` and noticed that they were not returning the same number/same ID's/Users/etc (where bot refers to <Client>). From my understand of the way the docs describe the property, the property should contain the Presences of all of my friends and was unable to resolve the issue in chat and was told that opening this issue would be a good idea. Please let me know what information you need and I will do my best to provide it. Thank you!

**Comment by hydrabolt** [comment]
If a friend is offline they might not have a presence, are the missing presences from users that are offline?

**Comment by flaw600** [comment]
Well, from what I understand of the docs, 'offline' is a valid `<Presence>.status` so should it not get those Presences? As to your question, it seems to be returning the same ID's rather than focusing on whether the user is offline, as some of the User Presences that it returns are offline. So I don't think that it focuses solely on online users, although yes in this instance the ID's that it does not return are offline (however, in the example shown below, some of the ones offline now did return as online earlier).

An example of what `<Client>.presences` returns: (scrubbing out ID's)
```Collection {
Presence { status: 'online', game: 'null' },
Presence { status: 'idle', game: 'null' },
Presence { status: 'offline', game: 'null' },
Presence { status: 'offline', game: 'null' },
Presence { status: 'offline', game: 'null' },
_array: null,
keyAray: (scrubbed out) }```

As can be seen, some of the returned Presences have a status of offline. I think that the ID's returned are the same each time it's called, but the way that I have the logs setup and the app deployed make it a pain to confirm that. Even setting `fetchAllMembers` to true doesn't fix the issue.

**Comment by GusCaplan** [comment]
users and members are not the same thing. You can fetch members all day and not get all the *users* your bot can see cached. the only way to do that is to use `client#fetchUser` which will return the user and add them to the cache. As for docs on valid presence objects, that refers to outgoing (setting your own presence) and does not necessarily represent what you might receive, since discord can and will do freaky things with their api.

**Comment by flaw600** [comment]
@GusCaplan fair enough, except I cannot use `<Client>.fetchUser` since `<Client>.presences` only works on a selfbot and `fetchUser` only works on true bot accounts. As for the cache, if `<Client>.presences` relies on the cache, then it would be nice if that warning was added to the docs since other properties and methods that rely on the cache have that warning. At present, the description for `presences` doesn't give any qualifications to what data will be excluded, merely saying that it returns the `Presences` for all of the friends of the logged in user. So I suppose my question is then whether `presences` relies on the cache, and if so, how can a selfbot add a user/friend to that cache? My second question is then also how those 6 users in the example above got into my cache as I never fetched any of them, nor do I share any guilds/servers with them (so essentially, I suppose this question is about how the cache works and why users would appear in the cache when never fetched or interacted with)

**Comment by hydrabolt** [comment]
While offline is a valid presence, Discord doesn't send us the presence if the user is offline at the time of ready (it is assumed they are offline), so we technically never cache a presence in `client.presences`, if there is no presence available when calling `user.presence`, we just make a temporary blank offline presence, which isn't added to `client.presences`.

It is still possible to get `offline` presences from users that may have been online at some point, creating a presence in the cache, and then going offline. Do you think this is possible? It'd be useful if you could see whether even users that are online at the time of ready are not cached.

**Comment by flaw600** [comment]
For `client.presences` is the only time that a user isn't added to the cache when the user is offline at 'ready'? If so, could Presences not be added to `<client>.presences` where users not currently in `client.presences` but are in `client.user.friends` obtain a Presence of `{ status: 'offline,' game: 'null' } at the time of call?

As for getting offline presences from users that were online at some point, are you suggesting that I wait for a friend to come online (at which point the Presence should be online)? While I could do that, it would rather defeat the purpose for my usecase, as for my usecase I care about the transition of a friend from offline to any other status, so if I were to do your suggestion I'd have no need to use `<client>.presences` if I understood you correctly. Moreover, it seems like a rather significant workaround for a property that implies to have the Presence for all the friends of the logged in user. Admittedly, I'm new, but at the very least it would be nice to have a warning stating that `Client.presences` may not contain Presences from users who were offline at the time of ready instead of implying that it will have the Presence of all the friends.

So my questions are: can Presences be added to `<Client>.presences` such that any user not in `presences` but in `client.user.friends` gets a Presence of offline, null respectively at the time of call in Discord.JS? This would fulfill the implied description made in the docs, from my understanding. If not, can your workaround be implemented in Discord.JS itself? As for your request, I'll keep an eye out for online users not being cached. As a note, I've enabled deeper logging for my bot, and noticed that I'm now getting inaccurate statuses. Currently, I have 3 online friends and `client.presences` reports that I have 4 online friends

**Comment by flaw600** [comment]
@hydrabolt is this code block supposed to return accurately?
```
    let friends = bot.user.friends;
    friends.keyArray().forEach((val) => {
        friends.get(val).presence;
    });
```
It seems to be returning accurately for me now, so if this is a valid way, could it be done this way as a standard? I ask this for knowledge purposes of course, as I'm not intimately familiar with how the Discord API works. So far, `<Client>.presences` is returning offline presences for Users that are in the cache because they were once online and it doesn't seem to be missing online presences so far, as you asked for.

**Comment by hydrabolt** [comment]
That would be a correct way to do it :)

I'll close this issue now that some confusion has been cleared up and it seems to be resolved.

**Comment by hydrabolt** [comment]
It's also reassuring that no online presences are missed, which means that the API definitely doesn't send presences for offline friends in ready, as it should be assumed they are offline if they do not have a presence; that is how `user.presence` operates.

**Comment by flaw600** [comment]
@hydrabolt Well, the confusion hasn't really been resolved. At present `<Client>.presences` doesn't produce all the presences of the friends of the logged in User as the docs say that it should. In my previous ask, I was asking if Discord.JS could not change the way that it handles `<Client>.presences` to the way that I described since the current way does to fulfill its promise in a large number of cases (I mean at any given moment a significant number of friends are likely to be offline). At the very least I would think that there should be a way to add a user to the cache, but even if one didn't want to go through the hassle of making a way, you could just do the way that I described. So could it be done that way, and if not, is there a reason why? Again, I say this not to criticize, but just to understand the design decisions that have been chosen.

**Comment by flaw600** [comment]
To be clear, the API _does_ send presences for offline friends if they were online previously. Or at least that's how Discord.JS seems to handle it, as the user has already been created in the cache, as you described. However, if one were to care about offline presences then currently using `<Client>.presences` does not work the way that is described in the docs currently.

**Comment by flaw600** [comment]
Also, user.presence returns successfully for every friend regardless of if they're offline, as demonstrated in my code block above
