### ISSUE TITLE
Detect region change

### ISSUE THREAD

**Issue by skiptirengu** [hydrabolt/discord.js#1104]
Currently when you change the server region while the bot is connected to the voice, will cause it to continue streaming to the old audio channel. I don't know if it is possible, but it would be useful to emit an event when this change occur.

**Comment by GusCaplan** [comment]
this is planned for a voice rewrite we are doing. we will post here with any updates

**Comment by skiptirengu** [comment]
Ok then, thanks for the reply!

**Comment by Programmix** [comment]
The latest PR referenced includes support for seamlessly reconnecting when a guild's voice region changes. 😄

**Comment by hydrabolt** [comment]
Fixed in the Programmix's mentioned PR
