### ISSUE TITLE
Guild.fetchMembers gets stuck

### ISSUE THREAD

**Issue by Programmix** [hydrabolt/discord.js#1113]
Unfortunately, I have no specific repro case for this (otherwise I'd likely try to fix it myself), but it seems that occasionally Guild.fetchMembers will break completely and throw `Already fetching members in this guild` errors even after the fetch timeout ends.

**Comment by GusCaplan** [comment]
i shall do a look into this

**Comment by GusCaplan** [comment]
fixed in #1115

**Comment by Programmix** [comment]
This has been fixed.
