### ISSUE TITLE
removing a user's messageReaction seems to result in error.

### ISSUE THREAD

**Issue by frzyc** [hydrabolt/discord.js#1114]
my code is literally
`client.on('messageReactionAdd', (messageReaction, user) => {
    messageReaction.remove(user).catch(console.error);
});`

always results in an error `'{"user_id": ["Value \\"undefined\\" is not snowflake."]}'`

**Comment by frzyc** [comment]
`fetchUsers(limit = 100) {
    const message = this.message;
    return message.client.rest.methods.getMessageReactionUsers(
      message, this.emoji.identifier, limit
    ).then(...);
  }`
also returns `this.emoji.identifier`

**Comment by frzyc** [comment]
Made a rash assumption, its rather the user id that is undefined....
so the remove() method in `src/structures/MessageReaction.js`
`remove(user = this.message.client.user) {
    const message = this.message;
    user = this.message.client.resolver.resolveUserID(user);
    if (!user) return Promise.reject('Couldn\'t resolve the user ID to remove from the reaction.');
    return message.client.rest.methods.removeMessageReaction(
      message, this.emoji.identifier, user
    );
  }`
resolves user as an ID, and it then sends that user, which is an ID to the removeMessageReaction method. (`src/client/rest/RESTMethods.js` )
However, the removeMessageReaction method assumes that user is an user object, so it tries to get user.id, but that is undefined in this case....

**Comment by are1000** [comment]
I still have this issue. Version `11.0.0``.
```
msg.react(getEmoji('ear')).then(reaction => {
      const youtubeStream = ytdl(songUrl);
      const dispatcher = connection.playStream(youtubeStream, { volume: 0.5 });
      this.set('currentSong', dispatcher);

      dispatcher.on('error', err => {
        console.log(err);
        reaction.remove().then(() => resolve());
      });

      dispatcher.once('end', () => {
        reaction.remove().then(() => resolve()).catch(err => console.log(err));
      });
    }).catch(err => console.log(err));
```

**Comment by Programmix** [comment]
This bugfix has not been deployed to the stable branch yet, because for some reason we haven't been releasing patch versions... *cough*

If you want the fix, you'll have to `npm i hydrabolt/discord.js`

**Comment by are1000** [comment]
Thanks @Programmix!

**Comment by MatthiasSaihttam** [comment]
Could you explain further why this hasn't been fixed? It seems weird to me that there's a bug in a necessary feature which has been fixed, but it hasn't been deployed yet.

**Comment by Programmix** [comment]
It's because the master branch has lots of changes worthy of a minor patch. Also, the developers can't agree on a release date for v11.1.0, which is necessary to get this patch out...

**Comment by Azekthi** [comment]
Thank you so much @Programmix! I don't have time to sit around waiting for the devs to figure out a release date. That did the trick and the bugs are no longer present. 👍
