### ISSUE TITLE
voiceChannel.leave() causes other voiceChannels to become silent

### ISSUE THREAD

**Issue by Blogshot** [hydrabolt/discord.js#1118]
Following situation:
The bot is playing audio in two voice channels, channel#1 and channel#2.

When the audio in channel#1 is finished, the bot closes the voiceConnection and leaves the channel. In this moment the audio in channel#2 is abruptly cut off.

However, the bot stays in channel#2 until the audio **should have been** finished and remains silent until it receives the end-event. It then disconnects the voiceConnection and leaves channel#2.

This happens with different mp3-files (50-100KB, 4-6 seconds). @SpaceEEC also experiences this with prism. His description:
```
bot left channel [...]
other guild went silent
pause -> resume -> sound back
if i skip at other guild the same happens
calling .end() or leaving voiceChannel causing my bot to "mute/pause" all other guilds voice
```

Code-example:
```
function playAudio(voiceChannel, file) {
    
    voiceChannel.join().then(connection => {

        connection.playFile(file).on("end", () => {
                connection.disconnect();
                voiceChannel.leave();
        });

    });
}
```

Additional: 
I'm using 11.0 in a fresh environment with `node-opus`, `uws` and `erlpack`.

Might be related to #801.

**Comment by GusCaplan** [comment]
this is an known edge case with the discord voice servers, and is not on our end.
