### ISSUE TITLE
Split message option attempts to send too many messages

### ISSUE THREAD

**Issue by appellation** [hydrabolt/discord.js#1120]
When specifying `{ split: true }` as a message option, the request rejects with `Cannot send empty message`.  This seems to be the result of the split message option attempting to send more messages than necessary, as the entire text does get sent but an error is still thrown.

**Comment by Gawdl3y** [comment]
@GusCaplan changed the split messages logic in v11, which could very well be the cause of this issue. What content triggers this specifically?

**Comment by appellation** [comment]
It's my help command: here's a [pastebin](http://pastebin.com/1cpzjjdJ).

> Yes, it is not a very optimized command.

**Comment by appellation** [comment]
Note: this is on `indev-prism`.  I haven't tested on `master`.

**Comment by PgBiel** [comment]
I have had some issues with split too, like on the first message it throws a bad request and stops. I made my own split function, but then it throws errors even though the messages send :/
