### ISSUE TITLE
playfile for radio ? 

### ISSUE THREAD

**Issue by generalmd2** [hydrabolt/discord.js#1123]
Hello,

I would like to know if it is possible with playfile or other recovered internet stream and if so how to do? I have been searching for a while but without succeeding :(

Bonjour, 

Je voudrais savoir si c'est possible avec playfile ou autre de récupéré un flux internet et si oui comment faire ? Je cherche depuis un moment mais sans réussir :(

**Comment by GusCaplan** [comment]
actual working example
```js
message.member.voiceChannel.join().then(connection => {
  require('https').get('https://listen.moe/stream', (res) => {
    connection.playStream(res);
  })
})
```
