### ISSUE TITLE
lastMessageID should come with the message's channel

### ISSUE THREAD

**Issue by eslachance** [hydrabolt/discord.js#1134]
Considering a guild can have up to 500 channels, it can be very tedious to do a fetchMessage - looping on every channel and attempting to fetch on that channel. It means numerous API requests. 

It would be easier if the channel of that message was provided along with the ID.

**Comment by PgBiel** [comment]
I'm making a PR for that, User.lastMessage and GuildMember.lastMessage

**Comment by PgBiel** [comment]
^there is the PR
