### ISSUE TITLE
Support for roles when creating an emoji

### ISSUE THREAD

**Issue by Hitakashi** [hydrabolt/discord.js#1140]
A couple other libraries allow sending roles with the creation of emojis, but it seems to be missing in this one. 

Sending an array of role ids as a 'roles' property to the API allows restricting the emoji to only be used by those roles. I'm not too sure what happens when a user bot tries this, but it does work for whitelisted applications.

**Comment by GusCaplan** [comment]
#1141

**Comment by Gawdl3y** [comment]
Available in master.
