### ISSUE TITLE
login() error callback not being called

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#115]
```javascript
bot.login('[USERNAME]', '[PASSWORD]', function(error, token) {
    if (error) {
        console.log('Problem occurred while logging in! ' + error);
        return;
    }
    console.log('-----------------------------------------------------------------------------');
    console.log('Token: ' + token);

});
```
During the Discord outage a couple minutes ago. Starting up my bot had it just sit there instead of the error callback being called telling me it had a problem logging in.
![Image of Logging in](https://cdn.discordapp.com/attachments/81385020756865024/130876673192230912/2015-12-27_22-05-11.png)

**Comment by abalabahaha** [comment]
dupe of #105
