### ISSUE TITLE
Fix callbacks in general

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#116]
I don't want to make a new issue for everything I find nor compile it into one thing. So let's just do this. Callbacks are broken. Error is being fired when in reality the function worked. This causes problems for when I want to tell a user that the thing worked or didn't as I myself can't differentiate it.

**Comment by abalabahaha** [comment]
Subissues: #105 #111 #112 #113 #114

**Comment by hydrabolt** [comment]
Hi, could you see if this is fixed in 21be3d3c77fc33e2d29b977ae82f07b03f7b2f9e? Thanks

**Comment by Lord-Ptolemy** [comment]
Looks to be fixed. I tested it on unban, ban, and kick. They no longer use the error callback for success.
