### ISSUE TITLE
Volume being ingored.

### ISSUE THREAD

**Issue by brunolazzaro** [hydrabolt/discord.js#1161]
So I have a small bot with a !youtube command so we can play some music or podcasts while we are on the voice channels. The code is essentially the same one that is on the `playStream` sample code:

```javascript
// play streams using ytdl-core
const ytdl = require('ytdl-core');
const streamOptions = { seek: 0, volume: 0.2 };
voiceChannel.join()
.then(connection => {
   const stream = ytdl('https://www.youtube.com/watch?v=XAWgeLF9EVQ', {filter : 'audioonly'});
   const dispatcher = connection.playStream(stream, streamOptions);
})
 .catch(console.error);
```

But the audio still comes out super loud. Any ideas? I've tried digging into the library code, but I don't see anything that stands out to me that could be the issue.

**Comment by appellation** [comment]
I can confirm that this happens on `#indev-prism`.

**Comment by Programmix** [comment]
### i love it when volume is ingored :^)

This could be an artifact of a recent PR I made to the branch... I'll take a closer look when I have more time tomorrow.

**Comment by Programmix** [comment]
All right, I did some testing and I cannot confirm this. Are you on the latest version of `#indev-prism`? Also, could you specify if:
1. the volume works with initial volume set properly (in the playStream options)
2. the volume works if changed after the dispatcher is created

**Comment by brunolazzaro** [comment]
How do I install latest? I know I'm on 11, installed from NPM.

**Comment by GusCaplan** [comment]
`npm i hydrabolt/discord.js#indev-prism` to get the latest voice changes, (which aren't released yet) but you will go off release, so at some point after confirming if the change was fixed, you should just do `npm i discord.js@latest`

**Comment by brunolazzaro** [comment]
I installed latest from `#indev-prism`.

This is the code I'm running:

```javascript
    let currentVoiceChannel = bot.channels.get(message.member.voiceChannelID)
    let options = { seek: 0, volume: 0.5, passes: 3 }

    currentVoiceChannel
    .join()
    .then(connection => {
      let stream = ytdl(`https://youtube.com/watch?v=${id}`, {filter: 'audioonly'})
      let dispatcher = connection.playStream(stream, options)
    })
    .catch(console.error)
```

The audio is still same volume as before.

**Comment by brunolazzaro** [comment]
It's working, although the scale it's a bit odd. 0.5 seems to not be noticeable whereas 0.05 lowers the volume considerably.

**Comment by GusCaplan** [comment]
cc @hydrabolt

**Comment by Programmix** [comment]
Try using setVolumeLogarithmic then, I suppose.

**Comment by hydrabolt** [comment]
Can you check if the latest voice updates help?

**Comment by brunolazzaro** [comment]
On stable or #indev-prism? I've been using #indev-prism and has been working properly.

**Comment by hydrabolt** [comment]
indev-prism, thanks 😄
