### ISSUE TITLE
Message member field inconsistent with message event

### ISSUE THREAD

**Issue by BeMacized** [hydrabolt/discord.js#1165]
Occasionally, the ["member" field](https://discord.js.org/#/docs/main/11.0.0/class/Message?scrollTo=member) is _null_ on the Message objects received from the [message event](https://discord.js.org/#/docs/main/11.0.0/class/Client?scrollTo=message). 

This seems to happen at random, not specific to a user.

Running Discord.js 11.0.0.

**Comment by AoDude** [comment]
Member will be undefined if the message is received in DM/GroupDM text channels. This is intended, as the member object is everything about a particular user's relationship to a particular guild. That context does not exist outside of guilds, such as in DM/GroupDM...

**Comment by BeMacized** [comment]
My bad, I forgot to mention that this does in fact happen for messages sent inside of a text channel of a guild. DM or Group DM is not applicable in this case.

**Comment by AoDude** [comment]
Couple things to check. Is this a large guild? `guild.large` will let you know. If so: is the effected user using invisible mode? (From the perspective of the api, they are offline, and the api doesn't just offer up all offline users in such a guild.) If this is the case, you can add [fetchAllMembers](https://discord.js.org/#/docs/main/stable/typedef/ClientOptions) to your client options to have the library forcibly fetch all the offline users.

If you are not in a large guild, are you using [disabled ws events](https://discord.js.org/#/docs/main/stable/typedef/ClientOptions)? Having guild member add event disabled will keep the library from updating members that come online while your bot is running.

**Comment by BeMacized** [comment]
The guild has 40k+ members, so that would tick the `guild.large` box. 
Many users come by a day, so I do not have the capability right now to check specific users that were affected. I will add the fetchAllMembers option anyways and report back if the issue persists.

**Comment by GusCaplan** [comment]
hello, this is an issue with discord. people who are invisible are treated as offline and not sent to us, but they can still send messages, which will result in the member being null. they said they are thinking of solutions to this.

**Comment by Gawdl3y** [comment]
Also, webhook messages don't have a member.
