### ISSUE TITLE
Promises not behaving as expected

### ISSUE THREAD

**Issue by Falconerd** [hydrabolt/discord.js#117]
Perhaps I'm just missing something. However, I'll give you some examples and their results:

__Assume these two functions__

    function sayYay(token = null) {
      console.log('Yay!', token);
    }

    function err(error) {
      console.error('Oh no!', (!!error));
    }

>

    bot.login(email, password)
    .then(sayYay)
    .catch(err);
> No log

    bot.login(email, password)
    .then(token => sayYay(token))
    .catch(err);
> No log

    bot.login(email, password)
    .then(() => sayYay)
    .catch(err);
> No log

    bot.login(email, password)
    .then(token => { sayYay(token) })
    .catch(err);
> No log

    bot.login(email, password)
    .then(sayYay())
    .catch(err);
> Yay!, null

    bot.login(email, password)
    .then(function(token) { console.log('Yay!', token) })
    .catch(err);
> No log

__With incorrect details, we get errors as expected__

    bot.login('asdf', '1234')
    .then(sayYay)
    .catch(err);
> Oh no!, true

**Comment by hydrabolt** [comment]
Hi, could you see if this bug has been fixed in 21be3d3c77fc33e2d29b977ae82f07b03f7b2f9e? Thanks

**Comment by Falconerd** [comment]
I can confirm this issue has been fixed. Thanks!
