### ISSUE TITLE
issue dont complete

### ISSUE THREAD

**Issue by xCuzImPro** [hydrabolt/discord.js#1170]
Voice Support with node-opus / opusscript #1169 
pls opening. for helping @meew0

**Comment by GusCaplan** [comment]
your issue is `Error: Incorrect login details were provided.` this has nothing to do with node-opus or opusscript, and it has nothing to do with erlpack. please stop opening useless issues

**Comment by xCuzImPro** [comment]
this is dont my problem.
my problem is i dont can install this voice support.
the login details is fixxed.

**Comment by GusCaplan** [comment]
https://discord.gg/bRCvFy9
