### ISSUE TITLE
Volume option doesn't work

### ISSUE THREAD

**Issue by ErikMartensson** [hydrabolt/discord.js#118]
When playing an audio file the volume option doesn't actually change the volume that is being sent to the rest of the users. This is the code I've tried:
```
myBot.voiceConnection.playFile('sounds/myfile.mp3', {volume: '0.1'}, function(stream) {});
```
I've tried setting that property as a string and float but there is no difference. I have also tried the volume option in the function **playRawStream** a few weeks ago, and it didn't work then either, but I haven't used that function in a while so I don't know if it's still a problem for that function.

But I know that **playFile** doesn't care about volume option. It's always really loud.

Is there anything wrong with my code, do anyone else have this problem?

I'm using Node v4.2.3 on Ubuntu.

**Comment by hydrabolt** [comment]
This is a known issue but isn't a big priority right now as users can just
change the volume of the bot themselves

**Comment by khionu** [comment]
I would argue that this is actually a little more important.... I've used TechniKhitty as a DJ now, and people who join the Voice Chat naive get a blast to their ear drums. It's quite an issue, as people need warning, and we can't warn people we don't know are about to join :/ Default volume is very loud.....

**Comment by macdja38** [comment]
I also have to agree but for a different reason. Setting the volume to anything but default on discord seems to degrade sound quality. It's mostly suitable when raising the volume but it seems to happen when lowering it as well.

**Comment by macdja38** [comment]
use:
'-filter:a', 'volume=`+(options.volume || 0.05),
instead of:
'-af', 'volume=' + (options.volume || 0.05)

**Comment by macdja38** [comment]
Problem seems solved for encoding streams but not file's in the #16 branch.

**Comment by khionu** [comment]
If you're talking about my issue, that was my error

**Comment by khionu** [comment]
Working in InDev.

**Comment by esciron** [comment]
I can't get any sound from the bot.
client.voiceConnection.playRawStream(request(url), {volume: '0.5'}, function(stream) {});

in the console it looks like it gets stuck and i have to ctrl+c it to skip that order and keep going

**Comment by aequasi** [comment]
That sounds more like an issue with ffmpeg/that file, than volume

Aaron Scherer




On Thu, Apr 14, 2016 at 10:09 AM -0700, "esciron" <notifications@github.com> wrote:












I can't get any sound from the bot.

client.voiceConnection.playRawStream(request(url), {volume: '0.5'}, function(stream) {});



in the console it looks like it gets stuck and i have to ctrl+c it to skip that order and keep going

**Comment by brunolazzaro** [comment]
I'm also having volume issues. Using this as an example:

`// play streams using ytdl-core
const ytdl = require('ytdl-core');
const streamOptions = { seek: 0, volume: 0.2 };
voiceChannel.join()
 .then(connection => {
   const stream = ytdl('https://www.youtube.com/watch?v=XAWgeLF9EVQ', {filter : 'audioonly'});
   const dispatcher = connection.playStream(stream, streamOptions);
 })
 .catch(console.error);`

Does nothing, the volume of the stream is still super loud. Any pointers?

**Comment by Gawdl3y** [comment]
Please open a new issue if you're having recent troubles.
