### ISSUE TITLE
Client#messageReactionAdd event doesn't work.

### ISSUE THREAD

**Issue by IreliaHasHands** [hydrabolt/discord.js#1189]
The event doesn't fire when a reaction is removed.

**Comment by hydrabolt** [comment]
Can you give some description??

**Comment by IreliaHasHands** [comment]
The event doesn't fire when a reaction is removed.  The guys in Discord said it was broken when I asked them.

**Comment by hydrabolt** [comment]
Removing a reaction wouldn't trigger `messageReactionAdd`...

**Comment by IreliaHasHands** [comment]
My typo in the title.  I meant the Remove version of the event.

**Comment by Programmix** [comment]
Could you please provide some information; the code you're using, the version of discord.js you're on...

**Comment by IreliaHasHands** [comment]
All is working on the master branch!  Thanks for responding anyway.
