### ISSUE TITLE
voiceLeave doesn't work

### ISSUE THREAD

**Issue by iwittenberg** [hydrabolt/discord.js#119]
```javascript
//Once bot is logged in and ready...

mybot.on("voiceLeave", function(user, voiceChannel) {
	console.log(user + " left " + voiceChannel);
});
```

Nothing is ever printed to the console

**Comment by macdja38** [comment]
seems related to https://github.com/hydrabolt/discord.js/issues/116

**Comment by hydrabolt** [comment]
Works on my end? Which version of discord.js are you running

**Comment by iwittenberg** [comment]
5.3.1

**Comment by hydrabolt** [comment]
Are you sure the bot can access the voice channel you're leaving?

**Comment by iwittenberg** [comment]
voiceJoin with the same code works just fine.  Switching between rooms with both a voiceJoin and a voiceLeave only ever outputs the voiceJoin.

**Comment by hydrabolt** [comment]
Oh, yeah that's the intention, however do you think I should change it to a `voiceSwitch` event? Discord's API only ever uses "`voiceLeave`" when you actually leave a channel, not switch.

**Comment by aequasi** [comment]
There should definitely be a voiceSwitch event too, if this is the intention of voiceLeave.
