### ISSUE TITLE
Minified webpack version is going bonkers!

### ISSUE THREAD

**Issue by ButterCheezii** [hydrabolt/discord.js#1191]
![](https://puu.sh/u6MW7/593e53365d.png)
![](https://puu.sh/u6N7C/917b794201.png)

This only happens on the minified version. The second screenshot was taken using the master.min file, just in case.

Non-minified version:
![](https://puu.sh/u6Nbz/b5c10dcf56.png)

**Comment by GetRektByMe** [comment]
Zoinks scoobs! Better get the gang on the case!

**Comment by GusCaplan** [comment]
You know the rawgit cdn has permanent caching right? So just as a warning, that cdn master url will always be the same now 😁

**Comment by ButterCheezii** [comment]
@GusCaplan Oh, RIP

**Comment by ButterCheezii** [comment]
That may be why it's erroring, the minified version might be cached. Too lazy to test it again.

**Comment by ButterCheezii** [comment]
Sorry, I'm not that eager to test it again. If you really want to know, it should be easy enough to test yourself 😛

**Comment by iCrawl** [comment]
Doesn't happen anymore after my tests.
