### ISSUE TITLE
How to send custom emojis in a server ? #question

### ISSUE THREAD

**Issue by manuel-di-iorio** [hydrabolt/discord.js#1193]
I tried wth `message.channel.send(":custom:")` where `:custom:` is the code of the custom emoji in that server, but it will be sent as plain text instead of replacing the message with an emoji.

Instead, Discord official emojis like `:smiley:` work.

**Comment by meew0** [comment]
Please use the [official discord.js Discord server](https://discord.gg/bRCvFy9) for questions; this issue tracker is only intended for bug reports and enhancement suggestions.

**Comment by manuel-di-iorio** [comment]
Thanks meew, however I found the guild custom Emoji class in this discord.js documentation :)
