### ISSUE TITLE
Is the server.members cache supposed to update on its own?

### ISSUE THREAD

**Issue by Enchanted13** [hydrabolt/discord.js#120]
**Edit** : should be worth mentioning I am on 5.2.0 and bot.users is correctly updated in real time.
I'm not sure if this is an issue or not. Basically imagine a command that returns a user's avatarURL.
command : !avatar Enchanted13
```javascript
bot.on("message", function(msg) {
       var command = messageText.split(" ");
       var keyword = command[0].toLowerCase();
       var params = command[1];
       bot.reply(msg, msg.channel.server.members.get('username', params).avatarURL);
});
```

This works pretty well, but whenever that user changes username, it isn't updated in msg.channel.server.members. Trying to "get('username', newUsername)" will not work and return null, but doing it with the old one works.
Adding this event handler to my code will make it work, but is it how it's supposed to be? Or should the server cache be updated automatically? :

```javascript
bot.on("userUpdated", function (userBefore, userAfter) {
    bot.servers[0].members.update(userBefore, userAfter);
});
```

**Comment by hydrabolt** [comment]
Found the issue, need to think of a creative way of fixing it though. Thanks!

**Comment by hydrabolt** [comment]
Hi, could you see if 2000b62b36d92f10f23faada661732ffa1b50c38 fixes this bug for you? Thanks

**Comment by Enchanted13** [comment]
It did! Thanks a lot!
