### ISSUE TITLE
Sending stream to voiceConnection fails

### ISSUE THREAD

**Issue by NotGGhost** [hydrabolt/discord.js#121]
Log: `[..\..\..\deps\mpg123\src\libmpg123\parse.c:1078] error: Giving up searching valid MPEG header after 65536 bytes of junk.`

Code:

```javascript
bot.joinVoiceChannel(voiceChannel, function(error, connection) {
		var ldc = request(url).pipe(new lame.Decoder());
		connection.playStream(ldc, function(err, str) {
			console.log(err);
			console.log(str);
		});
	});
```

request#pipe has been confirmed to be writing the legitmate mp3s and mp4s to a file stream.

**Comment by hydrabolt** [comment]
Can you try playRawStream instead of playStream?

**Comment by NotGGhost** [comment]
Still the same...


---- On Wed, 30 Dec 2015 05:34:36 -0800 Amish Shah &lt;notifications@github.com&gt; wrote ---- 

Can you try playRawStream instead of playStream?
 On 30 Dec 2015 11:47 a.m., "Ghost" &lt;notifications@github.com&gt; wrote:
 
 &gt; Log: [\\\deps\mpg123\src\libmpg123\parsec:1078] error: Giving up
 &gt; searching valid MPEG header after 65536 bytes of junk
 &gt;
 &gt; Code:
 &gt;
 &gt; botjoinVoiceChannel(voiceChannel, function(error, connection) {
 &gt; var ldc = request(url)pipe(new lameDecoder());
 &gt; connectionplayStream(ldc, function(err, str) {
 &gt; consolelog(err);
 &gt; consolelog(str);
 &gt; });
 &gt; });
 &gt;
 &gt; request#pipe has been confirmed to be writing the legitmate mp3s and mp4s
 &gt; to a file stream
 &gt;
 &gt; —
 &gt; Reply to this email directly or view it on GitHub
 &gt; &lt;https://github.com/hydrabolt/discord.js/issues/121&gt;.
 &gt;

**Comment by hydrabolt** [comment]
Not really sure, seems to be an issue with node-ffmetadata?

**Comment by meew0** [comment]
discord.js should be able to do the audio decoding on its own, try using `request(url)` directly inside of `playRawStream`.

**Comment by hydrabolt** [comment]
Probably fixed with meew's suggestion
