### ISSUE TITLE
Sodium implementation broken

### ISSUE THREAD

**Issue by iCrawl** [hydrabolt/discord.js#1219]
Installing sodium as an optional dependency for faster encryption and decryption results in no audio being played.

Specs are the usual:
Ubuntu 16.04, 
ffmpeg version 3.2.4-1~16.04.york1
node-opus 0.2.4

I tried downgrading to a lower ffmpeg version, uninstalling other optional deps, and nailed it down to sodium being the culprit.

Some things I remember when I did debugging: 
![image](https://cloud.githubusercontent.com/assets/20760160/23315415/7198fa10-fac6-11e6-89d3-0e1bfeb9492e.png)

So appearently speaking is true even tho no sound is produced, I assume packages are still send, or atleast some are.

**Comment by GusCaplan** [comment]
i don't believe macdja ever actually tested his sodium code 😆

**Comment by Gawdl3y** [comment]
Says the one who claimed his code was copied from yours. 🙄

**Comment by GusCaplan** [comment]
he claimed he wrote it 🙄
