### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by LLamaFTL** [hydrabolt/discord.js#1228]
I kinda recently am new to discord.js
making discord bots in general
and i need some help making my discord bot set it to playing something
Ive been searching for awhile trying to find some help
nothing has came up
and I'm wondering if anyone knows?
Thanks!

**Comment by Jamelele** [comment]
This should help
https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setPresence

If you have any more questions like this, then it's much easier to ask on the Discord server
https://discord.gg/bRCvFy9

**Comment by LLamaFTL** [comment]
Thanks!

**Comment by LLamaFTL** [comment]
Thanks!

**Comment by hydrabolt** [comment]
@Jamelele's answer is also correct, but `ClientUser.setGame(game, [playingURL])` is a much more direct way to set a game - https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setGame.

Also yes, please ask on our server in the future for questions like this :)
