### ISSUE TITLE
I can't login with email and password

### ISSUE THREAD

**Issue by ROM-Typo** [hydrabolt/discord.js#1237]
I am unable to use `client.login` with a email and password

**Comment by KyeNormanGill** [comment]
Using an email and password to login is no longer supported. You have to log in with a token provided by the discord website under your bots info.

**Comment by ROM-Typo** [comment]
is it the `token` localStorage value?

**Comment by KyeNormanGill** [comment]
If it's a selfbot yes. If it's a normal bot, then it's on the discord website under my apps in the developer section.

**Comment by ROM-Typo** [comment]
I used that and it said that invalid login details were supplied

**Comment by KyeNormanGill** [comment]
Are you sure you're using your latest token? And using the syntax correctly?

**Comment by ROM-Typo** [comment]
`client.login(token)`

**Comment by KyeNormanGill** [comment]
Something is wrong with the token or you're not referencing it correctly.
Try changing your discord password so it resets and use the new token.

**Comment by appellation** [comment]
Please take this to the official support server.  https://discord.gg/bRCvFy9

**Comment by ROM-Typo** [comment]
@KyeNormanGill Thanks that worked
