### ISSUE TITLE
Bulk Delete Endpoint Change

### ISSUE THREAD

**Issue by Mr-Quiggles** [hydrabolt/discord.js#1245]
Discord deprecated the old `bulk_delete` endpoint in favor for `bulk-delete`. Unless I somehow botched it, correcting it in `src/client/rest/RESTMethods.js` doesn't fix it.

**Comment by GusCaplan** [comment]
bulk delete is ded right now, unrelated to the deprecation of that endpoint

**Comment by hydrabolt** [comment]
Fixed in latest commit
