### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MrSouth** [hydrabolt/discord.js#1247]
Sorry, i'm don't know if this are in the right page, but...

So... I see a Discord Bot with music in JS to put the commands in my bot. The bot need ytdl-core. So, i installed. When i start my bot, this appears in CMD:

C:\Users\Gabriel\Desktop\OhGodMusicBot-master>node server.js
module.js:472
throw err;
^

Error: Cannot find module 'ytdl-core'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object. (C:\Users\Gabriel\Desktop\OhGodMusicBot-master\server.js:2:12)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)

C:\Users\Gabriel\Desktop\OhGodMusicBot-master>PAUSE

**Comment by Tvde1** [comment]
Are you sure you did the `npm install ytdl-core (-S)` in the right folder?

**Comment by robflop** [comment]
I'm sorry to say, but this is not discord.js related.

As you can read from the error message, the "ytdl-core" module was not found.

You did say you installed it, but it's not being found.

**Comment by MrSouth** [comment]
@Tvde1 Yes.
@robflop Okay. sorry D:

**Comment by MrSouth** [comment]
I tried to install ytdl-core 3 times, and the 3 times this don't worked.

**Comment by MrSouth** [comment]
Now i installed for the 4th time, and not works.

**Comment by appellation** [comment]
This is definitely not the correct place.  I won't even recommend joining the official support server since this issue is completely unrelated to the lib.

**Comment by hydrabolt** [comment]
Please read https://github.com/hydrabolt/discord.js/blob/master/CONTRIBUTING.md in future
