### ISSUE TITLE
Add ability to validate an invite code

### ISSUE THREAD

**Issue by aequasi** [hydrabolt/discord.js#125]
https://discordapi.readthedocs.org/en/latest/reference/invites/invites.html#parameters

**Comment by abalabahaha** [comment]
Can you test 2a00064

**Comment by meew0** [comment]
I'll assume this was correctly fixed due to inactivity.

**Comment by aequasi** [comment]
Don't really know if its fixed. Didn't want to try indev

**Comment by TehSeph** [comment]
Could have said something regardless. ¬_¬
