### ISSUE TITLE
ReferenceError: Symbol is not defined on OpenShift/Node.js v4.2.4

### ISSUE THREAD

**Issue by marcandrews** [hydrabolt/discord.js#126]
When I attempt to start my Node.js server app on OpenShift, I get the following error:
```
...node_modules/discord.js/lib/Util/Cache.js:1
(subClass,superClass):subClass.__proto__ = superClass;}var discrimS=Symbol();v
                                                                    ^
ReferenceError: Symbol is not defined
```

Another issue is that even though I have updated Node.js to 4.2.4 on my OpenShift instance, the ```OVERRIDE_DISCORD_MIN_VERSION=true``` environment variable is still required.

Any ideas on how I can solve this?

**Comment by abalabahaha** [comment]
Check your Node.JS version again. If it's really 4.2.4, it shouldn't require OVERRIDE_DISCORD_MIN_VERSION.

**Comment by marcandrews** [comment]
Thanks. There was a bug in my app cartridge and even though I had installed 4.2.4, it was still loading 0.10.

For more information, see https://github.com/ryanj/nodejs-custom-version-openshift/issues/2
