### ISSUE TITLE
MessageReaction.remove() gives a Bad Request Error

### ISSUE THREAD

**Issue by monsterbitar** [hydrabolt/discord.js#1265]
I am trying to remove reactions that people set on their own messages, but consistently get a bad request error. I assume this is something that might be updated on the discord API end that hasn't been updated here yet, or that it might have been overlooked as one of the less used functions of the API.

(Or I'm failing to send proper data despite my best attempts at doing so)

Here's a simplified code snippet that trigger the issue:

```// When a message is sent to a channel the bot listens to..
client.on("messageReactionAdd", (reaction, user) => 
{
	reaction.remove(user).then(reaction => 
	{
		console.log('Removed a reaction.');
	}, error => 
	{
		console.log('Unexpected error: ' + error);
	});
}```

**Comment by robflop** [comment]
I've just tried it with a testing bot, using this code:

```
bot.on("messageReactionAdd", (reaction, user) => {
	reaction.remove(user).then(reaction => {
		console.log('Removed a reaction.');
	});
});
```

and it worked flawlessly. The Commando bot on the Discord.js server also uses this event, so i'm rather sure it's an error in your code.

**Comment by monsterbitar** [comment]
Are you using the v11.0.0 version of discord.js?

**Comment by robflop** [comment]
I am, yes.

**Comment by monsterbitar** [comment]
It could very well be something wrong in my code, I'm by no means and expert in this regard. That said, this seems simple enough that I'd be surprised if the issue really was on my end. Here's the code without alterations on my end:

```// When a message is sent to a channel the bot listens to..
client.on("messageReactionAdd", (reaction, user) => 
{
	// If this message author is not a bot..
	if(!reaction.message.author.bot)
	{
		// If the message and the reaction was both from the same user..
		if(reaction.message.author.id == user.id)
		{
			// Remove the reaction from the message.
			reaction.remove(user).then
			(
				reaction => 
				{
					console.log('Remove a reaction that ' + user.username + ' had put on their own message.');
				}, error => 
				{
					console.log('Failed to remove a reaction that ' + user.username + ' had put on their own message: ' + error);
				}
			);
		}
		// If this reaction is on another persons message..
		else
		{
```

Which ends up printing this to the console:

`Failed to remove a reaction that TinyHeart had put on their own message: Error: Bad Request`

**Comment by robflop** [comment]
Have you made sure your bot has enough permissions? The code seems fine.

Try inspecting the Bad Request error completely (output it and read through it).

**Comment by monsterbitar** [comment]
Some possibly relevant informatin:

\# node -v
`v7.2.0`

\# npm list | grep -i discord
`├─┬ discord.js@11.0.0`

**Comment by monsterbitar** [comment]
The bot is allowed to manage messages (and some other things as well, not sure which is relevant).

I will see if I can output the error and read through it, thanks.

**Comment by monsterbitar** [comment]
Thanks for helping by pointing me in the right direction, the error structure does indeed have an explanation (the text property), which states:

`text: '{"user_id": ["Value \\"undefined\\" is not snowflake."]}',`

Now I wonder why my user is different from yours in this context, as we have the same source for them and everything really seems right at first glance..

**Comment by monsterbitar** [comment]
I added a console.log(user) right before the reaction.remove(user) statement, and at that point it still has a valid user:

``` User {
  id: '230003000431607808',
  username: 'TinyHeart',
  discriminator: '1831',
  avatar: '43720ccf580f36df3b49214cbc1756b6',
  bot: false,
  lastMessageID: '290422503438811136' }```

**Comment by robflop** [comment]
Hmm, that's weird. Could you try it with another user just for the sake of it?

**Comment by hydrabolt** [comment]
Could you see if using the master branch fixes this issue? `npm install hydrabolt/discord.js`

**Comment by monsterbitar** [comment]
```User {
  id: '189386282437181442',
  username: 'Fluffy Dragg0n',
  discriminator: '8290',
  avatar: '47bb2ac0cd2648f4967c5be1beca3755',
  bot: false,
  lastMessageID: '290424232741961729' }
Failed to remove a reaction that Fluffy Dragg0n had put on their own message
{ Error: Bad Request
 [ ... ]
       status: 400,
        text: '{"user_id": ["Value \\"undefined\\" is not snowflake."]}',
        method: 'DELETE',
        path: '/api/v6/channels/256700627692814336/messages/290424225867497472/reactions/%E2%9D%A4/undefined' },```

Will try to update to master and check again.

**Comment by monsterbitar** [comment]
@hydrabolt the master works just fine, and the difference I can see is that the user object is larger on master in the reaction add event:

``` User {
  id: '230003000431607808',
  username: 'TinyHeart',
  discriminator: '1831',
  avatar: '43720ccf580f36df3b49214cbc1756b6',
  bot: false,
  lastMessageID: '290425062853574659',
  lastMessage: 
   Message {
     channel: 
      TextChannel {
        type: 'text',
        id: '290124227787358220',
        name: 'testing',
        position: 0,
        permissionOverwrites: [Object],
        topic: '',
        lastMessageID: '290425062853574659',
        guild: [Object],
        messages: [Object],
        _typing: [Object],
        lastMessage: [Circular] },
     id: '290425062853574659',
     type: 'DEFAULT',
     content: 'teeeeees',
     author: [Circular],
     member: 
      GuildMember {
        guild: [Object],
        user: [Circular],
        _roles: [Object],
        serverDeaf: false,
        serverMute: false,
        selfMute: undefined,
        selfDeaf: undefined,
        voiceSessionID: undefined,
        voiceChannelID: undefined,
        speaking: false,
        nickname: null,
        joinedTimestamp: 1481272598912,
        lastMessageID: '290425062853574659',
        lastMessage: [Circular] },
     pinned: false,
     tts: false,
     nonce: '290425103236202496',
     system: false,
     embeds: [],
     attachments: Collection {},
     createdTimestamp: 1489313130821,
     editedTimestamp: null,
     mentions: 
      { users: Collection {},
        roles: Collection {},
        channels: Collection {},
        everyone: false },
     _edits: [],
     reactions: Collection { '%F0%9F%98%83' => [Object] },
     webhookID: null,
     hit: null } }```


compared to the previous size:

```id: '189386282437181442',
  username: 'Fluffy Dragg0n',
  discriminator: '8290',
  avatar: '47bb2ac0cd2648f4967c5be1beca3755',
  bot: false,
  lastMessageID: '290424232741961729' }```

**Comment by robflop** [comment]
Right, so problem's solved? 😃

**Comment by monsterbitar** [comment]
Kindof. I'll get back to v11.0.0 and let it spew error message and wait for a minor relase (like v11.0.1), feel uncomfortable sitting on master and not knowing if other things might be broken that I'll crash into only during edge cases.

**Comment by monsterbitar** [comment]
@hydrabolt you can close this, or keep it open until you backport the relevant changes and/or release master as a stable release - your call.

**Comment by robflop** [comment]
Sounds good 👍
