### ISSUE TITLE
Incorrect documentation for Client.login

### ISSUE THREAD

**Issue by LinearSpoon** [hydrabolt/discord.js#1266]
There is still an example of logging in with email/password in the documentation, but that possibility seems to be removed from the code.

https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=login

**Comment by GusCaplan** [comment]
docs for login have already been rewritten (to see latest select the branch `master` in the docs)

**Comment by LinearSpoon** [comment]
Thank you. I was just looking at stable branch/stable docs and found the mismatch.
