### ISSUE TITLE
"setChannelTopic" is wrongly listed as "setTopic" in the documentation

### ISSUE THREAD

**Issue by romdi** [hydrabolt/discord.js#127]
See http://discordjs.readthedocs.org/en/latest/docs_client.html#settopic-channel-topic-callback.

**Comment by abalabahaha** [comment]
@hydrabolt ...

**Comment by meew0** [comment]
This appears to be correct in the repo's docs, the readthedocs just have to be rebuilt.

**Comment by abalabahaha** [comment]
@meew0 readthedocs follows master

**Comment by Lord-Ptolemy** [comment]
Doesn't NPM follow the stable docs and indev follows latest docs? As NPM still uses ``setChannelTopic`` and not ``setTopic`` so you kinda just screwed over anyone using NPM because no update has been pushed to change that to ``setTopic``. So those looking at the docs will be using the wrong method.

**Comment by abalabahaha** [comment]
@Lord-Ptolemy in the code, it's setChannelTopic. In the docs, it's setTopic. It's supposed to be renamed _to_ setChannelTopic, not _from_.

**Comment by Lord-Ptolemy** [comment]
Guess that's what I get for not reading properly.
