### ISSUE TITLE
There seems to be a trend with the ready event and 115.237s

### ISSUE THREAD

**Issue by ButterCheezii** [hydrabolt/discord.js#1270]
`client.uptime` is always `115237` when the `ready` event is emitted

Why?

![](https://puu.sh/uIZfM/d1516f8c3f.png)

![](https://puu.sh/uIZ6i/f0206120cc.png)

I have only tested this twice. Both logs show 115.237s.

###### Excuse the edit. Memory recalled it weirdly.

**Comment by iCrawl** [comment]
It is not always 115237 seconds.

![](https://a.safe.moe/q4eFN.png)

**Comment by ButterCheezii** [comment]
It is on my end, I do not know why it is happening and I want to know how to fix it

**Comment by ButterCheezii** [comment]
And FYI client.uptime is in ms

**Comment by iCrawl** [comment]
I always get different values when I start up with the exact same code.

And yes I know, I edited the comment like 2sec after I said seconds.

**Comment by appellation** [comment]
This isn't the correct place for support questions.  Please join the official D.js support server.  https://discord.gg/bRCvFy9
