### ISSUE TITLE
playStream 'end' reason is "Stream is not generating quickly enough."

### ISSUE THREAD

**Issue by Vargash** [hydrabolt/discord.js#1272]
Everything seems like working fine, videos are played correctly until the end, but when music ends the reason printed from the `activeStream.on('end')` reason is not `stream` (as per docs) but `Stream is not generating quickly enough.`.

Do I have to manually close the stream, or something?
I'm using node-opus.

Code snippet:
```
const stream = ytdl(musicUrl, { filter: 'audioonly' });
stream.on('info', (info) => {
   const streamInfo = 'Reproducing ... ' + info.title + ' (' + info.length_seconds + 's)';
   message.channel.sendMessage(streamInfo);
});
activeStream = connection.playStream(stream, { volume: config.getVolume() });
activeStream.on('end', (reason) => { console.log(reason); });
```

**Comment by iCrawl** [comment]
The discussion for it is here: #1225 

Also this isn't the correct place for support questions. Please join the official d.js support server: https://discord.gg/bRCvFy9
