### ISSUE TITLE
How to get the User object from Message.mentions.user?

### ISSUE THREAD

**Issue by rmickey42** [hydrabolt/discord.js#1274]
Title explains it all.

**Comment by GusCaplan** [comment]
Please stop opening up issues for every tiny issue you get. It is a pain for us to deal with, and the issue tracker is for **issues with this library** not **support**.

Furthermore, if you read the docs, you would see that `message.mentions.users` is a Collection, which has a plethora of methods and accessors to retrieve the user instance you so desperately crave.

**Comment by rmickey42** [comment]
@GusCaplan Sorry. I figured out my issue and I'll stop.
