### ISSUE TITLE
messageReactionAdd and messageReactionRemove events not firing

### ISSUE THREAD

**Issue by CorpulentBrony** [hydrabolt/discord.js#1279]
I'm noticing some oddities with the messageReactionAdd and messageReactionRemove events in the stable branch version 11.0.

If I send a message in the chat and then add a reaction to it, the event fires as expected.  If another user adds a reaction or upvotes the added reaction, the event fires as expected.  But, if anyone tries removing a reaction from the message, no event fires.  In fact, I have been unsuccessful in getting the messageReactionRemove event to fire at all (I've additionally not been able to get messageReactionRemoveAll to fire).

The second issue occurs when a user removes their reaction and then re-adds the same reaction, no new messageReactionAdd event is fired for the re-add of the reaction.

The code right now:
```javascript
client.on("messageReactionAdd", (messageReaction, user) => console.log(messageReaction);
client.on("messageReactionRemove", (messageReaction, user) => console.log(messageReaction));
client.on("messageReactionRemoveAll", (messageReaction) => console.log(messageReaction));
```

**Comment by iCrawl** [comment]
This should be fixed in master.

**Comment by CorpulentBrony** [comment]
master is working as expected.

**Comment by iCrawl** [comment]
You'll have to opt using master until 11.1 is released on npm.

**Comment by 4D48** [comment]
This is working only on new messages, which have been created since bot has been on.

**Comment by Lewdcario** [comment]
Please don't necro dead threads. You can see the last post was almost a year ago.
