### ISSUE TITLE
messageReactionAdd event is called twice when the bot adds reactions to its own message

### ISSUE THREAD

**Issue by CorpulentBrony** [hydrabolt/discord.js#1285]
I'm experiencing some more strange message reaction event behavior.  I'm on master now.

It's a bit convoluted, but I have gotten the behavior to repeat reliably.  Here's what I do:

1.  The bot creates a new embedded message
2.  The bot adds a reaction to the message it just sent
    The first oddity occurs here, in that the `messageReactionAdd `event is called twice.  This only occurs when the bot adds its own reactions to the message.  Next:
4. A user adds a reaction to the message (either a new one or an "upvote")
    A single `messageReactionAdd `event is fired, as expected
5.  The bot edits the message embed in response to the above fired `messageReactionAdd `event
6.  A user removes the reaction they added to the message (either the new one or the "upvote")
    At this point, the second oddity occurs in that the `messageReactionRemove `event is not called at all.  If the message is not edited and another reaction is removed, the event will be called.  But the first one after the edit is ignored.

**Comment by bdistin** [comment]
Message editing breaking reaction remove should be fixed in pr #1236. I am not sure about bot reacting calling messageReactionAdd 2x though, I will see if I can replicate that.

You can test my pr by running `npm i bdistin/discord.js`, and see if that does indeed fix your issues.

**Comment by bdistin** [comment]
So, double `messageReactionAdd` happens in both master, and in my pr. I am not sure where it is coming from, as the data packet handler is actually being run 2x (as if there are 2 data packets). That particular bug seems like it will be out of scope of my pr. 

However the `messageReactionRemove` event not getting broken with message edits is fixed in my pr.

**Comment by iCrawl** [comment]
Fixed in 6ce2439

**Comment by AClmbr** [comment]
Hi all 👋

I just used the messageReactionAdd observation and I faced the same problem explained here: the event was called **twice per reaction** (only when the bot reacts).

Do you have an idea why?

**Comment by Rigelrain** [comment]
I came to this problem when I was having the same issue with ReactionCollector. Every time the bot reacts to it's own (in my case at least, an embedded) message, the filter function is called twice and if it passes the filter, then of course the 'collect'-event is also called twice. Does not happen when a user reacts to the message.
