### ISSUE TITLE
user.fetchProfile() => PromiseRejectionWarning: Forbidden

### ISSUE THREAD

**Issue by IceFight** [hydrabolt/discord.js#1290]
Hi. Im using a UserBot with the normal tokenlogin. But somehow i still can't use the Method user.fetchProfiles().

I've been trying everthing i could think of. Searching trough google got me here where someone only answered that you should use a UserBot. 

Im using a UserBot and i still get the forbidden message. What do i have to do, so that i can use this feature?

Thank you.

**Comment by meew0** [comment]
Please use the [official discord.js Discord server](https://discord.gg/bRCvFy9) for questions; this issue tracker is only intended for bug reports and enhancement suggestions.
