### ISSUE TITLE
Message embed image type

### ISSUE THREAD

**Issue by Marfjeh** [hydrabolt/discord.js#1292]
Hi! I'm not sure where to report it here or just send a bug report to discord...
In the Netherlands we have a weather company called Buienradar, and they give a Gif image via a URL But the URL does not have a .gif extension, URL: ```http://api.buienradar.nl/image/1.0/RadarMapNL``` if you open it in your browser then it will play the gif inside your browser.

After sending it in discord it wont show as a gif, but with a dirty fix to force a extension, I set a fake get request that does noting to emulate that it had a file extension: ```http://api.buienradar.nl/image/1.0/RadarMapNL?a=.gif``` After that, Discord will finally see it as a gif, but there's a problem it wont play, (see screenshot) Even adding it in the URL in your browser it still plays the gif, even with ```?a=.gif``` in the url.

so here's my question, is there a way to set the type of the image, that it will show as a gif?

![screenshot](https://s30.postimg.org/7azd9yow1/2017_03_20_09_58_04_331558.gif)

Code:
```JS

 message.channel.sendMessage({
        "embed": {
                title: 'Buienradar',
                url: 'http://www.buienradar.nl/',
                "image": {
                "url": "http://api.buienradar.nl/image/1.0/RadarMapNL?a=.gif",
                }
            }
        });

```

Sorry for my broken english...

**Comment by GusCaplan** [comment]
discord decides if the image is a gif solely off of the extension, because it is hard to get the mime type in a browser. this is not something lib specific.

**Comment by Marfjeh** [comment]
Hmm alright. thanks
