### ISSUE TITLE
SendMessage function message options doesn't work together

### ISSUE THREAD

**Issue by eybisi** [hydrabolt/discord.js#1293]
Given options {split:true,code:true} just adds ` ``` ` to first message's head and another  ` ``` ` to last message's tail.It should make all separate messages codeblock

**Comment by Gawdl3y** [comment]
This is already how it behaves.
![image](https://cloud.githubusercontent.com/assets/279900/24133613/910f29c0-0dd4-11e7-99ec-5724e4c5e64f.png)
