### ISSUE TITLE
C# Discord bot 401 unauthorized code

### ISSUE THREAD

**Issue by JayCobra** [hydrabolt/discord.js#1294]
my code: 
using Discord;
using Discord.Commands;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiscordBot
{
    class MyBot
    {

        DiscordClient discord;

        public MyBot()
        {
            discord = new DiscordClient(x =>
           {
               x.LogLevel = LogSeverity.Info;
               x.LogHandler = Log;
           });

            discord.UsingCommands(x =>
            {
                x.PrefixChar = '!';
                x.AllowMentionPrefix = true;

            });

            var commands = discord.GetService<CommandService>();

            commands.CreateCommand("Hello")
            .Do(async (e) =>
            {
                await e.Channel.SendMessage("Yo");
            });

                
            discord.ExecuteAndWait(async () =>
            {
                await discord.Connect("token",TokenType.Bot);
              
            });

        }
        private void Log(object sender, LogMessageEventArgs e)
        {
            Console.WriteLine(e.Message);
        }
    
    }
}

Im using the latest .Net version

**Comment by robflop** [comment]
Uh...this is discord.js. JavaScript.

You're looking for discord-net or dsharpplus.

**Comment by Gawdl3y** [comment]
[Discord.NET](https://github.com/RogueException/Discord.Net/tree/dev) or [DSharp+](https://github.com/NaamloosDT/DSharpPlus/).
