### ISSUE TITLE
removeMessageReaction always using undefined as user

### ISSUE THREAD

**Issue by MatthiasSaihttam** [hydrabolt/discord.js#1297]
[This function](https://github.com/hydrabolt/discord.js/blob/136cab240d3dd80a7ff963f94c6f5b21e4802644/src/structures/MessageReaction.js#L62) uses `resolveUserID` to resolve a user id, which it passes to `removeMessageReaction`. `removeMessageReaction` then, at multiple points, attempts to access `.id`of `user` as if it were an object, when it was given a string id already, the first example being [this](https://github.com/hydrabolt/discord.js/blob/dd8907472c3ff9e4754638a8601ae8ff6cd102b4/src/client/rest/RESTMethods.js#L858) line. This causes `MessageReaction.remove()` to not work. I don't have a whole lot of time to do a complex write up, in part just because I others to confirm that this is actually an issue and not specific to my Discord.js installation.

**Comment by Azekthi** [comment]
Can confirm, I was reporting this issue last night in D.JS's server.

**Comment by MatthiasSaihttam** [comment]
Just looked into it a bit more. This is actually a duplicate of #1114, and has been fixed. For some reason I don't understand, this fix hasn't been rolled out yet.
