### ISSUE TITLE
Error in typings

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [hydrabolt/discord.js#1302]
**Typings**: `sendMessage` **=>** `Promise<Message | Message[]>`
**Actually**: `sendMessage` **=>** `Promise<Message>`

Incorrect typing causes errors on compiling:
![image](https://cloud.githubusercontent.com/assets/10401817/24316942/fbecbb06-1124-11e7-9294-1f7fc117ac26.png)

**Comment by SpaceEEC** [comment]
It's actually correct.
When enabling splitting in the messageoption the message will be splitted up in more message when the content exceeds 2k chars.
In that case it would return an array of messages.

**Comment by iCrawl** [comment]
What @SpaceEEC said.
