### ISSUE TITLE
block specific variables

### ISSUE THREAD

**Issue by Rarapony** [hydrabolt/discord.js#1309]
https://github.com/hydrabolt/discord.js/issues/1122
I am also using c9.io for hosting. block specific variables do not work because cloud 9 uses node version 4.7.3
You can get mad at me if you want and I'm sorry but if there is any way I can modify ```class Client extends EventEmitter {``` or find a way to use strict without the other error, I'd love to hear it.

**Comment by iCrawl** [comment]
You can update your node version on c9.
