### ISSUE TITLE
RTP header extensions in voice data

### ISSUE THREAD

**Issue by Yahweasel** [hydrabolt/discord.js#1310]
Recently (last Thursday), the Discord web client started sending voice data with RTP header extensions ( https://tools.ietf.org/html/rfc5285 ). In Discord.js (and many other clients), these headers are being passed unmodified, and since they're obviously not valid Opus data, they cause problems when you try to decode them as Opus:

```
TypeError: The compressed data passed is corrupted
    at NodeOpusEngine.decode (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/opus/NodeOpusEngine.js:23:25)
    at VoiceReceiver.handlePacket (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/receiver/VoiceReceiver.js:147:59)
    at Socket.VoiceReceiver._listener.msg (/home/yahweasel/craig/node_modules/discord.js/src/client/voice/receiver/VoiceReceiver.js:54:14)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:545:8)
```

This bug was reported to Discord's API documentations (since it does not stipulate that any such data will be sent), and their response was approximately "lul not our problem peace out losers" ( https://github.com/hammerandchisel/discord-api-docs/issues/231 ). As such, it seems it's up to API clients to handle it. As the current state in Discord.js is that using PCM mode will crash your bot, something ought to be done :)

In my own bot I was able to work around the extra headers by stripping them out in my Opus packet handling code:

```
        if (chunk.length > 4 && chunk[0] === 0xBE && chunk[1] === 0xDE) {
            // There's an RTP header extension here. Strip it.
            var rtpHLen = chunk.readUInt16BE(2);
            var off = 4;

            for (var rhs = 0; rhs < rtpHLen && off < chunk.length; rhs++) {
                var subLen = (chunk[off]&0xF)+2;
                off += subLen;
            }
            while (off < chunk.length && chunk[off] === 0)
                off++;
            if (off >= chunk.length)
                off = chunk.length;

            chunk = chunk.slice(off);
        }
```

This is sufficient, but there's probably (well, definitely) a better way to handle it at a higher level, with the actual connection state intact. @Fiddlekins reports (see Discord bug report) that the RTP packet type should always be 0x80, but on these faulty packets it's 0x90, so presumably some component of Discord.js or its dependencies should be detecting this and properly parsing the header extensions, even if just to drop them.

I believe that anyone using a bot that listens to voice where some clients are using the web interface will encounter this bug. Probably not already reported simply because there are few such users. Although I haven't tried explicitly replicating the bug since I fixed it in my bot on Saturday, it's not difficult to replicate. Simply create a PCM voice receiver bot, then join the voice channel from a web client and say something. Boom.

(Note: While I mentioned this bug as background in my other bug report, #1296 , that one is with problems connecting to voice in the git version of Discord.js , not with the voice data received. Sorry for the confusion.)

**Comment by GusCaplan** [comment]
@Yahweasel thank you for bringing this up! i already spoke to people on the server about this, we are waiting on more information on the devs before pushing a fix.

**Comment by hydrabolt** [comment]
Thanks for bringing this to our attention! We'll look at this for our next release (after v11.1)

**Comment by hydrabolt** [comment]
Will add this today 👍

**Comment by hydrabolt** [comment]
Fixed (finally!)

I did notice an issue with packets from the mobile client though, so I'll take a look later.
