### ISSUE TITLE
Editing a message problems?

### ISSUE THREAD

**Issue by bjskistad** [hydrabolt/discord.js#1316]
I have the following code:
```
bot.on('message', message => {
  message.edit(filter.clean(message.content));
  if (message.content.substring(0, 5) === '/help') {
    message.channel.sendMessage('// help //\n\n`/help`  displays help\n');
  }
  if (message.content.substring(0, 5) === '/nsfw') {
    message.channel.sendMessage('NSFW words enabled');
  }
  
});

// log our bot in
bot.login(token);
```

I have all the right required modules, `filter` is a module.

The bot is logging that it is ready, (in another part of the code) and it won't edit the message.
How can I fix this?

**Comment by GusCaplan** [comment]
you can't edit other people's messages

**Comment by bjskistad** [comment]
Is there a way I can?

**Comment by bjskistad** [comment]
My bot has all permissions.

**Comment by iCrawl** [comment]
No.

**Comment by bjskistad** [comment]
Would you possibly know how to get roles from a specified user? Or see if they have the roll?

**Comment by GusCaplan** [comment]
**A REMINDER: THE ISSUE TRACKER IS ONLY FOR LIBRARY ISSUES, AND YOU SHOULD NOT EVER CHANGE THE SUBJECT OF AN ISSUE, ESPECIALLY WHEN THE ISSUE IS CLOSED**

https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=roles
