### ISSUE TITLE
Allow URLs to be used inside `sendFile`

### ISSUE THREAD

**Issue by meew0** [hydrabolt/discord.js#132]
As requested on Discord. Should be trivial to implement, just get a stream from superagent/whatever and send it.

**Comment by TehSeph** [comment]
:+1:

**Comment by Lord-Ptolemy** [comment]
I thought you could? As I use dropbox links & shoutcast streams directly into playFile and it works fine. Unless you mean other things besides those.

**Comment by TehSeph** [comment]
derp @meew0 the request was for `sendFile` not `playFile` :p

**Comment by Lord-Ptolemy** [comment]
That makes sense now.

**Comment by meew0** [comment]
Oh right, sorry :P changing it
