### ISSUE TITLE
method to get all server invite codes

### ISSUE THREAD

**Issue by aequasi** [hydrabolt/discord.js#133]

**Comment by khionu** [comment]
...... this is easy enough. You can [create invites](http://discordjs.readthedocs.org/en/latest/docs_client.html#createinvite-channel-options-callback), loop through the [cache](http://discordjs.readthedocs.org/en/latest/docs_cache.html).... just gotta code it.

**Comment by meew0** [comment]
Not create them, get existing ones, which discord.js doesn't support yet (as far as I know).
