### ISSUE TITLE
emojiCreate and emojiDelete events not firing

### ISSUE THREAD

**Issue by nficca** [hydrabolt/discord.js#1333]
Tested off master and from npm release. Same results on both.
```
<Client>.on('emojiCreate', emoji => {
  console.log(`${emoji.name} created`); // Does not get called!
});

<Client>.on('emojiDelete', emoji => {
  console.log(`${emoji.name} created`); // Does not get called!
});
```
Steps to reproduce:
1. Attach handlers to each of the Client events like above
2. Create a new custom emoji by going Server Settings > Emojis > Upload emoji
3. Expected: log, Actual: no log
4. Delete the emoji by clicking "Remove"
5. Expected: log, Actual: no log

**Comment by nficca** [comment]
Just tested `emojiUpdate` and got the same results.

**Comment by GusCaplan** [comment]
![](https://cdn.meme.am/cache/instances/folder743/400x/67534743.jpg)

https://github.com/hydrabolt/discord.js/blob/master/src/client/websocket/packets/handlers/GuildEmojisUpdate.js

**Comment by nficca** [comment]
I think I've found the issue.

https://github.com/hydrabolt/discord.js/blob/master/src/client/websocket/packets/handlers/GuildEmojisUpdate.js#L21

It seems that the idea here is that `data.emojis` contains the latest list of emojis, while `guild.emojis` contains the cached list of emojis. However, I've tested this and found that they each store the **same emojis**. 

So what's happening is that `cachedEmoji` is **always found** (so the `emojiCreate` event is never fired) and `cachedEmoji.equals(emoji, true)` is **always true** (so the `emojiUpdate` event is never fired).

I would try to fix this and PR, but as I'm not familiar enough with this repo and discord's api to know where to go from here.

**Comment by iCrawl** [comment]
At the moment we aren't quite sure if this is a discord issue or not (I marked it as one regardless).
@GusCaplan mentioned that emojis, when you add or remove one, shouldn't trigger the guild_update websocket event.
So for now we can't really do more than wait since fixing them, while it may actually be a discord API bug, would only be for so long until they fix it.
