### ISSUE TITLE
Discord.js Ban Isse : Unhandled promise rejection (rejection id: 2): Error: Bad Request

### ISSUE THREAD

**Issue by badluke1** [hydrabolt/discord.js#1352]
// I'm working on a bot for my personal server, but I get this error when trying to ban someone.
//Here's the code.

`
function SendEmbedNoFields(color, author, authorimage, title, url, description, footer, footerimg, parent){
    if(parent !== null){
        parent.sendEmbed({
            color: color,
            author: {
                name: author,
                icon_url: authorimage
            },
            title: title,
            url: url,
            description: description,
            timestamp: new Date(),
            footer: {
                icon_url: footerimg,
                text: footer
            }
        })
    }else{
        console.error("Parent of embed message is null! Please check the code and try to fix it.");
    }
}

function BanUser(userr, reason, channeel, msg){
    if(userr !== null){
        let UserToBeBanned = userr
        let ReasonToBeBanned = reason
        if(UserToBeBanned === null){
            // NULL THEN
            SendEmbedNoFields(Config.errorcolor, Client.user.username, Client.user.avatarURL, "Error!", "", "Please specify a user to be kicked! ( YOU DID NOT SPECIFY A USER TO BE KICKED )", "BracketBot Developed by : Developer", "", channeel)
        }else{
            // NOT NULL THEN
            try{
                msg.guild.member(msg.mentions.users.first()).ban()
                SendEmbedNoFields(Config.successcolor, Client.user.username, Client.user.avatarURL, "", "Server Ban", "We have successfully banned " + UserToBeBanned + " for " + ReasonToBeBanned + "!", "BracketBot Developed by : Developer", "", channeel);
                SendEmbedNoFields(Config.successcolor, Client.user.username, Client.user.avatarURL, "", "Server Ban", "You were successfully banned for " + ReasonToBeBanned + "!", "BracketBot Developed by : Developer", "", userr);
            }
            catch(err){
                console.log(err)
            }
        }
        if(ReasonToBeBanned === null){
            ReasonToBeBanned = "not following the rules!"
        }
    }else{
        SendEmbedNoFields(Config.errorcolor, Client.user.username, Client.user.avatarURL, "Error!", "", "We could not kick " + userr + "! ( THEY ARE NULL )", "BracketBot Developed by : Developer", "", channeel);
    }
}

if(commandIs("ban", message)){
        if(args.length < 2){
            SendEmbedNoFields(Config.errorcolor, Client.user.username, Client.user.avatarURL, "Error!", "", "You must specify who to ban! ( USER NOT FOUND! )", "BracketBot Developed by : Developer", "", message.channel);
        }else{
            if(args.length >3){
                SendEmbedNoFields(Config.errorcolor, Client.user.username, Client.user.avatarURL, "Error!", "", "You have too many arguments! ( OVER 3 ARGUMENTS! )", "BracketBot Developed by : Developer", "", message.channel);
            }else{
                BanUser(message.mentions.users.first(), args[3], message.channel, message)
            }
        }
    }
`

**Comment by badluke1** [comment]
There's no error... But its somewhere in the ban function

**Comment by bdistin** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
