### ISSUE TITLE
Why does guildMemberAdd not work?

### ISSUE THREAD

**Issue by mccrafter1212** [hydrabolt/discord.js#1358]
Here's my code:

`client.on('guildMemberAdd', (guild, member) => {
    member.sendMessage("Welcome to the server!")
});`

I get this error:
    member.sendMessage(member, "Welcome to the server!")
                 ^

TypeError: Cannot read property 'sendMessage' of undefined

So, for some reason member is becoming undefined. I'm not sure how to fix. Please help!

**Comment by GusCaplan** [comment]
the only arg given to the callback is member, just to clear this up
