### ISSUE TITLE
React on a user going from offline to online

### ISSUE THREAD

**Issue by TheJellyfishTFP** [hydrabolt/discord.js#136]
I'm trying to make my bot greet people when they come online on a server. It works now by using the presence event, except that it also greets the people who go from afk to online or switch games. Is there a way to check the status of the user before it changed? Here's the relevant part of the code, I just edited the ping pong example.

	bot.on("presence", function (pUser, pStatus, pGameID) {
		if (pStatus === "online")
		{
			switch(pUser.username)
			{
				//bunch of cases with special usernames go here, example
	case "example":
					{
						bot.sendMessage(/*channel ID goes here */,"example message")
						console.log(pUser.username)
						break;
					}
                
				default:
					{
						bot.sendMessage(/*channel ID goes here*/, "Welcome back " + pUser.mention() + "!")
						console.log(pUser.username)
						break;
					}
			}
		}
	});

Thank's in advance!

**Comment by TheJellyfishTFP** [comment]
I have the feeling this is the wrong place to ask this sonehow... If so, apologies.

**Comment by khionu** [comment]
You need to cache their last presence updates and compare. Try implementing this: https://www.npmjs.com/package/cache-manager

**Comment by hydrabolt** [comment]
Shouldn't have to do that, I'll just go about fixing this internally and
reply back

**Comment by khionu** [comment]
But.... that makes sense.... Presence updates occur in any change in state, not just from offline... I mean, maybe adding an event for becoming online/away/etc and one to handle game updates, I can see, but raw PresenceUpdates.....

**Comment by abalabahaha** [comment]
Or, we could add a user-before-presence-update parameter.

**Comment by TehSeph** [comment]
Yeah wouldn't the [userUpdated](https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1393) event also be able to handle everything the presence event above does as well? Why not just merge the two and leave it to the end user to determine what changed?

**Comment by khionu** [comment]
This I can go for. Seems a little weird to have such little data passed as anything but an object, though. Like this
```
Client.on("presence", (data) => {
    var statusBefore = data.prior;
    var statusAfter = data.current;
    /*
        function
    */
}
```

**Comment by TheJellyfishTFP** [comment]
@khionu I know. I just wanted to know if there was a way to fix it. I realize now that this might've been the wrong place to ask.

**Comment by khionu** [comment]
No, actually, you brought up a good discussion point that will lead to a good adjustment to the Library.

**Comment by abalabahaha** [comment]
After some discussion, it appeared that most people seem to prefer merging userUpdated into presence, and supplying a before User and after User. I attempted this in 0164d3e (still needs indev testers).

**Comment by AroojSyed** [comment]
how to set application status online or offline using toggle switch in react js
