### ISSUE TITLE
error when doing npm install discord.js

### ISSUE THREAD

**Issue by Ludde856x** [hydrabolt/discord.js#1360]
ok so i was wanting to make a discord bot and i was gonna use a tutorial which used this but when i dod npm install --save discord.js in cmd.exe this happened

npm http GET https://registry.npmjs.org/discord.js
npm http 304 https://registry.npmjs.org/discord.js
npm WARN engine discord.js@11.0.0: wanted: {"node":">=6.0.0"} (current: {"node":"v0.10.13","npm":"1.3.2"})
unbuild discord.js@11.0.0
npm http GET https://registry.npmjs.org/pako
npm http GET https://registry.npmjs.org/tweetnacl
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/types/node
npm http 304 https://registry.npmjs.org/pako
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/ws
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (D:\nodejs\node_modules\npm\lib\cache.js:687:35)
npm ERR!     at D:\nodejs\node_modules\npm\lib\cache.js:675:5
npm ERR!     at saved (D:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "discord.js"
npm ERR! cwd D:\NOOTBOT9000
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! type non_object_property_load
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\NOOTBOT9000\npm-debug.log
npm ERR! not ok code 0

**Comment by GusCaplan** [comment]
as the error says, you need to update your version of node
