### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by MonkeyPlayzMC** [hydrabolt/discord.js#1364]
Same as before this is my own code
Discord.roles.find("name", "Owner");

**Comment by bdistin** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by iCrawl** [comment]
Opening another issue isn't going to change things. Please go to the official server.

Then again, `Discord.roles.find()` is not valid.
You need a Collection with the roles property that you can iterate through.

**Comment by hydrabolt** [comment]
Any further issues such as this which aren't actually related to problems in the library itself will result in a ban from the repo
