### ISSUE TITLE
Error when installing discord.js

### ISSUE THREAD

**Issue by tom-barnes** [hydrabolt/discord.js#1367]
Please help, this is what happens, any suggestions why or how I could fix it?
![eyj1cmwioijodhrwoi8vaw1hz2uuchjudhnjci5jb20vaw1hz2uvnzlimwrhogq4nzljndrlzwi4nmixmjk3njm2mznmn2yucg5nin0](https://cloud.githubusercontent.com/assets/27276184/24901004/a01a9bdc-1e9d-11e7-95da-0380a156523f.png)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by tom-barnes** [comment]
what discord server dummy?

**Comment by elithrar** [comment]
@tom-barnes It's linked in the comment and in the README.
