### ISSUE TITLE
data.members, roles, or channels is undefined when creating a new Server on joinServer

### ISSUE THREAD

**Issue by brussell98** [hydrabolt/discord.js#138]
So sometimes when my bot is joining or leaving a server I get this error and my bot crashes.
[I pasted the most recent occurrence here: http://hastebin.com/simajucili.vbs](http://hastebin.com/simajucili.vbs)
I really have no clue how to fix this or even replicate it so I was hoping someone could help.

Node version: 4.2.4
Discord.js version: 5.3.2

**Comment by meew0** [comment]
It looks like this is because the server that gets created from the data when handling a `SERVER_CREATE` event doesn't have any of either roles or members (not sure which). This should be easy to fix, just add a null check for these

**Comment by brussell98** [comment]
After changes to my code I have yet to get this again. Therefor this issue can be closed.

**Comment by meew0** [comment]
What exactly did you change, for future reference?

**Comment by brussell98** [comment]
The only code changed was the removal of lines [211-252](https://github.com/brussell98/BrussellBot/blob/master/BrussellBot.js#L211)   
Now I just have [it log "Left server "+objServer.name](https://github.com/brussell98/BrussellBot/blob/heroku/BrussellBot.js#L188)

**Comment by brussell98** [comment]
Seems like I spoke too soon. Now i'm getting this a lot so I have new data.
The error is happening when the bot joins a server with this code:
```
>>> bot.joinServer(msg.content, function (err, server) {
				if (err) {
					bot.sendMessage(msg, "Failed to join: " + err);
					logger.log("warn", err);
				} else {
					logger.log("info", "Joined server: " + server.name);
                    bot.sendMessage(msg, "Successfully joined ***" + server.name + "***");
```
Nothing after the marked line is executed. It just gives me an error and crashes

**Comment by abalabahaha** [comment]
I expected as much.

**Comment by brussell98** [comment]
From researching, it seems that what's happening that `data` [passed here](https://github.com/hydrabolt/discord.js/blob/master/src/Client/InternalClient.js#L1135)  doesn't contain either `data.roles` `data.members` or `data.channels` when creating a new server.
