### ISSUE TITLE
how can i give to all members the same role... discord.js

### ISSUE THREAD

**Issue by AAAAAAAAAAkjhgfcdsdrtyuilo** [hydrabolt/discord.js#1388]
how can i give to all members the same role to with one command
Like 

``Me - Today at 12:17 PM``
+giveall lol
``Bot - Today at 12:17 PM``
I gived all members **lol**

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
