### ISSUE TITLE
Crash on linking a URL

### ISSUE THREAD

**Issue by nicholastay** [hydrabolt/discord.js#139]
*Screenshot of issue: http://i.imgur.com/AheCbuK.png*

After commit #2000b62, the above issue happens. However, it only crashes on a message with a URL in it, as demonstrated. If I use a commit anywhere before that specific commit which "fixes the references" in the cache stuff, everything is ok and the crash does not occur.

**Comment by hydrabolt** [comment]
I can't reproduce this unfortunately, could you try the latest commit https://github.com/hydrabolt/discord.js/commit/8a8ba51c2b77711c860dd62e8db0e613959a30a4

**Comment by abalabahaha** [comment]
@nicholastay what version of Node.JS are you running?

**Comment by nicholastay** [comment]
I have tried the latest commit and the issue still occurs

@abalabahaha I am on v0.12.9 of node.js as last time I tried a higher version the voice encoding would not work, so I had to stick on this lower version.

**Comment by abalabahaha** [comment]
@nicholastay the crash appears to be caused by Babel not transpiling an ES6 function (0.12 doesn't have ES6 stuff)

Have you tried reinstalling discord.js after changing node versions? Are there errors when installing discord.js?

**Comment by nicholastay** [comment]
@abalabahaha I have reinstalled discord.js after installing a different
version of node.js and there are no errors while doing so.

I assume from my debugging that it is `Object.assign()` that is not
supported in v0.12.x (and below). Perhaps a polyfill could be added for us
or some configuration to Babel could help?

**Comment by TehSeph** [comment]
He would have a point there.
`.assign()` is ES6 code and isn't being properly transpiled by Babel for lib.

**Comment by nicholastay** [comment]
Well I have indeed confirmed this myself. `Object.assign()` is the unsupported function, and in my bot I added a polyfill for it and it fixed the issue.

Perhaps this polyfill could be added to the transpiled ES5 Babel code for those not using updated versions of node.js?
