### ISSUE TITLE
Remove uws support

### ISSUE THREAD

**Issue by iCrawl** [hydrabolt/discord.js#1393]
Starting with **v12.0.0** we will be removing support for uws, as it introduces a lot of problems, and still does not handle disconnects correctly. 
Destroying your client and and login on a completely new instance is not a workaround we want to work with, `resumes` should always be preferred.

This holds especially true when it comes to the latest implementation from hammerandchisel where you are limited to 1000 sessions in a 24h period.
hammerandchisel/discord-api-docs#215

#### Changes:
- Dropping uws support

**Comment by BobbyWibowo** [comment]
Gotcha. For some reason, whenever I use uws, the bot won't login anyways. Though it always works fine with bufferutil.

**Comment by GusCaplan** [comment]
@iCrawl i saw you removed uws, but that would be a semver major change right? it was also a "planned for v12" thing, as this issue says

**Comment by iCrawl** [comment]
@GusCaplan The functionality was not removed, just the information that it can be used and the peerDependency entry in the package.json. People can still use it in v11.1.

**Comment by iCrawl** [comment]
Issues with uws have been fixed in lastest master, so this will put on hold until new errors occur which we are unable to fix from a library standpoint.

**Comment by w0298i** [comment]
The uws package is no longer available, so you don't really have a choice.
