### ISSUE TITLE
Allow setting bitrate on VoiceConnection

### ISSUE THREAD

**Issue by TurplePurtle** [hydrabolt/discord.js#1396]
**Please describe the problem you are having in as much detail as possible:**
When sending audio e.g. via `voiceConnection.playConvertedStream()`, there is no way of specifying the bitrate used to encode the audio stream. I would like to be able to specify the quality of the audio being sent.

**Comment by PgBiel** [comment]
You specify that at the voice channel itself, it's a setting

**Comment by PgBiel** [comment]
![How to set it](http://i.imgur.com/OqxP0rE.png)

**Comment by TurplePurtle** [comment]
@PgBiel If I understand correctly, that only saves a suggested bitrate to the discord server. However, it doesn't actually set the bitrate that the local opus encoder is using to encode the audio stream. Looking through the code I didn't find anything that changed the node-opus or opusscript settings.

**Comment by GusCaplan** [comment]
@TurplePurtle it isn't exposed atm because it would be "tricky" but we are planning to do this at some point.
