### ISSUE TITLE
Unsetting game does not work on mobile

### ISSUE THREAD

**Issue by Jotaro31** [hydrabolt/discord.js#1399]
After a game has been set either with `<ClientUser>.setGame(...)` or `<ClientUser>.setPresence(...)`, it is no longer possible to completely hide the "Playing" status on mobile (Android) and instead turns into "Playing null", regardless of the method used to unset the game.  

Desktop and Web clients display no additional status as expected.

```js
bot.user.setGame(null);
// no "Playing ..." text on Desktop - "Playing null" on Android

bot.user.setGame("");
// "Playing" both on Desktop and Android

bot.user.setGame();
bot.user.setGame(undefined);
bot.user.setPresence({status:"online"});
bot.user.setPresence({status:"online", game:null});
bot.user.setPresence({status:"online", game:undefined});
bot.user.setPresence({status:"online", game:{}});
bot.user.setPresence({status:"online", game:{name:null}});
// all of these hide the "Playing ..." on Desktop, but show "Playing null" on Android
```

**Further details:**

- discord.js version: 11.0.0
- node.js version: 7.9.0
- Operating system: Win 10 / Android 5.0.1
- This is a minor inconvenience, but feels unpolished

- [x] I have also tested the issue on latest master, commit hash: 94e2a853861d6752606e3d9bac2d359657e309b0

**Comment by hydrabolt** [comment]
Thanks for reporting the issue!

As a side note, `bot.user.setPresence({status:"online", game:{name:null}});` and `bot.user.setPresence({status:"online", game:{}});` would still cause the described issue after this fix as the `game` object isn't null - you can fix this by just using `game: null`
