### ISSUE TITLE
No message sent on using bot.reply(msg.channel, "message")

### ISSUE THREAD

**Issue by zaza7** [hydrabolt/discord.js#140]
As I was writing a command that sent a message tagging the author if not mentions were passed I stumbled that if I used `msg.channel, "message"` it would not send the message but if I use `msg, "message"` it sends the reply. Upon a bit of debugging done I found that if using the former "Destination is not resolvable to a message!" is returned.

Also bot.sendMessage(msg/msg.channel/msg.channel.id, "message") does work so it seems to be isolated to bot.reply

```
Discord.js: NPM 5.3.2
Node.js: LTS 4.x.x


CODE: 
bot.reply(message.channel, "Msg here");

bot.reply(message.channel.id, "Msg here");


ERROR:
[Error: Destination not resolvable to a message!]
```

**Comment by TehSeph** [comment]
Don't add the channel or id, just use `message` when using `.reply()`
It will resolve automatically and append a mention if not in a PMChannel.

**Comment by zaza7** [comment]
Hmm alright that's good to know. Thanks for the reply :+1:

**Comment by abalabahaha** [comment]
A bit of logic would be useful here. You can't really reply to an entire channel, but you can reply to what someone said, or the person themself.

**Comment by bruh11123** [comment]
It's supposed to be message.reply("Message Here")

And you can do message.channel.send("Message Here")

And if you want it to dm someone message.member.send("Message Here")
