### ISSUE TITLE
[suggestion] Message.author object should conditionally hold "GuildMember" instead of "User" object

### ISSUE THREAD

**Issue by PabloDons** [hydrabolt/discord.js#1405]
during multiple instances I have had to use the author's id to fetch the GuildMember object from the guild.members collection

instead of Message.author returning a User object, my code would certainly be more efficient if it returned  a GuildMember object.

Looking at the documentation, it appears GuildMember doesn't extend the User object, and instead has a "user" property that holds the User object. My first reaction to this is that I find it very strange and unnecessary. Obviously there must be an explanation. but as far as my knowledge goes about this library, there's no real reason why the Message.author property shouldn't conditionally be a GuildMember object. Conditional object type has been done before in this library anyway

**Comment by iCrawl** [comment]
`message.member` is a thing.

**Comment by PabloDons** [comment]
aah, I didn't see that. Though I still think that GuildMember should extend User. Having two unrelated objects to represent a user is strange to me. I'll try changing it myself and making a PR, but I'm not too familiar with classes, so no promises

**Comment by hydrabolt** [comment]
The reason `GuildMember` doesn't extend `User` is because if a user changes any of their details (e.g. their username), we'd have to modify multiple `GuildMember` instances of that user to reflect the change -- this is a lot more expensive than to just `GuildMember` contain a `User` instance.

That being said, we are considering using Proxies for v12 so that `GuildMember`s will virtually extend `User` without having the same performance hits.

**Comment by PabloDons** [comment]
that's very strange, I would imagine that making all the GuildMember instances have references instead of their own property value for things like username, you wouldn't need to change it for every single instance. Isn't the user property also a reference?

**Comment by GusCaplan** [comment]
members don't have usernames. users have usernames. users don't have roles. members have roles.  the terminology and where things are placed is very much by design.
