### ISSUE TITLE
GuildMembers as proxy objects

### ISSUE THREAD

**Issue by xDdude** [hydrabolt/discord.js#1415]
**Please describe the problem you are having in as much detail as possible:**
I've seen hydra talk about this once or twice and I was hoping we could have a discussion about the use of ES6 `Proxy`  objects when interacting with `GuildMember` instances. (Kinda related to #1405)

I did some of my own testing and it worked quite well as it simplified the relationship between `GuildMember` instances and `User` instances whilst still maintaining the performance benefits of storing the `User` instance as a reference on the `GuildMember` instance. Overall it is just more clear and concise that all properties of a user are accessible on the guild member directly, therefore simulating some kind of class extension.

Here is the main bit of code I was working with, I ended up making a static method on the GuildMember class to reduce the amount of times I had to use this. 
```js
const guildMember = new Proxy(new GuildMember(guild, guildUser), {
  get: (member, prop) => {
    if (Reflect.has(member, prop) && prop !== 'user') return Reflect.get(member, prop);
    else if (Reflect.has(member.user, prop)) return Reflect.get(member.user, prop);
  },
  getPrototypeOf: (member) => {
    return Reflect.getPrototypeOf(member);
  }
});
// Probably a few more traps
```
Using this allowed me to access any property of the user object from the guild member object itself whilst hiding the fact that the `<GuildMember>.user` property is still there. Obviously implementing this fully would be a little bit different and maybe hydra has something different in mind (?) but I think the benefits are there.  I can see potential issues such as the performance of proxies, initial confusion, debugging (console logs) and the fact that it is going to break a lot of code, but since v12 is already going break a lot of stuff I don't see why this would be too much of an issue.

I was just wondering what the general opinion of something like this was?

**Comment by GusCaplan** [comment]
users and members are separate on purpose (is it that hard to type .user.username???) and proxies are **MORE SLOW THAN YOU COULD EVER IMAGINE** so i don't think we will be doing this any time soon

**Comment by xDdude** [comment]
I just think that this kind of inheritance facade makes the lib easier to work with, tbh it just doesn't make much sense that there are basically two objects representing the same entity. Obviously this doesn't fix that problem internally but from the outside it appears like it does.

Also I was just wondering if you have some test cases or some kind of benchmark that shows how bad Proxy and Reflect are? I'm not doubting you considering some other implementations that came with es6 but I assumed they weren't as bad as you're describing them.

**Comment by xDdude** [comment]
ill just close this, it seems quite apparent that gus wont even consider this, so im guessing other collaborators and contributors will reflect a similar opinion therefore kinda msking this discussion pointless. kek

**Comment by aemino** [comment]
I support this, although I think there are some challenges that need to be worked out...

**Comment by hydrabolt** [comment]
I agree with aemino, it's very annoying to have to call member.user first and I'd be happy to try and look at and improve a solution using proxies or something

**Comment by hydrabolt** [comment]
Decided against this for the sake of performance
