### ISSUE TITLE
صورة " ضبابيةه

### ISSUE THREAD

**Issue by t-ToT** [hydrabolt/discord.js#1417]
![hd 2](https://cloud.githubusercontent.com/assets/28009199/25446654/de3b886c-2aba-11e7-844e-17a0fb943927.PNG)

**Comment by hydrabolt** [comment]
?

**Comment by GusCaplan** [comment]
name of pr is literally "blurry picture"

**Comment by hydrabolt** [comment]
gus this is an issue

**Comment by GusCaplan** [comment]
did i say otherwise? 👀
