### ISSUE TITLE
messageUpdated event new user object and old user object are same

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#142]
http://discordjs.readthedocs.org/en/stable/docs_client.html#messageupdated
Discord.js: NPM 5.3.2
Node: LTS 4.2.3
```javascript
bot.on('messageUpdated', function(newMSG, oldMSG) {
    console.log('[' + timestamp + '] ' + 'MESSAGE UPDATE: ' + newMSG.author.username + '[' + newMSG.author.id  + "] updated message. " + oldMSG.content  + ' --> ' + newMSG.content );
    if (newMSG.channel.server.id === '42463947818795009' || newMSG.channel.server.id === '97805743893270528' || newMSG.channel.server.id === '102588320181125120') {
        badWord(newMSG);
    }
});
```

```
WARNING! Inappropriate Word detected! by Lord Ptolemy [afk][102529479179509760] in Uskarian Servers[102588320181125120]/general[102588320181125120]: fuck

[Tue, 12 Jan 2016 03:08:17 GMT] MESSAGE UPDATE: Lord Ptolemy [afk][102529479179509760] updated message. fuck tub --> fuck tub
```

newMSG & oldMSG are the same.

Am I just missing something or is it really broken?

**Comment by TehSeph** [comment]
It looks like the event is passing a reference to the original Message object instead of a copy. So when the object gets updated in the line before the event is fired, the reference is updated as well, and both messages passed are the new message.

**Comment by abalabahaha** [comment]
can someone test latest indev

**Comment by TehSeph** [comment]
The problem is still in Indev.
`InternalClient.js` - [L1167](https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1167), [L1181](https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1181), & [L1182](https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1182)

**Comment by abalabahaha** [comment]
check 76ab439...

**Comment by TehSeph** [comment]
Oh, weird. That didn't show up for me like 5 mins ago when I made that comment linking the code.

**Comment by zaza7** [comment]
Running latest indev version, can confirm messageUpdated is now showing the old message and new message properly.

**Comment by khionu** [comment]
Confirmed fixed, indev

**Comment by abalabahaha** [comment]
This wasn't entirely fixed... Check in next time :P

**Comment by khionu** [comment]
>< Will do..
