### ISSUE TITLE
HELP WITH ADD MEMBERS TO ROLE.

### ISSUE THREAD

**Issue by Beaastexe** [hydrabolt/discord.js#1423]
Hello, i am new in discord.js and i want to create a bot to add members to role or remove.
Example, I want to put the user "Beaast_exe" in the role "Beaast" (this role has already created) and i write in the chat: "@DruggedBot role Beaast add @Beaast_exe" or ".role Beaast add @Beaast_exe".
Can anyone give me the code please ?

**Comment by hydrabolt** [comment]
Did you even read the issue template?

**Comment by Beaastexe** [comment]
no results

**Comment by Beaastexe** [comment]
i click in question and that's a error saying "no results"
