### ISSUE TITLE
createRole isn't setting role position

### ISSUE THREAD

**Issue by Vaeb** [hydrabolt/discord.js#1465]
Guild.createRole does not set the created role's position when a `position` value is defined in its roleData parameter. Calling setPosition for the created role still works fine. There are no errors, and printing the created role's position always results in `1`.

Might not be related, but usually this will result in two roles having the position value of `1` (which may be a separate issue?), however when setPosition is called on a different role, the position values sort themselves out (http://i.imgur.com/KmAnqP6.png, http://i.imgur.com/IAgsRMo.png, http://i.imgur.com/PwLi85X.png)

**Example code:**
```js
guild.createRole({name: "testRole", color: 0x00E676, position: 6})
.then(role => console.log(role.position))
.catch(console.error);
```

- discord.js version: 11.1.0 (tested on both Stable and Master)
- node.js version: v7.10.0
- Operating system: Ubuntu 16.04.2 LTS (Xenial)
- Priority: Medium

- [x] I have also tested the issue on latest master, commit hash: e6437388cfec19ab5804839b64504e379e9bb9a6

**Comment by GusCaplan** [comment]
this is a discord api thing not a discord.js thing
