### ISSUE TITLE
Support for RichEmbed#SetImage Height and Width parameters

### ISSUE THREAD

**Issue by Favna** [hydrabolt/discord.js#1468]
**Please describe the problem you are having in as much detail as possible:**

Discord API has Height and Width parameters for RichEmbeds on the Image [as seen here](https://discordapp.com/developers/docs/resources/channel#embed-image-structure). This is however not supported by DiscordJS. Allowing these optional parameters are useful for when developers want to resize images in any shape or form.

**Include a reproducible code sample here, if possible:**

Raw JSON that would go to Discord API:
```json
"embeds": [{
        "image":{
        "url":"IMAGE_URL_STRING",
        "height":IMAGE_HEIGHT_INTEGER,
        "width":IMAGE_WIDTH_INTEGER
        }
    }]
```

Example DiscordJS code:

```js
var embed = new Discord.RichEmbed();
embed.setImage("https://developers.google.com/identity/images/g-logo.png", 200, 200);
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 7.9.0
- Operating system: Raspbian
- Priority this issue should have – please be realistic and elaborate if possible: Low. There is no priority on this issue, but it would be a really nice addition to get in DiscordJS 11.2 / 12.0 whichever is the next.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Those are read-only, you can't modify those.

**Comment by Favna** [comment]
Oh really? crap sorry. That is not mentioned on the Discord API's page.

**Comment by jedabero** [comment]
That is indeed not mentioned, whats mentioned is:
> For the embed object, you can set every field except type (it will be rich regardless of if you try to set it), provider, video, and any height, width, or proxy_url values for images.

https://discord.com/developers/docs/resources/channel#create-message-limitations

Still not sure why setting the width and height is not working

**Comment by monbrey** [comment]
You literally quoted the sentence listing width and height as exceptions that can't be set.

It wasn't possible in May 2017 when this issue was closed and it still isn't possible now.

**Comment by jedabero** [comment]
> You literally quoted the sentence listing width and height as exceptions that can't be set.
> 
> It wasn't possible in May 2017 when this issue was closed and it still isn't possible now.

oops my bad, I read it wrong
