### ISSUE TITLE
Dispatcher ends right away. Reason is stream?

### ISSUE THREAD

**Issue by Jwiggiff** [hydrabolt/discord.js#1472]
**Please describe the problem you are having in as much detail as possible:**
I've been having this problem for a few weeks. My bot disconnects right away after connecting to a voice channel. The dispatcher end event is triggered immediately. It says the reason is stream, but I'm not sure how to fix that. Also, I only get this problem in this directory on my ubuntu server. If I run different code that does the same thing in a different directory it works, and running the exact same code on my windows 10 PC works too.

**Include a reproducible code sample here, if possible:**
```js
let { user1 } = args;
      let user = msg.guild.member(user1);
      if (!user.voiceChannel) {
        return msg.channel.sendMessage('Error: It didn\'t work!\nThe user needs to be connected to a voice channel, Sil$      }
      console.log('trolling ' + user)
      //The soundtracks jarvis plays when he trolls you
      var trolls = {
        0 : "./lib/Sounds/Air Horn.mp3",
        1 : "./lib/Sounds/Rick Roll.mp3",
        2 : "./lib/Sounds/Pokemon Go.mp3",
        3 : "./lib/Sounds/Sandstorm.mp3"
      };
      var randomTroll = trolls[Math.floor(Math.random() * (3 - 0 + 1) + 0)];
      var voiceChannel = user.voiceChannel;
      voiceChannel.join()
      .then(connection => {
        console.log('Connected!');
        const dispatcher = connection.playFile(randomTroll);
dispatcher.on('debug', (info) => {
          console.log(info);
        });
        dispatcher.on('error', (info) => {
          console.log(info);
        });
        dispatcher.on('end', (reason) => {
          console.log(reason);
          voiceChannel.leave();
        });
      })
      .catch(console.log);
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 7.9.0
- Operating system: Ubuntu Server 16.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible:

- [x ] I have also tested the issue on latest master, commit hash:
How do I get the commit hash?

**Comment by JMTK** [comment]
I'm not sure how you can get the commit hash from your current version if you're pulling off the master branch, but the commit hash is 
![image](https://cloud.githubusercontent.com/assets/877114/25807288/4f786802-33d4-11e7-98ba-226fd22f051f.png)
the part after /commit/ in the URL. In your `package.json` file, you can specify the commit hash optionally(it uses the latest commit without it).

**Comment by CharlotteDunois** [comment]
You can get the commit hash from `node_modules/discord.js/package.json`. The property name is `_shasum`.

**Comment by iCrawl** [comment]
Sounds more like an issue on your end than on the lib, considering how you described it.

**Comment by hydrabolt** [comment]
A few users have mentioned this only when using a linux distro

**Comment by Jwiggiff** [comment]
Hey I sliced my problem, I just reinstalled everything but I only installed node-opus, and not opusscript. I used to have both installed before

**Comment by atsaplin** [comment]
I have the exact same issue, and removing opusscript + installing node-opus did not fix it

**Comment by amishshah** [comment]
@atsaplin if you're having this issue, please create a new one instead!
