### ISSUE TITLE
.send dont works for rich Embeds Depracated .sendEmbed works fine

### ISSUE THREAD

**Issue by Zelle97** [hydrabolt/discord.js#1473]
Hello I recognized that the send() method wont work for Rich Embeds.
Correct me if im wrong but I tried with the sendEmbed Method and it works just fine.

**code sample:**
```js
else if (msg.content.startsWith(prefix + "test")) {

        var summoners = require("someJSON");
        general.leagueFunctions.getLolRankedInfoEmbed(summoners).then((embedArray) => {
            var promises = []
            for (var i = 0; i < embedArray.length; i++) {
                promises.push(msg.author.sendEmbed(embedArray[i]))
//This wont work. Error: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: Cannot send an empty message
                //promises.push(msg.author.send(embedArray[i]))
            }
            Promise.all(promises).then(() => {
                msg.author.send("GL HF!");
            })
        })


    }
```

**Further details:**

- discord.js version: 11.0.0
- node.js version: 6.10.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

Not that important. Works fine with the old implementation.

**Comment by dragonfire535** [comment]
For send you must do `msg.send({ embed: <embed> })`. Also, please ask questions such as this in the discord.js server, not the issue tracker.

**Comment by Zelle97** [comment]
Well If i dont want to send a message to the channel but to the user i have to use msg.author dont I ?
But still thanks I will close this issue and move on to the discord server
