### ISSUE TITLE
member.setVoiceChannel not working

### ISSUE THREAD

**Issue by curz46** [hydrabolt/discord.js#1476]
**Please describe the problem you are having in as much detail as possible:**

The `member.setVoiceChannel` method doesn't appear to work.
When called, it throws `TypeError: Converting circular structure to JSON` and after a while throws `Error: socket hang up` and crashes.

**Include a reproducible code sample here, if possible:**
```js
import { Client } from 'discord.js'
const client = new Client()

client.on('message', message => {
  if (message.content === 'test') {
    console.log('hi')
    const channel = message.guild.channels.find('name', 'voicechannel')
    message.member.setVoiceChannel(channel)
  }
})

client.login('xxx')
```

**Further details:**

- discord.js version: 11.1
- node.js version: v7.4.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: medium, library does not have support for moving guild members to different channels with this broken.

- [x] I have also tested the issue on latest master, commit hash:
f95f18b586069bb40ebe027c4a014a0263190641

**Comment by iCrawl** [comment]
Fixed in ff822970 and e3c3a4fd respectively.
