### ISSUE TITLE
Crashing on message.member if the author is not a guildMember (i.e. webhook bots or DMs)

### ISSUE THREAD

**Issue by Favna** [hydrabolt/discord.js#1477]
### **Please describe the problem you are having in as much detail as possible:**
A TypeError crash occurs when checking the message author's roles through `message.member.roles` or `message.guild.member(message.author).roles` in case the author is a bot created by a discord webhook. The exact type error (logged from code snippet below) is as follows:

```
TypeError: Cannot read property 'roles' of null
    at Client.client.on.msg (D:\UserFiles\DevProjects\testbot\app.js:11:19)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at MessageCreateHandler.handle (D:\UserFiles\DevProjects\testbot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\UserFiles\DevProjects\testbot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (D:\UserFiles\DevProjects\testbot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:329:35)
    at WebSocketConnection.onMessage (D:\UserFiles\DevProjects\testbot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:292:17)
    at WebSocket.onMessage (D:\UserFiles\DevProjects\testbot\node_modules\ws\lib\EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
```

The issue is caused by `message.member` (or `message.guild.member(msg.author)`) being `null` for webhook bots or if the bot runs in DM.

Lastly, here is as an attachment the NPM Debug log: [2017-05-09T22_28_32_710Z-debug.txt](https://github.com/hydrabolt/discord.js/files/988189/2017-05-09T22_28_32_710Z-debug.txt)

A temporary workaround to this issue is limiting webhooks to 1 or more specific channels and excluding them from the entire `client.on("Message")` chain by starting with either `if(message.author.bot) return;` or `if(!message.member) return;`

---

### **Include a reproducible code sample here, if possible:**

First of all create a webhook in Discord. I recommend using the website [Zapier](https://zapier.com/) to generate webhook messages as it has a test feature that you can use to quickly generate them without having to wait for an automated trigger. Then use the following code snippet:

```js
const Discord = require("discord.js");
const client = new Discord.Client();
const botToken = 'Some_Token_Here';
const roleToCheck = 'Some_Role_ID_Here';
client.login(botToken);

client.on("ready", () => {
    console.log("Bleep Bloop! This is Test HQ!");
});

client.on("message", message => {
    console.log(message.member);
    console.log(message.member.roles);
    try {
        message.member.roles.map(r => r.id).includes(roleToCheck)
        console.log('Role check passed')
    } catch (e) {
        console.error(e);
    }
})
```

Upon triggering the webhook test message in Zapier you should see the error as shown above being thrown. I have been able to reproduce this crash at a rate of 100% using only this code as well as using a fully developed bot so I am confident that it will be reproducible.

---

### **Further details:**

- discord.js version: 11.1.0
- node.js version: 7.9.0
- Operating system: Windows 10 Creators Update as well as Raspbian (Raspberry Pi 3)
- Priority this issue should have – please be realistic and elaborate if possible: low 

Initially I set this issue on high, however after talking with Crawl and others in #general on the server we can only draw the conclusion that taking this into account in the library can be done, but all of them kinda lead to a bad solution in the long run. Therefore I have edited the priority to low as it is something that still remains to be an issue, but requires a good amount of thought for a potential fix.

- [X] I have also tested the issue on latest master, commit hash: f95f18b586069bb40ebe027c4a014a0263190641

p.s. naming issues is hard. But so is naming software in general. I think that's an excuse ;-)

**Comment by appellation** [comment]
I'm unsure why this is an issue with the lib.  Webhook messages are still messages and you cannot expect a webhook to have a non-null `.member` property as they are not guild members.

**Comment by Gawdl3y** [comment]
Webhooks are not GuildMembers, so `member` will always be null for any of their messages. It's stupidly simple to skip over them:
```js
if(msg.webhookID) return;
```

I don't see any reason we should work around this in the lib. If anyone else has any opinions on the matter, continue discussing, by all means. Until then, I'm closing this.
