### ISSUE TITLE
Sending messages with Bots

### ISSUE THREAD

**Issue by Poke-Shop** [hydrabolt/discord.js#1479]
**Please describe the problem you are having in as much detail as possible:**
I want that my Bot sends a message if I write something like "Hello"! How can I do that?

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Please use the [official discord.js Discord server ](https://discord.gg/bRCvFy9) for questions; this issue tracker is only intended for bug reports and enhancement suggestions.
