### ISSUE TITLE
setStatus, setPlayingGame are broken.

### ISSUE THREAD

**Issue by OneMansGlory** [hydrabolt/discord.js#148]
Attempting to get the bot to display help commands, and stumbled across this:
![brokenjs](https://cloud.githubusercontent.com/assets/15380021/12353321/162ac6fe-bb5c-11e5-84a3-8a358a58170c.png)

**Comment by enebe-nb** [comment]
this is a incompatibility with node 0.12.*
find function is not supported, u can use `npm i array.prototype.find --save` and `require('array.prototype.find')` to add a polyfill to this function.
