### ISSUE TITLE
dispatcher bug on Linux systems

### ISSUE THREAD

**Issue by Dev-Yukine** [hydrabolt/discord.js#1499]
**Please describe the problem you are having in as much detail as possible:**

so i when i try to call the playFile function to play a file the Dispatcher just immediately call the end event after the start also i get that error from the error event:
```
TypeError: Cannot read property 'key' of undefined
    at StreamDispatcher.createPacket
   (/root/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:154:97)
      at StreamDispatcher.sendBuffer 
  (/root/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:122:25)
      at StreamDispatcher.process 
  (/root/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:231:14)
      at Socket.stream.once 
  (/root/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:312:12)
      at Object.onceWrapper (events.js:293:19)
      at emitNone (events.js:86:13)
      at Socket.emit (events.js:188:7)
      at emitReadable_ (_stream_readable.js:434:10)
      at emitReadable (_stream_readable.js:428:7)
      at readableAddChunk (_stream_readable.js:189:13)
```
 i think its a bug from D.js or how D.js handle ffmpeg on a linux based system because the same code run with no problems on my windows computer but on my Linux based VPS it dont work also here is a basic view how my code look and all vars are defined(checked all double times)  so maybe you know more (also i tried it on Ubuntu server 16.04 also and got the same problem)

**Include a reproducible code sample here, if possible:**
```js
            var voiceConnection = msg.guild.voiceConnection
            const dispatcher  = voiceConnection.playFile(`./audio_cache/xyz.mp3`, {"volume": 0.2})
            dispatcher.on('start', () => {
                    msg.channel.send(`**Start playing: ${title} Requested by** ${author}`)
                }
            )
            dispatcher.on('error', error => {
                console.log(error)
                }
            )
            dispatcher.on('end', () => {
                msg.channel.send(`**Finished playing:** ${title}`)
                }
            )
```

**Further details:**

- discord.js version: 11.1 Stable | 12.0 Master DEV
- node.js version: 7.10
- Operating system: Debian
- Priority this issue should have – please be realistic and elaborate if possible:  not as important 

- [x] I have also tested the issue on latest master, commit hash:
#1498

**Comment by devsnek** [comment]
@aemino is this the awaiting endpoint meme

**Comment by devsnek** [comment]
@Fr3akGam3r can you please test this on master and update your message to reflect that

**Comment by Fr3akGam3r** [comment]
@devsnek okay i updated to Master but still dont work and got the same error as before

**Comment by iCrawl** [comment]
I cannot seem to reproduce this.

**Comment by Fr3akGam3r** [comment]
@iCrawl did you test it on a linux system? and when yes how did you install ffmpeg Global or local? i tried both(with ffmpeg-binaries) and dont get any way to work but ony my windows this code work fine :/ installed on both node-opus and ffmpeg but still only work on a windows

**Comment by iCrawl** [comment]
Yes, I run everything I have on Linux. Whether that be in a Docker container or not.
FFmpeg globally with the apt package that comes with Ubuntu 16.04.
If you use Debian you might need to get the right backport or PPA for a correct version, so make sure thats not faulty.

**Comment by Fr3akGam3r** [comment]
@iCrawl i used backport to get it and tested also around to convert some files all work but only with discord.js the playFile() method wont work

**Comment by devsnek** [comment]
secretKey comes from the voice websocket, and is used (as you can see) to encrypt voice packets. It is interesting that you could get to the point of sending voice data without having a key, i would guess a race condition.

**Comment by Fr3akGam3r** [comment]
oh wait so i try to send VoicePackets without a key and thats why it error out? hmm okay thats interesting so i guess it could come from 1 of these 2 options 1. The Key takes to long to get 2.Voice is sending to fast
but idk how to fix that ._.

**Comment by Fr3akGam3r** [comment]
@devsnek what would you advice me to do now? i mean is that Error from me or Discord.js? D: im a bit confused on what i should try to fix because i tried so much and nothing seems to work

**Comment by Koyamie** [comment]
Same issue, dispatcher ends for undefined reason and multiples times (even without calling end event)

**Comment by JMTK** [comment]
I'm having this issue as well. Same error and line numbers. No specific file is showing this. If I run the same file twice, it'll work the second time.

**Comment by Fr3akGam3r** [comment]
@JMTK well mine never works what OS you are using?

**Comment by JMTK** [comment]
Linux: `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux`

Node: `v6.10.0`

Common issue seems to be Debian, but I haven't had this issue before. Somewhere between the Prism re-write and "now" is where something went wrong.. I haven't been able to place in the code where something could be wrong.

**Comment by aemino** [comment]
Hey
I write a lot of the voice code; perhaps you could do a bit of debugging for me.  My personal suspicion is that this has to do with race conditions involving connection speed discrepancies.  When your dispatcher begins streaming, could you please log `VoiceConnnection#status`? Thanks!

**Comment by Dev-Yukine** [comment]
@aemino So i logged the Status and it seems to be 1 the whole time (i also logged it when the bot joined and it was the same)

**Comment by aemino** [comment]
This is more or less what I expected... VoiceStatus 1 is `CONNECTING`, which means your bot hasn't fully connected when logging the status. Perhaps you could try surrounding your dispatcher code with `voiceConnection.once('connected', () => { ... });`?

If this works, I should be able to solve this issue pretty easily.

**Comment by Dev-Yukine** [comment]
@aemino hmm when i wrap my Dispatcher code in `voiceConnection.once('connected', () => { ... })` this never get executed also i evaled `msg.guild.voiceConnection.status` this like 2 mins after my bot were connected and it still says 1 i guess he cant connect properly?

**Comment by aemino** [comment]
Wait, how are you getting your connection to the voice channel in the first place? I see you referencing it from guild, but where in your code are you actually instantiating the connection?

**Comment by Dev-Yukine** [comment]
In my Code i have 2 commands 1 is called join that joins the members VoiceChannel (if he is in one if not he respond with something and return) and the second one who is called play only works if the Bot user has a VoiceConnection in this guild already (i check that by cheking if msg.guild.voiceConnection is null) and then try to download something and play that. Thats basically my Music bot

**Comment by Dev-Yukine** [comment]
@aemino also the exactly same code works on my Windows Computer (i tried to copy the code again mutiple times) where i programmed it but on my Debian VPS not that is strange and that where when i though about that must be a Bug from Discord.js i installed all modules i needed, FFMPEG works fine just that didnt worked at all :c

**Comment by aemino** [comment]
Could you check the status of the connection in your join command right after the join() promise resolves?

**Comment by Dev-Yukine** [comment]
@aemino oh strange the promise is never resolved :thinking: but also there is no error (i tried to catch it but neither a .then() fire or a .catch()) hmm

**Comment by JMTK** [comment]
I think it's `once('ready', () =>....` not `connected`: https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=ready

Though the docs say it should already be ready by the time the voice channel join promise resolves.

**Comment by Dev-Yukine** [comment]
@JMTK i think my problem is that my client cant connect properly because even after 2 hours it still says 1 and dont fire a .then() or catch() on my voiceChannel.join() hmm and also if i replace `connected` to `ready` it still dont get executed

**Comment by Dev-Yukine** [comment]
@aemino i guess it errors/stuck while try to established a connection but idk why he stuck or errors out :/

**Comment by aemino** [comment]
I'm not quite sure how this happens, although I'm relatively certain it has nothing to do with Linux/Windows.

**Comment by JMTK** [comment]
Did some more testing by spamming & I think this might be related to #1494 

I spammed a really short sound clip to play over and over quickly:
![image](https://user-images.githubusercontent.com/877114/26958195-42671600-4c97-11e7-99dc-5b12a07c5934.png)

![image](https://user-images.githubusercontent.com/877114/26958184-32b94eb2-4c97-11e7-8100-d8d9e91f711d.png)
Now my connection is stuck in a status of 4. It says there's a voice channel now but as you can see in the screenshot there's only me in the voice channel. The PR that you made @aemino seems to work in some scenarios but it still gets stuck in a status of 4 sometimes and no combination of voice channel leave/voice connection disconnect seem to make a difference. I'm still on #1521 right now.

**Comment by Dev-Yukine** [comment]
@aemino @iCrawl Just to get a little update here 2 examples show exactly the same issue btw links heer [#1579](https://github.com/hydrabolt/discord.js/issues/1579#issuecomment-307660483) and [this one from the Discord](https://puu.sh/whr9e/c9bf439312.png) so that im thinking im not the only one has an issue like that

**Comment by aemino** [comment]
In order to properly solve this bug, I need someone to provide a reproduction case that works consistently. Please also test it on Windows and Linux to determine if the issue is OS-specific.

**Comment by Dev-Yukine** [comment]
@aemino it works fine on my own Pc where i code and on a friends Windows root server(where i host atm) so im sure its because of that well the point with the consistense is problematic couz only i and a few others have that bug but i could give you acess to my VPS where a basic script what shows the problem is there and the bug is consistently around also pls let me now if that is okay for you

**Comment by aemino** [comment]
I don't need access to your VPS, but I need some code that can reliably reproduce the issue.

**Comment by Dev-Yukine** [comment]
`const Discord = require('discord.js');
const client = new Discord.Client();

client.login('tokenishere');

client.on('message', message => {
  // Voice only works in guilds, if the message does not come from a guild,
  // we ignore it
  if (!message.guild) return;

  if (message.content === '/join') {
    // Only try to join the sender's voice channel if they are in one themselves
    if (message.member.voiceChannel) {
      message.member.voiceChannel.join()
        .then(connection => { // Connection is an instance of VoiceConnection
          console.log("WORKS")
          message.reply('I have successfully connected to the channel!');
        })
        .catch(err => console.log("WONT WORK BECAUSE" + err));
    } else {
      message.reply('You need to join a voice channel first!');
    }
  }
});` if i so this simple thing it "connects" in Discord but wont send WORKS or WONT WORK so neither a then or a catch fires and the connection stuck at 1 like i said

**Comment by Dev-Yukine** [comment]
since no other input is here anymore and i use a Ubuntu server where it works fine now i will close this old issue

**Comment by Avon1** [comment]
are you using open shift vps i can not play too i some how manage to play it using .bin in node-modules but now they have banned ffmpeg and it dose not work any more

**Comment by Wqrld** [comment]
Can reproduce in a debian docker container with ffmpeg-static
