### ISSUE TITLE
Docs use-examples need updating, and discordjs.readthedocs.io should shut down

### ISSUE THREAD

**Issue by dylanh724** [hydrabolt/discord.js#1504]
Wondering why all these people are posting issues with old Discord.js code?

Well, the top of Google has your answer:

![image](https://cloud.githubusercontent.com/assets/8840024/26237863/61983f48-3ca9-11e7-9ff2-518dcaa1bd94.png)

1. This seems to be an official doc link of discord.js -- this should either be updated or disabled. The code examples are beyond-ancient, _yet I personally think they are friendlier than the "official docs"_ as they have more real-use examples.

2. Speaking of real-use examples, this is something that is lacking on discord.js official docs:
https://discord.js.org/#/docs/main/stable/general/welcome

There are only 2 common-use examples that are a bit useless -- for example, getting a guild from a normal collection is handled way differently than the average dev may expect. There should be more sample uses here, as if you Google for some, you run into a new ticket here asking why it doesn't work.

**In the current state, it's very comparable to ask someone to learn a different language and hand them a dictionary [a very nice one, nonetheless], rather than phrases and grammar**. The docs are a bit useless unless you study them like a dictionary, which is sort of counter-intuitive. Common-use examples would really help lower some FAQ and issues.

**Comment by iCrawl** [comment]
>Wondering why all these people are posting issues with old Discord.js code?

We don't really no. We are aware of the issue with the old docs site and are working on getting it resolved. (It's sadly not just a simple "delete the site or update it" at the moment).

We also know that the examples do not cover all possibilities the lib covers, but really anyone can submit a pull request and add an example to it. We don't particularly know exactly what people want, nor are we okay with writing a full music bot, for example, as an example, obviously.

**Comment by YorkAARGH** [comment]
We are aware that the website in question is the #1 result on Google so there's very little to nothing we can do about that at this moment in time, but they're working on trying to get it resolved.

Granted yes there are very few examples on the official documentation, how ever a third party has a nice selection of usable examples so if you wish to view the third party site please [click this link](https://anidiotsguide.gitbooks.io/discord-js-bot-guide/).

**Comment by hydrabolt** [comment]
@macdja38

**Comment by macdja38** [comment]
@hydrabolt the outdated message is right there in the google description... https://pvpcraft.ca/i/mlv3w.png

**Comment by dylanh724** [comment]
Ok, then the 2nd link. Even the first one, the average person won't read the description on the first link. It's usually "assumed right". Even the guys above didn't notice, either. Plus, as a new user, I have no idea what version it is at that point.

**Comment by devsnek** [comment]
:thinking: ![screen shot 2017-05-19 at 8 46 35 pm](https://cloud.githubusercontent.com/assets/5952481/26272022/471f122e-3cd4-11e7-9d71-1437fdd8a367.png)

**Comment by iCrawl** [comment]
2 of the same issues seem kinda pointless at this point, refer to #1585 instead.
