### ISSUE TITLE
Need a simple function for getting online count

### ISSUE THREAD

**Issue by dylanh724** [hydrabolt/discord.js#1505]
Currently you have to filter the members to get the count, and it's overly complex -- even with the widget.json immediately shows the online count right near the parent, effortlessly. Since the point of a wrapper is to make things easier, this seems like an intuitive addition.

If anyone has free time and knows the code well, this would be an awesome helper function to add.

**Comment by devsnek** [comment]
if you can't handle `members.filter(m => m.presence.status === 'online')` maybe you shouldn't be a computer programmer

**Comment by fjeddy** [comment]
I can almost guarantee that he's not a computer programmer :) And neither are you...

Talk about hostility.
