### ISSUE TITLE
User.previousMessage

### ISSUE THREAD

**Issue by MichaelPriebe** [hydrabolt/discord.js#1506]
I know of User.lastMessage, but in the message event, it shows as the current message. User.previousMessage could be used as the message previous to the current message. Useful for checking how fast a user posted, or if the two messages are similar or the same, and then take action based on that.

**Comment by devsnek** [comment]
just as a side note: checking how fast a user is posting messages should not be a two-data-point endeavor, just as a note. You will want at least five (but probably more).

**Comment by appellation** [comment]
I disagree with this.  If anything, there might be a case for setting the `lastMessage` property after the message event fires, but caching 2 messages on each user is pointless.

**Comment by MichaelPriebe** [comment]
If you set the lastMessage after message event fires that would work perfectly fine.

**Comment by hydrabolt** [comment]
Don't think discord.js needs to do this
