### ISSUE TITLE
messageUpdate fires twice per edit if the bot edits it

### ISSUE THREAD

**Issue by Typhoon31** [hydrabolt/discord.js#1507]
**Please describe the problem you are having in as much detail as possible:**

Hi,

given the following code below, my handler for 'messageUpdate' fires twice if my bot edits his own message. The first time it's the actual edit, but the second time it's an edit with the same content.
First, I thought it would be some buggy logic I've produced, but after testing it with your basic code example, it behaves the same.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require("discord.js");
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.username}!`);
});

client.on('message', msg => {
  console.log('New message event fired. ID: %s - Content: %s', msg.id, msg.content);
  if (msg.content === '!test') {
    msg.channel.send('Orig msg...')
      .then(nmsg => nmsg.edit('€ 1'))
      .then(nmsg => nmsg.edit('€ 2'))
      .then(nmsg => nmsg.edit('€ 3'));
  }
});

client.on('messageUpdate', (omsg, nmsg) => {
  console.log('Message edit event fired. ID: %s - Old content: %s - New content: %s', nmsg.id, omsg.content, nmsg.content);
});



client.login('<token omitted>');
```

Expected output:
```
New message event fired. ID: 315206569153396737 - Content: !test
New message event fired. ID: 315206570113761280 - Content: Orig msg...
Message edit event fired. ID: 315206570113761280 - Old content: Orig msg... - New content: € 1
Message edit event fired. ID: 315206570113761280 - Old content: € 1 - New content: € 2
Message edit event fired. ID: 315206570113761280 - Old content: € 2 - New content: € 3
```

Seen output:
```
New message event fired. ID: 315206569153396737 - Content: !test
New message event fired. ID: 315206570113761280 - Content: Orig msg...
Message edit event fired. ID: 315206570113761280 - Old content: Orig msg... - New content: € 1
Message edit event fired. ID: 315206570113761280 - Old content: € 1 - New content: € 1
Message edit event fired. ID: 315206570113761280 - Old content: € 1 - New content: € 2
Message edit event fired. ID: 315206570113761280 - Old content: € 2 - New content: € 2
Message edit event fired. ID: 315206570113761280 - Old content: € 2 - New content: € 3
Message edit event fired. ID: 315206570113761280 - Old content: € 3 - New content: € 3
```

**Further details:**

- discord.js version: latest on npm: `11.1.0`
- node.js version: `v7.10.0`
- Operating system: `W7 x64`
- Priority this issue should have – please be realistic and elaborate if possible: `low` (my edit handler returns if the message content stays the same)

- [x] I have also tested the issue on latest master, commit hash: 4aa734b9efc8dd0df8d1398183b866a8a2ef17b6

**Comment by hydrabolt** [comment]
Fixed in master

**Comment by Typhoon31** [comment]
It seems that `messageDelete` fires twice now (or still) with above code in DM when I (the user) send a message and delete it afterwards:

```js
client.on('messageDelete', msg => {
  console.log('Message delete event fired. ID: %s - Content: %s', msg.id, msg.content);
});
```

Using latest master 5f694d114946042b3dc4b9fb17597648cd8af9c0

**Comment by hydrabolt** [comment]
Hey @Typhoon31 can you try with the latest master? Pretty sure I fixed it there.

**Comment by Typhoon31** [comment]
Yup, seems fixed!

**Comment by Habor02** [comment]
what does the !test variable do here?
