### ISSUE TITLE
Channel Type undefined

### ISSUE THREAD

**Issue by froehlichA** [hydrabolt/discord.js#1509]
When executing this code, the `console.log()` prints four times, which is exactly the number of channels on the server, but the Channel Type is always undefined.
```
function doAnnouncement(message) {
	if(!checkOnServer(message)) return;
	
	for(var chan of message.guild.channels) {
		console.log("Channels: " + chan.type);
		if(chan.type=="text") {
			chan.send("ANNOUCEMENT: <Text>");
		}
	}
}
```

Expected output (With three text channels and one voice channel):
```
Channels: text
Channels: text
Channels: text
Channels: voice
```

Output given:
```
Channels: undefined
Channels: undefined
Channels: undefined
Channels: undefined
```

**Comment by Drahcirius** [comment]
Channels is a collection, when you loop through like that, chan becomes an array containing the channel id and the channel object, so `chan[1].type` will give you what you expect. 
For future reference, please use the official [discord.js discord server](https://discordapp.com/invite/bRCvFy9) for code related problems. The issue tracker is for bug reports and enhancement suggestions.

**Comment by froehlichA** [comment]
Ok, my mistake.
