### ISSUE TITLE
Cannot Mention in embed

### ISSUE THREAD

**Issue by modey2013** [hydrabolt/discord.js#1519]
`
.setTitle('Hello , ' + message.author.toString())
`
Shows The ID without Mention
![image](https://cloud.githubusercontent.com/assets/12548974/26353758/250da484-3fc2-11e7-8300-a5d0db20833a.png)

**Comment by Tvde1** [comment]
I think this is a discord issue and not discord.js.

**Comment by modey2013** [comment]
is there any other way to make a mention in embed ?

**Comment by devsnek** [comment]
no

**Comment by Tvde1** [comment]
@modey2013 Also, embeds don't mention in the first place. So just do @[username].

**Comment by Hakase-professor** [comment]
title can't have mentions or markdown

**Comment by modey2013** [comment]
"title can't have mentions or markdown"
should it work in .addField ?

**Comment by Hakase-professor** [comment]
yes will work in description too

**Comment by KingDGrizzle** [comment]
Mentions only "work" in descriptions and fields. They don't actually ping
the role / person, it just shows like it does.

**Comment by modey2013** [comment]
![image](https://cloud.githubusercontent.com/assets/12548974/26363420/43a5aae4-3fe1-11e7-9b20-4eb62d606c06.png)
![image](https://cloud.githubusercontent.com/assets/12548974/26363426/4c577186-3fe1-11e7-9baf-ee7b6dadca11.png)

Same Issue

**Comment by Hakase-professor** [comment]
any title like embed title or field can't have mentions and markdown
