### ISSUE TITLE
getChannelLogs returning a way lower amount of messagesthan input

### ISSUE THREAD

**Issue by Deukhoofd** [hydrabolt/discord.js#152]
According to the code, the function should return 500 messages when run with default values, this seems to only return 50 messages when using default values. When changing the limit, the amount of messages returned seems to vary. When I set the value to 1000 and 10000, it returned 100 messages. When set to 2000, it returned 50 again. My code looks like this:

    bot.getChannelLogs(channel, 1000, {}, function (err, ret) {
                console.log(ret.length)
                for (var i = 0; i < ret.length; i++) {
                    bot.deleteMessage(ret[i])
                }
                
            })

**Comment by abalabahaha** [comment]
Discord API is limited to 100 messages at a time. That piece of code you're referring to is weirdly outdated.

**Comment by Lord-Ptolemy** [comment]
*cough cough* http://discordjs.readthedocs.org/en/stable/docs_client.html#getchannellogs-channel-limit-options-callback *cough* outdated docs *cough*

**Comment by abalabahaha** [comment]
_cough cough @hydrabolt needs to find a time to setup docs for indev branch cough cough_

**Comment by Lord-Ptolemy** [comment]
*cough cough* @hydrabolt *cough* new npm & docs please

**Comment by TehSeph** [comment]
@abalabahaha @Lord-Ptolemy You guys want some cough-drops?

**Comment by meew0** [comment]
I think hydra has to be notified about this issue, has anybody pinged him yet? I'm gonna do it just in case: @hydrabolt

**Comment by abalabahaha** [comment]
Was there a need to ping hydra 2 more times within 8 hours... C'mon guys

**Comment by meew0** [comment]
Not to mention, as the owner of this repo, he gets notified anyway about every issue comment...

**Comment by TehSeph** [comment]
You get pinged by everything if you watch a repo. You can unwatch, even if you own it, and you won't be pinged. Github just auto-watches any repo you create. He might have unwatched this repo if he feels like it would cause distractions from his school work.

**Comment by khionu** [comment]
"You get pinged by everything when you watch a repo." Yes, as my inbox shows xwx
