### ISSUE TITLE
Retrieve user who deleted message(s)

### ISSUE THREAD

**Issue by nhatzHK** [hydrabolt/discord.js#1520]
**Add new action:**

**This features can be include in the GuildAuditLogs:**
```js
const Actions = {
  MESSAGE_DELETED: someNumber,
 //other actions that already exists
};
```

**Further details:**

- discord.js version: v7.10.0 (unrelated)
- node.js version: 4.6.1 (unrelated)
- Operating system: Linux 4.11.2-1-ARCH (unrelated)
- Priority : Feature request
- File : https://github.com/hydrabolt/discord.js/blob/stable/src/structures/GuildAuditLogs.js#L94

**Comment by iCrawl** [comment]
Already a thing on 11.1-dev: https://github.com/hydrabolt/discord.js/blob/11.1-dev/src/structures/GuildAuditLogs.js#L116

**Comment by nhatzHK** [comment]
Will this be push to stable anytime soon?

**Comment by iCrawl** [comment]
Whenever 11.2 lands on stable. We usually don't give estimates.

**Comment by WoaowMusic** [comment]
@iCrawl that site gives me a 404, any alternatives now?

**Comment by iCrawl** [comment]
Yea like mentioned, its already implemented.
