### ISSUE TITLE
<Guild>.channels is empty when creating a guild using OAuth bots.

### ISSUE THREAD

**Issue by CyberiumShadow** [hydrabolt/discord.js#1523]
**Please describe the problem you are having in as much detail as possible:**
This is probably a niche, but I'll still make the issue.

Essentially, as many of you are aware, there is a proviso within the discord API that allows OAuth bots that are in less than or equal to 10 guilds to create a guild programmatically via the API.

`<ClientUser>.createGuild()` is the method within the library that I am referencing.

Normally, when the guild is created via a user account, using the lib, the `<Guild>.channels` collection is populated with the default general voice and text channels.
However, this isn't the case for a guild programmatically created by an OAuth Bot, Upon creation of the guild via OAuth, I attempted to first check for `<Guild>.defaultChannel` that came up as nothing. I then attempted to map the `<Guild>.channels` collection with `<Guild>.channels.map(c => c.name)` and guess what? It only returned an empty array `[]`

Regarding the code samples included below, both samples do not go past `guild.defaultChannel.createInvite()` as at that point, defaultChannel does not exist within the guild instance.

**Include a reproducible code sample here, if possible:**
```js

/* ES6 Promises */
client.user.createGuild('Example Guild', 'london').then(guild => {
  guild.defaultChannel.createInvite().then(invite => client.users.get('<USERID>').send(invite.url));
  guild.createRole({
    name: 'Example Role',
    permissions: ['ADMINISTRATOR']
  }).then(role => client.users.get('<UserId>').send(role.id)).catch(error => console.log(error))
});

/* ES8 async/await */
async function createGuild(client, message) {
  try {
    const guild = await client.user.createGuild('Example Guild', 'london');
    const invite = await guild.defaultChannel.createInvite();
    await message.author.send(invite.url);
    const role = await guild.createRole({
      name: 'Example Role',
      permissions: ['ADMINISTRATOR']
    });
    await message.author.send(role.id);
  } catch (e) {
    console.error(e);
  }
}
createGuild(client, message);
```

**Further details:**

- discord.js version: Discord.JS Master (hydrabolt/discord.js.git#05a9f7e72fe0b56f9438ac13749819c4c07dc9cf)
- node.js version: 7.9.0
- Operating system: Some Linux Distro that I can't remember
- Priority this issue should have – please be realistic and elaborate if possible: Minor to Medium as this is primarily targeting a niche.

**Comment by iCrawl** [comment]
Fixed.
