### ISSUE TITLE
I am trying to Play downloaded MP3 files with my discord bot. Discord.js

### ISSUE THREAD

**Issue by VolleyGod** [hydrabolt/discord.js#1527]
**Please describe the problem you are having in as much detail as possible:**
I am trying to make my bot be able to play songs that are downloaded and put into the bot's folder (if that is what root means) Whenever i try to run the code below,(fs is for my points system) it comes back to say  "client.user.joinVoiceChannel is not a function" and "client.user.voiceConnection" is not a function. pls help

**Include a reproducible code sample here, if possible:**
```js
const Discord = require("discord.js");
const client = new Discord.Client();
const fs = require("fs")
client.login("MjgyNTc5OTU1ODY1MzU0MjQw.DADGlg.72nm3Q-7WSoznZJQbjLfvXCK4-E");//i made a new token

client.on('ready', () => {
  console.log('I am ready!');

client.on('message', message => {
  if (message.content == '*join') {
        message.reply('joined');
        client.user.joinVoiceChannel('317620078029832194');
  }
client.on('message', message => {
if (message.content == '*play') {
    //audio not playing
    console.log('play now');
    client.user.voiceConnection.playFile('./current.mp3');  
  }
});
```

**Further details:**

- discord.js version: 11.1.0 (that is what it says)
- node.js version: v.6.10.2
- Operating system: Windows 7 Professional 
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by vzwGrey** [comment]
You can use `npm ls discord.js` to easily read out your version of discord.js. Please do so and update your issue.

**Comment by VolleyGod** [comment]
I updated it
discord.js version 11.1.0

**Comment by vzwGrey** [comment]
Also, this is not a case of discord.js working incorrectly. For help with the library you should join the [Discord.js Official](https://discord.gg/bRCvFy9) server.

**Comment by VolleyGod** [comment]
do you see any obvious mistakes?

**Comment by Keanu73** [comment]
..Also try not to include your token - bad idea
