### ISSUE TITLE
uWs client connection error causes unhandled exception

### ISSUE THREAD

**Issue by tobbez** [hydrabolt/discord.js#1528]
Not 100% sure this counts as a bug. If you're unlucky, you may have your application using discord.js crash with the following:
```
events.js:168
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:166:17)
    at WebSocketConnection.onError (.../node_modules/discord.js/src/client/websocket/WebSocketConnection.js:358:17)
    at process.nextTick (.../node_modules/uws/uws.js:80:19)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
which is not very informative. Modifying the code to dump the actual error gets us:
```js
{ message: 'uWs client connection error',
  stack: 'uWs client connection error' }
```
Looking at the code of `WebSocketConnection.onError` tells us that someone already thought about this case:
```js
  /**
   * Called whenever an error occurs with the WebSocket.
   * @param {Error} error Error that occurred
   */
  onError(error) {
    this.client.emit(Constants.Events.ERROR, error);
    if (error.message === 'uWs client connection error') this.reconnect();
  }
```
However, that if statement will never execute in the standard case, since the exception is thrown before execution gets to that point, unless the user of the library handles `Client#error` which isn't even documented in stable docs (docs were (re-)added in #1466).

I would expect this type of error to be handled internally by the library.

In any case, I'd say it's a bug either with the code or the docs. Either this error shouldn't be emitted, or the docs should make it clear that you are *required* to handle `Client#error`.

**Further details:**

- discord.js version: 11.1.0
- node.js version: v7.10.0
- Operating system: gentoo
- Priority this issue should have – please be realistic and elaborate if possible:

- ⍁ I have not tested the issue on latest master but I believe it's affected as well, commit hash: 4292134647608206e2b3b379485a5494854c648e

**Comment by hydrabolt** [comment]
Ok, fixed in https://github.com/hydrabolt/discord.js/commit/ee679c732095be43378ce333680f4e68af6b239d, although I'd still recommend adding an `error` event listener.

**Comment by tobbez** [comment]
Thanks!

**Comment by magn0053** [comment]
I have the same error now.

**Further details:**
- discord.js version: 11.5.0
- node.js version: v6.14.33
- Operating system: Ubuntu 16.4
