### ISSUE TITLE
defaultAvatarURL is invalid

### ISSUE THREAD

**Issue by FireController1847** [hydrabolt/discord.js#1530]
**Please describe the problem you are having in as much detail as possible:**
The defaultAvatarURL link(s) is (are) invalid. It happens for users that don't have an avatar when using displayAvatarURL, and all the time when using defaultAvatarURL.

**Include a reproducible code sample here, if possible:**
```js
msg.channel.send(msg.user.defaultAvatarURL);
```

**Example:**
[Default Image 1](https://discordapp.com/embed/avatars/0.png)
[Default Image 2](https://discordapp.com/embed/avatars/1.png)
![](https://img.visual-fire.com/qtqnl.png)
![](https://img.visual-fire.com/7dm1z.png)
![](https://img.visual-fire.com/d2wik.png)

**Further details:**

- discord.js version: v12.0.0 (Commit 4292134647608206e2b3b379485a5494854c648e)
- node.js version: v7.10.0
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Moderate

- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Fixed in afe0bd8b
