### ISSUE TITLE
User search function does not return/provide the option to return results from channels flagged NSFW.

### ISSUE THREAD

**Issue by nermolov** [hydrabolt/discord.js#1533]
**Please describe the problem you are having in as much detail as possible:**
Using [guild.search](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=search) does not return results from channels flagged nsfw. This is is a parameter that can be set while making the request, as it is from the official discord client: `https://discordapp.com/api/v6/guilds/1234567890/messages/search?author_id=1234567890&include_nsfw=true`

**Include a reproducible code sample here, if possible:**
Provided that 1234567890 is an nsfw channel, this will return no results.
```js
guild.search({channel: 1234567890}).then(res => {
  console.log(`I found total results: ${res.totalResults}`);
}).catch(console.error);
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: v7.9.0
- Operating system: Arch Linux
- Priority this issue should have: Enhancement
- Relevant file: https://github.com/hydrabolt/discord.js/blob/master/src/structures/shared/Search.js

- [X ] I have also tested the issue on latest master, commit hash: 555317043e53103718bad1e47a6cf3757982beca

**Comment by devsnek** [comment]
thanks for letting us know, will be added soon

**Comment by devsnek** [comment]
added in #1534

**Comment by iCrawl** [comment]
Added in 3ec08d59 and respectively 1aa2293e
