### ISSUE TITLE
VoiceConnection emitting speaking events for users in other VoiceChannels

### ISSUE THREAD

**Issue by JSeed** [hydrabolt/discord.js#1536]
I'm working on a bot that processes incoming voice streams.  Whenever the `speaking` event is emitted by the `VoiceConnection` for the current `VoiceChannel` and `true` is passed, I set up a new stream and process the data after the stream's `end` event.  
I noticed I was processing a bunch more streams than expected, and that many of them were empty, so I started logging the `User`s who were being passed with the `speaking` event.  Turns out it was emitting `speaking` events for members of all of the `VoiceChannel`s on the guild, not just the members in the voice channel the bot was connected to.  

Reproduced with the following code:
```
bot.on('ready', () => {
    let channel = bot.channels.find(c => c.id == CHANNEL_ID);
    channel.join().then(connection => connection.on('speaking', user => console.log(user.username)));
});
```
By speaking in a different channel.

**Comment by aemino** [comment]
This seems to be the intended behavior. This is how Discord manages speaking events -- whenever you're in a voice channel, you get sent all speaking events. If you want to only listen to speaking events in the channel, just filter for it yourself. It's possible we could add an event like this for the VoiceChannel class...

**Comment by JSeed** [comment]
It dont think it really make sense for this to be in the `VoiceConnection` in that case, since the connection is specific to a single `VoiceChannel`.   I think given this exclusivity the expected behaviour would be that it would only emit events triggered by users in that `VoiceChannel`.  At the very least this should probably be clarified in the docs imo

**Comment by aemino** [comment]
Speaking from the API perspective, it absolutely makes sense for this to be bound to VoiceConnection.  The packets are sent by the voice connection websocket, meaning that in order to receive speaking events a voice connection is required.  I'm not sure the docs are in need of clarification; nowhere do they state that speaking events are bound to the current voice channel.

**Comment by JSeed** [comment]
I suggest the documentation change becuase while it may not explicitly state that they are bound to the voice channel, it is not very intuitive when it says that a connection `Represents a connection to a voice channel in Discord.` Almost everything else about a VoiceConnection is specific to the VoiceChannel it was created from.  I cannot receive data from users in other channels, I cannot play audio in other channels, why is it expected to be assumed that the events emitted by the connection are any different?

**Comment by hydrabolt** [comment]
Thanks for bringing up this issue. The documentation has been corrected to show that a VoiceConnection isn't specific to a voice channel, but instead a guild. The `speaking` event will continue to be emitted for users in other channels - the documentation now makes sense for it to do so.

While it would be possible to make VoiceChannel emit the event instead, it would be inefficient to make them EventEmitters. Instead, I'd just suggest filtering for the channel:
```js
connection.on('speaking', (user, speaking) => {
  if (connection.guild.member(user).voiceChannel.id !== connection.channel.id) return;
  // do something with filtered event
});
````
