### ISSUE TITLE
Cannot use .send on GuildMember object

### ISSUE THREAD

**Issue by FireController1847** [hydrabolt/discord.js#1537]
**Please describe the problem you are having in as much detail as possible:**
Been testing around, and it seems I've been completely incapable of being able to send guild owners messages.

**Include a reproducible code sample here, if possible:**
```js
msg.member.guild.owner.send("Test");
msg.guild.owner.send("Test");
msg.guild.member("ID").send("Test");
```

**Confirmed Working:**
```js
msg.member.guild.owner.user.send("Test");
msg.guild.owner.user.send("Test");
msg.guild.member("ID").user.send("Test");
```

**Error message:**
```
19|Slice   | DiscordAPIError: Unknown Channel
19|Slice   |     at item.request.gen.end (/root/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
19|Slice   |     at then (/root/node_modules/snekfetch/src/index.js:183:21)
19|Slice   |     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Further details:**

- discord.js version: v12.0.0
- node.js version: v7.10.0
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Moderate

- [x] I have also tested the issue on latest master, commit hash: Commit 22e8237bf1644b1dd83aeeb4909a870f2a53b284

**Comment by iCrawl** [comment]
Fixed in 20a9e4a0
