### ISSUE TITLE
Potential Slip up with Audit Logs

### ISSUE THREAD

**Issue by SnazzyPine25** [hydrabolt/discord.js#1538]
First of all I think `CHANNEL_ROLE_UPDATE` should go with the array with the actions that return with update.

Second of all, I think this is in reverse:
![](https://i-need.discord.cards/398d5b.png)

**Comment by aemino** [comment]
As counter-intuitive as it might seem, I'm pretty sure that those actions are actually not reversed.

**Comment by PgBiel** [comment]
for me only the `MEMEBER_BAN_REMOVE` looks off because it doesn't actually bring the member in :P

**Comment by devsnek** [comment]
@SnazzyPine25 ban add/remove are where they are on purpose.

**Comment by SnazzyPine25** [comment]
Well what about the absence of `MEMBER_ROLE_UPDATE`?

**Comment by devsnek** [comment]
good point

**Comment by iCrawl** [comment]
Fixed in 2f1eb71a and 29ead897 respectively.
