### ISSUE TITLE
Docs need to be updated for fetchBans()

### ISSUE THREAD

**Issue by FireController1847** [hydrabolt/discord.js#1544]
**Please describe the problem you are having in as much detail as possible:**
.fetchBans() is returning an object of {reason: bla, user: user} instead of what the docs say as a collection of users. So I don't know if it should be changed internally to user.banReason or if the docs should be updated.

**Include a reproducible code sample here, if possible:**
```js
m.guild.fetchBans().then(bans => {
  console.log(bans.first().username); // Expected output is the username
  console.log(bans.first().user.usetname); // Required output to get the username
});
```

**My original issue:**
```js
m.guild.fetchBans().then(bans => {
  let users = bans.filter(r => r.user.username == "Yepsehur");
  console.log(users.first());
  m.guild.unban(users.first()).then(() => {
    m.channel.send(users.first().user.username);
  }).catch(e => {
    console.error(e);
  });
});
```
```
Slice > Error: Couldn't resolve the user ID to unban.
Slice >     at Guild.unban (/root/node_modules/discord.js/src/structures/Guild.js:793:20)
Slice >     at m.guild.fetchBans.then.bans (eval at module.exports.on (/root/PrivateBots/Slice/Events/me ssage.js:185:44), <anonymous>:4:11)
Slice >     at process._tickCallback (internal/process/next_tick.js:109:7)  
```

**The fix:**
Change `m.guild.unban(users.first())` to `m.guild.unban(users.first().user)`.

**Further details:**

- discord.js version: v12.0.0
- node.js version: v7.10.0
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [x] I have also tested the issue on latest master, commit hash: 29ead897d6960032129e94222dede1fb077027d4

**Comment by devsnek** [comment]
in v12 we return an array of `{ user, reason }`. v12 is breaking. expect things to break

**Comment by FireController1847** [comment]
@devsnek Docs do not reflect this change. https://discord.js.org/#/docs/main/master/class/Client?scrollTo=guildMemberAdd

![](https://img.visual-fire.com/tip0q.png)

**Comment by iCrawl** [comment]
68c25fef
