### ISSUE TITLE
Removing Avatar is not possible

### ISSUE THREAD

**Issue by markokajzer** [hydrabolt/discord.js#1548]
**Please describe the problem you are having in as much detail as possible:**

It is not possible to remove the bot's avatar with discord.js.

The Discord API technically allows that by sending just the username and an empty string as the avatar to `/users/@me`. Because of [this line](https://github.com/hydrabolt/discord.js/blob/master/src/structures/ClientUser.js#L85) (in master) however, the avatar will always default to the set avatar when trying to use `.setAvatar('')`.

I am willing to submit a PR request for this. Shall I create a new method `.removeAvatar()` or shall I modify the edit function to work properly with empty avatars? I'd like to see this functionality added in version 11.1.0 as well, so would it be ok if I submit a PR for master and one for 11.1-dev, or will you not add any new functionality there?

**Further details:**

- discord.js version: 11.1.0
- Priority this issue should have – please be realistic and elaborate if possible: (Very) Low

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
I feel like this should behave the same way setGame does, when passing null it should reset your avatar.
Adding a new method for it seems pointless imo.
