### ISSUE TITLE
resume live video

### ISSUE THREAD

**Issue by OkitaSougoo** [hydrabolt/discord.js#1550]
**Please describe the problem you are having in as much detail as possible:**
I use `ytdl-core` to download a stream of a live YouTube video ([like this one](https://www.youtube.com/watch?v=1-AODuJpCG4)). It plays fine with `let dispatcher = connection.playStream(stream)`. The problem is that after pausing using `dispatcher.pause()` for about 5 mins, then use `dispatcher.resume()`, the `dispatcher` just ends with reason `undefined`.

**Further details:**

- discord.js version: master
- node.js version: 8.0.0
- Operating system: windows 10

**Comment by telunc** [comment]
This happens to me too.

**Comment by iCrawl** [comment]
I'm not sure if this is a discord.js issue.

ytdl-core has this: https://github.com/fent/node-ytdl-core/issues/157
And if I remember correctly, livestreams had some issues before.

@fent might have some more insight on this, or possibly @aemino if he can think of an issue inside the lib.

**Comment by iCrawl** [comment]
Seeing as you got your answer in https://github.com/fent/node-ytdl-core/issues/166
I will close this here.
