### ISSUE TITLE
VoiceBroadcast playArbitraryInput

### ISSUE THREAD

**Issue by telunc** [hydrabolt/discord.js#1556]
Discord is prompting this error when I have opusscript, node-opus, ffmpeg installed. I went into VoiceBroadcast.js and commented out this line  `if (!this.opusEncoder) throw new Error('Couldn\'t find an Opus engine.');` and it worked.

**Error output:**
```js
if (!this.opusEncoder) throw new Error('Couldn\'t find an Opus engine.');
                           ^
Error: Couldn't find an Opus engine.
```
**Sample code:**
```js
broadcast.playArbitraryInput(url);
```

**Further details:**

- discord.js version: 12.0.0 Master branch
- node.js version: 8.0.0
- Operating system: macOS Sierra 10.12.5

**Comment by aemino** [comment]
This should be resolved by #1563. Please try it out and let us know if the PR fixes it for you.
