### ISSUE TITLE
Role checking code

### ISSUE THREAD

**Issue by IWasAndrerstajn** [hydrabolt/discord.js#1558]
I want to make a command where a role will be checked and if there is a role like that the command should be executed but its not working heres the code.

if(commandIs("setst" || "setstreamtime", message)){
        let modRole = message.guild.roles.find("name", "CRIB MODERATORS");
        if(message.member.roles.has(modRole)){
            if(isNaN(args.length)){
                message.reply("Not a number. Please enter a number");
            }else{
                var st = args.length;
            }
        }else{
            message.reply("Not enough role premisions");
        }
    }

**Comment by iCrawl** [comment]
The template when you create an issue isn't there for fun only.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by IWasAndrerstajn** [comment]
Thanks
