### ISSUE TITLE
voiceJoin/voiceLeave doesn't trigger

### ISSUE THREAD

**Issue by mirkomilova10** [hydrabolt/discord.js#156]
I'm trying to get a voice channel id by the event voiceJoin/voiceLeave but it doesn't seem to trigger at all, possibly bugged?

**Comment by meew0** [comment]
Can you show your code and what exactly you're doing to trigger it?

**Comment by TehSeph** [comment]
Discord.js version, Node version, any errors, snippet of the code you're attempting... Something go off would be nice... Other users aren't having errors so to diagnose yours you need to be a bit more specific. :|

**Comment by mirkomilova10** [comment]
the code is a pretty simple console.log like:
```javascript
bot.on("voiceJoin", function(user,channel) {
		console.log(user + " joined " + channel);
});
```
Im on the latest Discord.js version (git cloned) and on Node v5.4.1

**Comment by mirkomilova10** [comment]
i have also tried using some the message event with this code:
```javascript
bot.on("message", function (msg) {
	//check if message is a command
	if(msg.author.id != bot.user.id && (msg.content[0] === '!' || msg.content.indexOf(bot.user.mention()) == 0)){
        console.log("treating " + msg.content + " from " + msg.author + " as command");
		console.log("voice channel id: " + msg.author.voiceChannel);
```
but i get a undefined id

**Comment by abalabahaha** [comment]
are you on the master or indev branch

**Comment by mirkomilova10** [comment]
master

**Comment by abalabahaha** [comment]
Try switching to indev

**Comment by mirkomilova10** [comment]
still no luck, no response on the console

**Comment by mirkomilova10** [comment]
aldought it's in-dev, the status parameter on the event presence doesn't return offile/online but it returns the user it went offile/online like
```
kobim went @kobim
```
instead of 
```
kobim went offline
```

**Comment by abalabahaha** [comment]
@mirkomilova10 stuff changed in indev, presence event now has 2 parameters: user before change, and user after change. Use user.status.
