### ISSUE TITLE
Stop connecting REST and Gateway so strictly

### ISSUE THREAD

**Issue by hydrabolt** [hydrabolt/discord.js#1564]
#### The Problem
The current issue is that we "bridge" requests and their corresponding gateway events so that we can receive an immediate effect when performing requests, e.g:
```js
message.edit('new content').then(message2 => {
  console.log(message2.content === message.content); // true
});
```
The issue with this is that discord.js creates fake gateway events so that the message is modified to respect the user's intent before the user receives the object back - in this case setting the content to `new content`. However, this creates the issue of the client effectively handling events twice --  this is the cause of #1507.

To remedy this, for most events we have basic checks in place - e.g. don't emit another delete event if the message has already been deleted internally. For delete events, we use the `restWsBridgeTimeout` option - this involves some horrible timeout magic so that everything runs smoothly for the developer.

However, for update events, especially message updates for larger bots, it becomes expensive to put checks in place to guarantee that events will not be duplicated - we can't compare messages to see if they are identical so often, it would slow down the client for very large bots. Again, this is why #1507 is caused. In general, this whole fake gateway event is bloating up the internals of discord.js, issues are beginning to arise, and it is causing degraded performance.

#### Proposed Solution
Now that we're using node 8, there's a really nice solution for this that removes fake events. I propose that, by default, requests resolve without waiting for the equivalent gateway event, i.e:
```js
message.edit('new content').then(message2 => {
  console.log(message2.content === message.content); // false
});
```

But to make it backwards compatible, we could allow users to await the gateway event:
```js
message.edit('new content').then(async message2 => {
  console.log(message2.content === message.content); // false
  await message2.gatewayEvent(); // naming needs to be improved :P
  console.log(message2.content === message.content); // true
});
````

You might be wondering what would happen if, for example, a user edited a message manually and their selfbot also did. To prevent `await message2.gatewayEvent()` from resolving if the user's manual edit was received before the selfbot's, we could temporarily cache only the properties that were requested to be changed, and once a message event with equivalent properties is received, it can then resolve and continue the flow.

If the gateway event isn't received in a configurable amount of time, `gatewayEvent()` could also resolve or reject based on the developer's choice -- it is flexible.

#### Final Thoughts
This is still only a suggestion, but I believe it's a lot better than what we currently have. If users still want to ensure their data has been modified to reflect their intended changes, then the solution is better in that it doesn't create any timeouts and uses minimal equality checks, although it would of course delay their flow slightly. If users do not care about waiting for gateway events and trust that their changes will be made, this provides performance boosts and minimises the risk of issues such as #1507 occurring.

**Comment by devsnek** [comment]
i'm working on creating a centralized event dispatcher for modifying state which should take care of this (it won't be redux i'm changing that)
