### ISSUE TITLE
Wrong file in npm registry 

### ISSUE THREAD

**Issue by Wodki** [hydrabolt/discord.js#1565]
Forgive me if I am wrong but in the registry `https://registry.npmjs.org/discord.js/-/discord.js-11.1.0.tgz`,
the files are not the same as shown here on github. 

In particular some things are missing as in the GuildAuditLogsEntry class, `createdTimestamp()` and `createdAt()`. Perhaps you linked something wrong cause am seeing things fine in github.

Thank you

**Comment by devsnek** [comment]
the master branch on github is ahead of the 11.1.0 release because we keep making changes for the next release on github.

the `stable` branch and __the latest release on npm__ should always be the same

**Comment by Wodki** [comment]
What I was saying is the _stable_ version I got from the npm registry and the one am seeing on discord seem to be different.

**Comment by iCrawl** [comment]
It is not.

**Comment by Wodki** [comment]
Well I just checked my GuildAuditLogs.js and it does not contain the two getter functions, though after installing master it does. I have the exact same issue with 1481.

**Comment by Fuechschen** [comment]
I just checked this and the getters are indeed missing. Cache was cleaned. Tried it with both node 6 and node 8. It seems like the npm package was uploaded at [c3be798](https://github.com/hydrabolt/discord.js/commit/c3be798663436648d6a831ff115ca2c65e61a1d0) but the github tag was created one commit later.

**Comment by iCrawl** [comment]
@hydrabolt 🙄 

If you don't want breaking changes but still have the fixes and features just update to the 11.1-dev branch.
`npm i -S hydrabolt/discord.js#11.1-dev`

You will need `git` for this.
