### ISSUE TITLE
NaN Region Data for guilds

### ISSUE THREAD

**Issue by gmedeadlystrike** [hydrabolt/discord.js#1566]
This is referring to the string produced by Guild.region

It was reported to me today by one of my bots EU users that their server region reports as "NaN"

This is whats known:

Only reported so far on eu-central servers Edit: (Now getting reports of it happening to all regions)

Newly created or region changed servers report region correctly, but after some time region data changes to NaN.

If a NaN  server changes their discord region to something else, and back again the region now reports correctly for some time. After a short while the server becomes NaN again.

**Further details:**

- discord.js version: 11.1 Master
- node.js version: 7.11.00
- Operating system: Server 2012 / Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: This issue should be medium / high. In my usage region data is used heavily to determain scheduled event times, and weekly Database updates. (EU vs NA) 

- [ ] I have also tested the issue on latest master, commit hash:
--note have not tested absolute latest commit yet, im about 2 days behind. _ will test when my EU-Central test server changes back to NaN

**Comment by devsnek** [comment]
i'm not sure why it would be `NaN` but server regions sometimes get borked

![](https://b1nzy.threw-the-ban-hammer-at.me/62d27d.png)

**Comment by devsnek** [comment]
ok so here's the deal. this is a discord issue, but we can technically abstract it away BUT i'm going to need you @gmedeadlystrike to do some `console.log`ing  and tell us what data gets passed in the Guild#patch method when the region goes to `NaN`

`node_modules/discord.js/src/structures/Guild.js` in the `patch` method add a console.log for `data.region` and then report back after you get some data

**Comment by iCrawl** [comment]
@gmedeadlystrike any update on that?

**Comment by gmedeadlystrike** [comment]
@iCrawl - I have not seen this issue pop up sense
