### ISSUE TITLE
How to add arguments to a command?

### ISSUE THREAD

**Issue by 975miles** [hydrabolt/discord.js#1567]
I don't really use javascript, I just want to make a bot for my (friend's) discord server so not everything has to be text. I tried to look in the documentation and other places from google for a way to add arguments, but none worked. Simple commands do work, but the code I have just crashes the bot immediately.

Current script:
```
if (msg.content.startsWith(prefix + "award")) {
      let [country, points] = message.content.split(' ').slice(1);
      msg.channel.send("The country ${country} has been awarded ${points} power points.");
      console.log("Command executed : !award")
    }
```

**Comment by iCrawl** [comment]
Please read the issue template the next time you create an issue. The issue tracker is not for questions. Use the discord server instead.

**Comment by 975miles** [comment]
k
