### ISSUE TITLE
[Feature] Add "bot.allShards" which has an array of all shard's client data

### ISSUE THREAD

**Issue by JacobGunther12** [hydrabolt/discord.js#1568]
I didn't know if I should follow the bug report format, so I decided not to. Here's my idea: Have an array under `bot.allShards` or `bot.shards` which contains all shards and their Client. Each of the values in that array will basically be the bot itself, so if I did `bot.shards[0].guilds.size`, it would return something like `946` if there are 946 guilds in the first shard. Would this be possible? It would be **extremely** helpful to me because I have to get user information across shards and I have to use `broadcastEval()` which is very tedious to do. If you want to see the code that I am using for that, click [here](https://hastebin.com/logogarafe.js). I know you're gonna yell at me for that code, but I don't care. Well thanks for reviewing this feature request. I **really** hope it gets added soon (within the next month, preferably v12).

**EDIT** Someone *just* told me about `fetchClientValues()`. I'm not sure if it's the same thing, but it's just returning `undefined`. I'm guessing by the name of the method, it's the same thing? - Jacob Gunther

**Comment by appellation** [comment]
You're basically requesting internal sharding.  See #1501 and #1414.

**Comment by iCrawl** [comment]
^
