### ISSUE TITLE
sendFile sending gif as jpg

### ISSUE THREAD

**Issue by zaza7** [hydrabolt/discord.js#157]
When using the sendFile function to send a gif to the chat it sends it as `image.png` causing an issue where the client will not be able to play the gif unless they click on it and click open original to see it in the browser.

**Comment by khionu** [comment]
As per outside discussion, issue is with HardCoding:
https://github.com/hydrabolt/discord.js/blob/indev/src/Client/Client.js#L193

**Comment by TehSeph** [comment]
That third parameter can be sent instead of defaulted.
`client.sendFile(destination, "/path/to/file.gif", "sent_name.gif");`

**Comment by zaza7** [comment]
Oops didn't see I could have a third argument with options specifying the name + extension. Thank you very much for pointing that out.

**Comment by abalabahaha** [comment]
Although yes, the lib should probably auto-detect the filename. Substring magic is easy enough.

**Comment by TehSeph** [comment]
@abalabahaha Agreed. It should auto-detect, and the optional arg should be for renaming.

**Comment by khionu** [comment]
Reopening as enhancement.
