### ISSUE TITLE
How do I make My Bot Join a Voice Channel 

### ISSUE THREAD

**Issue by VolleyGod** [hydrabolt/discord.js#1572]
**Please describe the problem you are having in as much detail as possible:**
First off, I know this isn't a issue but no one else wants to help. I don't even know where to start on how to make my bot join a voice channel. I went to hydrabolt's discord server but they said i look it up. But there are no clear answers. It would be great if anyone could help me with the code.  Here's what i have:
**Include a reproducible code sample here, if possible:**
```js
const Discord = require("discord.js");
const client = new Discord.Client();
const fs = require("fs")
const snekfetch = require("snekfetch");
const broadcast = client.createVoiceBroadcast();

client.login(im smart enough to know not to put that in);

client.on('message', message => {
  if (message.content === '*join') {
      client.joinVoiceChannel('322273089138196490')
 .then(connection => console.log('Connected!'))
 .catch(console.error);
 message.reply('OK')
 broadcast.playFile('./music.mp3');
for (const connection of client.voiceConnections.values()) {
  connection.playBroadcast(broadcast);
}}
    }
)
```

**Further details:**

- discord.js version:    idk
- node.js version: v.6.10.2
- Operating system: Windows 7
- Priority this issue should have – please be realistic and elaborate if possible: How to join a voice channel

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dev-Yukine** [comment]
ask on the Discord Server and the docs maybe?

**Comment by VolleyGod** [comment]
you know i was there

**Comment by VolleyGod** [comment]
and does anyone see any problems with my code?

**Comment by Dev-Yukine** [comment]
yes but you know the rules there? 

![](https://puu.sh/webHd/d4280041ee.png)

rule 2 apply here

**Comment by VolleyGod** [comment]
I GOOGLED IT AND NOTHING WORKED
SO IF YOU KNOW PLEASE JUST TELL ME. 
IF NOT THANK YOU FOR YOUR TIME.

**Comment by devsnek** [comment]
Hello! The GitHub Issue Tracker is not for individual programming issues, as it says in the template you deleted. Please refer to the server, the link to which is [here](https://discord.gg/bRCvFy9). Thank you for your understanding.
