### ISSUE TITLE
Cannot ban GuildMember

### ISSUE THREAD

**Issue by WizardLink** [hydrabolt/discord.js#1580]
**Please describe the problem you are having in as much detail as possible:**
After Space (Contributor, and Staff at d.js Official Guild) helped me, i have made awaitMessages with a variable then just wait resolve with await, before that i did with .then() wich is the same thing, but i need to detail eveything... After doing that, i have added the if statements to return what i wanted if it matched the right situation... After the GuildMember type "yes" on the TextChannel, it was supposed to ban the GuildMember mentioned, but instead of it, it resolved the "memberu.ban()" and executed the code line on resolve. The bot in this situation had ADMINISTRATOR permissions and the GuildMember had only READ_MESSAGES, tried with other GuildMembers, didn't work as well, and resolved the promise somehow. Here is a hastebin of my message handler, core file and the file with the problem https://hastebin.com/baluradiki.js (Problem), https://hastebin.com/avovekovul.js (Message Handler), https://hastebin.com/ahubilewep.js (Core [Main file on package.json])

**Include a reproducible code sample here, if possible:**
```js
exports.run = async function(client, message, args, pinku, rest, perms) {
  try{
    if(!message.guild.me.permissions.has('BAN_MEMBERS')) return await message.channel.send(`I don't have permission to ban members ${message.author}!`);
    if(!message.member.permissions.has('BAN_MEMBERS')) return await message.channel.send(`You don't have permission to ban anyone ${message.author}!`);
    if(!args[0]) return await message.channel.send(`${message.author}... You must specify a user so i can ban him <:omfg:315264558279426048>`);

    const memberu = await message.guild.fetchMember(message.mentions.users.first())

    let permlvl = 0;
    if (message.guild.roles.find('name', settings.modrolename) && memberu.roles.has(message.guild.roles.find('name', settings.modrolename).id)) permlvl = 1;
    if(memberu.permissions.has('MANAGE_GUILD') || memberu.permissions.has(['BAN_MEMBERS', 'KICK_MEMBERS', 'MANAGE_MESSAGES']) ) permlvl = 2;
    if (client.guilds.get('298969150133370880').members.has(memberu.user.id)){
      if (client.guilds.get('298969150133370880').members.get(memberu.user.id).roles.has('299655329791213569') || client.guilds.get('298969150133370880').members.get(memberu.user.id).highestRole.position > 17) permlvl = 3;
    }
    if (settings.owner === memberu.user.id) permlvl = 4;

    if(permlvl >= 2) return await message.channel.send(`I can't ban this member ${message.author}!`);

    if(!memberu.bannable) return message.channel.send(`I can't ban this member ${message.author}!`);

    await message.channel.send(`${message.author} are you sure you want to ban ${memberu.toString()}? You have 1 minute to reply with \`yes\` or \`no\``)
    var collected = await message.channel.awaitMessages(r => r.author.id === message.author.id && (r.content.toLowerCase() === 'yes' || r.content.toLowerCase() === 'no'), { time:6000 });

    if(collected.first().content.toLowerCase() === 'yes') {
      if(!args[1]) args[1] = 'No reason given.'
      memberu.ban(2).then(() => {
        message.channel.send(`**${memberu.user.tag}** was sucessfully banned!`)
      });
    };

    if(collected.first().content.toLowerCase() === 'no') {
      return message.channel.send('Canceled command sucessfully!');
    };

  }catch(err) {
  await message.channel.send(`This should not have happend! Report this to the official server\n\`\`\`js\n${err.stack}\n\`\`\``);
  }
  };
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: v7.7.4
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Normal, needs to check if it's really a bug first of all, if it really is, just treat it as a bug, and fix over time, i just want to be notified if it is, so i go other way around it to ban the GuildMember

- [ ] I have also tested the issue on latest master, commit hash: d6041f9fb379b6652140600a3789c30ca4e9ce56

**Comment by dragonfire535** [comment]
Nice node version

**Comment by WizardLink** [comment]
I thought i read npm, nice me.

**Comment by iCrawl** [comment]
I have to be honest, I have no idea what you are saying...

**Comment by devsnek** [comment]
`node.js version: v8.0.0`

**Comment by WizardLink** [comment]
@devsnek Sorry i did that issue before going to Peru, so yes... I shouldn't have opened it? Well you guys said me to so i'm here, and i fixed.

@iCrawl Basically i wanted when the command was called to send a message and wait for the answer, being YES or NO... When saying No, it just sends a message and stop. If saying Yes, it SHOULD ban the GuildMember, but it doesn't Ban, and worse of all... It somehow resolves the promise and execute the code block on the .then()

**Comment by devsnek** [comment]
```js
Discord.Message.prototype.ask = function(query) {
  return this.channel.send(query).then(m =>
    m.channel.awaitMessages(k => k.author.id === this.author.id, {
      max: 1,
      time: 60000,
      errors: ['time'],
    }).then(c => c.first().content));
}
```

**Comment by WizardLink** [comment]
... I know that, i just didn't do in that way because of another Contributor advice, to make code shorter, the real problem here is why it doesn't ban the GuildMember

**Comment by hydrabolt** [comment]
Can you still recreate this in master?

**Comment by WizardLink** [comment]
Sorry for the late reply, I don't use master, I'm currently using the stable version of d.js, as on my local environment that didn't work, i gave up on trying and instantly banned the member. I can try to reproduce again, but might be some kind of issue on my env, as at the time i had a lot of weird and yet unknown problems with d.js, which were helped by space. If you don't want me to try reproducing it again, you (or even me) can close the issue. Sorry again for the late reply.

**Comment by hydrabolt** [comment]
No problem, try again on the latest master if you can and if it's still an issue, re-open this issue 👍
