### ISSUE TITLE
Cannot use token obtained through OAuth for client.login()

### ISSUE THREAD

**Issue by oolivero45** [hydrabolt/discord.js#1581]
Whenever I try to use a token for a user account that I have obtained through OAuth to login, the login fails. Is this intentional, and there's some other function that I should be using, or is it a bug?

**Comment by iCrawl** [comment]
The token for any user account is located in your localStorage on the discord client, seen here: ![](https://a.safe.moe/p6xJ7.png)

**Comment by oolivero45** [comment]
@iCrawl I know - I'm trying to use an OAuth token instead. I want to be able to create something that can be used by others without having to give me their account token, which would give me full access to their account.

**Comment by iCrawl** [comment]
Well.... it will never be like a "Self-bot". It will just be a regular bot then. And that bot needs to be in the server they want to use it in.
They is simply now way to sort of "hijack" their account with a OAuth token.
