### ISSUE TITLE
Using tokens to reauthenticate

### ISSUE THREAD

**Issue by marcandrews** [hydrabolt/discord.js#159]
Is it possible to use tokens received from a successful ```login()``` to reauthenticate a user (i.e. login again)?

For example:
```
login(token, function (err) {
  if (!err) // login successful
});
```

**Comment by meew0** [comment]
discord.js automatically caches tokens, so this is usually not necessary. Why do you need this specifically?

**Comment by marcandrews** [comment]
I want to allow users to login to my site using Discord (and eventually build a Discord authentication strategy for Passport), and instead of storing their email and password, I would like to store the token and use that to re-authenticate.

**Comment by meew0** [comment]
This should be easy enough to implement, I'll take a look at it

**Comment by marcandrews** [comment]
Thanks!

Let me know how it goes or if you don't have time to implement this and I'll fork and try to implement it myself.

**Comment by khionu** [comment]
https://github.com/hydrabolt/discord.js/pull/160
