### ISSUE TITLE
fetchProfile and login only via token?

### ISSUE THREAD

**Issue by Gindu** [hydrabolt/discord.js#1592]
hey,
 how even is it possible to use the fetchProfile endpoint, when it's not possible to log as user account while login via email and password is gone?

**Comment by vzwGrey** [comment]
User accounts still use tokens. It's what your discord client uses to function.
And you can use those tokens like bot tokens in discord.js.

**Comment by iCrawl** [comment]
Next time please read the Issue template you just deleted without reading it.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

And you can get your user token with the devtools using Ctrl + Shift + I on Windows & Linux or Cmd + Option + I on macOS.
![](https://a.safe.moe/p6xJ7.png)
