### ISSUE TITLE
How do I make my discord.js bot mention a role?

### ISSUE THREAD

**Issue by EliteTactical** [hydrabolt/discord.js#1600]
I can't get my bot to mention the role I want it too. The role is "SIEGE TEAM" and i want the bot to respond to "!r6" with "@SIEGE TEAM get on"

**Comment by bdistin** [comment]
Please read the issue template the next time you create an issue. The issue tracker is not for questions. Use the discord server instead.

**Comment by Callcraft456** [comment]
Yea, close this , it doesnt an issue but just define `role` find it and then add ${role} to your send message thats it!
