### ISSUE TITLE
guildBanAdd is missing who is actually getting banned

### ISSUE THREAD

**Issue by JacobGunther12** [hydrabolt/discord.js#1603]
**Please describe the problem you are having in as much detail as possible:**
When the `guildBanAdd` event is fired, it never gives you who is actually getting banned. It gives plenty of information about the guild as the first callback argument, but that's it. This is not a feature that is in v12 yet. What is going on?

**Include a reproducible code sample here, if possible:**
```js
bot.on("guildBanAdd", console.log);
```

**Further details:**

- discord.js version: 11.0.0
- node.js version: 8.1.1
- Operating system: Debian 8.8 jessie
- Priority this issue should have – please be realistic and elaborate if possible: Medum to High

- [X] I have also tested the issue on latest master, commit hash: 35e8601

**Comment by Drahcirius** [comment]
guildBanAdd comes with (guild, user) as paramters. Your log used that way only gets the first parameter. If you do `client.on("guildBanAdd", (guild, user)=>console.log(user));` instead, you'll see that the user does come with the event.

**Comment by JacobGunther12** [comment]
Actually, it did log both. I just didn't see that it put both arguments so close together. Thanks

**Comment by F0xyProxy** [comment]
What's is guildBanAdd code?
