### ISSUE TITLE
Something took to long to do

### ISSUE THREAD

**Issue by IWasAndrerstajn** [hydrabolt/discord.js#1604]
When i run my code to start the bot it displays an error: Somthing took to long to do. Here is a screen shoot from it:
https://prnt.sc/fkgj4c
I also made another bot without any commands in the code just the starting code and it still didnt work

**Further details:**

- discord.js version: 11.1.0
- node.js version: 8.1.1
- Operating system: Windows 7 64Bit

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by appellation** [comment]
You haven't indicated any specific issue you're seeing with the library.  A reproducible code sample (which was requested in the issue template you've apparently disregarded) would be instrumental in determining the underlying cause of this issue.

**Comment by IWasAndrerstajn** [comment]
but its not in my code i tryed it in more than one code and it still didnt work

**Comment by IWasAndrerstajn** [comment]
anyway here is the code https://pastebin.com/snSf0Ljp

**Comment by eslachance** [comment]
"Something Took Too Long" is not a code problem. It's a connection problem. This indicates that the connection between your code and the Discord websocket timed out. This can be because of a bad connection, an outgoing firewall, or a badly configured network. It's not a lib issue.

**Comment by IWasAndrerstajn** [comment]
is there anyway to see what blocks the bot from running??

**Comment by dayxhep** [comment]
@IWasAndrerstajn , when you login
```js
bot.login('MzIw');
```
Change it by :

```js
bot.login('MzIw').catch(console.error);
```
This will display the error from Discord.js
I think that you have some trouble to connect, so let's what Discordapi answers you

**Comment by amfich** [comment]
help 
Profile - https://glitch.com/@tubamfich
http://prntscr.com/rvawbg
