### ISSUE TITLE
Adding target: parameter to fetchauditlogs

### ISSUE THREAD

**Issue by Wodki** [hydrabolt/discord.js#1607]
**Please describe the problem you are having in as much detail as possible:**
I am trying to fetch the last ban from the auditlogs. I initially tried simply using as option limit:1 but it appeared that the entrie returned is not always the last one. I know this is on discord's end. So I decided to use the user option. Looking at source and docs it appears it can be a few things including the id or the user object. I tried both. By using the id as in `guild.fetchAuditLogs({user: user.id})` I get many logs not limited to this id only. Below its the same thing instead using the user object.

**Include a reproducible code sample here, if possible:**
```js
client.on('guildBanAdd', (guild, user) => {
    guild.fetchAuditLogs({user: user}).then(logs => {
        console.log(logs.entries) //empty collection
    });
});
```

**Further details:**

- discord.js version: 11.1-dev
- node.js version: 6.11.0
- Operating system: windows 7/centOS
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Comment by OSCAR-WOS** [comment]
I too can second this issue. I've tried on 11.1 & 11.1-dev. I've tried all UserResolvables and still yields nothing. I was listening on event [MESSAGE_DELETE].
```
if (message.guild.member(<bot>.user).hasPermission('VIEW_AUDIT_LOG')) {
  await message.guild.fetchAuditLogs({user: <message>.author, type: 'MESSAGE_DELETE'})
  .then((guildAuditLogs) => {
    console.log(guildAuditLogs.entries)
  })
}

**Comment by Wodki** [comment]
Generally it has an issue with the action type DELETE. Even if I use a timeout and wait a second it will still return an empty colletion, while this is not the case with the action type UPDATE

**Comment by SpaceEEC** [comment]
I did a bit of debugging.
The user option seems to be only for the executor, aka the user who "initiated" the audit log entry, not the target.

However fetching audit logs directly without a timeout seems to work fine,
just fetch by type and then find by target.
```js
// example for guildBanAdd
client.on('guildBanAdd', (guild, user) => {
    guild.fetchAuditLogs({ type: 22 /* MEMBER_BAN_ADD */ }).then(logs => {
      // GuildAuditLogsEntry for this user and type
      console.log(logs.entries.find('target', user));
    });
});
```
I tested this on Master ([#00eebd](https://github.com/hydrabolt/discord.js/commit/00eebd34cb76e5366285025cb4deccfa0840618e)) with `MEMBER_KICK` (20), `MEMBER_BAN_ADD` (22), `MEMBER_UPDATE` (24) and `MESSAGE_DELETE` (72), everything logged as expected for me.

**Comment by Wodki** [comment]
I am currently doing it that way and indeed it works that way. I tested in 11.1 and 11.1-dev and stable (with small changes in the auditlog class). So I guess its an issue with fetching the logs for the _affected_ user from a deleted action.

**Comment by OSCAR-WOS** [comment]
Maybe adding a ``target:`` parameter to be put inside the object?

**Comment by iCrawl** [comment]
Decided against since it could be confusing what the meaning behind a `target:` parameter is.
You already have means to do this.
