### ISSUE TITLE
embed image server icons

### ISSUE THREAD

**Issue by Idevtanm** [hydrabolt/discord.js#1609]
I'm trying to add a image of server icons to embeds (not rich embeds).

```js
{url: ${message.guild.iconURL}}
```

**Comment by iCrawl** [comment]
Next time please read the Issue template you just deleted without reading it.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
