### ISSUE TITLE
VoiceConnection's UDP Stream not receiving data after idle timeout

### ISSUE THREAD

**Issue by AviiNL** [hydrabolt/discord.js#1613]
**Please describe the problem you are having in as much detail as possible:**
The udp stream stops receiving any data after a few minutes of idle in a voice channel

**Include a reproducible code sample here, if possible:**

https://gist.github.com/AviiNL/c37b2f9ec230699c722a76120e225bbb

**Further details:**

- discord.js version: 11.1.0 / master
- node.js version: 6.5.0 / 8.1.2 (tested both node versions on windows and linux)
- Operating system: Windows / Linux
- Priority this issue should have – please be realistic and elaborate if possible:
High - Parsing voice input is rather pointless now when not receiving data

- [x] I have also tested the issue on latest master, commit hash:
66cc5b2

**Comment by iCrawl** [comment]
Does this still happen?

**Comment by hydrabolt** [comment]
(in case it does, our voice stuff is being rewritten anyway)

**Comment by Scorpi** [comment]
Can confirm this bug. Windows 8.1 x64, node 8.5.0, discord.js 11.2.0
There's no close/error events from UDP socket, just no messages after 5 minutes (no matter silence or not).
