### ISSUE TITLE
Question (If message includes "xx", show "xx")

### ISSUE THREAD

**Issue by magnificentdev** [hydrabolt/discord.js#1631]
Hello,

i used
```
bot.on('message', (message) => {
    if(message.content == 'xyz') {
        // mit @ vor Nachricht // message.reply('Ja?');
        message.channel.sendMessage('**Message answer from BOT**);
    }
});
```

It works, when i type "xyz" only.
But when i type hello xyz - nothing happens.

How can i fix that?

PS: I'm a total noob, please give me an example :)

Thank you.

**Comment by Dev-Yukine** [comment]
Ask on the Discord Server please this "formular" is only for **Issues** with the Lib

**Comment by presskoala** [comment]
Thats because "hello xyz" does not equal "xyz".

**Comment by magnificentdev** [comment]
I already used Discord!

@presskoala I know, i need to know how i can do that.
