### ISSUE TITLE
Bug: channel.createInvite() always throws the error: TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by RealBlazeIt** [hydrabolt/discord.js#1639]
I tested it on master, 11.1-dev, and stable, all resulting in the same error.

Stack: https://cdn.discordapp.com/attachments/222078374472843266/330159294798495755/unknown.png

**Comment by devsnek** [comment]
you can't use createInvite with user accounts. #wontfix

**Comment by RealBlazeIt** [comment]
Then maybe that should be specified in the documentation like it is for the other methods that can only be used by bots.

**Comment by devsnek** [comment]
@RealBlazeIt it is planned for v12 docs
