### ISSUE TITLE
Cannot read property "get" of undefined.

### ISSUE THREAD

**Issue by brandonator365** [hydrabolt/discord.js#1646]
Hi, I'm trying to make my bot able to send messages to a certain channel in a server I'm designating by ID. However, every time I try to get the channel's ID using defaultChannel, I get this error when I use the command. "Cannot read property "get" of undefined."

Here's the code I'm using. It might look pretty bad, but I'm still learning node.js.

var channel = client.servers.get('id', "285566600143306752").defaultChannel;
client.sendMessage(channel, "Hello");

The exception obviously happens at "get". How can I fix this?

**Comment by devsnek** [comment]
this is all d.js v8 code. we are currently at v11.1.0.
```js
const channel = client.guilds.get('285566600143306752').defaultChannel;
channel.send('hello');
```

**Comment by brandonator365** [comment]
Yeah, I knew that code was outdated. Thanks for the help on getting it up to date, though! All is right with the world again.
