### ISSUE TITLE
[Feature] Blacklist channels to prevent sending messages to them

### ISSUE THREAD

**Issue by JacobGunther12** [hydrabolt/discord.js#1664]
**Please describe the problem you are having in as much detail as possible:** A while ago, I did a global announcement to every server my bot was on. For me, this was a huge mistake. It got my bot muted on Discord Bots server. Because of this, I had an idea. What about a way to blacklist the bot from sending messages to a channel or blocking the bot from joining certain voice channels? This can also apply to blacklisting sending messages to certain users and whole servers too. For example:
```javascript
bot.blacklist.guilds.set(msg.guild.id, msg.guild); // blacklist the current server
bot.blacklist.users.set(msg.author.id, msg.author); // blacklist the author of the message
bot.blacklist.channels.set(msg.channel.id, msg.channel); // blacklist the current channel
bot.blacklist.channels.set(msg.guild.channels.find("General").id, msg.guild.channels.find("General")); // blacklist the voice channel called General (prevents from connecting to it)
```
Blacklisting things could benefit like preventing a global announcement to that server that the admins get onto you about. This would help me a lot, and I think this would be a valuable feature.

**Further details:**

- discord.js version: 1.11.0
- node.js version: v8.1.3
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by eslachance** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

Did you *completely* ignore this note?

**Comment by JacobGunther12** [comment]
Ah, ok
