### ISSUE TITLE
<member>.presence does not match <user>.presence

### ISSUE THREAD

**Issue by Darqam** [hydrabolt/discord.js#1665]
**Please describe the problem you are having in as much detail as possible:**
Running an eval of `message.member.presence` returns (in this case): `Presence { status: 'online', game: null }`

While running `message.author.presence.` returns : `Presence { status: 'online', game: [Object] }`
with the `message.author.presence.game` returning the expected 
```
Game {
  name: 'Hello Kitty Super Mountain Adventures!',
  type: undefined,
  url: null }
```

So basically member presence does not seem to reflect the set game properly.

**Include a reproducible code sample here, if possible:**
```js
message.member.presence

and

message.author.presence

```

**Further details:**

- discord.js version: 11.1-dev
- node.js version: 8.1.1
- Operating system: Win10
- Priority this issue should have – please be realistic and elaborate if possible: low, it's mainly a consistency issue.

- [ x ] I found this issue while running code on a __user account__

**Comment by devsnek** [comment]
user presence is just "whatever presence came from a member for that user last"
use member presence whenever possible

**Comment by iCrawl** [comment]
Not much we can do about this. Do what Gus told you.
