### ISSUE TITLE
VoiceConnection.disconnect() causes dispatchers to stop sending packets.

### ISSUE THREAD

**Issue by Monskiller** [hydrabolt/discord.js#1668]
**Please describe the problem you are having in as much detail as possible:**
Whenever I disconnect the bot from a voice channel/connection (either by .disconnect or .leave) it causes dispatchers on other servers to stop sending packets. Users need to either pause and resume the stream to hear the bot again, or leave and rejoin the channel.

Bot's using ytdl-core to get an opus stream and play it.
Only workaround I've found is to quickly pause and resume when disconnect even is fired.

```js
client.voiceConnections.get(guild.id).on("disconnect", () => {
	client.voiceConnections.forEach(vc => {
		if (vc.dispatcher) {
			if (!vc.dispatcher.paused) {
				setTimeout( function() {
					vc.dispatcher.pause();
					setTimeout( function() {
						vc.dispatcher.resume();
					}, 300);
				}, 100);
			}
		}
	})
})
```

Yeah, it's ugly.

**Include a reproducible code sample here, if possible:**
```js
const buffer = require("buffered2").BufferedStream;
let song;

song = new buffer();
ytdl(yt.id, { filter: "audioonly" }).pipe(song);

client.voiceConnections.get(guild.id).playStream(song);

client.voiceConnections.get(anotherGuild.id).disconnect();
```

**Further details:**

- discord.js version: 11.1.0
- node-opus version: 0.2.6
- node.js version: 8.1.2
- Operating system: Ubuntu 16.04.2 LTS (Xenial Xerus)
- Priority this issue should have – please be realistic and elaborate if possible:
Medium, unless I'm doing something wrong.

- [ ] I found this issue while running code on a __user account__

- [x] I have also tested the issue on latest master, commit hash: 4e5556ba09e3c41a3a572abfb98521a2fd1918bf

**Comment by RosieCode95** [comment]
this issue is most likely this which discord have known about for some time, this is a client side bug and nothing todo with ur bot.

https://trello.com/c/fVzj57Pa/181-bot-disconnecting-from-an-audio-server-in-mutual-guild-stops-playback-in-current-voicechannel
