### ISSUE TITLE
MaxListenersExceeded when assigning single role to multiple users in same loop

### ISSUE THREAD

**Issue by Kezaraux** [hydrabolt/discord.js#1671]
**Please describe the problem you are having in as much detail as possible:**
I was trying to loop over an array of GuildMembers and assign a role to each one. I then encountered this issue (this is from when I had a .then() on my code):
`(node:36968) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 guildMemberUpdate listeners added. Use emitter.setMaxListeners() to increase limit`

**Include a reproducible code sample here, if possible:**
```js
var assignNoxusMember = function(m) {
    const mem = m.guild.members.array();
    const roleToAdd = m.guild.roles.find("name", "ROLE NAME");
    const noxusRolesArr = ["Array of roles to check against"];
    let arrOfTargets = [];
    for (let i = 0; i < mem.length; i++) {
      if (mem[i].hoistRole) {
        if (noxusRolesArr.indexOf(mem[i].hoistRole.name) >= 0) {
          mem[i].addRole(roleToAdd).catch(console.error);
        }
      }
    }
  };
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 8.1.3
- Operating system: Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: Moderate? I have no indicator of how this should be ranked.

- [ ] I found this issue while running code on a __user account__
Not sure what that is asking me? I assume no though?

- [X ] I have also tested the issue on latest master, commit hash: 4e5556ba09e3c41a3a572abfb98521a2fd1918bf
^ I hope that's what I'm supposed to put there. New to this posting an issue thing.

**Comment by iCrawl** [comment]
This is sort of a non-issue. It is expected to happen, those listeners are not permanent though.

**Comment by hydrabolt** [comment]
Well it is still issue as an unnecessary warning is raised. There's a workaround we could add to fix it.

**Comment by hydrabolt** [comment]
Just to clarify, are you using the latest version of discord.js on npm, or are you using the master branch on this repository?

**Comment by Kezaraux** [comment]
Umm, latest version on NPM? I sort of thought they were the same, but I guess not.

**Comment by Kezaraux** [comment]
Okay, I'm a monkey. After I downloaded the master branch files and swapped them out in my project, I ran the same code and I didn't get the error message! However, there is a noticeable pause after about 10 members have been updated, but it continues to run.

**Comment by devsnek** [comment]
that "noticeable pause" is the ratelimiter making sure you don't get beaned
