### ISSUE TITLE
Bot closing because of "fn()".

### ISSUE THREAD

**Issue by AnAuguseh** [hydrabolt/discord.js#1674]
**Please describe the problem you are having in as much detail as possible:**
When ever your running the bot, the error says: ```js
C:\Users\USER\Desktop\Projects\FOLDER\node_modules\discord.js\src\client\Client.js:422
      fn();
      ^

TypeError: fn is not a function
    at Timeout.setTimeout [as _onTimeout] (C:\Users\USER\Desktop\Projects\FOLDER\node_modules\discord.js\src\client\Client.js:422:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Include a reproducible code sample here, if possible:**
None, something isn't a function!

**Further details:**

- discord.js version: v11.1.0
- node.js version: v8.1.3
- Operating system: Windows 10 Pro
- Priority this issue should have – please be realistic and elaborate if possible: ```js
fn();``` not being a function.

**Comment by iCrawl** [comment]
This is related to the outage the discord servers had.

**Comment by PathogenDavid** [comment]
@iCrawl Can you point us to a specific commit or set of commits that fixed this issue? I'd like to hotfix this issue until the next full release.

**Comment by SpaceEEC** [comment]
You can find the pr here: #1673 
And the relevant commit here: [c0e9ce2](https://github.com/hydrabolt/discord.js/commit/c0e9ce2a1dc2f86755def2b7e0c025fe191c558b)

**Comment by PathogenDavid** [comment]
Thanks for both the fix and the link!

(Sorry for the late response, only just now realized I forgot to respond.)
