### ISSUE TITLE
ReactionAdd event ignores old messages even if the bot is running on a bot account

### ISSUE THREAD

**Issue by meldsza** [hydrabolt/discord.js#1675]
The code at 
https://github.com/hydrabolt/discord.js/blob/master/src/client/actions/MessageReactionAdd.js
Ignores messages that haven't been already cached. So if I want to listen to message reactions that were sent before my not restarted, I would not be able to.

**Further details:**

- discord.js version: master
- node.js version: 7.8
- Operating system: CentOs
- Priority: 5/10

I found this issue while running code on a **bot account**

- [x] I have also tested the issue on latest master, commit hash:

**Comment by dragonfire535** [comment]
Indeed, you will have to fetch any messages not in cache for events to fire.

**Comment by Drahcirius** [comment]
This is currently the expected behaviour, Currently, #1376 is on the roadmap for v12, which will allow you to receive previously uncached reaction events with a client setting.

**Comment by meldsza** [comment]
Is there a separate branch for v12 i can contribute to?

**Comment by Drahcirius** [comment]
Master branch is v12. Contributions are welcome, but I will be submitting a PR for it soon.

**Comment by iCrawl** [comment]
Duplicate of #1376
