### ISSUE TITLE
Cross Origin error in FF and not Chrome

### ISSUE THREAD

**Issue by TechEdison** [hydrabolt/discord.js#1678]
**Please describe the problem you are having in as much detail as possible:**

Getting a CORS error when trying to access the API. It's only affecting Firefox and not Chrome.

Open the Developer console on Firefox and navigate to https://www.discordmobile.ml/ for a reproducible error. No need for credentials, just push Submit.
![screenshot from 2017-07-10 10 50 42](https://user-images.githubusercontent.com/29295528/28024069-aca7a3c0-655d-11e7-9baa-4ada0f2c269f.png)

**Further details:**

- discord.js version: 6.0.0 Webpack
- node.js version: N/A
- Operating system: 
   - Ubuntu 16.04/Firefox 53.0.3 64bit (Not working)
   - Mac OS X 10.7/Chrome ? 64bit (Working)
   - Windows Phone 8/IE 11 Mobile (Working)
   - Windows Phone 10/Edge Mobile (Working)

**Comment by iCrawl** [comment]
discord.js version 6?

**Comment by TechEdison** [comment]
Yes it's required for certain aspects of the API. I didn't write the original code, but the original code required 6.0.0

**Comment by iCrawl** [comment]
We do not support any versions outside of https://github.com/hydrabolt/discord.js/tree/webpack anymore.

Those are stable (11.1), 11.1-dev (11.2) and master (12).

**Comment by TechEdison** [comment]
Ah that's too bad.. Thank you for the insight.
