### ISSUE TITLE
How to create a role?

### ISSUE THREAD

**Issue by TheZipCreator** [hydrabolt/discord.js#1681]
So basically I do not know how to create a role in discord.js
Also
client.createRole doesn't work, so I have no idea how I'm supposed to do this.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
