### ISSUE TITLE
presenceUpdate Double Fire with Duplicate Members for oldMember and newMember

### ISSUE THREAD

**Issue by xCykrix** [hydrabolt/discord.js#1684]
**Please describe the problem you are having in as much detail as possible:**
Event presenceUpdate fires twice, oldMember and newMember being the same both times.

**Include a reproducible code sample here, if possible:**
```js
$.client.on('presenceUpdate', (userbefore, userafter) => {
    console.log("Update Event Fired for " + userbefore.user.tag);

    if(userbefore.user.presence.game === userafter.user.presence.game) {
        return console.log("Same Game"); // Logged Twice, same for both users.
    }
    console.log("GameBefore: " + userbefore.user.presence.game.name);
    console.log("GameAfter: " + userafter.user.presence.game.name);
});
```

**Further details:**

- discord.js version: v11.1.0 and v12.0.0-dev
- node.js version: v8.1.2
- Operating system: WindowsOS
- Priority this issue should have – please be realistic and elaborate if possible: Medium, it is not a huge issue but is entirely breaking if you need to rely on presence changes.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: (v11.1.0: 04f0534) (v12.0.0: 111fa2d)

**Comment by devsnek** [comment]
know issue, fixed with #1618

**Comment by xCykrix** [comment]
Ah, thank you. So I guess when that request is fullly merged it should work on fixing this problem and some others?

**Comment by hydrabolt** [comment]
Fixed in that commit ^, as a sidenote use `member.presence` not `member.user.presence` because the latter is not really a real thing.
