### ISSUE TITLE
Bot goes offline after 500 times client.user.setGame

### ISSUE THREAD

**Issue by Ksnz** [hydrabolt/discord.js#1686]
When i called client.user.setGame every 0.5 seconds he goes to offline.
I don't know english well but want to help lol 😅

**Comment by devsnek** [comment]
can't repro

**Comment by Dev-Yukine** [comment]
why would you call setGame every 0.5 seconds :thinking:

**Comment by CharlotteDunois** [comment]
@Ksnz It's because Discord closed the gateway connection because you are flooding it.
