### ISSUE TITLE
Discord JS Install not working

### ISSUE THREAD

**Issue by Parkourist** [hydrabolt/discord.js#1689]
I keep getting this i cant find anything about it.
it happens when i want to install discord.js in cmd

npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read
npm ERR! EISDIR: illegal operation on a directory, read

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PRIVATE\AppData\Roaming\npm-cache\_logs\2017-07-16T18_57_49_970Z-debug.log

**Comment by devsnek** [comment]
That's an npm error, not a discord.js error, and is out of scope of our issue tracker.
