### ISSUE TITLE
.playFile() & .playStream() delays

### ISSUE THREAD

**Issue by CheesyZaem** [hydrabolt/discord.js#1693]
First of all, I am not quite sure if this has something to do with versions stuff, and I think it is an issue, and yes this is my first time doing this, and yes I have been asking for several days in the support server, but no one seems to figure it out so I have decided to post it here, if this is not an issue then I am so sorry.

Issue: If a bot is playing songs, when a song ends, the .playFile() delays, at first it does not delay but after a lot of songs, it can delay for up to 2 minutes(according to what I've only experienced), the duration of delay increases more and more after each song. According to what I've been experimenting it might not be because of my code, and yes I am still a noob, even though I've been coding with Discord.JS for like 7 months.

Additional information (Mostly assumption): 
i) The delays are differentiated in each server, even though the bot has delayed a lot in a server, but if you play in another server it'll play immediately.
ii) Messages sent before the delays, which kinda means it has nothing to do with CPU usage or whatever.

Further details:
Discord.JS version: 11.1.0
Node.JS version: 8.0.0
Operating system: Ubuntu

**Comment by iCrawl** [comment]
I'm not sure why people always delete the Issue template. Would be nice if you could edit your post with the Issue template.

**Comment by gmedeadlystrike** [comment]
i have seen this issue as well

**Comment by iCrawl** [comment]
Can't repro

**Comment by Dev-Yukine** [comment]
I also have that issue here and it only happen if my bot plays on 2 different voiceConnections at the same time here but the dispatcher start event id emitted when the stream should start

**Comment by 69** [comment]
Same here, the first play is almost instant but then it gradually gets more and more delayed until it takes up to half a minute for the file to play back. I only use one voiceConnection ever.

**Comment by co-jo** [comment]
I had an issue with similar symptoms. In my case, it happens when you pause, and unpause a stream. It was due to the pausedTime prop on the AudioPlayer class. Everytime a new dispatcher is created, the pausedTime is carried over as the AudioPlayer is instantiated once per connection. Any summation on this prop between dispatchers (Noticed a few lines in the StreamDispatcher) will also be carried over. Based on the way the nextTick is calculated in StreamDispatcher, this delay only really occurs when startTime === Date.now() (When a dispatcher emits the start event).

My resolution was resetting this field to 0 on a new dispatcher instance.

For example;

```
message.channel.join()
    .then(connection => {
      ....
      const dispatcher = connection.playFile(path);
      dispatcher.on('start', => {
        connection.player.streamingData.pausedTime = 0;
      });
      ....
    });
```

**Comment by Dev-Yukine** [comment]
i can only say for myself in my code i dont have any pause&resume function so it cant be this for my thing

**Comment by Dev-Yukine** [comment]
@co-jo your fix work well so far for myself thank you 👍

**Comment by devsnek** [comment]
can't someone just make a pr /tableflip

**Comment by jamesbrooks** [comment]
@co-jo Thanks for pointing out your fix involving `connection.player.streamingData.pausedTime`. I've been trying to battle this issue for a while thinking it was a combination of v8/node/opus version conflicts causing me this issue but after reading your post and logging that pausedTime value I could see it increasing every playback - setting it back to zero has completely resolved the issues I've been having for many months!
