### ISSUE TITLE
Setnickname

### ISSUE THREAD

**Issue by xodinexox** [hydrabolt/discord.js#1698]
```
client.on("message", function(message)  {
  var name = message.sender;
  let prefix = "!";

  if (!message.content.startsWith(prefix) || message.author.bot) return;

  if (message.content.startsWith(prefix + "lol")) {
    name.setNickname("[Lol] " + name);
```

Hello i have problem with setnickname
Error:  Cannot read property 'setNickname' of undefined

Thanks for help

**Comment by vzwGrey** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
