### ISSUE TITLE
<TextChannel>.fetchMessages() messes with chronological order of <TextChannel>.messages.

### ISSUE THREAD

**Issue by Tvde1** [hydrabolt/discord.js#1699]
**Please describe the problem you are having in as much detail as possible:**

`<TextChannel>.fetchMessages()` doesn't put the messages into `<TextChannel>.messages` in chronological order.

**Include a reproducible code sample here, if possible:**

Here's the steps to reproduce the problem.
1. Open a chat with at least one message.
2. Send a message with the text "Expected".
3. Start bot and fetch messages.
4. eval `channel.messages.last()`.

We'd expect to see the message with the content "Expected" because it is the last sent message. However an older message (cached by `fetchMessages`) appears.

**Further details:**

- discord.js version: v12.0.0-dev
- node.js version: v8.1.0
- Operating system: Windows 10 x68
- Priority this issue should have – please be realistic and elaborate if possible: low

- [X] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash: edfd50d003a7168000ed10b01f8e3817d58439ca

**Comment by Tvde1** [comment]
I'm not sure if this is a bug or if the user should just sort them by timestamp if they need it to be in the right order.

**Comment by bdistin** [comment]
Maps and by extension Collections are only sorted by insertion order, so fetchMessages inserting them at the end is expected. Additionally, Collection.sort() returns a new Collection, it doesn't modify the source collection.

**Comment by Tvde1** [comment]
Should the collection be sorted after the messages are fetched?

**Comment by bdistin** [comment]
<Channel>.messages.sort() does not change <Channel>.messages; it gives you a brand new sorted collection. <Channel>.messages would still be in the same order.

**Comment by appellation** [comment]
You're welcome to do that if you want, but it's meaningless overhead to include sorting in the `fetchMessages` method itself.

**Comment by Tvde1** [comment]
I do thing we should `messages = messages.sort()` in the method because it may cause weird behavior for people who haven't found out how the method adds newly cached messages.

**Comment by appellation** [comment]
1. Sorting is slow
2. Not everyone needs their collection sorted
3. If you need a guaranteed order in your collection, you should be sorting it anyway

**Comment by Tvde1** [comment]
Hmm okay. Closing this issue.
