### ISSUE TITLE
setUsername not working on user account bots

### ISSUE THREAD

**Issue by NewVoids** [hydrabolt/discord.js#1702]
Hello everyone,
I trying to change a userbot's username using the setUsername function. However, whenever I try to call it, it says "password: Password does not match.". I know the password is correct. Does anyone know how I can solve this issue?
Here's my code.
`client.login('my token')
client.password = 'my password'
client.on('ready', () => {
client.user.setUsername('mybot','my password')
});`

Thank you,
Josh

**Comment by vzwGrey** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the Discord server instead of opening an issue.

**Comment by NewVoids** [comment]
@vzwGrey I believe this is an issue. I asked in the discord and they didn't know what it was.

**Comment by vzwGrey** [comment]
Well, you don't set `client.password` manually. You just login with `client.login('your token')` and then you can use the Client#setUsername method in the ready event handler.

**Comment by NewVoids** [comment]
I tried it without client.password and it still didn't work

**Comment by HasanBrandsXD** [comment]
This happend to me too when I had Discord.JS 11.0.0, but the latest one does not have this issue. For now, I can't repro this.

**Comment by CyberiumShadow** [comment]
![image](https://user-images.githubusercontent.com/4259904/28805576-77396d4c-76ae-11e7-9c30-e8aae810edaf.png)
It works when I make the direct API request.

However, within the library itself, this occurs including the correct password 
![image](https://user-images.githubusercontent.com/4259904/28805595-9c2d20b2-76ae-11e7-8988-5acd87b5d635.png)

Looking into the source files, on D.JS latest within the APIRequest.js in the REST Folder
I have console.logged `this.options.data` 
![image](https://user-images.githubusercontent.com/4259904/28805775-a7e00522-76af-11e7-9293-0c312455aa8d.png)

Run an eval to change username whilst including the password as the second argument as per docs, and you see that data.password is **UNDEFINED** 
![image](https://user-images.githubusercontent.com/4259904/28805786-c42279c2-76af-11e7-95cf-7948d4b48cac.png)

@vzwGrey @iCrawl
