### ISSUE TITLE
Website background glitch

### ISSUE THREAD

**Issue by WernerderChamp** [hydrabolt/discord.js#1706]
I'm using Firefox 54.0.1 to access discord.js.org but around every second time the background glitches and makes the bottom of the page hard to ready.

Please fix it. Screenshots are attached
![website_bug2](https://user-images.githubusercontent.com/23498090/28472966-22626684-6e43-11e7-9153-a801552fcebc.png)
![website_bug](https://user-images.githubusercontent.com/23498090/28472965-225f16f0-6e43-11e7-8db8-039f8127b52d.png)

**Comment by iCrawl** [comment]
This should be reported here: https://github.com/hydrabolt/discord.js-site
