### ISSUE TITLE
Error: socket hang up happens when the bot joins/leaves a server

### ISSUE THREAD

**Issue by Dev-Yukine** [hydrabolt/discord.js#1707]
**Please describe the problem you are having in as much detail as possible:**
```events.js:182
  throw er; // Unhandled 'error' event
  ^
  Error: socket hang up
     at createHangUpError (_http_client.js:343:15)
     at TLSSocket.socketOnEnd (_http_client.js:435:23)
     at emitNone (events.js:110:20)
     at TLSSocket.emit (events.js:207:7)
     at endReadableNT (_stream_readable.js:1045:12)
     at _combinedTickCallback (internal/process/next_tick.js:102:11)
     at process._tickCallback (internal/process/next_tick.js:161:9)
```
this error happen often in the last time when my Bot joins or leaves a server and it should not be an issue with my code/internet connection of my bots VPS.

**Further details:**

- discord.js version: 11.1
- node.js version: 8.1.4
- Operating system: Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:
medium because it happen pretty often and a bot should not crash every 6 hours :thinking: 

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
it shouldn't be, but it is.

**Comment by Dev-Yukine** [comment]
so its something in my code?

**Comment by melmsie** [comment]
I've also gotten a ton of this lately for no reason. No code has been changed.

**Comment by devsnek** [comment]
its your network, sorry to disappoint.

**Comment by Dev-Yukine** [comment]
oh okay well i will close this issue then but it s the same for me it worked so well for a long time and now i get it like idk every 7 hours maybe :c

**Comment by gavwin** [comment]
I've been getting the same issue as well, I highly doubt it's my network..,

**Comment by PassTheMayo** [comment]
same issue here, hasn’t been occurring until today after reinstalling d.js

**Comment by devsnek** [comment]
@PassTheMayo @gavwin @Dev-Yukine @melmsie where do you host

**Comment by PassTheMayo** [comment]
OVH @devsnek

**Comment by PassTheMayo** [comment]
Melmsie uses OVH too

**Comment by melmsie** [comment]
Wholesale

**Comment by PassTheMayo** [comment]
Oh

**Comment by melmsie** [comment]
Weird that two separate hosts are having the same issue with something that
I don't have an issue with in Eris. :Thonk:

**Comment by PassTheMayo** [comment]
I haven't been having this issue until recently. I don't know what the issue is. I haven't touched iptables or blocked anything. Just to be safe, I am going to reinstall the VPS. /shrug

**Comment by meldsza** [comment]
I have been having this issue a lot since the past 10-15 days
I host on vultr

**Comment by Dev-Yukine** [comment]
since a lot of people here having this again. mine was an error in my guildCreate/guildLeave event code where i had an error using snekfetch. could you confirm your guildCreate/guildLeave event code isn't the issue?

**Comment by meldsza** [comment]
I have disabled guildCreate and guildLeave so I can confirm that those events may not be the cause of the issue

**Comment by ChrisTalman** [comment]
Was any progress made with this issue? I've encountered these exceptions quite randomly on various occasions over the past year or so. This shouldn't be happening.

**Comment by DedaDev** [comment]
I also have this problem, also my app is freezing every ~2min.

**Comment by FantzFoXx** [comment]
Same problem here...

**Comment by Aviorleking** [comment]
Same issue here tested on local machine and on openshift

**Comment by yoshifan509** [comment]
Having this issue too. Happens about 5 seconds after I run a command.

**Comment by MerriemWeebster** [comment]
I host on heroku. Been having this issue since I re-installed discord.js.

**Comment by cheesits456** [comment]
I host on my own personal computer. My bot had been running for ~2 months with no downtime and no changes to any of the code when this error started happening for me. Once every ~5 minutes, the bot crashes and gives a 'socket hang up' error from line 165 of events.js

**Comment by Aviorleking** [comment]
mine is listening to it is it where the error com from ?

**Comment by ChrisTalman** [comment]
In my experience, listening to the event seems to prevent network errors like `ECONNRESET` from being thrown. Having said that, I haven't tested this extensively, so my perception might be mistaken.
