### ISSUE TITLE
sendFile - http links do not work

### ISSUE THREAD

**Issue by nicholastay** [hydrabolt/discord.js#171]
HTTP links do not work but HTTPS links do.

I believe it is because of the regex written at src/Resolver.js#80 (https://github.com/hydrabolt/discord.js/blob/indev/src/Client/Resolver/Resolver.js#L80). It perhaps should be `/^https?:\/\//` as the `(s)` means an 's' character is required as a group capture, not as an optional capture.

**Comment by meew0** [comment]
For me, it works fine now, but I've had reports of it not working. Can someone confirm this is working (@khionu?)

**Comment by meew0** [comment]
I've made the other issue separate (#172) as they seem to be largely unrelated.
