### ISSUE TITLE
[Enhancement] Allow to build an emote from it's name

### ISSUE THREAD

**Issue by lodi-g** [hydrabolt/discord.js#1712]
Hi,

I'm trying to react to a post using an emote name (and not the unicode character), like what follows:

```js
let emote = ':ok_hand:';
msg.react(emote);
```

It doesn't work and I was told in the Discord.js Discord server that it is not possible to do so.
I think it could be an improvement to be allowed to do the following:

```js
let emoteName = ':ok_hand:';
let emote = new ReactionEmoji();
emote.setName(emote);
msg.react(emote);
```

Thanks

**Comment by vzwGrey** [comment]
For that to be be possible we'd have to map all the emoji shortcodes Discord uses to their respective unicode character. This would take *ages* seeing how many emojis Discord has.

It'd be a lot quicker for you to do a small google search for the 5-6 emojis you need. (Literally all it takes is "ok hand unicode" and you'll find the unicode character for it).

**Comment by q-ata** [comment]
https://www.npmjs.com/package/node-emoji

**Comment by devsnek** [comment]
we already decided against this a very long time ago, just paste the raw emoji in, it isn't hard

**Comment by lodi-g** [comment]
@vzwGrey It took me approx. 5 minutes to do it for 35+.

```js
const emTable = {
  'a': '🇦',
  'b': '🇧',
  'c': '🇨',
  'd': '🇩',
  'e': '🇪',
  'f': '🇫',
  'g': '🇬',
  'h': '🇭',
  'i': '🇮',
  'j': '🇯',
  'k': '🇰',
  'l': '🇱',
  'm': '🇲',
  'n': '🇳',
  'o': '🇴',
  'p': '🇵',
  'q': '🇶',
  'r': '🇷',
  's': '🇸',
  't': '🇹',
  'u': '🇺',
  'v': '🇻',
  'w': '🇼',
  'x': '🇽',
  'y': '🇾',
  'z': '🇿',
  '0': '0⃣',
  '1': '1⃣',
  '2': '2⃣',
  '3': '3⃣',
  '4': '4⃣',
  '5': '5⃣',
  '6': '6⃣',
  '7': '7⃣',
  '8': '8⃣',
  '9': '9⃣'
};
```

Leaving it here, in case you want to spend like an hour completing it. A few regexes and it's done (picked them [here](http://twitter.github.io/twemoji/2/test/preview.html)).

@q-ata That is a slow, bloated, and unneeded solution.

@devsnek Thank you for helping! I didn't try pasting it, it really isn't hard. -- Jokes aside, there is a handful reason why you wouldn't want to 'paste the raw emoji in': 
* Not all text editors support it fully (most still count the emote as 3 chars - that is what it *really* is, but it's quite annoying)
  * Even Discord copies the name of the emote and not it's unicode character.
* You may want to **generate** an emote from a message.
* It's not heavy to implement and (depending of the Emoji class implementation) easy.

**Comment by devsnek** [comment]
> Not all text editors support it fully

if your text editor doesn't support unicode then its shit and don't use it
> Even Discord copies the name of the emote

not true in all cases and even so has nothing to do with this, because we aren't the discord client
>You may want to generate an emote from a message.

what you do with a message isn't out problem (see below)
> It's not heavy to implement and (depending of the Emoji class implementation) easy.  

```js
// assuming node-emoji
message.react(emojis.get('ok_hand')); // now we don't need to bloat our deps with things, and you can still do this all by yourself!
```

**Comment by iCrawl** [comment]
>we already decided against this a very long time ago, just paste the raw emoji in, it isn't hard

📕

**Comment by lodi-g** [comment]
@devsnek Again a great insight that shows how much concerned you are with your users. But tbh, discord.js is shit and I will stop using it. I think that would be better.
And where do you see me talking about **any** dependancies?

**Comment by KingDGrizzle** [comment]
And what makes you think Discord.JS is shit? For not implementing something thats as easy as going to discord, typing `:ok_hand:` adding a `\` before and then copying that in your msg.react code..

**Comment by lodi-g** [comment]
Please read the whole thing before commenting, you have no idea what you're talking about.

**Comment by appellation** [comment]
I'm confused about why this is so hard for you to do yourself; since it's clearly a big deal for you, what's stopping you from just making the emoji map?  The decisions of the library do not have to impact your own code on such a level.

Personally, I disagree with this issue because I do not want discord.js to get bloated with either a new dependency or a massive emoji map that I will never use.  As multiple people have pointed out, it is extremely simple to use raw unicode or make/use your own emoji map if your are inclined to do so.

Frankly, it's shocking that someone could be so self-centered as to assume a convenience feature they'd use would be universally useful to most of the consumers of the library; while I understand that we need to discuss these ideas in order to determine perceived viability, your attitude about forcing it down our throats in the face of reasonable objections has done nothing but antagonize.  Regardless, best of luck with your new discord library.

**Comment by motet-a** [comment]
@lodi-g Moreover, I’ll probably look preachy, but [friendlyness and respectfullness](http://todogroup.org/opencodeofconduct/) are quite important on GitHub — that’s just how the community work. Thanks.

**Comment by lodi-g** [comment]
I'm sorry if I appeared aggressive or not respectful of your work ; that was not meant to happen.
Also, nice link @motet-a, though I do think I'm not the only one that should read it.
