### ISSUE TITLE
Fetching Audit Logs turns into Missing Permissions error if unable to fetch invites

### ISSUE THREAD

**Issue by CharlotteDunois** [hydrabolt/discord.js#1718]
**Please describe the problem you are having in as much detail as possible:**
When I try to fetch Audit Logs with my bot, this turned without `MANAGE_SERVER` permissions always into a `Missing Permissions` error, even though the bot clearly had permissions to view the audit logs. Upon further investigation, I saw that there was an outgoing request to fetch invites, which failed.

I see this as bug as I think fetching Audit Logs shouldn't fail, even if it can't fetch invites, which means we need to a `catch` block to the fetch invites promise.

**Further details:**

- discord.js version: v11.1-dev
- node.js version: 8.1.3
- Operating system: Debian Jessie & Win7

**Comment by devsnek** [comment]
fixed in #1721
