### ISSUE TITLE
DiscordAPIError: undefined on bot startup

### ISSUE THREAD

**Issue by tripl3dogdare** [hydrabolt/discord.js#1725]
**Please describe the problem you are having in as much detail as possible:**

I get the following error upon starting up my bot:

```
(node:4968) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: undefined
(node:4968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It does not seem to interfere with functionality, but it's quite annoying and I have no idea where it might be coming from.

**Include a reproducible code sample here, if possible:**
```js
const bot = new Discord.Client()
bot.login(data.token)

bot.once("ready", () => {
  Object.keys(cmds).forEach(key => {
    cmds[key].name = key
    if(cmds[key].aliases) cmds[key].aliases.forEach(al => cmds[al] = { aliasTo: key, hidden: true })
  })

  bot.user.setGame("in VR | "+data.prefix+"help")
  bot.user.setAvatar("./site/assets/avatar.png")

  console.log("Initialization complete.")
  bot.on("ready", () => {
    console.log("Reconnected.")
    bot.user.setGame("in VR | "+data.prefix+"help")
  })
})

bot.on("disconnect", e => e.code === 1000 ? bot.destroy().then(() => {
  bot.login(data.token)
  console.log("Disconnected with code 1000 - restarting client")
}) : console.log("Disconnected."))

bot.on("reconnecting", () => console.log("Attempting to reconnect..."))
bot.on("error", e => console.log(`Something went wrong.\n${e}`))
```

**Further details:**

- discord.js version: ^11.1.0
- node.js version: 8
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low (not actually affecting functionality, just annoying)

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by eslachance** [comment]
```
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
```

Gotta love it when people **completely** ignore this.

**Comment by SpaceEEC** [comment]
Most likely related to #1554.

**Comment by tripl3dogdare** [comment]
This isn't a usage issue. It's a bug. There is nothing in my code that would cause this as far as I can tell. Please refrain from being an ass.

**Comment by eslachance** [comment]
Ok. I admit. I was an ass. Soz.

**Comment by tripl3dogdare** [comment]
@SpaceEEC Ah, that seems like it might be right. Thank you! I'll try taking a look into that.

**Comment by tripl3dogdare** [comment]
Yup, that was the issue. I've added an error handler to eat the rate limiting error there - it shouldn't be an issue in production, my bot is only rebooting often enough to cause the issue because I'm actively working on it. Thanks for the help!

**Comment by SpaceEEC** [comment]
You might want to only change the bot's avatar when it's necessary, because unlike your game status it will stay across restarts.
Glad you could sort out your issue anyway.
