### ISSUE TITLE
Expose shard type property with the introduction of internal sharding

### ISSUE THREAD

**Issue by gmedeadlystrike** [hydrabolt/discord.js#1726]
Enhancement Request

Internal sharding is a great addition for many bots, but it now introduces the possibility of client.shard being a thing without there being multiple processes. 

In order to make switching between a development and production environment simple on a sharded bot I would frequently use 
`if(client.shard){
//Do some shard code (usually broadcast eval)
}else{
//Do some normal code
}
`

However this is no longer a valid option with internal shading.

Adding a property to the shard to determine if it was spawned via a manger or internal would open a lot of options

**Comment by devsnek** [comment]
writing code in general for internal vs manager will be very different and shouldn't be done in such a way that they can be easily switched, as this would be bad for perf and such. IMO we should not do this

**Comment by gmedeadlystrike** [comment]
I agree having constant checks would indeed be a hit in performance. But the way I do this, it shouldn't be.

I have some operations that need to resolve guilds, update object properties that pose some challenge on sharded environments requiring the use of broadcast eval. To make my life easier being able to switch between my non-sharded dev bot, few shards beta-bot, and many shards prod-bot. I restructured the few functions that do call upton these methods.

On bot launch I create a object that is "mostly" globably accessible. I have a 2 .js files, one contains normal DJS functions, the other contains broadcastEval equivalents. Then based on the sharded status on the process, I mount one set or the other to said object which can then be called as needed without additional checks.

I guess this "Could" open up some avenues for poor code and performance, but aren't there already many many avenues for said issues. 

> Give person a gun, maybe he shoots himself, maybe he doesn't

**Comment by devsnek** [comment]
i don't think you quite understand the structure of internal sharding. It just makes more ws connections. To the end user you can't tell its even sharding. The only way to tell will be `client.ws.shards.size > 1`

**Comment by Lewdcario** [comment]
Closing since this appears to be dead/resolved.
