### ISSUE TITLE
npm install fails, missing node-opus?

### ISSUE THREAD

**Issue by WEDSGARBAGEDAY** [hydrabolt/discord.js#173]
when running the command "npm install --save discord.js" it always fails due to what appears to be the absences of the node-opus module.
The errors mostly look like this:
fatal error C1083: Cannot open include file: 'config.h': No such file or directory [path\to\directory\node_modules\discord.js\node_modules\node-opus\build\deps\libopus.vcxproj]

**Comment by khionu** [comment]
Do you have Visual Studio?

**Comment by WEDSGARBAGEDAY** [comment]
Yes, I've installed visual studio community 2015 and have it working. For reference, when installing chalda's discord bot (https://github.com/chalda/DiscordBot) the same thing happens but doesn't cause a complete failure (all other modules are installed and the bot can run)

Was there something I was supposed to do with node-opus before installing discord.js?

**Comment by hydrabolt** [comment]
I know it's unlikely, but can you try specifying the `msvs_version` flag? `npm install --msvs_version=2015 discord.js`

**Comment by WEDSGARBAGEDAY** [comment]
Just tried it and got the same output, I think 2015 is the default on my computer. 
I also just noticed that when running install it creates a node_modules folder inside discord.js-master containing a node-opus folder and so on all the way down to discord.js-master\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref\build\Release\obj\binding\binding.tlog, which has a bunch of TLOG files inside. Not sure if this info helps at all, just seems strange

**Comment by hydrabolt** [comment]
Can you try running one of the examples? I think it might just be a slight voice issue but I'm not sure.

**Comment by WEDSGARBAGEDAY** [comment]
running npm install in example directory gives same results (works except for node-opus) and all three examples work fine

**Comment by abalabahaha** [comment]
Try getting Node 5, and make sure you have VS C++ and Python 2.7

**Comment by WEDSGARBAGEDAY** [comment]
Ah, thanks, that was the problem. I thought I had the latest node.js installed but I was only on the latest stable version.

**Comment by abalabahaha** [comment]
Yes, Windows appears to have a problem with long file paths, but Node 5 brings sub-sub-subdependencies to the main node_modules folder instead of making a really deep tree of folders

**Comment by TehSeph** [comment]
Technically it's `npm 3.3.x` that changes the directory structure, but Node 5.x comes with 3.3.x bundled and also fixes some http and fs bugs as well as an updated V8 version so it's better to upgrade anyway.

**Comment by abalabahaha** [comment]
_unless LTS_
