### ISSUE TITLE
Getting a different output from an event than what the docs say

### ISSUE THREAD

**Issue by KingDGrizzle** [hydrabolt/discord.js#1733]
**Please describe the problem you are having in as much detail as possible:**
While trying to do some events, I've found out that `on("guildMembersChunk")` returns an Array, not a Collection as the documentation says.

I feel like this can either be a code bug, or a documentation mistype. Either way, it probably should get fixed

**Include a reproducible code sample here, if possible:**
```js
bot.on("guildMembersChunk", (members, guild) => {
    console.log(members.size) // returns undefined
    console.log(members.length) // returns number
});
```

**Further details:**

- discord.js version: 11.1-Dev
- node.js version: 8.1.4
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Extremely Low, as this event isn't used by many people

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
The documentation on it is wrong.
It is working correctly for master.

**Comment by KingDGrizzle** [comment]
Ah, alright. Thanks for letting me know 😃
