### ISSUE TITLE
Name option in <Guild>.createRole(options) doesn't work.

### ISSUE THREAD

**Issue by Tvde1** [hydrabolt/discord.js#1744]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to create a role with the name 'Test' but it keeps creating roles called `new role`.

**Include a reproducible code sample here, if possible:**
```js
message.guild.createRole({
        name: 'test',
        hoist: true,
        mentionable: false
    });
```

**Further details:**

- discord.js version: master
- node.js version: v8.2
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Medium. It isn't annoying for everyone, but a pretty bad bug.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
``Guild#createRole`` expects the RoleData under the key ``data`` for the options object in master.
[For reference](https://discord.js.org/#/docs/main/master/class/Guild?scrollTo=createRole).

So something like this:
```js
message.guild.createRole({
  data: {
    name: 'test',
    hoist: true,
    mentionable: false,
  },
});
```

**Comment by Tvde1** [comment]
ah thanks!
