### ISSUE TITLE
createGroupDM Parameters do not resolve correctly according to Documentation

### ISSUE THREAD

**Issue by ShadowJonathan** [hydrabolt/discord.js#1746]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js
/**
 * @type {SnowFlake} WITH
 * @type {Discord.Client} HAMMER
 * @type {Discord.Client} CLOUD
 */
CLOUD.user.createGroupDM([{id: HAMMER.user.id}, {id: WITH}])
```

**Further details:**

- discord.js version: master, `discord.js@12.0.0-dev`
- node.js version: 7.7.2
- Operating system: Windows 10, Pro
- Priority this issue should have – please be realistic and elaborate if possible:
> This should only be solved if Discord.js is diving into Group DM's, which i dont see happening that fast.
> Regardless, i want to make a intra-skype-discord bot for a few friends that refuse to use the other platform.
> This is not a breaking issue, as it is trying to solve `UserResolvable`, instead of `GroupDMRecipientOptions`, which i can easily adjust to, but the code is not acting as expected from the [documents](https://discord.js.org/#/docs/main/master/typedef/GroupDMRecipientOptions) (as elaborated below)

- [x ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ShadowJonathan** [comment]
Debugging trail:
```js
// ClientUser.js:361
  createGroupDM(recipients) {
    const data = this.bot ? {
    // yada yada yada
    } : { recipients: recipients.map(u => this.client.resolver.resolveUserID(u)) }; // <- here it goes fucking wrong
    return this.client.api.users('@me').channels.post({ data })
      .then(res => new GroupDMChannel(this.client, res));
  }
```
```js
// ClientDataResolver:57  
resolveUserID(user) {
    if (user instanceof User || user instanceof GuildMember) return user.id;
    if (typeof user === 'string') return user || null;
    if (user instanceof Message) return user.author.id;
    if (user instanceof Guild) return user.ownerID;
    return null;
  }
```

**Comment by devsnek** [comment]
you never said what the problem is. you just posted some code that is mostly not yours

**Comment by ShadowJonathan** [comment]
> as it is trying to solve UserResolvable, instead of GroupDMRecipientOptions

But a PR has already been made that fixes this, thanks, @SpaceEEC!
