### ISSUE TITLE
role.setPermissions or role.edit doesn't work

### ISSUE THREAD

**Issue by ShayBox** [hydrabolt/discord.js#1759]
**Please describe the problem you are having in as much detail as possible:**
I updated to master, and my working bot that creates a role and updates its permissions doesn't do that anymore.

I can get
```js
message.guild.createRole({
    data: {
        name: 'USER-' + message.author.id,
        color: args[0],
        permissions: []
    },
    reason: 'Hex Bot'
})
```
To create a role with no permissions, but if I put a .setPermissions or .edit in the .then it will create the role with two permissions it wasn't told to give. (External emojis and add reaction)

And trying to run
```js
role.edit({
    data: {
        color: args[0],
        permissions: ['ADMINISTRATOR']
    },
    reason: 'Hex Bot'
}).catch(error => client.catch(error))
```
Doesn't edit the permissions. same with setPermissions, it works in stable though.
And it does update the color.

**Further details:**

- discord.js version: Master (12.0.0-dev #317a352)
- node.js version: v8.2.1
- Operating system: Windows 10 x64 & Generic Linux x86_64
- Priority this issue should have – please be realistic and elaborate if possible:
Medium priority, Needs to be fixed before v12 is released but its still not a big problem for in-dev

- [x] I found this issue while running code on a __user account__
- [x] I found this issue while running code on a __bot account__
- [x] I have also tested the issue on latest master, commit hash: #317a352

I found this issue last night, and waited until this morning to update Discord.JS and try again, it still happens.

I have tried on both bot and user accounts. on three separate dev servers.

**Comment by MrJacz** [comment]
it would be 
```js
role.edit({
            color: args[0],
            permissions: ['ADMINISTRATOR']
          },
          reason: 'Hex Bot'
        }).catch(error => client.catch(error))```

**Comment by ShayBox** [comment]
I tried that originally, but It needs the data: {}
![image](https://user-images.githubusercontent.com/9505196/29003047-7093bcea-7a7d-11e7-8aa6-541abf28fb11.png)

**Comment by MrJacz** [comment]
Let me test this as im on dev

**Comment by ShayBox** [comment]
Alright, thanks

**Comment by MrJacz** [comment]
Works fine for me

**Comment by MrJacz** [comment]
@ShayBox

**Comment by ShayBox** [comment]
... What the...

**Comment by MrJacz** [comment]
```msg.guild.createRole({
        data: {
          name: 'USER-' + msg.author.id,
          color: 113233,
          permissions: []
        },
        reason: 'Hex Bot'
      }).then(role => role.edit({
          data: {
            color: 132131,
            permissions: ['ADMINISTRATOR']
          },
          reason: 'Hex Bot'
        }).catch(error => client.catch(error)))
``` i think your problem is args in color you might need to write a check

**Comment by ShayBox** [comment]
The rest of the code has filters for that, and with data: {} it updates the color just fine, and creates the role with the color and no permissions... why would it... 🤔

**Comment by MrJacz** [comment]
So whats the problem?

**Comment by ShayBox** [comment]
That your bot works without the data: {} but mine doesn't, and that with or without data: {} I cant get it to update an existing role with permissions

**Comment by MrJacz** [comment]
Can i see your full code i think i know why

**Comment by MrJacz** [comment]
and any errors if you are getting any

**Comment by ShayBox** [comment]
https://hastebin.com/epuxarazuy.php
As of that bit of code, it will create the role. with no permissions.
thats fine,
then the next time its triggered and it tries to update the role because it already exists, it wont add the administrator permission, it adds external emojis and add reactions

**Comment by ShayBox** [comment]
And there are no errors

**Comment by MrJacz** [comment]
That regex needs to be in a string iirc

**Comment by ShayBox** [comment]
Why would you... you don't put something in a string if your going to reference it once and never modify it...

**Comment by MrJacz** [comment]
Umm wot

**Comment by MrJacz** [comment]
you know what a string is

**Comment by ShayBox** [comment]
I'm assuming you meant put them into two strings, 
![image](https://user-images.githubusercontent.com/9505196/29003185-f3996c46-7a7f-11e7-8e7c-51d7385fefee.png) Either way it works fine, and has been. the only thing that's changed is I had to add the `data: {}` when I updated to master

**Comment by MrJacz** [comment]
https://hastebin.com/isahihekov.js it doesnt change much but please use template literals

**Comment by MrJacz** [comment]
^ they are your friend

**Comment by ShayBox** [comment]
I purposely remove those. Thanks for telling me what there called so I can put them in my linter config

**Comment by MrJacz** [comment]
Haha no problem i still dont get your error tho could you 
Me and Shaybox have tested and it seems to be a LIB issue as i've tested .setPermissions not work soooooo @vzwGrey

**Comment by ShayBox** [comment]
*Ignore the first line, he forgot to remove it and is too lazy to remove it*

**Comment by PgBiel** [comment]
In your first picture, you wrote `reason: 'Hex bot'` and that's not how it works, because you wrote it out of the object (hence why your editor pointed it out as an error). As seen in the current code, the syntax for `.edit` is `(data, reason)`. So, it'd be:
```js
role.edit({
  permissions: [permission1, permission2]
}, "reason"); // `reason` is what displays as reason in audit logs.
```
`.setPermissions` is just for setting permissions, so you'd write:
```js
role.setPermissions([permission1, permission2], "reason");
```

Also, next time, try checking in the documentation (it is there!), and if that doesn't help, try asking in the Discord.js guild. 👍

**Comment by ShayBox** [comment]
Well
```js
message.guild.roles.find('name', 'Test').edit({
  permissions: ['ADMINISTRATOR']
}, 'Test')
```
Succeeds, but does not edit the permissions.

and both with `data: {}` or without works fine, master just cant edit permissions for existing roles for some reason, feel free to join and test with us, but me and MrJacz have both come to the conclusion that its Discord.JS https://discord.gg/jPJ5S5s

**Comment by PgBiel** [comment]
It's the correct syntax. If it succeeds but does not edit, check your console for any rejections or whatsoever. The bot could have no permissions to do so.

Also, using `data: {}` changes nothing; if you put that in the object, nothing special happens because it doesn't use that property.

**Comment by ShayBox** [comment]
Well, it apparently does do something, because putting `color:` in there will edit the color just fine.
And no warnings, no errors, no rejections, it has permissions. Feel free to join and debug for yourself

**Comment by PgBiel** [comment]
Now that I see it, it seems that you aren't actually very wrong...
![Uh-oh?](http://i.imgur.com/xsKIdmJ.png)
It seems that it doesn't pass permissions to the data object...?

**Comment by ShayBox** [comment]
Well... that would be why...

**Comment by UnderSwitch** [comment]
This seems to still be an issue, however, for me, both Role.edit() and Role.setPermissions() don't work at all. I did see in the files that all .setPermissions() does is provide an easier shortcut directly to .edit(). Many attempts to get these to work but they do not ever update the role permissions. The bot has the highest role in the server with admin so that is not the issue. These functions also seem to block the code execution in the scope implying a crash somewhere in edit() or a sub-function.
`
discordClient.guilds.get(guild.id).roles.get(role.id).setPermissions(0)
`
The line above is supposed to reset the permissions to nothing, but it actually doesn't seem to do anything. This is not an issue with either of the get() functions as they return the proper values of the guild and role. The role in question is below the bot role and do keep in mind the bot role has permission int 8, meaning admin permissions. I have tried calling edit directly, with also no success:
`
examplerole.edit({ permissions: 0 })
`
That's the end of it so far, but if you need me to do anything in more detail, please let me know!

**Comment by almostSouji** [comment]
I can **not** reproduce this behavior on any of the currently supported versions: 11.5, 11.5-dev, 12.0.0-dev
Please make sure you are up to date or specify the version (if possible the commit) you are on.
