### ISSUE TITLE
Error: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by PassTheMayo** [hydrabolt/discord.js#1762]
**Please describe the problem you are having in as much detail as possible:**
I don't exactly know how to explain it, but I also have no example code, because I don't know what is going on. It just started happening as soon as I tried to use `disabledEvents` on the client constructor, but it threw this error. I removed it and it's still giving me the same error. I moved the bot to my VPS and same error. It doesn't seem to be a port issue, because this is the only bot running. Anyone else having this error?

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version: 12.0.0
- node.js version: 8.2.1
- Operating system: Debian 8.4
- Priority this issue should have – please be realistic and elaborate if possible: Extremely High

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 54ff8ce

**Comment by devsnek** [comment]
weeee we aren't sure how to fix this either. we believe it to be an upstream bug with `ws`, but we aren't sure. please try reproducing with `uws` and with/without `bufferutil` installed.

**Comment by PassTheMayo** [comment]
@devsnek That seemed to fix the issue, thanks!

**Comment by devsnek** [comment]
@PassTheMayo can you be specific on what fixed the issue, we aren't sure here how to fix it

**Comment by PassTheMayo** [comment]
@devsnek I just did `npm install uws`, and restarted the bot. It was successful at login and did everything correctly.

**Comment by ShayBox** [comment]
Hmm thanks! I was having this issue too but was just ignoring it.

**Comment by jaipradeesh** [comment]
https://tools.ietf.org/html/rfc6455#section-5.2

https://github.com/websockets/ws/issues/1140#issuecomment-308016758

**Comment by PassTheMayo** [comment]
@jaipradeesh That explains nothing. Plus we already got this resolved anyways, thanks.

**Comment by jaipradeesh** [comment]
```
   RSV1, RSV2, RSV3:  1 bit each

      MUST be 0 unless an extension is negotiated that defines meanings
      for non-zero values.  If a nonzero value is received and none of
      the negotiated extensions defines the meaning of such a nonzero
      value, the receiving endpoint MUST _Fail the WebSocket
      Connection_.
```

This error means that the client is sending a compressed frame but the permessage-deflate extension is disabled.

**Comment by kramer65** [comment]
@jaipradeesh - Your saying this, but I'm unsure what you mean. 

> This error means that the client is sending a compressed frame but the permessage-deflate extension is disabled.

I've got a self made bot, which connects to a remote API, and I just got an error saying `Error: RSV2 and RSV3 must be clear` as well. I'm using the regular [node ws lib](https://github.com/websockets/ws) for the websocket, so I'm not sure how I as a client am wrong in sending a compressed frame. 

Have you got any tips on debugging this?

**Comment by lukeeey** [comment]
I'm still getting this error, and when its a fatal one so my script crashes

**Comment by advaith1** [comment]
@kramer65 @lukeeey As PassTheMayo did, just install uws and it should work.

**Comment by lukeeey** [comment]
Don't you think I did that

**Comment by dionjwa** [comment]
I'm getting this when I stream data from an arduino IoT nano, it streams for about a few seconds, data is good, then it hits this error. Since it sends good data prior to this error, I don't believe the error message is accurate, otherwise the error message would show up in the first message(s). It's a bit of a showstopper, cannot seem to stream websocket data using ws and uws is not a realistic option due to it's various issues.
