### ISSUE TITLE
Discord API Deprecation

### ISSUE THREAD

**Issue by TrumpSupporter** [hydrabolt/discord.js#1763]
Discord API and Gateway versions 3, 4, and 5 are deprecated, and will be discontinued on October 16th.

There is Discord API and Gateway version 6. Have you considered updating the Discord API version on this library to 6?

**Comment by iCrawl** [comment]
We already run on 6 for quite a while.

**Comment by devsnek** [comment]
we actually use v7 for the discord api, and v6 for the gateway (the latest versions of both) 😉
