### ISSUE TITLE
<VoiceChannel>.setName() bug

### ISSUE THREAD

**Issue by Medallyon** [hydrabolt/discord.js#1769]
**Please describe the problem you are having in as much detail as possible:**
`<VoiceChannel>.setName("My Voice Channel")` throws a `DiscordAPIError: Invalid Form Body`:
```js
{ DiscordAPIError: Invalid Form Body
  bitrate: int value should be greater than 8000.
    at item.request.gen.end (node_modules/discord.js/src/client/rest/handlers/RequestHandler.js:52:65)
    at then (node_modules/snekfetch/src/index.js:257:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
  name: 'DiscordAPIError',
  message: 'Invalid Form Body\nbitrate: int value should be greater than 8000.',
  path: '/api/v7/channels/345586797092405249',
  code: 50035 }
```

**Include a reproducible code sample here, if possible:**
```js
msg.guild.channels.get("345586797092405249").setName("My Voice Channel").catch(console.error);
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: 8.1.4
- Operating system: Ubuntu 14.04

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 3c7869c1b7c04af72e37bb151290299db50cdc76

**Comment by Medallyon** [comment]
One way to circumvent this bug is by using the `<VoiceChannel>.edit()` function and passing the `name` and `bitrate` parameters, where bitrate should be a `Number` between `8000` and `96000`.

**Comment by Sir-Will** [comment]
Is there any way to update to latest so I don't have to wait until this fix gets pushed to stable?

**Comment by robflop** [comment]
``npm install discord.js#master`` for master branch. 

But know that the master branch will likely break a lot of other parts of your code since things are different.

**Comment by Sir-Will** [comment]
Hm, throws this error: `Error: Invalid tag name "discord.js#master": Tags may not have any characters that encodeURIComponent encodes.`

I don't really have a choice, without this fix my bot is pretty much useless.

**Comment by Sir-Will** [comment]
Nvm, `npm install git+https://github.com/hydrabolt/discord.js.git` seems to have worked.
