### ISSUE TITLE
Users' voice channels not updating

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#177]
on commit https://github.com/hydrabolt/discord.js/commit/4b8f85d44ac7f9b8a2bf9bcec75e74e1285cc35b the user's VoiceChannel is not being updated from the time the bot is started. 

steps to reproduce.
Join a voice channel with a standard client.
Start up your bot
change to a different voice channel, preferably on the same server.
have it Join the voice channel of the author of a command you use to have it join a voice channel.

it will join the voice channel you were in when you started the client, not the one  you are currently in.
note that the same bot was tested on https://github.com/hydrabolt/discord.js/commit/358c40c3557cc0cbd05aa33fad0c50ee7222bd5a and worked perfectly.

**Comment by hydrabolt** [comment]
The API isn't designed to work when the account you are logged in with is being used somewhere else too. You shouldn't be running the Client alongside your bot.

**Comment by abalabahaha** [comment]
Oh whoops I misread this...

I believe the design for Discord only allows for one voice connection per account per server.

**Comment by macdja38** [comment]
@abalabalaha is that relevant to this bug?

**Comment by macdja38** [comment]
Ohh, when I say the client I mean discord that I have my own personal account logged into

**Comment by abalabahaha** [comment]
Clarity pls...

**Comment by hydrabolt** [comment]
@macdja38 the API still isn't designed to work when there is interference by another bot or a client...

**Comment by mees-** [comment]
I have the same issue, i think he means that when you implement a summon command (bot.joinVoiceChannel --> message.author.voiceChannel) it joins the channel you were in when the bot started.

**Comment by macdja38** [comment]
Yup

**Comment by macdja38** [comment]
I'll repeat myself, when I say client, I mean discord with my own personal account, not the bots account.

**Comment by macdja38** [comment]
I tested it the same way with two different commits, it works on the old one, it's broken I. The new one.

**Comment by jennyl** [comment]
wanted to add to this (I'm not using Indev tho)
> Not in a channel on main account
> Start bot
> Join a channel
> `voiceJoin` event is NOT detected -- the event is detected in `voiceStateUpdate`
> Leave channel
> `voiceChannel` in the `voiceLeave` callback returns a SERVER object, not a voice channel object

**Comment by khionu** [comment]
@jennyl please test using InDev, as that would be what is patched, if there is an issue.

**Comment by jennyl** [comment]
Just tested using indev, still the same

**Comment by Maltroth** [comment]
Can confirm that `message.author.voiceChannel` in a message event is not updated after the bot has been initialized. From master or indev.
