### ISSUE TITLE
MessageOptions typing for property 'code' should be 'string' | 'boolean'

### ISSUE THREAD

**Issue by jbelford** [hydrabolt/discord.js#1773]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version:
- node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
This issue should be opened here: https://github.com/zajrik/discord.js-typings
