### ISSUE TITLE
Adding a member to a role not working

### ISSUE THREAD

**Issue by EmperorSuper** [hydrabolt/discord.js#1776]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to add a role to a selected member,
I've tried using message.server.members.get("name", "Super").addRole(role).catch(console.error);
but it gives the error "Cannot read property 'members' of undefined"

**Include a reproducible code sample here, if possible:**
```js
bot.on ("message", message => {
    if (message.content == "RAINBOWROLE") {
        let role = message.guild.roles.get("304888807516405761");
        var colorchangeInt3 = setInterval(colorchange3, 1000)   
        message.server.members.get("name", "Super").addRole(role).catch(console.error);
        function colorchange3(){
            role.setColor("#ff0000")
            role.setColor("#1000ff")
            role.setColor("#00ff15")
            role.setColor("#f2ff00")
            role.setColor("#e500ff")
        }
    }
});
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 8.1.2
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low this is more if a question then an issue with discord.js

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ShayBox** [comment]
Sorry, we dont help make rainbow bots.

**Comment by devsnek** [comment]
Please disable all "rainbow role" or other quick changing color systems in you bot. There will be no further attempt to support you.

**Comment by YorkAARGH** [comment]
Also please use the official bot accounts as User Accounts for bots are against the API ToS and by extension the Discord ToS.

**Comment by EmperorSuper** [comment]
Wait what?
@devsnek Why? Is that not allowed?
@YorkAARGH I am using a bot account

**Comment by ShayBox** [comment]
No, its heavily not allows, and is api abuse.

**Comment by YorkAARGH** [comment]
My bad, you said you encountered the problem whilst running the code on a user account.
