### ISSUE TITLE
bulkDelete delete channels with the messages ?

### ISSUE THREAD

**Issue by ClemCa** [hydrabolt/discord.js#1778]
**It seems like when there are no messages in the channel, bulkDelete simply delete the channel**
**The logs of the bot :**
```
C:\Users\clément\IdeaProjects\ClemCacahuete>node clemcacahuete_bot.js
Created webhook with token: sxD-jxQM-xNsKkfvY6X0NnBMxpYbmM_R7YX66cYoqAxSlqbRLoz1bS7UKqQsIWhmLJjD and ID: 336896802722938880
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: Unknown Channel
(node:12992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Unknown Channel
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): DiscordAPIError: Unknown Channel
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): DiscordAPIError: Unknown Channel
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): DiscordAPIError: Unknown Channel
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): DiscordAPIError: Unknown Channel
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): DiscordAPIError: Unknown Channel
(node:12992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): DiscordAPIError: Unknown Channel
[...] //i have a second test on a second channel, it's the same thing until the 25th
```

```js
}else if (message.content === prefixgeneral+"Delete Cacahuète" || prefixgeneral+"Delete Cacahuète") {
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.bulkDelete(100)
            message.channel.send("nettoyage qualité :peanuts: !!!")
            message.channel.delete(5000)
            message.channel.bulkDelete(1)
        }
```

**Further details:**

- last version:
- last version:
- windows 10:
- It's not an big issue, but it can be problematic for the users of the bot

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

ps : thanks to the one who said me to delete the webhook :D I forgot that it was write in the issue

**Comment by Dev-Yukine** [comment]
im not even sure if a webhook can use bulkDelete 🤔

**Comment by ClemCa** [comment]
the bulkDelete haven't any relation with the webhook 😄

**Comment by Dev-Yukine** [comment]
sure it have 🤔

**Comment by ClemCa** [comment]
i didn't use the webhook to bulkDelete

**Comment by ClemCa** [comment]
ps : thanks to the one who said me to delete the webhook :D I forgot that it was write in the issue

**Comment by vzwGrey** [comment]
Why even bulkDelete if you're deleting the channel anyway

**Comment by ClemCa** [comment]
the problem is that : if you clean the channel, how do do if the clean delete the channel...

**Comment by iCrawl** [comment]
He is asking why do you bulkDelete the messages when you intend to delete the channel anyway? It's useless. The messages are gone the moment you delete the channel, there is no point in having them be bulkDeleted beforehand.

**Comment by ClemCa** [comment]
i understand, but what i am saying is that if you want to keep the channel and juste bulkDelete the messages...

**Comment by appellation** [comment]
Regardless of the inanity of what you're doing, the issue you're having is not a problem with the library.  Please ask questions such as this in relevant discord servers.

**Comment by iCrawl** [comment]
Why do you call `message.channel.delete(5000)` then?

**Comment by vzwGrey** [comment]
You can bulkDelete messages just fine, however you are deleting the channel before the bulkDeleting is even done, thus throwing that error.

**Comment by ClemCa** [comment]
ooops, i forgot to delete message.channel.delete, my bad, i'll close the issue 😢
