### ISSUE TITLE
bot.user.setStreaming() wont work when i try to use it on my selfbot

### ISSUE THREAD

**Issue by Windowsxd** [hydrabolt/discord.js#1779]
while i was making my selfbot i tried to make it when its ready it would set my status to streaming
but whenever i did that it always gave me an error 
```js
TypeError: bot.user.SetStreaming is not a function
```
this is the peice of code i used to stream
```js
bot.on('ready', () => {
	console.log("redi for action!1");
	bot.user.SetStreaming("wot", "twitch.tv/asd", 1)
});
```

**Comment by iCrawl** [comment]
Obviously case sensitivity is important. Apart from that: 

__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
