### ISSUE TITLE
Playing status not working.

### ISSUE THREAD

**Issue by moriczgergo** [hydrabolt/discord.js#1798]
**Please describe the problem you are having in as much detail as possible:**
I have update discord.js in my package.json to use code in master because `Playing` statuses stopped working. I've heard that on master it's fixed, but it still doesn't work for me.

**Include a reproducible code sample here, if possible:**
```js
client.on('ready', () => { //On successful login
    console.log("Up and running!");
    client.user.setGame("with roles"); //Set the "Playing" text
});
```

**Further details:**

- discord.js version: 9b97fe2
- node.js version: v8.4.0
- Operating system: Ubuntu 16.04 LTS
- Priority this issue should have: medium

* [ ] I found this issue while running code on a __user account__
* [x] I have also tested the issue on latest master, commit hash:

**Comment by dmfj** [comment]
Same here.

**Comment by SpaceEEC** [comment]
I can not reproduce this.
![grafik](https://user-images.githubusercontent.com/24881032/29429405-ddcc30c8-8390-11e7-84c8-b7980751198b.png)

Are you really sure you are on the latest commit?
Just changing the entry in the package.json won't update the files,
can you double check with `npm ls discord.js`?

**Comment by moriczgergo** [comment]
@SpaceEEC Weird, I've ran yarn after updating the entry... Welp, let me see again.

**Comment by iCrawl** [comment]
You'll need to run `yarn upgrade` otherwise your .lock file will just laugh at you.

**Comment by moriczgergo** [comment]
@iCrawl Oh, sorry for my stupidity. :D
