### ISSUE TITLE
Discord.js not working

### ISSUE THREAD

**Issue by TiaTnT** [hydrabolt/discord.js#1801]
I've tried the recent versions of node.js, when I go to make a bot, I just use code from the discord.js site, and then put the token for the bot there, no errors in the code, but when I try to open it in cmd prompt with node app.js it doesn't load, however if I use the token for my account, it loads, takes like 5 seconds tho, it always worked good with past versions of discord.js, but now, it doesn't. I've tried many tutorials online, I follow all the steps, but always run into it just not loading.

**Comment by eslachance** [comment]
Why did you completely ignore and delete this comment? 
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by TiaTnT** [comment]
shit, thanks, and ignore or delete comment? what

**Comment by TiaTnT** [comment]
rip

**Comment by iCrawl** [comment]
![](https://a.safe.moe/U2Otb.png)

This comment.
