### ISSUE TITLE
setGame(str) function is not working

### ISSUE THREAD

**Issue by bgencacat** [hydrabolt/discord.js#1807]
Nodejs -v 8.2.1
Discordjs -v 11.1.0

`const Discordjs = require( 'discord.js' );
const Config = require( './config.json' );
const Hacer = new Discordjs.Client();

var prefix = Config.prefix;
Hacer.on('ready', () => {
    const user = Hacer.user;
    console.log(user.username + " is running up now.");
    user.setStatus( 'dnd' );
    user.setGame( 'This is the game.' );
});
`

setGame method doesn't set my bot's game. No error, no anything else. Only no game. Status working well.

**Comment by SpaceEEC** [comment]
Already fixed in #1785.
If you don't want to update to the 11.1-dev branch you can use `client.user.setPresence({ game: { name: 'yourGameGoesHere', type: 0 } });` as a workaround.
