### ISSUE TITLE
Connection while runned as cluster causes error

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [hydrabolt/discord.js#1808]
**Please describe the problem you are having in as much detail as possible:**
Running Cluster with discord.js (as shard) then attempt to connect causes crash of the cluster with unhandled error
```
 Error { Error: read ENOTCONN
    at _errnoException (util.js:1022:11)
    at WriteStream.Socket._read (net.js:485:20)
    at WriteStream.Readable.read (_stream_readable.js:431:10)
    at WriteStream.Socket.read (net.js:367:43)
    at resume_ (_stream_readable.js:811:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3 code: 'ENOTCONN', errno: 'ENOTCONN', syscall: 'read' }
```
- Init scripts configured to start bot in Shards mode 
- It forks required number of clusters (each shard = 1 cluster)
- Each cluster should connect to Discord with given number of shard
- Then it should complete loading of modules (these can check in what shard they're runned)
- While Init script calls method to connect to Discord, Cluster crashes with unhandled error

I know, it's absolutely shame. But I'm only learning, I have never worked with Discord Shards and Clustered scripts 😦 

I had choice between child processes and clusters: I decided to use clusters as they provide socket to communicate between master and other workers. Modules could use it to give important information to each other.

**Include a reproducible code sample here, if possible:**
My bot is opensource and here branch where I tried to configure 
https://gitlab.com/SnowballBot/Snowball/tree/feature-sharding

You probably need to clone and compile this pile of code.
`yarn install` then `grunt` (should work)

Use this simple config to load only what you need: (eval & ping)
```json
{
    "name": "BOT NAME USED IN LOGS",
    "token": "TOKEN HERE",
    "modules": [{
        "name": "ping",
        "path": "ping"
    }, {
        "name": "eval",
        "path": "eval"
    }],
    "autoLoad": ["ping", "eval"],
    "botOwner": "BOT OWNER ID",
    "localizerOptions": {
        "languages": ["ru-RU", "en-US", "uk-UA", "be-BY"],
        "source_language": "ru-RU",
        "default_language": "en-US",
        "directory": "./languages/"
    }
}
```
To start bot in sharded mode use this in `out` directory:
`node init.js --initshards --shards=5`

You also can run script as one of the shards, but it won't print any error (bash script below)
```bash
NODE_ENV=development DEBUG_SHARDS=yes SHARD_ID=0 SHARDS_COUNT=5 node init.js --initshards --shards=5
```

**Further details:**

- discord.js version: discord.js@12.0.0-dev
- node.js version: v8.3.0
- Operating system: Microsoft Windows 10 Pro Insider Preview 10.0.16257 N/A Build 16257
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 8b8a365e99f8c86d1dc4a49c863b825b10203435

**Comment by devsnek** [comment]
reproducible code should be *the simplest way to reproduce an error* i would expect a single 10-30 line codeblock being all that was needed, please try to simplify this down to the actual issue.

**Comment by DaFri-Nochiterov** [comment]
It's could not be in 30 line codeblock, because there's cluster logic.
Here's ~100 lines gist:
https://gist.github.com/DaFri-Nochiterov/5b4135021ed47205b2aebfd723bcb316 

Actually, found that this crash only occurs after adding these lines
```js
        process.stderr.on("data", (data) => {
            if (!process.send) {
                return;
            }
            process.send({
                type: "stderr",
                data: new String(data)
            });
        });
        process.stdout.on("data", (data) => {
            if (!process.send) {
                return;
            }
            process.send({
                type: "stdout",
                data: new String(data)
            });
        });
```

By logic it should redirect any data from console, but for some reason it causes crash after calling `client.login(token)`

**Comment by devsnek** [comment]
tbh you could just use the ShardManager class, and your error comes from ipc channels closing, which is outside the scope of this issue tracker

**Comment by DaFri-Nochiterov** [comment]
yes, it's not issue about `discord.js`. Sorry for bothering you
