### ISSUE TITLE
stopTyping does not work on a timer

### ISSUE THREAD

**Issue by Sgtpanda** [hydrabolt/discord.js#1812]
**Please describe the problem you are having in as much detail as possible:**
The following code sample fails with the error
```
/<snip>/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:275
    if (this.client.user._typing.has(this.id)) {
            ^

TypeError: Cannot read property 'client' of undefined
    at stopTyping (/home/panda/nodestuff/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:275:13)
    at Timeout.setTimeout [as _onTimeout] (/home/panda/nodestuff/node_modules/discord.js/src/client/Client.js:422:7)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Include a reproducible code sample here, if possible:**
```js
function sendAndStop(channel,message){
  channel.stopTyping();
  client.setTimeout(channel.stopTyping,5000);
  return channel.send(message);
}
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 8.4
- Operating system: Ubuntu 16.04.3 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
you need to do `client.setTimeout(channel.stopTyping.bind(channel), time)`
