### ISSUE TITLE
Add ability to change volume

### ISSUE THREAD

**Issue by aequasi** [hydrabolt/discord.js#182]
Something like this:

https://github.com/reneraab/pcm-volume/blob/master/index.js#L22

Add mute/unmute helper methods too

**Comment by macdja38** [comment]
Is their a reason you believe this would be better than the current method of setting the volume for a specific Audio stream by passing it an object containing the requested volume?

**Comment by aequasi** [comment]
The current method cannot change the volume of the stream on the fly.

**Comment by macdja38** [comment]
so, in theory all ffmpeg filters could be made to work the same way? allowing user's to change something like the bass on the fly?

**Comment by meew0** [comment]
Theoretically yes, but I assume stuff like that is more complicated than a simple volume adjustment. It could eventually be done but in my opinion there's more important stuff to do before it

**Comment by aequasi** [comment]
This isn't really low priority. Its already implemented with #184 @khionu

**Comment by abalabahaha** [comment]
Associated PR was merged apparently

**Comment by aequasi** [comment]
Yeah, not sure why it didn't auto resolve this

**Comment by abalabahaha** [comment]
PR didn't tag this issue in the title or commit message
