### ISSUE TITLE
Error: Still spawning shards.

### ISSUE THREAD

**Issue by PassTheMayo** [hydrabolt/discord.js#1827]
**Please describe the problem you are having in as much detail as possible:**
I am using an Auto Sharder but I am getting an error while spawning *some* shards, but the shard starts eventually. Here's the error:
```js
 { Error: Still spawning shards.
    at ShardingManager.fetchClientValues (/root/bots/guess-that-number/node_modules/discord.js/src/sharding/ShardingManager.js:185:70)
    at Shard._handleMessage (/root/bots/guess-that-number/node_modules/discord.js/src/sharding/Shard.js:136:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) name: 'Error' }
```
When I upgrade to master, I get the same issue. I'll post the code under the other category. Am I doing anything wrong?

**Include a reproducible code sample here, if possible:**
```js
const Discord = require("discord.js");
const dateformat = require("dateformat");
const config = require(__dirname + "/config.json");
const log = require("./managers/logger.js");

const shard = new Discord.ShardingManager(__dirname + "/index.js", {
    totalShards: "auto",
    token: config.token,
    respawn: true
});

shard.on("launch", s => {
    log("Launching shard " + (s.id + 1) + "/" + shard.totalShards);
});

shard.spawn();
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: v8.4.0
- Operating system: Ubuntu 16.04.2
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: `b9ea83a`

**Comment by CharlotteDunois** [comment]
The error gets thrown when you try to get a value of `<Client>` from each shard using `<ShardClientUtil>.fetchClientValues` while the Sharding Manager is still spawning shards.

**Comment by hydrabolt** [comment]
^ you're going to have to wait until the shards are done.
