### ISSUE TITLE
The method "bulkDelete" on TextChannel, when using a number tries to use the "fetchMessages" method which no longer exists. 

### ISSUE THREAD

**Issue by MinecraftBoxGuy** [hydrabolt/discord.js#1838]
**Please describe the problem you are having in as much detail as possible:**
When using the bulkDelete method with a number it fails because it tries to use the fetchMessages method which was deleted in the latest commit. [Here](https://github.com/hydrabolt/discord.js/blob/master/src/structures/interfaces/TextBasedChannel.js#L281)
This is because of MessageStore existing where you can do more things so 
```js
channel.messages.fetch({ limit: messages })
```
Should be used

**Include a reproducible code sample here, if possible:**
```js
msg.channel.bulkDelete(50).catch(console.error);
```

**Further details:**

- discord.js version: 12
- node.js version: 8.1.2
- Operating system: Debian 8 Server
- Priority this issue should have – please be realistic and elaborate if possible:
Moderate. A big issue to anyone who has a purge command and is on master

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by ShayBox** [comment]
Yep. Am experiencing this myself
