### ISSUE TITLE
Bitrate range should not be hardcode to 16 ~ 128

### ISSUE THREAD

**Issue by mmis1000** [hydrabolt/discord.js#1839]
**Please describe the problem you are having in as much detail as possible:**
The discord.js added the botrate limit in @1493
But it hardcode the bitrate range to 16 ~ 128 bps in `NodeOpusEngine.js` and `OpusScriptEngine.js`
The api actully accept higher bitrate range than that limit (althoungh the max value of slider on client is 128).
I think we should just warn users if their setting is beyond that instead of hardcode it

![statics from chrome://webrtc-internals/](http://puu.sh/xkHnm/1a1d332d6a.png)

**Include a reproducible code sample here, if possible:**
I have used the following patch to test bitrate limit

```
in VoiceBroadcast.js
===
  playOpusStream(stream, { seek = 0, passes = 1, bitrate = this._opusBitrate } = {}) {
    const options = { seek, passes, stream };
    this._opusBitrate = bitrate;
===
  readStreamBuffer() {
    const opus = this.currentTranscoder.opus;
    const bufferLength = (opus ?  this._opusBitrate / 8 * 10 : 1920) * 2;
```
and following ffmpeg command to gen opus stream
```
ffmpeg -loglevel panic -f s16le -ac 2 -ar 48000 -i - -vn -map 0:a -acodec libopus -f data -sample_fmt s16 -vbr off -ar 48000 -ac 2 -ab 512k pipe:1
```
**Further details:**

- [X] I have also tested the issue on latest master, commit hash: 3c532f16bc48175597a7bbed4fbba4637812184d

**Comment by Drahcirius** [comment]
Apologies if I'm mistaken, but won't the bitrate get down sampled to whatever the channel setting is, even if you send it at 512kbps? If so, what would be the benefit of sending over the client limit?

**Comment by gmedeadlystrike** [comment]
I brought this up as well when he was discussing this in the D.JS discord server. According to his tests, he is receiving back a full 512kb stream, whenever said stream is being sent.

**Comment by Drahcirius** [comment]
After some testing, this does indeed seem to be the case, channel bitrate is only for sending, not receiving. I was seeing 512kbps in a channel with 8kbps bitrate setting, with no audible downsampling. Checking the API, it only recommends 48kHz sample rate and no mention about bitrate, so it may be acceptable to send higher bitrate audio.

**Comment by aemino** [comment]
Considering that Discord sets the default maximum bitrate in the slider as 128kbps, I think it would be a disservice to them to allow higher. Honestly, I'm not even sure why the API accepts higher bitrates than that. If the limit was to be unlocked, I'd have to have a conversation with one of the devs.

**Comment by hydrabolt** [comment]
I agree with @aemino here, I don't think Discord would like us to seeing as higher bitrates are a feature of VIP voice channels.
