### ISSUE TITLE
Ban Permissions

### ISSUE THREAD

**Issue by NookDevv** [hydrabolt/discord.js#1842]
}

    if (!message.guild.member(client.user).hasPermission("KICK_MEMBERS")) {
      return message.channel.send("I don't have permission (KICK_MEMBERS) to do this.")
    } 

I have this code, how do I turn that into permission check for a member (If a member with no perm does !ban I don't want them to be able to ban the user).

**Comment by dragonfire535** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by Dev-Yukine** [comment]
The issue tracker is only for issues/bugs with the libary. Ask on the Discord server for help/questiond eith discord.js
