### ISSUE TITLE
message.guild.me isn't set for newly joined servers

### ISSUE THREAD

**Issue by Typhoon31** [hydrabolt/discord.js#1848]
Hi,

given the following code:

```js
if (message.guild && !message.channel.permissionsFor(message.guild.me).has('SEND_MESSAGES')) {
  return message.author.send('`SEND_MESSAGES` permission missing for this channel!');
}
```

the following error occurs on guilds the bot just joined:
`Uncaught promise Error TypeError: Cannot read property 'has' of null`
because `message.guild.me` is undefined / not set.

A restart of the process solves this, it is still working on servers the bot has been on since start.

**Further details:**

- discord.js version: latest master b7c55f02c20bee5dab107ff453a6d3ea1a4a776a
- node.js version: 8.3.0
- Operating system: W10 x64
- Priority this issue should have – please be realistic and elaborate if possible: high

**Comment by SpaceEEC** [comment]
Looks like the GuildMember of the bot is not cached, you can fetch it using `GuildMemberStore#fetch` (located under `Guild#members`). Or if you are on stable `Guild#fetchMember`.

**Comment by Typhoon31** [comment]
It is working for `stable` tho, so you don't need this if you're on `11.1`.

**Comment by PgBiel** [comment]
Are you sure the "Cannot read property `has` of null" is in your `.has` access of `.permissionsFor(message.guild.me)` possibly returning `null`? Or does the full error stack say otherwise?

**Comment by hydrabolt** [comment]
Are you using any bot frameworks?

**Comment by hydrabolt** [comment]
I'm going to close this and move the discussion to #1870 as they're both the same issue.
