### ISSUE TITLE
guild.fetchMember() shows a joinedTimestamp of 0 for some members

### ISSUE THREAD

**Issue by CAC27** [hydrabolt/discord.js#1854]
Issue seems to happen on large servers only, might have to do with caching
**Examples**
```js
guild.fetchMember(user.id).then(m => console.log(m.joinedTimestamp));
// >> returns epoch time (0) in some cases (also tried adding cache arg as false; no change)
guild.member(user.id).then(m => console.log(m.joinedTimestamp));
// same as above
client.rest.makeRequest('get', `/guilds/${guild.id}/members/${user.id}`, true).then(data => console.log(data.joined_at));
// >> returns correct value every time
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 7.7.4
- Operating system: Windows 10 & Ubuntu 16.04.3
- Priority – Fairly low, not too common of an issue and non-destructive

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
fetch member:
```js
return this.client.rest.methods.getGuildMember(this, user, cache);
```
getGuildMember:
```js
  getGuildMember(guild, user, cache) {
    return this.rest.makeRequest('get', Endpoints.Guild(guild).Member(user.id), true).then(data => {
      if (cache) return this.client.actions.GuildMemberGet.handle(guild, data).member;
      else return new GuildMember(guild, data);
    });
  }
```

**Comment by hydrabolt** [comment]
Thanks for finding this issue! It seems that I tried to resolve a user instead of a user ID, which means that if the user wasn't already cached, the lib would try to fetch based on a query so you end up with a collection rather than a single GuildMember.
