### ISSUE TITLE
VoiceChannel .members acting like TextChannel .members

### ISSUE THREAD

**Issue by MinecraftBoxGuy** [hydrabolt/discord.js#1855]
**Please describe the problem you are having in as much detail as possible:**
In master, when trying to view who is in a voice channel, it seems to cache it. At first it shows 0, then when I join it shows 1 but when I leave it shows 1. I think this may be because the code to shows members for a voice channel has been replaced by the code to shows members for a text channel which caches. [This link](https://github.com/hydrabolt/discord.js/blob/master/src/structures/GuildChannel.js#L203) is for master, as you can see it is the code used for a TextChannel. [This](https://github.com/hydrabolt/discord.js/blob/04f0534d33eabfc422b1665fab51256067ea1e49/src/structures/VoiceChannel.js#L16) is the old link.

**Include a reproducible code sample here, if possible:**
```js
<VoiceChannel>.members.size; //0
// Join the channel.
<VoiceChannel>.members.size; //1
// Leave the channel
<VoiceChannel>.members.size; //1
```

**Further details:**

- discord.js version: 12
- node.js version: 8.1.2
- Operating system: Debian 8 Server
- Priority this issue should have – please be realistic and elaborate if possible:
Not that high. Only in the next release (which is far away)

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by KyeNormanGill** [comment]
According to source you joining and leaving the voice channel shouldn't change the collections size 🤔 
It's just every user that has visibility of the channel...

**Comment by MinecraftBoxGuy** [comment]
That is what it says. It is like TextChannel but it doesn't seem to be behaving in that way. Thank you for your help.

**Comment by devsnek** [comment]
probably a state problem, but to be fair... https://github.com/hydrabolt/discord.js/blob/master/src/structures/VoiceChannel.js#L17

**Comment by MinecraftBoxGuy** [comment]
Is that being overwritten. It doesn't show up in the docs
