### ISSUE TITLE
[Feature] Tidy eval feature

### ISSUE THREAD

**Issue by khionu** [hydrabolt/discord.js#186]
Currently, standard JS `eval()` will print misc "ugly" stuff, like `[object Object]` when sending a message, so, I think a `Client.eval` might be nice.

Obviously low priority.

**Comment by meew0** [comment]
..what do you need `eval()` for that you need this feature?

**Comment by khionu** [comment]
For inside a bot? So many people use Eval in their Bots, and it's extremely helpful. Would be nice to have it neater. Again, this is more of a "cosmetic" issue, a feel enhancement. I would like to leave this open for anyone who minds making a PR for this.

**Comment by abalabahaha** [comment]
Per internal discussion, this is outside the scope of discord.js
