### ISSUE TITLE
V8 Engine Crash on Channel.createWebhook

### ISSUE THREAD

**Issue by gmedeadlystrike** [hydrabolt/discord.js#1862]
**Please describe the problem you are having in as much detail as possible:**
Calling channel.createWebhook() will result in the process maxing CPU usage followed by the Javascript V8 Engine Crash

**Include a reproducible code sample here, if possible:**
```js
await msg.channel.createWebhook('Friendship Hook', 'https://yt3.ggpht.com/-te1DAtfJ2oQ/AAAAAAAAAAI/AAAAAAAAAAA/PzjHNLJcBjM/s900-c-k-no-mo-rj-c0xffffff/photo.jpg', `New Friendship Hook requested by ${msg.member.displayName}`);
```

**Further details:**

- discord.js version: Master
- node.js version: 8.4.x
- Operating system: Win10 + Ubuntu 16.x
- Priority this issue should have: 🔥HIGH🔥

- [ ] I found this issue while running code on a __user account__
- [✔️ ] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Fixed in latest commit fam 🔥💯👌👌
