### ISSUE TITLE
Can I Run Two Bots In One Script?

### ISSUE THREAD

**Issue by Herofied1180** [hydrabolt/discord.js#1873]
```js
const Discord = require('discord.js');
const client = new Discord.Client();
const Toke = 'Censored';
const Toke1 = 'Censored';


//My Bot Code is Here


//Login Code
client.login(Toke);
client.login(Toke1);
```

- discord.js version: (Latest I think)
- node.js version: v8.4.0
- Operating system: macOS 10.12.3

My issue: I cannot seem to find a good way to run two bots in one index.js script. If there is any way to do this please tell me.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by Herofied1180** [comment]
sorry ok I will do that in the discord server

**Comment by Herofied1180** [comment]
but wait why do I have to wait like 10 minutes. Ok I will just wait then...
