### ISSUE TITLE
voiceConnection.playFile issues on RPi

### ISSUE THREAD

**Issue by BlitzKraig** [hydrabolt/discord.js#189]
Running a bot on my Raspberry pi, everything working fine apart from playFile, playRawStream etc.

```
connection.playFile(filePath, function(err, str){
console.log(err);
console.log(str);
});
```
The bot is in the channel, the file exists, and no errors seem to be thrown.

The only thing that is logged is:
```
StreamIntent {
domain: null,
_events: {},
_eventsCount: 0,
_maxListeners: undefined }
```

Am I being stupid?...

**Comment by BlitzKraig** [comment]
So after some digging, Opus seems to be failing silently for me. Going to look further into this.

**Comment by BlitzKraig** [comment]
```
if (!self.encoder.opus) {
				self.playing = false;
				self.emit("error", "No Opus!");
				self.client.emit("debug", "Tried to use node-opus, but opus not available - install it!");
				return;
			}
```
in VoiceConnection doesn't throw any errors to the console, and doesn't stop the streaming attempt, just constantly fails over and over in the background.

**Comment by khionu** [comment]
Future note, these can be detected through `Client.on("debug"....`

**Comment by BlitzKraig** [comment]
Some more investigation has led me to: 
`Could not locate the bindings file`
when requiring opus. Seems like an issue with my node, npm, or opus installation.

Thanks

**Comment by abalabahaha** [comment]
It should probably throw errors if the user attempts to play something without opus

**Comment by BlitzKraig** [comment]
I had to manually reinstall opus with some funky flags, but got it working. This seems like an issue on my end, however, might be worth throwing a visible error on require node-opus failure in case anyone hits a similar issue.

**Comment by Maltroth** [comment]
I think I'm in the same boat, mind sharing your "funky flags" @BlitzKraig ? Can't get it to install on my end.

**Comment by BlitzKraig** [comment]
At a family party all night tonight, I'll post here tomorrow with as much info as I can. If you can't wait, there is definitely some info available using Google and some well placed console logs, but it took me a while to find. Try logging the error that's thrown when Opus is initialized, think it was in voiceconnection. Good luck!

**Comment by BlitzKraig** [comment]
Sorry @Maltroth, took an unexpected holiday to Amsterdam and forgot all about this! I hope you were able to fix your issue.

**Comment by Maltroth** [comment]
Yes! Was a dumb error on my side with the \ instead of \\ in my path. Thank you for the follow-up @BlitzKraig .
