### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by MrFifth** [hydrabolt/discord.js#1891]
Hey, when I add this part of code below vvvvvvvv in my original code, it gives me this error in my command prompt: 
![image](https://user-images.githubusercontent.com/31648280/30051087-c411b842-9231-11e7-83a4-134afb0e1adf.png)

let member = msg.mentions.members.first();
if(member)
return msg.reply("You haven't mentioned a member yet, command declined.");
let muteRole = msg.guild.roles.find("name", "Muted");
if(muteRole)
return msg.reply("You haven't got a role by the name of 'Muted', command declined.")
let params = msg.content.split(" ").slice(1);
let time = params[1];
if(time) return msg.reply("There is no time specified, command declined.")

member.addRole(muteRole.id);
msg.channel.send(`You've been muted for ${ms(ms(time), {long: true})} ${member.user.tag}`);

setTimeout(function() {
  member.removeRole(muteRole.id);
  msg.channel.send(`${member.user.tag} You've been unmuted.`)

-11.2.1 Discord.js
-8.4.0 Node.js
- Windows 8.1 64-bit

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
The issues page is for issues **with the library**.  Please go to the server to inquire about your code.

**Comment by hydrabolt** [comment]
Please read the issue template you deleted in future.

**Comment by MrFifth** [comment]
Go to which Server?

Okay.

**Comment by MrFifth** [comment]
Sorry, which template and how do I view it?

________________________________

**Comment by MrFifth** [comment]
Which server?

________________________________

**Comment by dragonfire535** [comment]
The issue template that comes up right when you try to make a new issue.

**Comment by MrFifth** [comment]
thank you.

________________________________
