### ISSUE TITLE
guild.joinedAt() makes no sense

### ISSUE THREAD

**Issue by Typhoon31** [hydrabolt/discord.js#1895]
It seems that there is a copy paste mistake:

https://github.com/hydrabolt/discord.js/blob/stable/src/structures/Guild.js#L259

because this just makes no sense, we have `createdAt` for this.

**Comment by vzwGrey** [comment]
`createdAt`: The time the guild was created
`joinedAt`: The time the client user joined the guild

They're not the same.

**Comment by iCrawl** [comment]
🤔
