### ISSUE TITLE
Error: %1 is not a valid Win32 application when using discord.js >= 11.2.0

### ISSUE THREAD

**Issue by jbelford** [hydrabolt/discord.js#1897]
When updating to discord.js 11.2.1 from 11.1.0 I get errors with node-opus.
The error I'm getting in particular is: 
```
Promise Rejection (Error: %1 is not a valid Win32 application.
\\?\D:\jackb\Documents\DiscordBot\node_modules\node-opus\build\Release\node-opus.node)
Error: %1 is not a valid Win32 application.
\\?\D:\jackb\Documents\DiscordBot\node_modules\node-opus\build\Release\node-opus.node
```

This occurs when creating a stream.

This only seems to occur when using versions >= 11.2.0. I have tried many things already including completely rebuilding my project and reinstalling all dependencies and always get an error. I have tried it with both node 6.0.0 and 8.0.0 and still get this error. When I switch back to 11.1.0 everything works as usual.

**Further details:**

- discord.js version: 11.2.1
- node.js version: 6.0.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
you should report this error over at https://github.com/Rantanen/node-opus

**Comment by jbelford** [comment]
Thing is I'm not sure it's node-opus causing the issue here. Since it's working just fine with the previous version.

**Comment by iCrawl** [comment]
I have it working on 11.2.1 and 12.0.0.

Can you test this with master? Just a simple example would work, since if you switch fully you would probably have a lot of breaking changes.

**Comment by PgBiel** [comment]
https://github.com/hydrabolt/discord.js/commit/b3216f26d658ea3ad5d4c4a603f63f200af506f9; see if installing a different version of node-opus works

**Comment by iCrawl** [comment]
This is the commit you should have linked 18de265fcc8035d785ce4a03f618a27a72fc8ad8

**Comment by PgBiel** [comment]
just realized that, oops

**Comment by jbelford** [comment]
I tried a simple example and still getting this error. I also tried with all the updated dependencies.
The following code still works with 11.1.0 but not on 11.2.1 for whatever reason. :/
```js
const Client = require('discord.js').Client;
const ytdl = require('ytdl-core');

const client = new Client();

client.on('ready', () => {
  const voice = client.channels.get('346852913651515395');
  voice.join().then( connection => {
    const dispatch = connection.playStream(ytdl('https://www.youtube.com/watch?v=Kp7eSUU9oy8', { filter: 'audioonly' }));
    dispatch.on('start', () => {
      console.log('Started streaming');
    });
    dispatch.on('end', () => {
      console.log('Stopped steaming');
    })
  });
});
```

**Comment by PgBiel** [comment]
I mean, you gotta try with the old dependency version that's what I was saying

**Comment by jbelford** [comment]
Ah. Tried that but still no luck.

**Comment by jbelford** [comment]
I've fixed my issue. I was previously installing my dependencies with npm using windows bash. This was cause 'node-gyp' didn't work right on windows and never bothered fixing it as installing on bash worked just fine. Its a slightly different architecture though so I guess that had to break eventually. Anyway I fixed 'node-gyp' issues and everything working now. 👍
