### ISSUE TITLE
Webhook caching behaviour isn't realistic

### ISSUE THREAD

**Issue by Voakie** [hydrabolt/discord.js#1906]
While sending messages via a Webhook, you can specify a username in the WebhookMessageObjects. When assigning a different username every time, those will be displayed in Discord like you expect them to, different every time. When collecting the messages with discord.js though, the username doesn't change (because it caches the first one and then just reads from cache).

**Demo for 11.2.1 and 0607720ec80eb7801daeae7e9ba59e85b8b8c20d**
```js
channel.createWebhook("bump").then(webhook => {
    for (i = 0; i < 5; i++) {
        var random = Math.random().toString()
        webhook.send(random, { username: random })
    }

    webhook.delete()
}).catch(console.error)

const collector = channel.createMessageCollector(() => true)

collector.on("collect", msg => {
    console.log(`Username: ${msg.author.username}, Content: ${msg.content}`)
})

// Note how in Discord, username and content are always the same.
// In the console, only the first log should match that criteria
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: v8.4.X
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: __medium__ - Discord.js supports name overrides per message, so those name overrides should also reflect when fetching or collecting messages from a channel.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 0607720ec80eb7801daeae7e9ba59e85b8b8c20d

**Comment by devsnek** [comment]
Yea I made this decision because the author username change is technically an alias and the change isn't a full patch so I wasn't sure what to do except manufacturer a user for that specific message which gets dangerous with references quite quickly but if you have a better solution let me know

**Comment by Voakie** [comment]
@devsnek Maybe just don't cache webhooks as message authors at all. Not sure how the new DataStore concept works though.
