### ISSUE TITLE
File attachments behind a redirect cause an empty file to be uploaded

### ISSUE THREAD

**Issue by tomforster** [hydrabolt/discord.js#1907]
If you attach a file with TextChannel.send("blah",{files:['attachment:<URL>']});
and that url returns a 301 redirect, the redirect is no longer followed, but does return an empty body which discord.js sends to the discord api.

This is due to a fix in snekfetch 3.3.0, which properly defaults the followRedirects option to false.

This can be fixed either by rolling back snekfetch to 3.2.9 or by passing the {followRedirects:true} options object to the snekfetch.get call in ResolveFile() in ClientDataResolver.js. Happy to create a PR for this but I dont have enough knowledge of the project to know if this is the best approach.

If you don't believe this is a discord.js issue, then I suggest a seperate improvement: the snekfetch responses should be checked for empty bodies or for non 200 error codes, and an appropriate error should be thrown rather than forwarding empty attachments to the discord api.

- discord.js version: 11.2.0
- node.js version: 8.1.3
- Operating system: any

- Priority this issue should have – please be realistic and elaborate if possible:
I think this probably effects anyone who uses url based file uploading, but I have no idea how many users that is. It certainly completely broke my image link sharing bot.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
This is intended behavior, don't give links which redirect.

**Comment by tomforster** [comment]
Intended behaviour or not, shouldn't a link that didn't return a payload throw an error? Also I'm not sure why a 301 would have returned a payload at all but thats not really in scope for this project.

**Comment by tomforster** [comment]
Ok, ill check for redirects on every url beforehand.

Though I do have to say that this is going to trip up a lot of newbies, especially since imagehosts like imgur routinely use 301s to redirect older links from imgur.com to i.imgur.com.

**Comment by CharlotteDunois** [comment]
My opinion is that discord.js should only pass a buffer from a HTTP response with HTTP 2XX code. That means that redirects should be followed, but if this should actually be the implementation, is open for discussion.

**Comment by Ev1dentFir3** [comment]
Redirects are sketchy as hell and if you are going to post a redirect just follow the link yourself and then have discord use the real link. Makes no sense really to use redirects unless your trying to mask a destination.

**Comment by CharlotteDunois** [comment]
@Ev1dentFir3 You're just assuming everyone uses user input to upload images to Discord, which no one ever mentioned. I agree, user input is something else and should be manually resolved. But we're not talking about certain cases at all. This is a general issue and links should be followed, if they issue a HTTP 3XX code (as a HTTP to HTTPS redirect does!).

**Comment by dragonfire535** [comment]
I should note that this is actually no longer an issue, all redirects are by default followed in snekfetch again.
