### ISSUE TITLE
Random Crashes?

### ISSUE THREAD

**Issue by hydrabolt** [hydrabolt/discord.js#191]
Yesterday there was a pretty big API change and bots running on servers with more than 250 users will most likely experience crashes. If you have any stacktraces to random crashes, please post them along with the version of node and discord.js you are running.

**Before posting:**

* Ensure you are using the latest indev commit
* If the issue still persists, then please post

**Comment by brussell98** [comment]
Still getting `TypeError: Cannot set property 'roles' of undefined` on commit `9a57e7ab03f...` at line 1642 in InternalClient

**Comment by hydrabolt** [comment]
@brussell98 Could you try https://github.com/hydrabolt/discord.js/commit/315ae22a7f746d50ef021f43d21ce52061e1fbd7 and tell me if you are able to recreate it?

**Comment by brussell98** [comment]
Ah oops I installed the commit before it instead. I'll report any crashes on 315ae22
