### ISSUE TITLE
voiceConnection.playFile failing silently

### ISSUE THREAD

**Issue by Maltroth** [hydrabolt/discord.js#192]
While browsing the issues, I got on #189 which put me on the right track. node-opus wasn't installed and it's no where said that this was required. The comment found in AudioEncoder.js line 17 should probably throw an error instead.

I had trouble installing it, but I just needed to install Visual C++ tools to my MVS installation. But even after installing it, I got the same results. The playFile trigger the end event without playing anything. After some digging, I end up in the "ending 2" of the playStream function which means that the buffer is null. The stream variable only contains a Socket object, not sure if it's what I want.

I'm fairly new to NodeJS, maybe a miss something really stupid.

**Comment by meew0** [comment]
I assume you do have ffmpeg installed?

**Comment by Maltroth** [comment]
Nope, it is required?

**Comment by hydrabolt** [comment]
Can we see your code? And yes, ffmpeg/libav tools are required

**Comment by Maltroth** [comment]
Okay, ffmpeg is installed but I get errors with libav, is this the right one https://github.com/OptimalBits/navcodec?

And here's the part of my code:
```
function streamToChannel(voiceChannel, file) {
    // Join the channel
    bot.joinVoiceChannel(voiceChannel, function (error, voiceConnection) {
        // Be sure to be connected
        if (error == null && voiceConnection) { 
            // Play the asked file if it exists
            voiceConnection.playFile(file, { volume: 0.5 }, function (error, streamIntent) {
                streamIntent.on("error", function (error) {
                    console.log("error " + error);
                });
                
                streamIntent.on("time", function (time) {
                    console.log("time " + time);
                });

                streamIntent.on("end", function () {
                    console.log("end");
                });
            });
        }
    });
}
```

**Comment by hydrabolt** [comment]
You don't need both, one will do. Is ffmpeg in your path? Try running ffmpeg in your terminal or command prompt to check

**Comment by Maltroth** [comment]
ffmpeg is responding accordingly. still does nothing app-side :(

**Comment by khionu** [comment]
InDev appears to be broken, atm, though I am most certainly having an error, 100% of the time.
```
[debug] bypassed direct API login, used cached token
Bot is ready
[debug] ready packet took 5ms to process
[debug] ready with 1 servers, 11 channels and 3 users cached.
[debug] removed temporary voice websocket listeners
buffer.js:643
    throw new RangeError('index out of range');
    ^

RangeError: index out of range
    at checkOffset (buffer.js:643:11)
    at Buffer.readInt16LE (buffer.js:778:5)
    at Volume._transform (C:\Users\Khionu\WebstormProjects\meowbot\node_modules\discord.js\lib\Voice\VolumeTransformer.js:34:51)
    at Volume.Transform._read (_stream_transform.js:166:10)
    at Volume.Transform._write (_stream_transform.js:154:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Volume.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:529:20)
    at emitOne (events.js:90:13)
```
[My Code](http://ghost.iamtrue.net/paste/zjo67)

**Comment by aequasi** [comment]
I'm using it right now on indev without issue, fwiw

**Comment by khionu** [comment]
Latest? I pulled not even an hour ago. Also, it was fine when I used NPM

**Comment by aequasi** [comment]
Yup

**Comment by abalabahaha** [comment]
@khionu try not to hijack issues...

**Comment by khionu** [comment]
Sorry, I thought this might be relevant, I'll make a separate issue.

**Comment by Maltroth** [comment]
Will test with indev as soon as I can

**Comment by Maltroth** [comment]
I just tried with the latest indev, I merely come to the same results.

"ending 2" from VoiceConnection.js trigger 100% of the time, but this time, it waits the length of the actual audio file which is 8s long. Not sure how I get there since "ending 2" would be ~200ms max ...

**Comment by dricephd** [comment]
fwiw I seem to have the same issues on 6.0.0 where playFile() fails silently if I try to put any local path in. However when providing a url it works if it's valid, but provides no error or context when it fails.

**Comment by khionu** [comment]
@dricephd have you tried putting in an absolute path, for local?

**Comment by dricephd** [comment]
I've tried absolute starting from C:\ and several variations starting from the folder the script was running, can't seem to get it to function or receive an error.

**Comment by Maltroth** [comment]
Just confirmed on my side as well that a online path (complete URL) works, but not a local one like @dricephd said. Also tried absolute local path, relative local path, etc.

**Comment by meew0** [comment]
That seems like a problem with ffmpeg, because it does the file handling itself entirely, discord.js just passes the input path directly to it.

**Comment by dricephd** [comment]
Hmmm well this is awkward. I tried the path a different way: `'C:\\Users\\Matt\\DrIceDiscordBot\\music_cache\\o4wJGWcHzVA.mp3'`

That seems to have worked, I think it was an odd combination previously of the backslashes? It'd be odd that multiple of us seem to have had the same exact problem though....

**Comment by abalabahaha** [comment]
Typically, a `\` in code is used to escape something (eg. `\n` translates to a newline). Windows uses `\` for its file paths... `\\` in code is \ in human.

**Comment by Maltroth** [comment]
Oh wow, why did I not try that .. But the issue isn't invalid, the function still fails silently if you have an error somewhere.

**Comment by meew0** [comment]
I agree, we should be checking for ffmpeg's status code and throwing an error if it fails.

**Comment by abalabahaha** [comment]
FFMPEG errors thrown in 4e58de

**Comment by vecchiotom** [comment]
i had the same problem, but the solutions worked fine! thanks!
