### ISSUE TITLE
MessageReaction.count is wrong sometimes (until fetchUsers is called)

### ISSUE THREAD

**Issue by evaera** [hydrabolt/discord.js#1920]
**Please describe the problem you are having in as much detail as possible:**

When applying a reaction to a message, reading the `reactions` from that message will have their `count` property set to 2, even though it is 1. Calling `fetchUsers` on the MessageReaction will correct this.

This only happens sometimes, but appears to happen more consistently if you wait until after adding a second reaction.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');

const bot = new Discord.Client();

bot.on('message', async message => {
	await message.react('👍');
	await message.react('👎');
	console.log(message.reactions.find(reaction => reaction.emoji.name === '👍').count);
});


bot.login(process.env.TOKEN);

```

**Further details:**

- discord.js version: master
- node.js version: 8.1.4
- Operating system: ubuntu 16.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: c46c092d0de1d556c71d26bc3de45fb481dd75df

**Comment by lloti** [comment]
Can't reproduce on Windows 10

**Comment by evaera** [comment]
After upgrading to the latest commit as of now, it's fixed. Appears a change fixed this as a side-effect. Closing :)
