### ISSUE TITLE
clone() doesn't change name

### ISSUE THREAD

**Issue by Sir-Will** [hydrabolt/discord.js#1923]
**Please describe the problem you are having in as much detail as possible:**
Running the code below with the master branch doesn't change the title of the cloned channel.

**Include a reproducible code sample here, if possible:**
```js
voiceChannel.clone('simple name', true)
```

**Further details:**

- discord.js version: master
- node.js version: 8.2.1
- Operating system: Ubuntu

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 63f6247ce5daf9ae6c065c07ed65aacf8d867dd7

**Comment by PgBiel** [comment]
that's because channel names can't have spaces ya doofus

**Comment by SpaceEEC** [comment]
You have to pass the clone method an options object instead of multiple arguments.
That is documented [here](https://discord.js.org/#/docs/main/master/class/VoiceChannel?scrollTo=clone).

For example:
```js
voiceChannel.clone({ name: 'simple name' });
```

**Comment by Sir-Will** [comment]
Ah, that's how it works now, thanks.
Already looked at the docs and saw that thing about options but couldn't figure out how the args should look like.
