### ISSUE TITLE
Error: `RangeError: index out of range`

### ISSUE THREAD

**Issue by khionu** [hydrabolt/discord.js#193]
I'm getting this error everytime I attempt to run it, but only on InDev. No errors, but a few seemingly irrelevant warnings, in the install. I have VS Community, VC++ Tools, Py2.7.8, and FFMpeg, PATH set (though I should double check that, was done during a third party script, might have been flawed).

Again, this is only with InDev, not NPM

[My code](http://ghost.iamtrue.net/paste/zjo67) and [my error](http://ghost.iamtrue.net/paste/f4kat)

**Comment by liquidsystem** [comment]
I was getting a similar error with indev before. When I decided to rewrite my bot to make it more "clean", I noticed that the errors no longer occurred. Curious why it happened too.

**Comment by meew0** [comment]
Seems like a problem with the VolumeTransformer, it attempts to get data from packets that doesn't exist

[Relevant code](https://github.com/hydrabolt/discord.js/blob/indev/src/Voice/VolumeTransformer.js#L30)

**Comment by abalabahaha** [comment]
Still annoying how inconsistent this is and how little data we have on this.

**Comment by meew0** [comment]
This should be fixed in indev now, reopen it if it happens again
