### ISSUE TITLE
MessageReactionAdd not functioning as expected

### ISSUE THREAD

**Issue by Mas281** [hydrabolt/discord.js#1933]
**Please describe the problem you are having in as much detail as possible:**
The "messageReactionAdd" event will only fire on messages that have been sent since the user last logged in. That is to say that when I restart the bot I am creating, the messageReactionAdd event will no longer fire on messages which it previously would in the last session.

**Include a reproducible code sample here, if possible:**
```js
bot.on("messageReactionAdd", (reaction, user) => {
    console.log(reaction.emoji.name);
});
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.4.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium, completely destroys the possibility of any reaction-based systems on messages sent before  the bot logs in. 

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by dragonfire535** [comment]
You will need to fetch messages not in cache for reactions to fire, until we get autofetch.

**Comment by Mas281** [comment]
Ok, thanks for the info!
