### ISSUE TITLE
Error with discord API

### ISSUE THREAD

**Issue by heidar** [hydrabolt/discord.js#1944]
Hello,

I woke up this morning to both my Discord bots being broken. I'm using 11.2.0 with node 8.5.0 running on Ubuntu 17.04 (kernel 4.10). It was broken on previous versions but I upgraded to make sure that old version weren't the problem. It did not fix things.

I also tried regenerating my tokens and re-authorizing my bots on my server, no change.

```
(node:10954) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: undefined
(node:10954) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If someone could shed some light, I'd be very grateful as our bots are down until this is fixed.

Thanks!

**Comment by heidar** [comment]
I've just seen that Discord has blocked all IPs from Hetzner, where my bots are hosted.

**Comment by Sir-Will** [comment]
Hey, I got the same issue. Did you find anything about why they did this?

**Comment by Dev-Yukine** [comment]
![unknown](https://user-images.githubusercontent.com/20647088/30516986-f0871b98-9b4f-11e7-89a9-a2749ec6f64f.png) they said that on Twitter
