### ISSUE TITLE
Unhandled Rejection at: Promise Promise

### ISSUE THREAD

**Issue by Sir-Will** [hydrabolt/discord.js#1948]
**Please describe the problem you are having in as much detail as possible:**
For some reason my bot is no longer starting and throwing the error below.

```
Unhandled Rejection at: Promise Promise {
  <rejected> { DiscordAPIError
    at item.request.gen.end (/home/scripts/Discord/DynamicChannels/node_modules/discord.js/src/rest/handlers/RequestHandler.js:52:65)
    at then (/home/scripts/Discord/DynamicChannels/node_modules/snekfetch/src/index.js:263:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'DiscordAPIError',
  message: '',
  path: '/api/v7/gateway',
  code: undefined } } reason: { DiscordAPIError
    at item.request.gen.end (/home/scripts/Discord/DynamicChannels/node_modules/discord.js/src/rest/handlers/RequestHandler.js:52:65)
    at then (/home/scripts/Discord/DynamicChannels/node_modules/snekfetch/src/index.js:263:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'DiscordAPIError',
  message: '',
  path: '/api/v7/gateway',
  code: undefined }
```

**Further details:**

- discord.js version: master
- node.js version: 8.2.1
- Operating system: Ubuntu

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 3ace61a1795639487508856c1238884a27c61105

**Comment by iCrawl** [comment]
Is this related to #1944 perhaps?

**Comment by Tvde1** [comment]
Do you have Hetzner host your bot?

**Comment by Sir-Will** [comment]
@iCrawl looks like it.
@Tvde1 yes

**Comment by Dev-Yukine** [comment]
@Sir-Will well aslong you host your bot on a hetzner server we cant help you since Discord blocked **all** IPs from hetzner

**Comment by Sir-Will** [comment]
Alright, thanks for letting me know. If someone finds any information about this please let me know.

**Comment by devsnek** [comment]
@Sir-Will can you perform `curl https://discordapp.com/api/v7/gateway` from your hetzner box and post the output

**Comment by Sir-Will** [comment]
`{"url": "wss://gateway.discord.gg"}`

**Comment by devsnek** [comment]
it appears hetzner is unblocked then?

**Comment by Sir-Will** [comment]
Just tried to start the bot again and it works again. Thanks for letting me know.
