### ISSUE TITLE
Request Handlers queue blocking

### ISSUE THREAD

**Issue by maxerbox** [hydrabolt/discord.js#1949]
I'm having some serious issues with discord.js, I guess it's from the request handlers. I'm using the sequential option. My bot isn't sharded and is supporting 750 guilds, but when the thing comes overloaded, it's looking like there is a problem with the request queue. I mean if the bot has to send a message in a channel, it will not send it. But if the guy retry the command, it will send it with the previous not sent message. I don't think it's from rate limiting, or there is a problem because it should send it anyway.

Example of my problem: 

User: !info 
Bot: nothing sent, but added to message queue or something like, it should be send instantly 
User: retry !info 
Bot: sent the previous info command and the new one at the same time, which send 2 messages

It happens in a production environment, so I can't debug the library.

**Further details:**

- discord.js version: ~~11.1.0~~ actually happens also in 11.2.1
- node.js version: v6.11.3
- Operating system:  Linux 4.4.0-57-generic #78-Ubuntu GNU/Linux

- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by robflop** [comment]
Have you tried seeing if the problem persists on the currently latest version of discord.js, 11.2.1?

**Comment by maxerbox** [comment]
Same issue in 11.2.1

**Comment by maxerbox** [comment]
After some research, it's from the globalLimit = true that isn't handled when it occurs
https://github.com/hydrabolt/discord.js/blob/42c195c8571b28ecc076af3679b7af4e385f3b45/src/client/rest/RequestHandlers/Sequential.js#L66

Which block the request handling 
https://github.com/hydrabolt/discord.js/blob/42c195c8571b28ecc076af3679b7af4e385f3b45/src/client/rest/RequestHandlers/Sequential.js#L93

**Comment by devsnek** [comment]
I don't believe this is an issue on master for the upcoming v12.0 release as ratelimiting has been rewritten

**Comment by maxerbox** [comment]
@devsnek It happens in the 11.2.0 release

**Comment by maxerbox** [comment]
I patched it up, here are the edits I've done on the source code: 

Handle function:
https://github.com/hydrabolt/discord.js/blob/42c195c8571b28ecc076af3679b7af4e385f3b45/src/client/rest/RequestHandlers/Sequential.js#L91
```
  handle() {
    super.handle();
        if (this.busy || this.remaining === 0 || this.queue.length === 0) return;
    if(this.globalLimit) {
        this.busy = true;
        this.restManager.client.setTimeout(()=>{
           this.execute(this.queue.shift()).then(() => {
           this.busy = false;
           this.handle();
           });
        }, this.lastRetryTimeout + this.restManager.client.options.restTimeOffset)
    }
    this.execute(this.queue.shift()).then(() => {
      this.busy = false;
      this.handle();
    });
  }
}
```

I added a new property called `lastRetryTimeout` in the constructor

` this.lastRetryTimeout = 0;`

I also edited the `execute(item)` function to put the last timeout in the `lastRetryTimeout` property
https://github.com/hydrabolt/discord.js/blob/42c195c8571b28ecc076af3679b7af4e385f3b45/src/client/rest/RequestHandlers/Sequential.js#L66

```
            if (res.headers['x-ratelimit-global']) {
                this.lastRetryTimeout = Number(res.headers['retry-after'])
                this.globalLimit = true;
            }
```

It should do the trick until the new release

**Comment by maxerbox** [comment]
I've edited the changes I've done on the fix in the message above.

**Comment by telunc** [comment]
@maxerbox Thank you for the update!
