### ISSUE TITLE
How to get bots to dm someone?

### ISSUE THREAD

**Issue by WebmetsHD** [hydrabolt/discord.js#1954]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version:
- node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by bdistin** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [**Discord server**](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
