### ISSUE TITLE
.attachFile() and/or .setImage() don't allow usage of folders

### ISSUE THREAD

**Issue by UghThatGuyAgain** [hydrabolt/discord.js#1956]
**Please describe the problem you are having in as much detail as possible:**

For the RichEmbed, it appears that .attachFile() and .setImage() won't allow you to use folders as directories. I haven't done extensive testing, but:

**Include a reproducible code sample here, if possible:**
```js
// Will not work; Image is inside of the champion folder
.attachFile("camille/src/img/champion/81.png")
.setImage("attachment://camille/src/img/champion/81.png")
```
However, not using a folder (as the example gives) will work as expected. 
**Further details:**
- Priority this issue should have – please be realistic and elaborate if possible:
Not very high on the priority scale. I haven't seen anyone complain about it, but it seems a little bit silly, especially if you're using material that doesn't have a cdn or a usable URL and you don't want to have to put it in a place that isn't needed. 

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by UghThatGuyAgain** [comment]
Also forgot to mention that I apologize for any mistake that I may have made inside my code causing it to be incorrect anyways.

**Comment by Drahcirius** [comment]
It should work if you have the setImage as  `.setImage("attachment://81.png")`
The attachment path doesn't follow the same directory structure as your local environment.
