### ISSUE TITLE
Discord API v7 cant send message

### ISSUE THREAD

**Issue by ohlookitsAugust** [hydrabolt/discord.js#1957]
**Please describe the problem you are having in as much detail as possible:**
I am trying to code a `cleverbot` integration from [Cleverbot](https://cleverbot.io); I keep getting this error and I don't know what to do; it keeps happening and I honestly don't know what to do.

**Include a reproducible code sample here, if possible:**
```js
    if (args.length < 1) {
        return msg.reply("Add a argument!")
    } else {
      cleverbot.configure({botapi: cfg.api_keys.Cleverbot});
      cleverbot.write(args.join(" "), function(response) {
          msg.channel.startTyping();
          setTimeout(() => {
              msg.channel.send(response.output).catch(console.error);
              msg.channel.stopTyping();
          }, Math.floor(Math.random() * 6 + 3));
      });
    }

```

**Further details:**

- discord.js version: v11.2.1
- node.js version: v8.4.0
- Operating system: Ubuntu Server
- Priority this issue should have – please be realistic and elaborate if possible:
Getting this error:
```js
0|Yumi     | { DiscordAPIError: Cannot send an empty message
0|Yumi     |     at item.request.gen.end (/root/YumiBoat/src/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
0|Yumi     |     at then (/root/YumiBoat/src/node_modules/snekfetch/src/index.js:263:21)
0|Yumi     |     at <anonymous>
0|Yumi     |     at process._tickCallback (internal/process/next_tick.js:188:7)
0|Yumi     |   name: 'DiscordAPIError',
0|Yumi     |   message: 'Cannot send an empty message',
0|Yumi     |   path: '/api/v7/channels/265156286406983680/messages',
0|Yumi     |   code: 50006 }
```

- [ ] I found this issue while running code on a __user account__
- [ X ] I have also tested the issue on latest master, commit hash:

**Comment by BigBrainAFK** [comment]
My spidersenses are telling me this is not a lib problem.

You tried to send an empty message. Check if `response.output` actually contains smth.
