### ISSUE TITLE
Optional comma in message reply

### ISSUE THREAD

**Issue by Mrtenz** [hydrabolt/discord.js#1958]
The comma added to the message when using `message.reply()` does not make sense and doesn't look good. It would be nice if it was optional to add the comma or not.

**Comment by iCrawl** [comment]
You can always construct the reply yourself with:
`message.channel.send(`${msg.author} text here`);`

and remove the comma yourself.

**Comment by Mrtenz** [comment]
Of course I could do that, but using `message.reply()` is more convenient and making it optional isn't that much work anyway.

**Comment by iCrawl** [comment]
This is a stylistic choice and makes grammatically sense, considering you are replying to someone.
All `reply()` does is exactly what I have written above.

**Comment by hawezo** [comment]
This is old, but I second this. If you changed your mind since then, that would be a simple but appreciated change. :)

If you really want a comma by default, maybe you can add an argument in the constructor? 

```javascript
public reply(content?: StringResolvable, options?: MessageOptions, comma?: boolean): Promise<Message | Message[]>;
```

**Comment by BretHudson** [comment]
> ```js
> public reply(content?: StringResolvable, options?: MessageOptions, comma?: boolean): Promise<Message | Message[]>;
> ```

Instead of a boolean `comma` argument, perhaps a `delimiter` that defaults to `','`? That way users could send an empty string, or a `':'` if they wanted to "@BretHudson: You have failed!".

**Comment by iCrawl** [comment]
```ts
export default () =>
	Structures.extend('Message', (Message) => {
		return class MyMessage extends Message {
			public reply(content?: StringResolvable, options?: MessageOptions) {
				return this.channel.send(`${msg.author}: ${content}`, options;
			}
		};
	});
```

**Comment by ItsPapaia** [comment]
#2910 might help.

**Comment by BretHudson** [comment]
@iCrawl This is fantastic, thank you!

@ItsPapaia Sweet, hope this gets merged soon! 😄 I was considering opening a PR, but looks like someone beat me to it haha
