### ISSUE TITLE
send Message using PMchannel id

### ISSUE THREAD

**Issue by koreldan** [hydrabolt/discord.js#196]
Hi, 

i've tried to send a PM to a user using PMChannel.id but it didn't work giving me this message in console log: 
" Uncaught (in promise) TypeError: Cannot read property 'id' of null "

Any tips to how to resolve this or how to send a private message to a user ? 

Thx in advance.

**Comment by abalabahaha** [comment]
Interesting... The library apparently did not resolve PM Channel IDs, just regular channel IDs or PM channel objects

For now, you could pass the PMChannel object itself. Or, if you know how to install the indev branch, I just pushed a fix to that.

**Comment by koreldan** [comment]
thank you.

Could you compile a web distribution of it ?

**Comment by abalabahaha** [comment]
Oh webdist... You will have to wait a while for the next release. For now, just pass the PM Channel object itself.

**Comment by koreldan** [comment]
ok thx

**Comment by buley** [comment]
This also held true for me using `Client.sendMessage`. I had to loop through `bot.channels` to find the `text` `type` and then use that object rather than a string id `Resolvable`.

**Comment by abalabahaha** [comment]
@buely this should be fixed by now, can you try updating discord.js?
