### ISSUE TITLE
channel.edit({position: value}) is editing rawPosition and not position (aka can't move channels inside of categories)

### ISSUE THREAD

**Issue by Ev1dentFir3** [hydrabolt/discord.js#1974]
**Please describe the problem you are having in as much detail as possible:**

Test Case 1: When you do `currentChannel.edit({ position: currentPosition })` it's not editing `position` it's instead editing `rawPosition`

Test Case 2: When you do `currentChannel.edit({ rawPosition: currentPosition })` it properly edits `rawPosition`

**Include a reproducible code sample here, if possible:**

The below code is used to store channel order in memory and incrementally reorder them for easy channel cloning and reordering later.

```js
    orderChannels: function () {
        var channelsOrdered = client.channels.array().slice(0);
        channelsOrdered = channelsOrdered.filter(function (channel) {
            return channel.type == 'voice' && typeof channel.position !== 'undefined';
        });


        channelsOrdered = channelsOrdered.sort(function (channelA, channelB) {
            return channelA.rawPosition - channelB.rawPosition;
        })
        
        var currentPosition = 2;
        channelsOrdered.forEach(function (channel) {
            currentChannel = client.channels.get(channel.id);
            currentChannel.edit({ bitrate: 96000, position: currentPosition })
                .then(channel => {
                    console.log(channel.type + ' channel: ' +channel.name + ' position set to: ' + channel.position + ' & rawPosition set to: ' + channel.rawPosition)
                })
                .catch(console.error);
            currentPosition = currentPosition + 2;
        });

        console.log(channelsOrdered)
    }
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: v8.4.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: **Medium-High** (as this is a bug that effects editing channels directly)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
I think you have a misunderstanding of how properties are expressed from our class. you should use Channel#setPosition

**Comment by Ev1dentFir3** [comment]
ok that's something I'll look at, but edit has worked find up until now for reordering channels, why would I need to switch to another method instead of this one being fixed?

**Comment by Ev1dentFir3** [comment]
let me be more specific, in another function I need to do a more extensive channel edit like this...
``js
 voiceStateUpdate: function (oldMember, newMember) {
        //user Joins group catagory
        if (newMember.voiceChannelID) {
            const newChannel = newMember.guild.channels.get(newMember.voiceChannelID);
            console.log(newChannel)
            if (newChannel.name.startsWith(client.autoChannel.config.PluginSettings.channelPrefix)) {
                newChannel.clone('--' + client.autoChannel.config.PluginSettings.newChannelName, true, false, "none")
                    .then(createdChannel => {
                        createdChannel.edit({
                            bitrate: 96000,
                            userLimit: newChannel.userLimit,
                            parentID: newChannel.parentID,
                            position: newChannel.position + 1
                        })
                            .then(createdChannel => {
                                newMember.setVoiceChannel(createdChannel)
                                createdChannel.overwritePermissions(newMember.user, client.autoChannel.config.groupCreatorPermissions)
                                client.autoChannel.currentAutoChannels.push(createdChannel.id)
                            })
                    })
            }
        }
}
```

but `position` in the above code is editing `rawPosition` instead so it doesn't work.

**Comment by KingDGrizzle** [comment]
Screenshot of other weird behaivour: https://i.kingdgrizzle.ml/2017/10/G7P232.png
Basic example:
```javascript
// Assuming the channel position is 0 (channel.position)
<channel>.edit({ position: 1 }) // Does nothing
<channel>.setPosition(1) // Works, but seems to return the old position?
```
Something strange is up with channel positions, thats for sure.. This affects both categorized and non-categorized channels (text channels in the case of categories).

**Comment by KingDGrizzle** [comment]
I don't know if this is good to be here, but anyways..

You can actually set the channel position to anything, even values outside the limit.

For instance, if you have 2 channels in a category, you could set the first channel to position 4. And it would have rawPosition 4.. That might be on Discords side, but its weird anyways.

**Comment by Ev1dentFir3** [comment]
Here is a simple bot that prints the channels by rawPosition or by order as seen in client, or both at the same time. You guys can use it to see what I'm talking about.

The reason I would rather change position over rawPosition is because I really just want to move channels inside of parent and not mess with the full channel list if possible.

Bot: https://hastebin.com/pagelicuxa.js
Example Output: https://hastebin.com/bilatumili.txt

**Comment by Ev1dentFir3** [comment]
Here is a simple bot that prints the channels by rawPosition or by order as seen in client, or both at the same time. You guys can use it to see what I'm talking about.

The reason I would rather change position over rawPosition is because I really just want to move channels inside of parent and not mess with the full channel list if possible.

Bot: https://hastebin.com/pagelicuxa.js
Example Output: https://hastebin.com/bilatumili.txt

If you look at the Example Output above you will notice in the "Game 1" category and also in the "Uncategorized" section there are channels that doesn't respect channel order according to `rawChannel`

**Comment by Ev1dentFir3** [comment]
I've been chatting with the guys in the API discord, and it looks like this isn't a discord.js issue, but an overall API issue effecting all libs where positions are just funky at the moment. Mason who is one of the Discord Employees on the server also confirmed it's an issue they are looking at so I assume they might drop another updates for it soon.
