### ISSUE TITLE
Copy message as it is from one channel to another(all kinds of message)

### ISSUE THREAD

**Issue by rahulserver** [hydrabolt/discord.js#1976]
**Please describe the problem you are having in as much detail as possible:**
I am trying to find a way to be able to copy message from one channel to another using discord js. For text only messages, its easy, but for message with attachments, it looks cumbersome and I can't seem to figure out how to do it.

**Include a reproducible code sample here, if possible:**
I tried this:
```
var channelId="somechannelid";
Client.on('message', msg=>{
      Client.channels.get(channelId).send(msg);
});

```
But it puts this in channel:
```
<@null>
```

I wonder how do I do it!
**Further details:**

- discord.js version: 11.0.0
- node.js version: 7.5.0
- Operating system: windows(dev) and linux(heroku prod.) 
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
This is for issues with the library. Please take your implementation issues to the official server.
