### ISSUE TITLE
'voiceStateUpdate' not detects selfMute.

### ISSUE THREAD

**Issue by Crypti-x** [hydrabolt/discord.js#1977]
When the Bot and I are in a VoiceChannel, I mute myself (not serverwide) `console.log('2');` is **not** triggered. "ja" is not triggered too. Why?

```js
meme = "123DISCORD ID";
function _podoff() {
	if (_voiceReceivers.get(kanal)) {
		_voiceReceivers.get(kanal).destroy();
		_voiceReceivers.delete(kanal);
		_voiceConnections.get(kanal).disconnect();
		_voiceConnections.delete(kanal);
	}
}
function _onReady() {
	console.log('Ready!');
	
	_podon();
}

function muted(oldMember, newMember) {
 console.log("ja");
 if (oldMember.selfMute == false && newMember.selfMute == true) {
	 console.log('2');
	 if (newMember.id == meme) {
		console.log('3');
		_podoff();
		process.exit(0);	 

	 }
 }
}

function error(e) {
	console.log(e.stack);
	process.exit(0);
}

const client = new Discord.Client();
const _voiceConnections = new Map();
const _voiceReceivers = new Map();
const _writeStreams = new Map();
client.on('ready', _onReady.bind(this));
client.on('voiceStateUpdate', muted.bind(this));
client.on('guildMemberSpeaking', _onGuildMemberSpeaking.bind(this));
client.login(TOKEN).catch(console.error);
```
If I leave the channel for example `console.log("ja");` is triggered.

**Comment by robflop** [comment]
Could you please fill out the issue template so we can start investigating this?

See [here](https://github.com/hydrabolt/discord.js/blob/master/.github/ISSUE_TEMPLATE.md) for the template.

**Comment by Crypti-x** [comment]
I don't need to fill out the form anymore, because the problem has been solved by your code, thank you! Everything seems to work now.

**Comment by Crypti-x** [comment]
The issue isn't solved. Now I never get `console.log("ja");`
Version: `discord.js@11.2.1` Windows64 / node.js `v8.4.0` / `selfbot`

**Comment by Crypti-x** [comment]
Magicly now it works
