### ISSUE TITLE
.get isnt working for messageReaction

### ISSUE THREAD

**Issue by Monkeyyy11** [hydrabolt/discord.js#1984]
Hello, 

I runned the codeline below on stable and it worked. Now I installed discord.js-master and it doesnt work. ( I know that my codeline is not good and I could do it differently. )
I have the following error: TypeError: Cannot read property 'count' of undefined

```js
messageReaction.message.reactions.get(encodeURIComponent('‼')).count === 5
```

If I use:
```js
messageReaction.message.reactions.get('‼').count === 5
```
I receive the error: TypeError: Cannot read property 'count' of undefined

**Further details:**

- discord.js version: discord.js@12.0.0-dev
- node.js version : 8.3.0
- Operating system: Windows 10 64Bit
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by BigBrainAFK** [comment]
First its better to use the specific hash of the master version that you are using.

But it works 100% fine for me... I can only imagine that the message you check doesn't have the emote you specified.

**Comment by Monkeyyy11** [comment]
I fixed it, thx anyway!
