### ISSUE TITLE
channel.send() is not sending instead it got queued.

### ISSUE THREAD

**Issue by telunc** [hydrabolt/discord.js#1985]
**Problem**
I have a bot that sends news to subscribed channel daily. But for some reason, the messages don't seem to send instead they got queued. They do send until someone prompt another command such as `!ping`. Any idea why it's doing this?

**Code**
```js
guilds.forEach(async(guild) => {
    let channel = client.channels.get(guild.channel);
    if (!channel) return;
    posts.forEach((post) => {
        channel.send('', { embed: { color: 0x33A2FF, title: post.title, description: post.description, thumbnail: { url: post.image }, url: post.link } });
    });
});
```

**What happened**
<img src="https://i.imgur.com/tfviNsJ.png" />

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.0.0-alpine
- Operating system: Ubuntu 16.04.3 x64
- Priority this issue should have – Low

**Comment by Dev-Yukine** [comment]
this is related to #1949 and you can get a temporary fix there it should not occour on master anymore since rate-limits were rewritten
