### ISSUE TITLE
MessageReaction.users not fully expanded from Message.fetchMessages() or Message.search()

### ISSUE THREAD

**Issue by DilatoryCheetah** [hydrabolt/discord.js#1987]
**Please describe the problem you are having in as much detail as possible:**
When you iterate through the Messages collection that is return by either Message.fetchMessages() or Message.search(), you get an empty collection for the users collection for each MessageReaction for each message.  I am trying to grab the list of all reactions and the usernames for each person that reacted.

**Include a reproducible code sample here, if possible:**
```js

	var messageContent = "Test message";
	channel.fetchMessages({
		limit: 10
	}).then(messages => {
		messages.filter(f => f.content == messageContent).map(m => {
			if (m.reactions.size > 0) {
				m.reactions.map(r => {
					console.log(`${r.emoji.name}:`);
					console.log(r.users.map(u => u.username).join(" "));
				});
			}
		});
	}).catch(console.error);
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: v8.6.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
2

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Those are api limitations:
- If you use fetchMessages you get reactions, but no users.
On stable you can manually fetch up to 100 of those with `MessageReaction#fetchUsers`: [docs](https://discord.js.org/#/docs/main/stable/class/MessageReaction?scrollTo=fetchUsers)
On master you can fetch all of them if needed (100 per call): [docs](https://discord.js.org/#/docs/main/master/class/MessageReaction?scrollTo=fetchUsers)

- If you search you get no reactions at all.
You have to manually fetch the messages again to also get reactions, and then fetch the users with the above mentioned method.

**Comment by DilatoryCheetah** [comment]
Great, that worked.
