### ISSUE TITLE
FFMPEG Volume option not working.

### ISSUE THREAD

**Issue by zaza7** [hydrabolt/discord.js#199]
While testing the Indev branch, the `volume` option for FFMPEG is no longer passed. I tried one commit before the Volume Wrapper was added and it works, installing the commit with the wrapper breaks the option.
The commit in question where it still works is ca873ac36ea9c1f5c974f407f20d158c1a405689
The commit where it no longer works is 3c64cfce4a387cba695be37f3214845d1139c7b7

**Comment by meew0** [comment]
Well, the volume wrapper replaces the ffmpeg volume option - it's superior because it allows changing the volume while something is playing, rather than setting the volume once and never being able to change it.

**Comment by zaza7** [comment]
Could you give me an example on it's usage please?

**Comment by meew0** [comment]
Pass the volume as normal as an option to `playXYZ`, or use `voiceConnection.setVolume(0.5)` (or any other value you would use as an option) after starting playback.

**Comment by zaza7** [comment]
Thank you very much, I will use that.
