### ISSUE TITLE
Audit Log reasons are cut off after hashtags

### ISSUE THREAD

**Issue by Devoxin** [hydrabolt/discord.js#1995]
**Please describe the problem you are having in as much detail as possible:**
When an action is performed on a user that is logged within audit log, if you log the responsible user's tag (e.g. `User#0001 added role because test`), anything from that hashtag onwards is omitted (so it'd look like `User` with nothing else)

**Include a reproducible code sample here, if possible:**
```js
message.guild.members.first().kick(message.author.tag + ' kicked for being the first member in the list')
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 8.6.0
- Operating system: Debian 8.9
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Works for me on latest stable (11.2.1).

Relevant commit and line that fixed that issue https://github.com/hydrabolt/discord.js/commit/be4ccb368697ce29701b6e3849e1b0c5f74f4621#diff-c30fd3a31c6d613505dede2fd2b5ff2dR40

**Comment by BigBrainAFK** [comment]
Next time pls update to the latest stable and master to see if one of the 2 already has a fix or not.
