### ISSUE TITLE
Not getting any input from #createPCMStream

### ISSUE THREAD

**Issue by InventivetalentDev** [hydrabolt/discord.js#2000]
**Please describe the problem you are having in as much detail as possible:** 
I'm trying to get audio input using [`voiceReceiver.createPCMStream` ](https://discord.js.org/#/docs/main/stable/class/VoiceReceiver?scrollTo=createPCMStream) and sending it to a file for testing. But that file always stays empty, no matter how long audio was recorded.  

I'm currently using the code from these examples: 
https://gist.github.com/eslachance/fb70fc036183b7974d3b9191601846ba 
https://gist.github.com/yeahok/669fd987f5724185cb4df2f2e3ac10cf

**Include a reproducible code sample here, if possible:**
```js
message.member.voiceChannel.join().then(connection => {
            let voiceReceiver = connection.createReceiver();

            connection.on('speaking', (user, speaking) => {
                if (speaking) {
                    console.log("listen on");
                    let fileStream = fs.createWriteStream('./test/audiotest.pcm');
                    let audioStream = voiceReceiver.createPCMStream(user);

                    audioStream.pipe(fileStream);

                    audioStream.on('end', () => {
                        console.log("listen off");
                        fileStream.end();
                    });
                }
            });
            console.log("connected");
        });
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: v8.6.0
- Operating system: Ubuntu 14.04.5 LTS

**Comment by InventivetalentDev** [comment]
I'm guessing this is caused by https://github.com/hydrabolt/discord.js/issues/1310

**Comment by hydrabolt** [comment]
Probably fixed in master, can you try it out?

**Comment by InventivetalentDev** [comment]
Yep, just tried and works fine on master. Thanks c:

**Comment by texruska** [comment]
Has this problem resurfaced? I seem to be having the exact same issue on discord.js version 11.3.2
