### ISSUE TITLE
messageReactionAdd/messageReactionRemove event on client never gets emitted

### ISSUE THREAD

**Issue by javiqaz** [hydrabolt/discord.js#2009]
**Please describe the problem you are having in as much detail as possible:**
The events messageReactionAdd/messageReactionRemove, never get trigger, meanwhile .on('message'... , works fine

**Include a reproducible code sample here, if possible:**
```js
client.on('messageReactionAdd', (reaction, user) => {	
	console.log('Added a reaction.');	
});
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.6.0
- Operating system: Win 10 x64
- Priority this issue should have – please be realistic and elaborate if possible: middle-high priority

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by dragonfire535** [comment]
Are the messages in cache? Also, you can do `.on`.

**Comment by javiqaz** [comment]
@dragonfire535 
```
client.on('message', message => {   
       console.log("Message sent");
});
```
Works fine

**Comment by dragonfire535** [comment]
nono, are the messages you're trying to react to in the message cache? As in, were they sent after start-up?

**Comment by javiqaz** [comment]
there are no in the cache, but message event works perfectly, the problem is with messageReaction

**Comment by dragonfire535** [comment]
message reaction events won't work on messages not in cache.
