### ISSUE TITLE
disallow trying to delete the @everyone role

### ISSUE THREAD

**Issue by jhgg** [hydrabolt/discord.js#201]
fail when trying to delete a role, when role_id == guild_id.

**Comment by meew0** [comment]
How is this high priority?

**Comment by abalabahaha** [comment]
Because it's Jake

**Comment by uniquoooo** [comment]
admin aboose

**Comment by meew0** [comment]
Shouldn't Discord fix this on their end though? There's always users that don't use pre-made libraries and if it's such a big problem they can just send a 400 or something when somebody tries to do this.

**Comment by hydrabolt** [comment]
Agree with @meew0

**Comment by khionu** [comment]
I would point out that Discord has a large taskload of features to get to, and that in lieu of them being able to get to that right away, however simple/quick of a patch, it should be Library end. Besides, I might be wrong, but wouldn't that kind of change be something that would be more expected in the New API? They might not patch it in the current API, and just make sure they cover that point then.

**Comment by abalabahaha** [comment]
I don't think it works anyway. It's just for convenience

**Comment by jhgg** [comment]
Why send a request you know is going to fail? Logic is literally to check if role id is same as Guild id.
