### ISSUE TITLE
"value" argument is out of bounds after often play on the same voiceConnection

### ISSUE THREAD

**Issue by Dev-Yukine** [hydrabolt/discord.js#2016]
**Please describe the problem you are having in as much detail as possible:**
after very long playing audio on the same voice Connection (e.g. always creating a new dispatcher on end event on the same connection) on a lot of servers the following error occurs: 
"TypeError: "value" argument is out of bounds:" 
shortly after that another error occurs from prism-media.

full trace stack can be viewed [here](https://hastebin.com/agukirumiw.js)

this happend only when i use 24h+ the same voiceConnection with playStream/playFile

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.6.0
- Operating system: Linux Ubuntu server 14.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Fixed in voice-rewrite
