### ISSUE TITLE
stopPlaying with playRawStream sometimes gives an error.

### ISSUE THREAD

**Issue by ciruz** [hydrabolt/discord.js#202]
When I play a stream with ``ytdl-core`` and ``discord.js`` **sometimes** my script crashes when stopping the playback.

My play function:
```js
bot.voiceConnection.stopPlaying();
bot.voiceConnection.playRawStream(ytdl(video, {filter: 'audioonly'})); //Note: video is only a YouTube url
```

My stop function:
```js
bot.voiceConnection.stopPlaying();
```

**50% of the time it works fine and stopping or loading another audio works without any issues**, but the other 50% the script crashes with this error (there is no pattern recognizable) when i call ``stopPlaying();``

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at Pipe.onread (net.js:550:26)

```

``node.js: v5.7.0``
``npm: 3.6.0``
``discord.js: 6.0.0``
``ytdl-core: 0.7.10``

Any ideas?

**Comment by TehSeph** [comment]
It's a known issue with ytdl. See #60

**Comment by ciruz** [comment]
Hey @TehSeph thanks for your answer.

I found the issue you talking about on ytdl-core, also with a fix from @meew0 
https://github.com/fent/node-ytdl-core/issues/65

Thanks man!
