### ISSUE TITLE
"Cannot Send an Empty Message" Error If Message Is an Emoji or Not a "Normal" Character

### ISSUE THREAD

**Issue by computerwiz160** [hydrabolt/discord.js#2024]
**Please describe the problem you are having in as much detail as possible:**
If the message being sent is not a "normal" character (ex: ( ͡° ͜ʖ ͡°)), a "cannot send an empty message" error happens.

**Include a reproducible code sample here, if possible:**
```js
client.on('message', message => {
    let test = "🅱"
    message.channel.send(test);
    //DiscordAPIError: Cannot send an empty message
});
```
```js
client.on('message', message => {
    let otherTest = "( ͡° ͜ʖ ͡°)"
    message.channel.send(otherTest);
    //DiscordAPIError: Cannot send and empty message
});
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: v6.11.4
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Not super high, but def breaks some quote systems that contain emojis/faces

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Drahcirius** [comment]
Thanks for the bug report! We were scratching our heads in the staff channel trying to reproduce the bug, but you've figured it out for us.
The current fix is to downgrade to snekfetch 3.4.5 on master, so if you need your bot to be up, just sure to run `npm i snekfetch@3.4.5` and you should be up and running again.
Hopefully we'll have a better fix for this later.

**Comment by BobbyWibowo** [comment]
For those who use Yarn, try https://yarnpkg.com/en/docs/selective-version-resolutions:
```
  "resolutions": {
    "discord.js/snekfetch": "3.4.5"
  }
```
or something like that..

**Comment by dragonfire535** [comment]
The issue has been fixed with the latest snekfetch release.
