### ISSUE TITLE
On presenceUpdate event oldMember.user.presence.status === newMember.user.presence.status

### ISSUE THREAD

**Issue by mrpinkcat** [hydrabolt/discord.js#2025]
**When presenceUpdate event was called, oldMember.user.presence.status is equal to newMember.user.presence.status**

**Code sample here:**
```js
bot.on('presenceUpdate', (oldMember, newMember) => {
  console.log(`${oldMember.user.username} ${oldMember.user.presence.status} to ${newMember.user.presence.status}`);
// Mr. Pink 🐱 online to online
});
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.5.0
- Operating system: Windows 10 64bits
- Priority this issue should have – please be realistic and elaborate if possible: It keeps me from adding an essential feature to my bot

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
status isn't the only thing that changes for a presence update. any part of the presence object changing will trigger it

**Comment by mrpinkcat** [comment]
Yes of course, I know, but if I change my status exclusively, it doesn't work.

**Comment by hydrabolt** [comment]
can you use the members presence and not the users

**Comment by mrpinkcat** [comment]
It works ! Thanks
```js
oldMember.presence.status != newMember.presence.status
```

**Comment by exsterno** [comment]
> 
> 
> It works ! Thanks
> 
> ```js
> oldMember.presence.status != newMember.presence.status
> ```
> 
> Sorry for the inconvenience

how do i make my bot give the member a role if there status includes .gg/cut

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
