### ISSUE TITLE
Make a Private TextChannel with a Role

### ISSUE THREAD

**Issue by xXZ3r0Xx** [hydrabolt/discord.js#2029]
I want to create a private Textchannel for only one role. But i cant find this method on the discord.js website.
Can you help me pls :) ?

PS: Sorry for my bad English

**Comment by bdistin** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
