### ISSUE TITLE
Why isn't {split: true} default for sendMessage

### ISSUE THREAD

**Issue by Worm4real** [hydrabolt/discord.js#2032]
Just spent awhile googling to figure out how to get sendMessage to split, ended up trying splitMessage (deprecated) and eventually found how it was handled now. Though why isn't it just default functionality? Why wouldn't you want split on by default?

**Comment by devsnek** [comment]
because its a spammy feature by nature and you shouldn't really ever be sending messages over 2000 chars anyway

**Comment by iCrawl** [comment]
^+1

**Comment by iCrawl** [comment]
There is certainly a use case for split and more than 2k characters, but it has major drawbacks when it comes to spammy outputs. Ever tried some nice guild.members eval on a large server? Yea, you might not want to have split: true by default in those cases.
And calling split: false explicitly on those is more of a hassle than activating it whenever you need it.

**Comment by Worm4real** [comment]
I was just using it for the sound list for my soundbot and all I got was 

(node:3252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.

after which I I had to spend a while googling to figure it out. I'm obviously not making the most complex bot but at least it would have been nice for the error to mention split.

**Comment by devsnek** [comment]
`content: Must be 2000 or fewer in length.` this is really obvious, no need to mention split

**Comment by Worm4real** [comment]
Look the list is longer than 2000 characters, I'm really sorry but that's just the way it is.

**Comment by devsnek** [comment]
so enable splitting for your message?

**Comment by dragonfire535** [comment]
Look the split option is default false, I'm really sorry but that's just the way it is.

**Comment by Worm4real** [comment]
Look I'm past enabling it. I trust there's reasons beyond my shitty bot why you would just took me awhile to find it.

**Comment by appellation** [comment]
So if I accidentally send a message with 100k characters, discord.js should automatically send 50 messages?

No one is saying that you're retarded for wanting to send over 2k characters: the option exists so you can do precisely that.  However, you should not do so without due consideration; hence the default to false.  Further, the user should be notified of the failure to send the message.  The only elegant solution in this situation is to panic and error, which discord.js does.

**Comment by Worm4real** [comment]
Look I said I was over the idea of it being default. Still would be something to mention the capability the function to do what you want it to rather than implying it needs to be fed 2000 character chunks.
