### ISSUE TITLE
voiceConnection.playFile does not works twice

### ISSUE THREAD

**Issue by kitsuyui** [hydrabolt/discord.js#2034]
I met strange bug on master branch (68a30584db44580d1e00e6da57e24e0ae5bb1808).

Following code works fine on released version [11.2.0](https://github.com/hydrabolt/discord.js/releases/tag/11.2.0). It sounds either wav file; first and second.

And it fails on master branch. It sounds first wav file only.

```js
const Discord = require('discord.js');
const client = new Discord.Client();

const play = async (voiceConnection, filepath) => {
  const player = voiceConnection.playFile(filepath);
  await new Promise(resolve => player.on('end', resolve));
}

client.on('ready', () => {
  const channelId = process.env['DISCORD_CHANNEL'];
  const channel = client.channels.get(channelId);
  channel.join().then(async (voiceConnection) => {
    await play(voiceConnection, 'test.wav');
    await play(voiceConnection, 'test.wav');
  });
});

client.login(process.env['DISCORD_TOKEN']);
```

**Further details:**

- discord.js version:
  - 11.2.0 ... OK
  - master ... NG
- node.js version: v8.6.0
- Operating system: macOS High Sierra
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 68a30584db44580d1e00e6da57e24e0ae5bb1808

## Related to:

[#1693 .playFile() & .playStream() delays](https://github.com/hydrabolt/discord.js/issues/1693)
[#1745 Fixes #1693](https://github.com/hydrabolt/discord.js/pull/1745)
[#2017 Dispatchers taking a long time to start in VoiceConnections where one has already played](https://github.com/hydrabolt/discord.js/issues/2017)

**Comment by Dev-Yukine** [comment]
why should you be able to play to files/streams on the same connection :thinking: ? i dont think that this is needed (same for the PR ofc)

**Comment by kitsuyui** [comment]
@Dev-Yukine 
Do you mean voiceConnection is for temporary object in the voice session?

I just wanted to create a bot that talks using voice synthesizer.
So I expect to play short voice sounds several times.

It may be my misunderstanding that voiceConnection is consistent connection in a session of voiceChannel.
If it would be wrong, but what is the correct way?

**Comment by Dev-Yukine** [comment]
oh sorry seems like i misunderstood that. are you sure its happening because of the timestamp property reset?

**Comment by kitsuyui** [comment]
Ya, it seems to. The timestamp property reset causes delay or never playing.
It looks to me like  https://github.com/hydrabolt/discord.js/pull/1745 is over-correction.

**Comment by kitsuyui** [comment]
😄
