### ISSUE TITLE
messageDeleteBulk event fires twice

### ISSUE THREAD

**Issue by lloti** [hydrabolt/discord.js#2036]
**Please describe the problem you are having in as much detail as possible:**
The messageDeleteBulk event is fired twice

**Include a reproducible code sample here, if possible:**
```js
const { Client } = require('discord.js');
const bot = new Client();

bot.on('message', msg => {
  if (msg.content === '!bulk-delete') msg.channel.bulkDelete(2);
});

bot.on('messageDeleteBulk', m => console.log(`Bulk deleted ${m.size} messages.`));

bot.login('token');
```

**Further details:**

- discord.js version: Master
- node.js version: 8.6.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium-High

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 68a30584db44580d1e00e6da57e24e0ae5bb1808

**Comment by robflop** [comment]
I've just confirmed this on the provided hash (latest at time of writing). Looking into it now.
