### ISSUE TITLE
Browser sample broke

### ISSUE THREAD

**Issue by lhr0909** [hydrabolt/discord.js#204]
http://hydrabolt.github.io/discord.js/browser.html

When I tried to log in, it seems like it errored out.

    Uncaught TypeError: Cannot read property 'evalPerms' of null

**Comment by khionu** [comment]
You do see the spot where it said "Experimental?" As far as I know, that's not even using a recent version of Discord.JS. It's not a proper implementation of D.JS, you should follow the docs to install your own instance.

**Comment by TehSeph** [comment]
@khionu webdists should be built for latest (6.0.0), though don't think they've been tested.

**Comment by khionu** [comment]
WebDists? Yeah. But specifically that instance?

**Comment by khionu** [comment]
Not prevalent to the Library as far as development.

**Comment by abalabahaha** [comment]
Still a legit issue with the demo

**Comment by raistlinthewiz** [comment]
Works fine for me?

**Comment by khionu** [comment]
Might have been fixed and the issue simply not updated. I'll ping the team.

**Comment by meew0** [comment]
Fixed in https://github.com/hydrabolt/discord.js/commit/8021bbdb5ecba3c6868e1597a090bcc7a03119cd
