### ISSUE TITLE
channel.startTyping() promise rejections

### ISSUE THREAD

**Issue by LinearSpoon** [hydrabolt/discord.js#2040]
**Please describe the problem you are having in as much detail as possible:**
`channel.startTyping()` continuously throws promise rejection warnings if the bot doesn't have permission to send messages. Is it possible for discord.js to stop trying to type if the bot doesn't have permission? If this is expected behavior, is there a way I can call `channel.stopTyping()` after permission is taken away while the bot has already started typing?

**Include a reproducible code sample here, if possible:**
1. Type "start" to have the bot start typing.
2. Disable the bot's permission to send messages in the channel.
3. Node begins emitting UnhandledPromiseRejectionWarning every few seconds.

```js
let Discord = require('discord.js');
let bot = new Discord.Client();

bot.on('ready', function() {
	console.log(Discord.version);
});

bot.on('message', function(message) {
	if (message.content == 'start')
		message.channel.startTyping();
	if (message.content == 'stop')
		message.channel.stopTyping();
});

bot.login('...');
```

```
12.0.0-dev
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Missing Access
(node:6636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): DiscordAPIError: Missing Access
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): DiscordAPIError: Missing Access
```
**Further details:**

- discord.js version: 12.0.0-dev (discovered in stable)
- node.js version: 8.7.0
- Operating system: Windows 8 and Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 68a30584db44580d1e00e6da57e24e0ae5bb1808

**Comment by Dev-Yukine** [comment]
first of you could just catch the promise and handle the error, second you want to test if you have permission in that channel to send messages before using that function so it wont reject due permissions

**Comment by LinearSpoon** [comment]
`channel.startTyping()` doesn't return a promise, so there is nothing to catch. Also my bot does test if it has permission to send messages beforehand. It doesn't help me if the bot loses permission after typing has already started.
