### ISSUE TITLE
Discord Bot writing what i write

### ISSUE THREAD

**Issue by vaskofo** [hydrabolt/discord.js#2043]
Hello there,

Quite new to the GitHub and Discord JS Bot creation and i was kinda curious if i could make the bot write what i write in another channel or in the console itself, is it possible?

Thanks in advance :)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
