### ISSUE TITLE
Messages from the same channel retain the author from the first message caught

### ISSUE THREAD

**Issue by KTachyon** [hydrabolt/discord.js#2045]
**Please describe the problem you are having in as much detail as possible:**

I'm really wondering how it is possible that this wasn't caught by anyone and I was really rejecting the idea of creating an issue because of this...

I have basically picked up the code you had on your main page and used it to just print out the author's username. The problem is that, after I get the first message from some channel with the correct author, all other messages from the same channel will feature the same author. The message itself contains the correct information, though.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log('I am ready!');
});

client.on('message', (message) => {
  console.log('author', message.author.username);
});

client.login("my token");
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 6.10.0 & 6.11.4
- Operating system: Mac OS X 10.13 (High Sierra)
- Priority this issue should have – please be realistic and elaborate if possible: I'd say High. But I'm still a little bit confused about this not working at the moment.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by dragonfire535** [comment]
I just tested this, the author is logging as normal.

**Comment by KTachyon** [comment]
I was looking at discord.js' package.json, it seems to require node v8.0.0 or above. It actually works when using version v8.0.0, so it's probably an issue with node v6.x.x, perhaps?

If the intention is to support only above nove v8.0.0, then I guess this is a non-issue.

**Comment by iCrawl** [comment]
That's because you are looking at the master branch which is the development version.

**Comment by KTachyon** [comment]
@iCrawl You're right. The version I have installed states `"node": ">=6.0.0"`. I'm not sure why I'm getting the issue on versions 6.10.0 and 6.11.4 though. Did you run that test on these versions @dragonfire535?

**Comment by KTachyon** [comment]
Actually, I just saw this happen with version 8.0.0 as well. Really weird, since it was working properly before and there were no significant changes to the code :\

**Comment by dathappysheep** [comment]
davb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by KTachyon** [comment]
Extra data:
* It works fine if I destroy and create a new client between each message (which isn't ideal).
* The issue seems to happen only with bot-only channels (channels where only bots "speak").
  - Listening to multiple channels, the author will be logged correctly for all people channels, but not for the bot-only channels.

**Comment by KTachyon** [comment]
Ok, I figured it out. The situation is far more specific than I was thinking.

So this is a single bot that changes name, so the ID of the bot is the same, but the name is different. Since discord.js "caches" the users here:

https://github.com/hydrabolt/discord.js/blob/11.2.0/src/client/ClientDataManager.js#L42

It will always fetch the initial name and not the current one.

**Comment by iCrawl** [comment]
This isn't probably much to ask for, but can you install master via `npm i hydrabolt/discord.js` and test this case again? It should be resolved there iirc.

Please make sure the entries in the package.json and package-lock.json update when you update.

**Comment by KTachyon** [comment]
@iCrawl Yes, it's fixed on the master, though it currently locks you to v8.0.0
