### ISSUE TITLE
Discord.js

### ISSUE THREAD

**Issue by lonewolfdesign** [hydrabolt/discord.js#2048]
I'm having an problem. I am trying to list how many members there are in total there are in all of the servers my bot is in. Github was helpful with getting how many guilds the bot is in. 
This is the code:
if(command == '..botsize'){
	message.reply(client.guilds.size)
	message.reply(client.guilds.members)
}
Thank you for the help

**Comment by Dev-Yukine** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

you should read a template before deleting it 🤔

**Comment by lonewolfdesign** [comment]
Thank you

**Comment by XtremePlayzCODE** [comment]
```js
if (command == '..botsize') {
    message.reply(client.guilds.size);
    message.reply(client.guilds.map(g => g.memberCount).reduce((f, l) => f + l));
}
```
If you want it to reply with this:
```
@person, 12 (guilds)
@person, 150 (total guild members for every guild)
```
then the above code is exactly what you need.
