### ISSUE TITLE
Unhandled 'error' event - VoiceConnection.playFile

### ISSUE THREAD

**Issue by sebastienfulmer** [hydrabolt/discord.js#205]
When attempting to use VoiceConnection, the following error occurs.
```
events.js:154
      throw er; // Unhandled 'error' event`
```

Code segment:
```
var Discord = require('discord.js');
var CozyBot = new Discord.Client();
CozyBot.joinVoiceChannel(CozyBot.servers.get("name","Basically Gaming").channels.get("name","music"),function(err,connection) {
    connection.playFile("/beans.mp3");
});
```

The server resolution and channel resolution work fine in joinVoiceChannel, as if the playFile statement is replaced with a sendMessage statement, it works fine.

**Comment by khionu** [comment]
Full stacktrace, does it include `ECONNRESET`?

**Comment by abalabahaha** [comment]
@khionu playing a file doesn't do ECONNRESETs usually

@sebastienfulmer check the `err` object in your callback, before you do playFile. Maybe you have an error there?

**Comment by FavreNicolas** [comment]
```
if (!justbot.voiceConnection == null){
    justbot.voiceConnection.stopPlaying();
}
justbot.joinVoiceChannel(channel, function(error) {
    if (error){
      console.log(error);
    }else {
      //No error, your code
    }

  });```

And play file

```
justbot.voiceConnection.playRawStream(REQ(url), {"volume":0.25}, function(err, player) {
    if (err)
        console.log(err)
     if (player)
        justbot.sendMessage(channelText, ":musical_note: `" + msg.from.username + " A demander d'ecouter " + message.text + "`");
         justbot.setStatus("idle", "Soundcloud Music")
        //console.log(player)
});
```

**Comment by khionu** [comment]
@FavreNicolas please make a separate issue to report your own problem. There is not enough said here to even say what this specific issue is, yet.

**Comment by FavreNicolas** [comment]
No I show him my code, me it works

**Comment by abalabahaha** [comment]
That code is actually quite broken

**Comment by sebastienfulmer** [comment]
@abalabahaha, doing ```console.log(err)``` doesn't alleviate the problem, and I still get the error
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn help ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

**Comment by khionu** [comment]
Wrap your third line in a try/catch, like this
```js
try {
    // your voiceconnection code
} catch (ex) {
    console.log(ex.stack);
}
```

**Comment by meew0** [comment]
No need to do that, this error means you don't have FFmpeg installed. Install it (and make sure it's in your PATH) and it will work
