### ISSUE TITLE
Error emitting instead of DiscordAPIError

### ISSUE THREAD

**Issue by somefajita** [hydrabolt/discord.js#2051]
**Please describe the problem you are having in as much detail as possible:**
When trying to leave a guild that you also own, an error is emitted.
_Error [GUILD_OWNED]: Guild is owned by the client._
This should be a DiscordAPIError, not simply an Error.

**Include a reproducible code sample here, if possible:**
  1. Be the owner of a guild
  2. Type "leave" to attempt to leave the guild
```js
let Discord = require('discord.js');
let bot = new Discord.Client();

bot.on('ready', function() {
	console.log('ready');
});

bot.on('message', function(message) {
	if (message.content == 'leave') {
		message.guild.leave().catch(console.error);
	}
});

bot.login('...');
```

**Further details:**

- discord.js version: 11.2.1 + 12.0.0-dev
- node.js version: 8.7.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low
- [x] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 296046dbc6faa0b6aeabd0c7efdc470c0c834b16

**Comment by Gawdl3y** [comment]
No, because it's not an error being generated by the API. It's a [manual check](https://github.com/hydrabolt/discord.js/blob/master/src/structures/Guild.js#L1071) in Discord.js.
