### ISSUE TITLE
New libsodium-wrappers/libsodium update breaks playStream/playFile

### ISSUE THREAD

**Issue by Dev-Yukine** [hydrabolt/discord.js#2053]
**Please describe the problem you are having in as much detail as possible:**
if you install the newest version of libsodium-wrappers (0.7.2) and try to use playStream/playFile this error occurs 

TypeError: secretbox.close is not a function

the tracestack refers to the StreamDispatcher.js file or more exactly to the Secretbox.js file

full stacktrace can be view [here](https://hastebin.com/tijexamuvo.js)

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.7.0
- Operating system: Linux Ubuntu 14.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: low (but you should note that on the github page aslong it is not fixed)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 0004e19ecade46d705768ef5c5b0932e6dc3cabf

**Comment by appellation** [comment]
To be clear, this does not represent an error with Discord.js as version 0.7.2 is outside the semver range specified in the package.json.  However, it would probably be a good idea to update and accommodate the latest version.

**Comment by Dev-Yukine** [comment]
thats true but i also would like the idea of update and accommodate the latest version since i like to have all my dependencies on latest version 👀

**Comment by hydrabolt** [comment]
Updated the dependency for it and fixed in 96ce1b0945a0c24f3c263d33f48e39ed22753767

**Comment by Jeffroiscool** [comment]
Somehow this issue can also occur when not using libsodium.
My npms: https://pastebin.com/vfPSuqdd

![image](https://user-images.githubusercontent.com/4972345/32221150-b4312898-be34-11e7-94c1-2056271e0709.png)

I ended up applying https://github.com/hydrabolt/discord.js/commit/96ce1b0945a0c24f3c263d33f48e39ed22753767 manually to my installation which fixed it.

**Comment by Dev-Yukine** [comment]
are you sure? because i ended up fixing it by using sodium instead libsodium on stable and it worked out for me. please make sure that you didn't installed libsodium-wrappers v0.7+

**Comment by Jeffroiscool** [comment]
I'm pretty sure it's not installed as you can see in the pastebin. It doesn't matter in the end when the fix goes live on npm though but just knowing it can occur without libsodium can be good.
