### ISSUE TITLE
How many times per minute can I change the bots game?

### ISSUE THREAD

**Issue by PlayBy** [hydrabolt/discord.js#2067]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

I am trying to change the game every 5 seconds, but it will only change like 5 times. is there a limit on how many times per minute you can change the bots game?

**Further details:**

- discord.js version:
- node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
