### ISSUE TITLE
Presence Update stops firing on rate limit without a way to catch it

### ISSUE THREAD

**Issue by JMTK** [hydrabolt/discord.js#2075]
**Please describe the problem you are having in as much detail as possible:**
When a user's presence is changed in quick succession, the `presenceUpdate` event stops firing and the `rateLimit` **does not** fire in this scenario.

**Include a reproducible code sample here, if possible:**
```js
function userIsStreaming(u) {
    let g = u ? u.presence.activity : null;
    return Boolean(g && g.type === "STREAMING");
}

mybot.on('presenceUpdate', (oldUser, newUser) => {
    console.log("Presence update");
    let isNewStreaming = userIsStreaming(newUser);
    let isOldStreaming = userIsStreaming(oldUser);
    console.log(newUser.user.tag, isOldStreaming, isNewStreaming);
});

mybot.on("debug", (e) => { console.log("DEBUG>", e); });
mybot.on("guildUnavailable", (e) => { console.log("GUILD UNAVAILABLE>", e); });
mybot.on('rateLimit', () => { console.log("Rate limited>"); });
mybot.on("warn", (e) => {
    console.log(shardLogPrefix + "WARN>", "(" + moment().format('MMMM Do YYYY, h:mm:ss a') + ")", e);
});
mybot.on("unknown", (e) => {
    console.log(shardLogPrefix + "UNKNOWN>", "(" + moment().format('MMMM Do YYYY, h:mm:ss a') + ")", e);
});
```
Here's a quick gif I took of it in action, the booleans represent the old/new member streaming being true or not. 
https://i.imgur.com/NHMTUB9.gifv

**Further details:**

- discord.js version: (v12) https://github.com/hydrabolt/discord.js/commit/1a8e8c7a67b59242537a6c97e383bc6aa4e8c8dd
- node.js version: v8.1.3
- Operating system: Debian
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:
https://github.com/hydrabolt/discord.js/commit/1a8e8c7a67b59242537a6c97e383bc6aa4e8c8dd

**Comment by SpaceEEC** [comment]
The rate limit you are experiencing occurs in your discord client, not the bot.
Also the rate limit event only fires for http rate limits, not for the gateway rate limit(s).

**Comment by JMTK** [comment]
Fair enough. Though when it gets to this point, my Discord client is "correct" in that I'm not streaming or streaming at that point, but I can't figure out how I can make sure the bot isn't reporting the status incorrectly when someones client rate limits them.
