### ISSUE TITLE
Unhandled "error" event

### ISSUE THREAD

**Issue by dave909904** [hydrabolt/discord.js#2077]
**Please describe the problem you are having in as much detail as possible:**
After my bot has been running for around 30 minutes, it stops with this error:
![capture](https://user-images.githubusercontent.com/16968381/32139621-8e22af9e-bc0b-11e7-804c-b7d22d95406a.PNG)
I'm fairly certain it isn't my code because I have never touched events.js
I included lines 182-185 below
**Include a reproducible code sample here, if possible:**
```js
/**
 * Expose
 */
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.8.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low, this is a fairly minor error that seems to be confined to me

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment]
looks like your pc lost internet, nothing really to do about that

**Comment by dave909904** [comment]
@devsnek probably was. I live in an area with Comcast lines from the 80's. You can imagine how stable that is.
