### ISSUE TITLE
Music does not play on latest indev

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#208]
Some time after Commit https://github.com/hydrabolt/discord.js/commit/538df5f76b7022cf2fa49f3a478f1be16ef67411 my music bot stops making sound. eg, it fails at playing music silently. 

I am playing music using ytdl to play a stream. testing on debian with FFMPEG I compiled around January or so, it was latest at the time..

**Comment by macdja38** [comment]
Just a little note, playing music is still working in https://github.com/hydrabolt/discord.js/commit/7ec859d5a16adda994c4855d3481a58234359381, I believe if anything it's commit https://github.com/hydrabolt/discord.js/commit/4e58de8cd6547bc205cce3d81744edbd9935dd11 that breaks it.

**Comment by abalabahaha** [comment]
I'm already aware of the error. It has been reported before you submitted the issue.

**Comment by abalabahaha** [comment]
Someone said ef679e8 worked
