### ISSUE TITLE
voiceChannel.setUserLimit(0) is useless

### ISSUE THREAD

**Issue by Pigpog** [hydrabolt/discord.js#2082]
Setting the userLimit of a voice channel to 0 does absolutely nothing. It doesn't change the userLimit. When using the below code sample, it logs that it changed the userlimit to the current userlimit.

```js
voiceChannel.setUserLimit(0)
  .then(vc => console.log(`Set user limit to ${vc.userLimit} for ${vc.name}`))
  .catch(console.error);
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.8.1
- Operating system: Linux Mint 18.1
- Priority this issue should have – please be realistic and elaborate if possible: 2/5 because it isn't completely breaking (workaround: set it to 99) but it is still a bug and shouldn't be this way.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash: 29a81ea

**Comment by Dev-Yukine** [comment]
this error works on newest master btw it seems to be fixed some commits ago
