### ISSUE TITLE
Discord.RichEmbed() not working.

### ISSUE THREAD

**Issue by grekxx** [hydrabolt/discord.js#2084]
Like the title says, my richembed command is not working. The bot starts up and other commands work, but my command what contains richembed doesnt work.

--THE CODE--

client.on('message', message => {
  if (message.content === ";about") {
  const embed = new Discord.RichEmbed()
  .setAuthor('Sagoui Bot', 'http://vignette2.wikia.nocookie.net/truecapitalist/images/f/f7/Discord_logo1600.png/revision/latest?cb=20170221133121')

.setColor(0x00AE86)
.setDescription('lol, embed not working.')
.setFooter('© grekxx_', 'https://cdn.discordapp.com/avatars/277455846336626689/2b146729658f579efeb3fc5d699fcb83.png?size=2048')

.setTimestamp()
.addField('Field1',
  'Example field1')
}
});

Can someone help me please?

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
