### ISSUE TITLE
TextChanne#send and User#send option split isn't working.

### ISSUE THREAD

**Issue by MrJacz** [hydrabolt/discord.js#2086]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
https://hastebin.com/yuwizidevo.js

**Further details:**
Basically when trying to use `msg.author.send("string here", { split: { char: '\u200b' }});` i get this error https://hastebin.com/qutofamefu.md and when i requrie the Util#splitMessage function and do it manually it works 😒 
- discord.js version: v12.0.0-dev
- node.js version: 8.8.1
- Operating system: Windows 10 64bit
- Klasa Version: v0.4.0-dev
- Priority this issue should have – please be realistic and elaborate if possible: Medium 

- [ ] I found this issue while running code on a __user account__
- [ x ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Should be fixed with #2085, feel free to try it out and leave an approve if it's working, or tell me if not 👀

**Comment by MrJacz** [comment]
Will do in the next hour or so 👍

**Comment by MrJacz** [comment]
@SpaceEEC Your PR didnt work 🤔

**Comment by MrJacz** [comment]
Wait dont mind me just NPM not installing your pr/fork

**Comment by MrJacz** [comment]
Works fine!
