### ISSUE TITLE
Deprecation warning for send: thinks i'm using sendMessage

### ISSUE THREAD

**Issue by olvrb** [hydrabolt/discord.js#2087]
Upon sending a message with message.channel.send, i get the following warning:

`DeprecationWarning: TextChannel#sendMessage: use TextChannel#send instead`

And yes, i'm using the latest version of discord.js 11.2.1.

I'm running this on a bot account, if that's important.

**Comment by Dev-Yukine** [comment]
this warning will **only** occour if you use sendMessage somewhere, just replace **all** sendMessage with send 👀
