### ISSUE TITLE
Guild.addMember is broken

### ISSUE THREAD

**Issue by dragonbane0** [hydrabolt/discord.js#2089]
**Please describe the problem you are having in as much detail as possible:**

Guild.addMember despite being called with a valid user ID, auth token and invoked from a bot where said user authenticated himself with the guilds.join scope, returns an error and doesnt add the member to the server:
```
TypeError: Cannot read property 'id' of undefined
    at Object.Member (C:\nodecg098\node_modules\discord.js\src\util\Constants.js
:154:22)
    at RESTMethods.putGuildMember (C:\nodecg098\node_modules\discord.js\src\clie
nt\rest\RESTMethods.js:469:64)
    at Guild.addMember (C:\nodecg098\node_modules\discord.js\src\structures\Guil
d.js:509:37)
```

As far as I can see line 469 in RESTMethods.js is incorrect by specifying the user with user.id instead of just user (since Constants.js does memberID.id again which is then undefined). On first glance   getGuildMember has the same issue. Replacing user.id with user fixed this issue for me and the member was then correctly added to my server

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.7.0
- Operating system: Windows 7, 64 bit
- Priority this issue should have – medium

**Comment by Kupuyc** [comment]
Bug still actual for 11.3.2. Is it ok?

**Comment by winterwings** [comment]
Just for info: 11.4.0 also had this error, but 11.5.0 works fine!
(Using snowflake method.)
