### ISSUE TITLE
Detecting Speaking

### ISSUE THREAD

**Issue by Aleksanderp** [hydrabolt/discord.js#2095]
So i was looking over the API documentation and i didn't see anything regarding possibility of getting or ever checking if a user is speaking in a channel. Under Voice section there was something labeled as coming soon. So if anyone knows how could i get all the users speaking in a given channel. I was trying to make a bot that would auto mute users who would spam voice chat (using it for too long), also a bit more advanced if you can make out how loud the voice is (not how loud the discord user has set it to be, just what the speakers mic is outputting) - that might be out of reach tho.

Hope i didn't just make a really big mistake and miss it somewhere in the documentation.

Thanks for any response! :+1:

**Comment by hydrabolt** [comment]
Docs here https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=speaking
