### ISSUE TITLE
DiscordAPIError: Unknown Webhook

### ISSUE THREAD

**Issue by Tvde1** [hydrabolt/discord.js#2098]
**Please describe the problem you are having in as much detail as possible:**
Whenever I try to use my command (which used to work a few master commits ago), I get this error now:
```
Uncaught Promise Error:
DiscordAPIError: Unknown Webhook
     at item.request.gen.end (/app/node_modules/discord.js/src/rest/handlers/RequestHandler.js:78:65)
     at then (/app/node_modules/snekfetch/src/index.js:204:21)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)
```
**Include a reproducible code sample here, if possible:**
```js
// user is an User object.
let webhook = await message.channel.createWebhook(user.username, { avatar: user.displayAvatarURL() });

webhook.send(text.join(' '));
webhook.delete();
```

**Further details:**

- discord.js version:
- node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [X] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash: `62544905a06152ca769c4e6d5f16337b134ac67e`

**Comment by devsnek** [comment]
you need to await webhook.send or it will run at the same time as delete and cause a race condition

**Comment by Tvde1** [comment]
oof thanks I'll try it

**Comment by Tvde1** [comment]
That fixed it, thanks!
