### ISSUE TITLE
Support Rich Presence ?

### ISSUE THREAD

**Issue by HelloEdit** [hydrabolt/discord.js#2099]
Hello !

I just received the Discord popup announcing [Rich Presence](https://youtu.be/Ss-IvNjl7JQ) support, I wanted to know if the compatibility with Discord. js would be supported in the near future!

Thanks !

**Comment by bdistin** [comment]
Although this may seem like an enhancement suggestion, Rich Presence isn't supported on bots. It's only for gamebridge/discord sdk. This is not something that can be implemented.

![img](https://puu.sh/yj3bH/33b8bee2e6.png)

**Comment by HelloEdit** [comment]
@bdistin Oh, I thought it was an update to the Game property.... We could have created fantastic things, but I'll wait for Discord to support this feature ! Thank

**Comment by RumbleFrog** [comment]
I recently came across this: https://github.com/Favna/Discord-Self-Bot/blob/c0ccf539835e889a4a16281be4da8cb41b5f6eac/src/discordSelfBot.js#L61-L88

I wonder if it's possible now?

**Comment by dragonfire535** [comment]
It is possible to set a Rich Presence using `setPresence`. However, this will not show on bots.

**Comment by devsnek** [comment]
@RumbleFrog you'll be banned from discord for
1) using a selfbot
2) sending rich presence like that

if you want to use rich presence, discord.js has an official rpc extension at https://npmjs.org/discord-rpc

**Comment by RumbleFrog** [comment]
@dragonfire535 Yes, I know it's only viable for self-bots.

@devsnek Thanks for the resources.
