### ISSUE TITLE
Discord.js Async Await Problem

### ISSUE THREAD

**Issue by stevenvr-0548** [hydrabolt/discord.js#2109]
I am having an issue where the async and await are constantly throwing an error:

![capture](https://user-images.githubusercontent.com/31238961/32822207-ad13d91c-c9d7-11e7-8852-fc1d219fc35a.PNG)

While there's nothing wrong with my code:

Here's the async part:

```js
client.on("message", async message => {
           // commands
});
```

And here's the command with the await part:

```js
    if(command === "mutual") {
        if(args.length < 1)
            return message.reply('Please provide a name of a Discord server you are in!');
        
        const query = args.join(' ').toLowerCase();
        const guild = client.guilds.find(guild => guild.name.toLowerCase() === query);
        
        if(!guild)
            return message.channel.send('That server could not be found!');
        
        const mutual = client.users.filter(user => inGuild(message.guild, user) && inGuild(guild, user));
        
        const {url} = await client.utils.gistUpload(mutual.map(user => `-${user.username}`).join('\n'), 'txt');
        
        message.channel.send({
            embed: client.utils.embed(`Mutual members of ${guild.name}`, limitTo(mutual.array().map(user => user.username), 25, ', '), [
                {
                    name: 'Full List',
                    value: url
                }
            ])
        }).delete(30000);
    }
```

If anyone is able to help me with this, that would be amazing! Thanks in advance

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the Discord server instead of opening an issue – you will get redirected there anyway.

**Comment by stevenvr-0548** [comment]
Beste Kampradio Luisteraar,

Uw bericht is succesvol ontvangen, het bericht wordt behandeld, u krijgt zo spoedig mogelijk antwoord.

Met Vriendelijke Groet,

Team Kampradio

**Comment by DakshMiglani** [comment]
Hello @stevenvr-0548 , you cannot use async-await with arrow function, you have to use the function keyword. Like this:

```

client.on("message", async function(message) {
           // commands
});

```

**Comment by Tvde1** [comment]
@DakshMiglani's answer won't work.
Update node...

**Comment by DakshMiglani** [comment]
@Tvde1 I assumed that he's using Node 8.x.x, and even then arrow functions do not work with async.

**Comment by Tvde1** [comment]
If he did have the right node version, he wouldn’t get this error.

**Comment by DakshMiglani** [comment]
Well, He can always use babel.
