### ISSUE TITLE
The reaction collectors break when user sends message

### ISSUE THREAD

**Issue by Wodki** [hydrabolt/discord.js#2114]
**Please describe the problem you are having in as much detail as possible:**
When using reactions in DMs if a user sends any message after the message that the reactions are on, the collectors are not collecting anything at all by clicking the reactions. After the time limit has passed though, they do end normally.

**Include a reproducible code sample here, if possible:**
```js
collector = msg.createReactionCollector((reaction, user) => user.id === author.id, { time: 60 * 1000}); 
collector.on('collect', r => { ... });
collector.on('end',(collected, reason) => { ... });
```
Or
```js
msg.awaitReactions((reaction, user) => user.id === author.id, {max: 1, time: 60*1000, errors: ['time'] })
 .then(collected => console.log(`collected anything`)
 .catch(collected => {
    console.log(`Done collecting.`);
});
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: v8.9.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: High

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Drahcirius** [comment]
The reason you're not getting logs in a DM is because your filter checks for the `member.id`, but there is no member associated with DMs. If you use `author.id` instead, it would work.

**Comment by Wodki** [comment]
Perhaps that was my mistake since I used the member keyword, but I its actually author. Let me edit it. Also to add a bit more into the description, as I mentioned if I send any message after the message with the reactions it collects nothing, but if I dont it works flawlessly, Therefore its not that it has to do anything with my filters, or my code, but more than likely with discordjs.

**Comment by rei2hu** [comment]
I believe this is a bug with 11.2.1 where the DM channel's message collection only caches a single message for some reason. I can't personally say this is the exact bug, but the person I was helping out said that this was the case after a bit of debugging. I then asked said person to try it on master and they said it worked fine.

**Comment by Lewdcario** [comment]
This should be fixed if you run `npm i hydrabolt/discord.js#11.3-dev`.
