### ISSUE TITLE
Bot crashes when Discord returns bad server value

### ISSUE THREAD

**Issue by blackjackkent** [hydrabolt/discord.js#2124]
**Please describe the problem you are having in as much detail as possible:**
I'm running a Discord bot as a long-running process (under forever.js, if that's relevant) on a Linux box...I've noticed that occasionally the thing will just die without any evident reason behind it. Finally managed to have a look at an error log for one of these crashes, which reads as follows:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND gateway.discord.gg gateway.discord.gg:443
    at errnoException (dns.js:53:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
```
My (cautious) interpretation of the above is that the discord.js framework asploded on one of Discord's recent server hiccups, but it's possible this isn't correct and there's an issue on my end. I'd appreciate any guidance or opinions on where the problem lies. :)

**Include a reproducible code sample here, if possible:**
My bot implementation is not very elaborate, but can be found at https://github.com/blackjackkent/bjkbot.

**Further details:**

- discord.js version: 11.2.1 (With Commando 0.9.0)
- node.js version: 8.6.0
- Operating system: Ubuntu Linux 4.10.0-38-generic
- Priority this issue should have – please be realistic and elaborate if possible: Probably not inordinately high (unless other people are experiencing the same issue), but it does seem like there's potentially a defensive programming issue here if I'm interpreting things correctly, which might be important given Discord's occasional instability recently.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
I'm not going to review your complete code, but there's several things wrong with it.

First of all you should have an event listener for the `warn` and `error` event. The error is telling you that too.
Second: Please do not put your message handler into the ready event, that's just screaming for issues down the line.

**Comment by iCrawl** [comment]
Since it has been 21 days without an update I am going to close this issue.
