### ISSUE TITLE
Multiptle Voice Channels

### ISSUE THREAD

**Issue by aequasi** [hydrabolt/discord.js#214]
Keeping a list of things that need to be updated:

`client.voiceConnection` should be an array of `VoiceConnection`'s
`client.joinVoiceChannel` should add to the array
`client.leaveVoiceChannel` should take a channel resolvable

**Comment by kdparker** [comment]
This is impossible. Discord itself only allows a user to be in one channel at a time. If you need to get around this, you'll have to have more than one bot.

**Comment by aequasi** [comment]
Not anymore. Bot accounts can be in multiple

Aaron Scherer




On Fri, Mar 18, 2016 at 9:07 PM -0700, "Keegan Parker" <notifications@github.com> wrote:












This is impossible. Discord itself only allows a user to be in one channel at a time. If you need to get around this, you'll have to have more than one bot.

**Comment by abalabahaha** [comment]
@kdparker the shiny new (beta) bot accounts don't have voice connection limits (but still one voice channel per server)
