### ISSUE TITLE
The package erlpack does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by wipsdafox** [hydrabolt/discord.js#2141]
**Please describe the problem you are having in as much detail as possible:**
When running npm install, it gives the errors "The package erlpack does not satisfy its siblings' peerDependencies requirements!" and "Peer discord.js@11.2.1 wants erlpack@hammerandchisel/erlpack"

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 6.12.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: medium, prevents install

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
This only affect stable as of now, and the reason is because hammerandchisel switched organization name to discordapp.

So if you want to use erlpack while on 11.2.1 just install it with `npm i discordapp/erlpack` and you'll be good to go.

**Comment by falstro** [comment]
I'm not sure how to interpret this, doing a fresh npm init; npm install discord.js fails with the above message - except with "erlpack@discordapp/erlpack", doing a fresh checkout of 11.3-dev and npm install /patch/to/discord.js also fails with the same message for me. There's only the single line so I don't get where the contradiction/incompatability is. Doing npm install discordapp/erlpack works fine so it can find it alright, but it still won't allow me to install discord.js. What am I missing?

Thank you for your time.
