### ISSUE TITLE
Can't add items to shop

### ISSUE THREAD

**Issue by The-Evil-Pig-YT** [hydrabolt/discord.js#2147]
Hi!
Recently, I have been having a problem, where when I make shop item, it doesn't go on the shop.
If you have a solution, please help me. I really need help, as it is affecting my server a lot.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by hydrabolt** [comment]
does our issue tracker get worse everyday or something

**Comment by professor-cat** [comment]
setup GitHub bot that will track if issue follows issue template and user has filled some info. If it doesn't follow issue template give some useful URLs like where to ask for help and close issue with lock.
Also, it would be better if it ignored contributors.

That should stop 99% of issues like this

**Comment by hydrabolt** [comment]
hm that sounds like a good idea tbh
