### ISSUE TITLE
"messageUpdate" fails to fire when a private message is edited.

### ISSUE THREAD

**Issue by kayabaNerve** [hydrabolt/discord.js#2148]
"messageUpdate" fails to fire when a private message is edited.

```js
client.on("messageUpdate", (omsg, nmsg) => {
    //Handle Message
});
```

- discord.js version: 11.2.1
- node.js version: v9.2.0
- Operating system: Ubuntu 16.04

- [x] I found this issue while running code on a __BOT user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
Can you try running `npm i hydrabolt/discord.js#11.3-dev` and see if that fixes the issue for you?

**Comment by kayabaNerve** [comment]
That fixed it! Thanks.

**Comment by Alpacatty** [comment]
This exact same thing is happening for me on 11.3.2 (Node 9.10.1)--the event just doesn't fire at all when a DM is edited.
