### ISSUE TITLE
Add new bot API stuff

### ISSUE THREAD

**Issue by abalabahaha** [hydrabolt/discord.js#215]

**Comment by meew0** [comment]
Just making a comment here to track the progression
- [x] Multi-server voice
- [x] 429 handling
- [ ] Gateway v4
  - [x] Guild streaming (backported to v3)
  - [ ] Op 9 handling
  - [ ] Two-way heartbeats
  - [ ] *[Roadmap]* v5 (only op10 handling)
- [x] *[Roadmap]* No more read states - we don't need to do anything about this as we were never handling them at all
- [ ] *[Roadmap]* Sharding
- [x] *[Roadmap]* New rate limits (nothing to be done here either)
