### ISSUE TITLE
Setting size on animated avatar makes it stop moving.

### ISSUE THREAD

**Issue by BlackWolfff** [hydrabolt/discord.js#2152]
**Please describe the problem you are having in as much detail as possible:**
This is more discord bug than library.
If url for animated avatar have `?size=1024` (or any size) so it's 'resized', it just stops being animated, in discord preview or rich embeds, but it works in browsers...
It is really annoying because there's no way to tell if avatar is animated or not before actually getting it with .avatarURL and then check if it starts with `a_` (or ends with `.gif`), so if you want to get best avatar resolution you have to set size option, which breaks gifs.
The way to fix it is to not allow size option in animated avatars at all (set size option to `false` if it is animated etc.)
But that makes other problems, what if you want to resize animated avatar? Resizing works (you can make smaller/bigger avatar) but it breaks animation... idk

~~and this is my first github issue, my english is probably terrible, please don't hurt me~~
**Include a reproducible code sample here, if possible:**
```js
/**
You must have nitro and gif avatar for this example to work, 
or you can test it on someone else with nitro.
`msg` is of course Message object from eg. 'message' event
*/
let thisWillAnimate = msg.author.avatarURL()
let thisWontMove = msg.author.avatarURL({size: 1024}) // any size will do
msg.channel.send(`${thisWillAnimate}\n${thisWontMove}`)
```

**Further details:**

- discord.js version: 12.0.0-dev
- Priority this issue should have – please be realistic and elaborate if possible:
  idk, It's a bit annoying but won't crash anything.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iDroid27210** [comment]
This problem isn't really related to discord.js but I know people can be confused.

Images on Discord travel through a CDN (Content Delivery Network), it can happen for some avatars that the GIF isn't proceeded correctly and breaks it.
The problem in your case is that the avatar isn't made to be a GIF in a size of 1024px so the avatar does not move.
There's no real solution imo for this problem... it's more a Discord-related problem.

**Comment by Lilwiggy** [comment]
Yeah it's discord'd CDN just being a bit dumb. I found a fix of just adding &.gif to the end of the url and it animated properly then. Basically if the URL doesn't end in .gif the cdn won't animate it, and because of the resize it won't anime cause it doesn't end in .gif. Adding &.gif to the end of the URL fixes this issue.
