### ISSUE TITLE
Sending attachment with content sends ONLY attachment

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [hydrabolt/discord.js#2156]
**Please describe the problem you are having in as much detail as possible:**
While you sending a message with content and attachment, djs sends only the attachment without the content.

**Include a reproducible code sample here, if possible:**
```ts
await msg.channel.send("Here's your file", new MessageAttachment(Buffer.from(result), `${Date.now()}.txt`));
```

**Further details:**

- discord.js version: latest from Github
- node.js version: `v9.2.1`
- Operating system: `Linux 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` / `Ubuntu 17.04 zesty`

- [ ] I found this issue while running code on a __user account__
- [x] I have tested the issue on latest master, commit hash: 20689a51a1c37ff7b7edaff357621640d68bac67

**Comment by lloti** [comment]
> discord.js latest
> `Attachment`

I tested on master with `MessageAttachment` and it's working fine.

**Comment by KingDGrizzle** [comment]
Unless you import `MessageAttachment` as Attachment in your code (ala `const { MessageAttachment: Attachment } = require("discord.js")`), this works for me.
Make sure result isn't actually null or whatnot.

*By the way, you forgot a `$` in your template for the file name.*

**Comment by Soumil07** [comment]
This does not look like D.js master as it's MessageAttachment, but I've tested the same code on master and can confirm the same issue. :thumbsup:

**Comment by DaFri-Nochiterov** [comment]
@Soumil07 ah, that's because the example code comes from my actual code, where I imported `MessageAttachment` as `Attachment` as because I'm lazy to change all the.. 1 reference using `Ctrl`+`H` 🤦‍♂️ 
Anyway, fixed. As well as the wrong filename mentioned by @KingDGrizzle. 👍
