### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by NitWitPotato** [hydrabolt/discord.js#2159]
ReferenceError: bot is not defined
    at Object.<anonymous> (C:\Users\(my name)\Documents\Code\DiscordBot\index.js:7:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

What do I do? The bot appears as offline.

**Comment by olvrb** [comment]
This is a question for the [discord server](https://discord.gg/bRCvFy9).

**Comment by hydrabolt** [comment]
if you people don't start reading the damn template I'm going to pull an Alex Hultman and just disable the issue tracker

**Comment by hydrabolt** [comment]
seriously do you not even think to read before you mindlessly post your error

**Comment by hydrabolt** [comment]
nearly a quarter of our issues (probably more since the old issues aren't really documented) are people posting their issues which aren't a fault of discord.js so you can see why this is pissing me off

**Comment by NitWitPotato** [comment]
@hydrabolt stop being so toxic!

**Comment by hydrabolt** [comment]
I'm sorry for lashing out at you, but in the future could you please read the template before posting? We've been trying to keep our issue tracker just for issues and if everyone could play a more active role in that, it'd be helpful.

**Comment by NitWitPotato** [comment]
@hydrabolt Alright, I apologize for calling you toxic and not reading the template.
