### ISSUE TITLE
Bug: Missing initializer in destructuring declaration

### ISSUE THREAD

**Issue by gmedeadlystrike** [hydrabolt/discord.js#2162]
**Please describe the problem you are having in as much detail as possible:**
Attempting to use ShardingManager#BroadcastEval will result in this error

```
{
	SyntaxError: Missing initializer in destructuring declaration
	at Client._eval( ~\discord.js\src\client\Client.js: 410: 17)
	at ShardClientUtil._handleMessage( ~\discord.js\src\sharding\ShardClientUtil.js: 130: 76)
	at emitTwo(events.js: 125: 13)
	at process.emit(events.js: 213: 7)
	at emit(internal / child_process.js: 774: 12)
	at _combinedTickCallback(internal / process / next_tick.js: 141: 11)
	at process._tickCallback(internal / process / next_tick.js: 180: 9) name: 'SyntaxError'
}
```

**Further details:**

- discord.js version: Master https://github.com/hydrabolt/discord.js/commit/443961ce43bc37dbe8705e42a28afcfaf8e94a7d (Latest as of post time)
- node.js version: 8.9.x LTS
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [x] I have also tested the issue on latest master, commit hash:

**Comment by Lewdcario** [comment]
Sounds like you goofed up in your `broadcastEval`. Especially since it's a syntax error, as the error message indicates. I can't even reproduce such an error on the latest master branch.

**Comment by gmedeadlystrike** [comment]
@Lewdcario alright, was redoing my sharding manager to the new standard after i notice that the class was changed it in recently. Will test a old eval script that works on production bot. I know in the previous version there was a legit error on malformed eval statements

Will check and report back

**Comment by gmedeadlystrike** [comment]
@Lewdcario  Alright - malformed eval statement was indeed the case, appreciate the quick responce, I will see about making a PR myself to add back in a userfriendly error for bad eval statements instead of the fatal error above.

**Comment by 1Computer1** [comment]
Uhh no, the error is specific to the syntax error with your code.

**Comment by gmedeadlystrike** [comment]
@1Computer1  not sure i follow that, I removed all deconstructing from my manager, and have non in my eval script, and still received the same error
