### ISSUE TITLE
Guild#createChannel() and VoiceChannel#edit(): bitrate error

### ISSUE THREAD

**Issue by Jisagi** [hydrabolt/discord.js#2163]
**Please describe the problem you are having in as much detail as possible:**
Both Guild#createChannel() and VoiceChannel#edit() fail because of the same error.
```
DiscordAPIError: Invalid Form Body.
bitrate: int value should be greater than or equal to 8000.
```
This is already fixed on 11.3-dev but not on master. See Issue https://github.com/hydrabolt/discord.js/pull/2144 for reference.
Would be nice if this is fixed on master, too.
The only workaround is not using options at all on creation and setting everything after creation.

**Include a reproducible code sample here, if possible:**
```js
<guild>.createChannel('name', 'voice', { bitrate: 96 })
<VoiceChannel>.edit({ bitrate: 96 })
```

**Further details:**

- discord.js version: master
- node.js version: 8.9.1
- Operating system: Windows 7 & debian 8.2
- Priority: Medium - It is possible to create a voice channel by not parsing any options and later setting every manually but that is more than ugly if you have the possibility to parse everything (or at least most of it) on creation.

- [ ] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash: 443961ce43bc37dbe8705e42a28afcfaf8e94a7d

**Comment by KingDGrizzle** [comment]
I think that Discord.js expects you to give the actual bitrate in bits rather than kbs. Correct me kf I'm wrong tho.

**Comment by Jisagi** [comment]
> I think that Discord.js expects you to give the actual bitrate in bits rather than kbs. Correct me if I'm wrong tho.

That is correct, but the normal behaviour would be to use kbps. At least i thought so.
After checking the documentation for master again i found this:

\<guild>#createChannel(): `Bitrate of the new channel in bits`
\<VoiceChannel>#edit(): `The bitrate of the voice channel`
\<VoiceChannel>#setBitrate(): `Sets the bitrate of the channel (in kbps)`

First says in bits, second one nothing and the third one in kbps. Even more confusing. Either change the methods (createChannel & edit) to kbps or everything else to bits.

**Comment by KingDGrizzle** [comment]
Ok, granted, the edit for bitrate is misleading (needs to say its meant to be in bits not kbs), I disagree with all methods going kbps. edit is meant to be used only by people who *know* what they're doing (as it doesn't do much handling of the data, it assumes it's right). This is why utility functions, like setName or setBitrate take a more user-friendly input, and make it a "Raw" input, if you will.

I agree with VoiceChannel#edit (and with that, ChannelData) not stating it needs to be in bits not kbps (and I'm going to fix that right now :3), but I disagree with making everything in bits or kbs.

**Comment by Jisagi** [comment]
Sounds ok for me i guess if the documentation clearly states which uses bits and which kbps. Since you already said you are gonna fix the the edit methods documentation i'm closing this issue.

Thanks for the explanation.
