### ISSUE TITLE
Unhandled promise rejection when content is over length maximum

### ISSUE THREAD

**Issue by vityavv** [hydrabolt/discord.js#2166]
**Please describe the problem you are having in as much detail as possible:**
Sometimes, since I'm using some random stuff, I accidentally send messages that are 2000 or longer. Then, the logs go something like this:
```(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 6.11.4 or whatever Heroku runs (maybe 8.6 now? I dunno)
- Operating system: Whatever Heroku does.
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by KingDGrizzle** [comment]
How is this an issue? It clearly states the message is too long. Discord.js doesn't automatically handle your input if it's too long, you need to use split for that.
