### ISSUE TITLE
`Client.channels` does not include DMs after restart

### ISSUE THREAD

**Issue by adri326** [hydrabolt/discord.js#2170]
**Please describe the problem you are having in as much detail as possible:**

When querying channels from `Client.channels`, I noticed that the DM channels weren't listed until a message gets sent in one of them

**Code sample:**
```js
var Discord = require("discord.js");
var client = new Discord.Client();
client.login(token); // Log in with a token or whatever method you prefer

client.on("message", context => {
  console.log();
  console.log(Array.from(client.channels.filter(channel => channel.type == "dm").keys()).join("\n")); // Filter the DM channels, then list their ID
}
```
When the bot receives a DM, it'll start logging this DM channel's ID. However, if the bot restarts, it will no longer log these DM channels (until it receives a DM)

**Further details:**

- discord.js version: 11.2.1
- node.js version: 9.2.0
- Operating system: Antergos Linux release 17.10 (ISO-Rolling)
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I found this issue while running code on a**n** user account
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by bdistin** [comment]
see discordapp/discord-api-docs#184 not something d.js can fix.
