### ISSUE TITLE
awaitMessages() breaking with a filter

### ISSUE THREAD

**Issue by Soumil07** [hydrabolt/discord.js#2172]
**Please describe the problem you are having in as much detail as possible:**
TextChannel#awaitMessages does not work when a filter function is passed as the first arg. 

**Include a reproducible code sample here, if possible:**
```js
const check = await msg.channel.awaitMessages(m => m.author.id === msg.author.id, { time: 10000 }) 
console.log(check) 
```

The above code returns an empty collection. 

**Further details:**

- discord.js version: master commit 1598efa
- node.js version: 8.6.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [ ] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Is the channel a dm or guild channel?

Also for clarity: The issue is that you actually send a message which you expect to be collected?
And not that you are sending no messages and expecting the promise to reject or similar.

Can you also please fill in an actual commit hash?
I assume it's _current_ latest, which will be outdated the second something new will be comitted.

**Comment by Soumil07** [comment]
It was tested on a guild channel.

And yes I am sending messages. Using it without a filter, like

```js
await msg.channel.awaitMessages(() => true, { time: 30000 })
``` works as usual.

I'm on commit 1598efa

**Comment by kyranet** [comment]
I cannot reproduce this issue in the music-rewrite branch (assuming the changes in the MessageCollector are minimal or non-existent with latest master). That method works in both DMs and guilds. Please fill the details to match this repository's issue template (in this issue's description, and full commit hash). I might test it on latest master later when I come back home.

**Comment by dragonfire535** [comment]
Can't reproduce on latest master.

**Comment by Soumil07** [comment]
https://cdn.discordapp.com/attachments/339944237305036812/390829487484436482/Screenshot_2017-12-14-11-56-35-720_com.discord.png

This is on latest master.

**Comment by Soumil07** [comment]
Closing this because I found out it was related to the framework I use and it has been fixed.
