### ISSUE TITLE
How do I make my bot say something when someone mentions it?

### ISSUE THREAD

**Issue by YeeSaur** [hydrabolt/discord.js#2176]
I want my bot to say something when someone mentions it (like "@PictureBot hi")

This is my current code:
const Discord = require('discord.js');

const bot = new Discord.Client();

bot.on('ready', () => {
	console.log("Online");
});

bot.on('message', message => {
	if(message.author !== bot.user) return;

	if(message.content === "!cat") {
		message.channel.sendMessage("https://www.rd.com/wp-content/uploads/2016/02/06-train-cat-shake-hands.jpg");
	}
});

bot.on('message', message => {
	if(message.author !== bot.user) return;

	if(message.content === "@PictureBot") { // This doesn't work. Doesn't work either if I put the#1234
		message.channel.send("Hello!")
	}
})

bot.login("token");

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
