### ISSUE TITLE
Does not send multiple instances of the same file

### ISSUE THREAD

**Issue by vityavv** [hydrabolt/discord.js#2177]
**Please describe the problem you are having in as much detail as possible:**
I am creating a dice roller where you can roll the dice as many times as possible. The problem is that when I pass an array of files to the `channel.send` that includes multiple instances of the same file, it only sends one instance of sed file.

**Include a reproducible code sample here, if possible:**
```js
var files = [];
var total = 0;
var number = Number(message.content.substring(substring)) || 1;
for (var i = 0; i <= number; i++) {
	var result = Math.floor(Math.random()*6);
	total += result;
	files.push(["images/dice1.png", "images/dice2.png", "images/dice3.png", "images/dice4.png", "images/dice5.png", "images/dice6.png"][result]);
}
message.channel.send({files});
message.channel.send(`Total: ${total}`);
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 6.11.4
- Operating system: MacOS High Sierra
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
I can reproduce this, it looks like discord drops duplicated images, "duplicated" as the same file name.
Giving them a different file name works for me on stable and master.

In your case you could probably do something like this here before sending to ensure unique file names:
```js
files = files.map((file, index) => ({ attachment: file, name: `roll${index}.png` }));
```
This will will make an array of [FileOptions](https://discord.js.org/#/docs/main/stable/typedef/FileOptions) out of your array of strings.

**Comment by vityavv** [comment]
Thanks, that worked!
