### ISSUE TITLE
sendFile not working

### ISSUE THREAD

**Issue by crimeangothic** [hydrabolt/discord.js#2180]
Trying to make a bot send an image to the chat and I couldn't find an updated way to send it so i used the deprecated method sendFile. has it been completely removed?
TypeError: bot.sendFile is not a function
    at DiscordClient.<anonymous> (C:\chad-bot\index.js:45:9)
    at emitMany (events.js:147:13)
    at DiscordClient.emit (events.js:224:7)
    at DiscordClient.handleWSMessage (C:\Us

**Comment by lloti** [comment]
Yes, that is what deprecated means, to be removed

**Comment by devsnek** [comment]
use `.send({ files: [x] })` where `x` is what you would have put in `sendFile(x)`

**Comment by crimeangothic** [comment]
i got the error TypeError: bot.send is not a function. Here is the code that's causing the error. What am i doing wrong?

case 'a':
                bot.send({
                    to: channelID,
                    files: 'https://imgur.com/YJvvBpu'
                });
            break;

**Comment by devsnek** [comment]
thats not discord.js, we can't help you

**Comment by hydrabolt** [comment]
I'm just going to note that this is also a fault of the outdated documentation _still_ not being taken down despite multiple requests
