### ISSUE TITLE
on voiceJoin/voiceLeave bug

### ISSUE THREAD

**Issue by Otokiru** [hydrabolt/discord.js#219]
Sometimes, when I unmute/mute my mic, it will trigger the on voiceJoin and voiceLeave

Running node v5.9.0 on Ubuntu 14.04

//Edited
Forgot to state that my discordjs version is 6.1.0

**Comment by Programmix** [comment]
Is this bug still prevalent?

**Comment by Otokiru** [comment]
Yes it is

**Comment by GexoXYZ** [comment]
Probably related to #360 
```js
if (data.voice_states) {
	for (var voiceState of data.voice_states) {
		let user = this.members.get("id", voiceState.user_id);
		let channel = this.channels.get("id", voiceState.channel_id);
		if (user && channel) {
			this.eventVoiceJoin(user, channel);
		} else {
			this.client.emit("warn", "user doesn't exist even though READY expects them to");
		}
	}
}
```


https://github.com/hydrabolt/discord.js/blob/27a0361afcee2ffa5506d3cec534d3137c040f92/src/Structures/Server.js#L92-L102

**Comment by abalabahaha** [comment]
@Otokiru can you try getting the latest indev branch? I can't seem to reproduce

`npm install hydrabolt/discord.js#indev`

**Comment by Otokiru** [comment]
Ok, will try and monitor it.
Will let you know by EOD.
Thanks :)

**Comment by Otokiru** [comment]
Okay, i think its fixed now.
Thanks alot~ :)
