### ISSUE TITLE
Discord.js Mentions

### ISSUE THREAD

**Issue by Warido37** [hydrabolt/discord.js#2191]
# Hi, i want to make a `/kill` command but if somebody mentions someone then it sorta returns the ID or something... >> _- Warido killffed <@246972515442884619>_
Hi, i want to make a `/kill` command but if somebody mentions someone then it sorta returns the ID or something... >> _- Warido killffed <@246972515442884619>_
### `const commando = require('discord.js-commando');

class Kill extends commando.Command{
    constructor(client){
        super(client,{
            name : 'kill',
            group : 'kill',
            memberName : 'kill',
            description : 'Return a percentage of true love!',
        });
    }

    async run(message, args){
        if(args.length !== 0){
            if(message.mentions.length == 0){
                message.channel.sendCode('diff','- ' + message.author.username + ' killffed ' + args.toString());
                message.delete();
            }else{
                message.channel.sendCode('diff','- ' + message.author.username + ' killffed'  + args.toString());
                message.delete();
            }
        }
    }
}

module.exports = Kill;`

**Comment by Bacon1153** [comment]
Please ask your questions on the [Discord server](https://discordapp.com/invite/bRCvFy9)
