### ISSUE TITLE
Bot stopped playing in all the guild when stopping only in one guild

### ISSUE THREAD

**Issue by thomasxd24** [hydrabolt/discord.js#2192]
**Please describe the problem you are having in as much detail as possible:**

So at master branch, i have found that if the bot is playing something in multiple, if you end one of the dispatcher in one of the guild, of course the bot in that guild will end, but it also leads to the music that are playing stop too, its not really stop because if you reconnect yourself the bot continues to play the music. To explain in a simple way, let me show you a way to reproduce this with the code below:

- the bot is in at least 2 guild, we will say guild A and guild B here
- the user join a voiceChannel in Guild A, and execute !play so that the bot plays the music in Guild A
- the user then leave the voiceChannel in GuildA and joins the one in Guild B, and execute !play in GuildB so that the bot plays the music in Guild B.
- now the bot is playing in both GuildA and Guild B,
-now the user stays at Guild B with the bot and he execute !leave in Guild A where the bot is at
- so the bot is now stopped in Guild A but also at Guild B which is not normal. the user have to disconnect and reconnect to Guild B to hear the bot plays. So he is not really stopped

**Include a reproducible code sample here, if possible:**
```js
var Discord = require('discord.js');
const request = require("request");

var bot = new Discord.Client({});
bot.radio = new Discord.Collection();

    bot.on('ready', function (evt) {
        
    });
    bot.on('message', async msg => {
        if(msg.content == "!play")
        {
            var connection = await msg.member.voiceChannel.join()
            var	dispatcher = connection.playStream(request("https://radio.truckers.fm/"), { passes: 1 })
					.on('end', (rea) => {
						console.log(rea)
					})
					.on('error', err => {
						msg.reply('Error occurred in stream dispatcher:'+ err);
						console.log('Error occurred in stream dispatcher:'+ err)
                    });
            var radio = {
                voiceChannel : msg.member.voiceChannel,
                dispatcher : dispatcher
            }
            bot.radio.set(msg.guild.id,radio)


        }
        else if(msg.content == "!leave")
        {
            var radio = bot.radio.get(msg.guild.id)
            radio.dispatcher.end()
            radio.voiceChannel.leave()
            bot.radio.delete(msg.guild.id)
        }
    }
)
bot.login("MzkxMDAyNTAwNzA0MTA4NTQ5.DSLFtQ.uNoX4a51gFhrXtua-TnN5ZoTmGo")

```

**Further details:**

- discord.js version: 12.0.0 `master` commit : https://github.com/hydrabolt/discord.js/commit/1598efa0b8a22d6ca50e10bd15c215fcef27fcb5
- node.js version: v9.0.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
i think it would between medium and high because it can disturbing for other people to always reconnect to the voiceChannel.

- [x] I found this issue while running code on a bot for radio
- [x] I have also tested the issue on latest master, commit hash: 1598efa

**Comment by iCrawl** [comment]
This is a discord client issue.

**Comment by thomasxd24** [comment]
so i cant do anything for it, or do we have to wait for discord to fix this?
also is this affecting every bot?

**Comment by Dev-Yukine** [comment]
1.Yep you need to wait until Discord Fix that
2.Yes its affecting every bot

**Comment by SpaceEEC** [comment]
This here should be the relevant [trello card](https://trello.com/c/fVzj57Pa/181-bot-disconnecting-from-an-audio-server-in-mutual-guild-stops-playback-in-current-voicechannel).
