### ISSUE TITLE
client.guilds should return IDs not names.

### ISSUE THREAD

**Issue by 2E0PGS** [hydrabolt/discord.js#2201]
**Please describe the problem you are having in as much detail as possible:**

Discrepancies in the API and it's documentation. 
`client.guilds.array().sort();` returns names of servers however the documentation states it should return ID numbers "All of the guilds the client is currently handling, mapped by their IDs".

However `client.channels.array().sort();` returns ID numbers like it should.

**Include a reproducible code sample here, if possible:**
```js
	else if (terminalInput === '/channels') {
		console.log("Number of Available Channels: " + myClient.channels.size);
		var list = myClient.channels.array().sort();
		console.log("Available Channels: " + list);
	}
	else if (terminalInput === '/servers') {
		console.log("Number of Available Servers: " + myClient.guilds.size);
		var list = myClient.guilds.array().sort();
		console.log("Available Servers: " + list);
	}
```

**Example output from above code:**
```js
Number of Available Servers: 1
Available Servers: Test Gaming Server

Number of Available Channels: 23
Available Channels: <#100000000000000000>, 
```

I cleared the above output of identifying info so hence the IDs being a load of zeros and the name being "Test Gaming Server". I also removed the other IDs that are listed but there was 23 listed so `client.channels` works fine.

**Further details:**

- discord.js version: 11.2.1
- node.js version: v6.12.0
- Operating system: Ubuntu Linux 16.04 x64
- Priority this issue should have – please be realistic and elaborate if possible: 
Medium since documentation should reflect API directly.

**Comment by devsnek** [comment]
collection#array is an array of the items in the collection, so client.guilds.array() would be guild objects not names or IDs. the actual behavior you're seeing is Guild#toString which returns the name not id.

**Comment by 2E0PGS** [comment]
Yes but that does not explain this behavior both are collections and both should be similair in their behavior. It should return an array of IDs for both...

**Comment by devsnek** [comment]
nope. collections aren't arrays they are maps.
you can visualize a map a little like this:
```js
Map {
  'some id' => 'some value',
  'some id 2' => 'some value 2' }
```
using `array()` basically gets rid of the keys (in this case the ids) and so you get
```js
['some value', 'some value 2']
```

however if those values happen to be objects with `toString()` methods...

```js
> function X(n) { return { toString() { return n } } }
undefined
> array = [X('some value'), X('some value 2')]
[ { toString: [Function: toString] },
  { toString: [Function: toString] } ]
> array
[ { toString: [Function: toString] },
  { toString: [Function: toString] } ]
> 'Available things: ' + array
'Available things: some value,some value 2'
>
```

**Comment by 2E0PGS** [comment]
I know they are maps. But I am converting them to arrays using .array() no?

Right why does array remove keys for guilds but not channels. Surely the key is the ID for both?
Is this because of the toString() method is what your saying?

Why does this have a custom toString method instead of using native javascript toString() method?
Why does channels not also have a toString method. I know native toString could be used here so maybe there is something special about this custom toString method?

Array method has a special cause for objects with toString methods? and it uses that to return a name array instead for convenience?

**Comment by devsnek** [comment]
the array contains guild **objects* or channel **objects**. these **objects** contain **methods**. one of these **methods** is called "toString". the toString **method** is used when you try to concatenate a string and an array (like you are doing). if you just log the array you'll see the actual objects. if you want the IDs do `channels.array().map(c => c.id)` and `guilds.map(g => g.id)`

**Comment by vzwGrey** [comment]
The `toString` method on the Guild class differs from the `toString` method on the Channel class.
For guilds it just returns the name, while for channels it returns a channel *mention*; `<#12345678987654321>` is not (just) the channel's ID, it's a whole mention. This is just how the `toString` methods on both of these classes works.

This is not the fault of the `array` method, the `array` method returns an array with all the objects contained in the original Collection. However concatenating them with a string (which you are doing in your `console.log(...)`) calls `toString` on all of them.

If you want to see all of their ids, or all of their names, use the `map` method like Gus already told you. However keep in mind converting the Collections to an array is not necessary to use the `map` method, because it is implemented for Collections as well and works exactly the same as it does for arrays.

**Comment by 2E0PGS** [comment]
Ah this clears things up. I see where / how it differs now and whats causing this behavior. Surely this could be mentioned in the API documentation since here it shows both alpha names with no mention of IDs under toString for GuidChannel.toString():

https://discord.js.org/#/docs/main/stable/class/GuildChannel?scrollTo=toString

This one seems fine however:
https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=toString

Apologies if i'm mistaken.

**Comment by dragonfire535** [comment]
Likely that is the output in the Discord client, where it would be displayed as "#general".

**Comment by vzwGrey** [comment]
Yes, the `Hello from #general` is how it will be displayed in the Discord client, the `#general` being a channel mention.

**Comment by 2E0PGS** [comment]
Why does the other examples with IDs being returned not show the resolved name then? Since channel IDs resolve in the client so do user IDs.

https://discord.js.org/#/docs/main/stable/class/User?scrollTo=toString

A users mention is same as a username no?

**Comment by SpaceEEC** [comment]
That's because your console does not resolve such a mention.

**Comment by 2E0PGS** [comment]
My console doesn't resolve channel names either!? So why is that shown in the API doc.

**Comment by SpaceEEC** [comment]
Why and how should _any_ console resolve discord mentions?

**Comment by 2E0PGS** [comment]
It shouldn't thats my point but above another user mentioned the API doc shows an output as #general but that makes little sense since the console wouldn't display #general it would not resolve it. So surely the API doc should reflect what you would see in a console not what you would see in a discord official client.

**Comment by SpaceEEC** [comment]
Looks like the `GuildChannel#toString` example is wrong then.

**Comment by 2E0PGS** [comment]
Indeed.
