### ISSUE TITLE
Presence Game Types Other Than 0 Broken.

### ISSUE THREAD

**Issue by RekkyRek** [hydrabolt/discord.js#2205]
Game types other than 0 don't seem to be working. Is this intentional?

```js
client.user.setPresence({ game: { name: 'you.', type: 3 } })
```
Sets the bots presence to "Playing you." instead of "Watching you."
![image](https://i.imgur.com/DE0PkgT.jpg)

**Comment by Lewdcario** [comment]
Could you not ignore the issue template please

**Comment by RekkyRek** [comment]
@Lewdcario oh, sorry! I'll do better next time. v11.2.1

**Comment by Lewdcario** [comment]
This is currently not supported in stable as that feature was released after. You may get this ability by installing 11.3-dev (`npm i hydrabolt/discord.js#11.3-dev`), or master branch (`npm i hydrabolt/discord.js`)

**Comment by RekkyRek** [comment]
@Lewdcario awesome! That worked :) (Also, super impressed with response time :+1:)
