### ISSUE TITLE
Errer write after end when using voiceConnection.stopPlaying()

### ISSUE THREAD

**Issue by mees-** [hydrabolt/discord.js#221]
Im having this error when calling bot.voiceConnection.stopPlaying() before the stream is over, this didn't use to happen on 6.0.0. it works fine when just letting the stream run out.
`Error: write after end`

**Comment by JMTK** [comment]
@mees- What did you do to fix this?

**Comment by mees-** [comment]
@JMTK I reverted back to ytdl-core 0.7.10 because the new version seemed to cause the problem
