### ISSUE TITLE
MessageReaction fetchUsers max limit, what if there are over 100 users?

### ISSUE THREAD

**Issue by shukriadams** [hydrabolt/discord.js#2214]
MessageReaction has two ways of getting users who added to the reaction ...

    reaction.users 

which is a collection, and 
    
    reaction.fetchUsers(maxUsers) 

which returns a promise. fetchUsers() has a maximum limit of 100 users - how do we deal with reactions that have over 100 users on it? 

Also, the .users collection isn't very reliable, I've noticed that sometimes it returns an empty collection even if there are definitely users visible on the dischord app.

**Comment by Lewdcario** [comment]
This is not an issue with the library. Please move to the discord server.

**Comment by SpaceEEC** [comment]
Fetching more than 100 users is not supported in current stable (11.2.1).
The master branch (12.0.0-dev), which has breaking changes, however is supporting that. ([Docs](https://discord.js.org/#/docs/main/master/class/ReactionUserStore?scrollTo=fetch))

I supposes it's possible to backport that for 11.3.0 in a not breaking manner.

**Comment by shukriadams** [comment]
@SpaceEEC Thanks for the info, that's good to know. I don't need this functionality immediately, I can wait it out until 12 is released, just glad to know it's being looked at. Closing ticket.
