### ISSUE TITLE
Event on server joining

### ISSUE THREAD

**Issue by FavreNicolas** [hydrabolt/discord.js#222]
Hello,

My use new bot accoun,
Je voudrais pouvoir afficher dans la console quand quelqu'un l'ajoute à sont serveur via le lien https://discordapp.com/oauth2/authorize?&client_id=<BotID>&scope=bot

**Comment by abalabahaha** [comment]
Does the on("serverCreated") event not fire?

**Comment by FavreNicolas** [comment]
Ok thanks
