### ISSUE TITLE
AvatarURL Not working correctly

### ISSUE THREAD

**Issue by Nahue1337** [hydrabolt/discord.js#2220]
Already solved, it wasn't an error, how do i delete this?. :p

**Comment by lloti** [comment]
For some reason, I don't believe you're on 11.2.1

**Comment by Dev-Yukine** [comment]
it seems like you use the master version of discord.js because on master it is a method now instead a property what takes ab options argument what can dertermine the size and file ending

**Comment by Nahue1337** [comment]
Sorry, my bad, apparently npm view discord.js version outputs the latest version available.
Also i solved this by adding a () after avatarURL, it was my fault, not discord.js.
My apologies.

**Comment by Dev-Yukine** [comment]
thats fine while this issue is solved now, you can close this issue.
