### ISSUE TITLE
Incorrect wording in documentation.

### ISSUE THREAD

**Issue by vim2meta** [hydrabolt/discord.js#2222]
**Please describe the problem you are having in as much detail as possible:**
Several `Collection` prototype methods are said to be `identical to Array.x()`. This is not always true. `client.channels.find((x) => ...)` will return `null` if no result is found even though [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) states that the return value will be `undefined` if not found. 

This may seem like minor issue, but it will produce unexpected results for those who write more verbose code: 
```js
const result = client.channels.find((x) => ...);
if (result === undefined) // true with arrays, but false with collections
```
There is also the fact that both return values are entirely different types. `null` being an `object` and `undefined` being its own separate type.

Since `null` has been baked into a lot of discord.js functions, I won't expect that to change for backwards compatibility, but a minor documentation update is a quick fix.

**Further details:**

- discord.js version: 12.0.0
- node.js version: 9.3.0
- Operating system: Arch Linux
- Priority: low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: [229eb2b](https://github.com/hydrabolt/discord.js/tree/229eb2be2da11563c3c9978664e050044de720df)

**Comment by devdutchy** [comment]
+1
