### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by Alipoodle** [hydrabolt/discord.js#2226]
**Please describe the problem you are having in as much detail as possible:**
On Master the GuildChannel properties for messages are missing! It is fine on Stable and for other channels types but missing for GuildChannel!

[Master - GroupDMChannel Doc](https://discord.js.org/#/docs/main/master/class/GroupDMChannel?scrollTo=messages)
[Master- GuildChannel Doc](https://discord.js.org/#/docs/main/master/class/GuildChannel)

**Comment by KingDGrizzle** [comment]
Well of course. A guild channel includes:
a. TextChannels
B. Voice Channels
C. Category Channels

You want to look at TextChannels, which extend GuildChannels

**Comment by maxerbox** [comment]
I noticed that a lot of properties are missing in https://discord.js.org/#/docs/main/11.3.2/class/TextChannel (which is the stable version) comparing the the master version of docs

**Comment by Gawdl3y** [comment]
The master branch is the in-development version of v12.
