### ISSUE TITLE
Problem with setting status

### ISSUE THREAD

**Issue by Marcus-Roman** [hydrabolt/discord.js#2234]
**Please describe the problem you are having in as much detail as possible:**
Recently I was doing some testing on user accounts, basically when a certain command is ran it will set that accounts status to Streaming args. The error though is I'm not getting a stacktrace nor is it working.

**Include a reproducible code sample here, if possible:**
```js
module.exports.run = async (client, message, args) => {
    message.edit(":white_check_mark:  Now streaming: **" + args.join(' ') + "**")
    client.user.setStatus(null, {
        name: args.join(' '),
        type: 1,
        url: 'linkhere'
      })
}
```

**Further details:**

- discord.js version:
- node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
