### ISSUE TITLE
Friends List support

### ISSUE THREAD

**Issue by FavreNicolas** [hydrabolt/discord.js#224]
You add the support of the Friends list ??

**Comment by meew0** [comment]
No, bots won't be able to have friends in the future and thus it would be pointless to implement this.

**Comment by aequasi** [comment]
This library can be used for non-bot accounts too

Aaron Scherer




On Fri, Mar 18, 2016 at 12:05 PM -0700, "meew0" <notifications@github.com> wrote:












No, bots won't be able to have friends in the future and thus it would be pointless to implement this.
