### ISSUE TITLE
setGame won't work.

### ISSUE THREAD

**Issue by Wetzu212** [hydrabolt/discord.js#2240]
Hello. i have this issue which i've been having for quite a while now.
``client.on("guildCreate", guild => {
  // This event triggers when the bot joins a guild.
  console.log(`New guild joined: ${guild.name} (id: ${guild.id}). This guild has ${guild.memberCount} members!`);
  client.user.setGame(` | -help`);
});

client.on("guildDelete", guild => {
  // this event triggers when the bot is removed from a guild.
  console.log(`I have been removed from: ${guild.name} (id: ${guild.id})`);
  client.user.setGame(` | -help`);
});``

The 'Playing' on my bot won't even show. I don't know if it's the command or is it a problem in the bot.js.

**Comment by devdutchy** [comment]
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by JamieStivala** [comment]
Ask for help on the discord.js server https://discord.gg/bRCvFy9 :)
