### ISSUE TITLE
Issue while starting a discord bot

### ISSUE THREAD

**Issue by 7ekhed** [hydrabolt/discord.js#2245]
So I have been trying to make a discord bot, and am configuring the app.js file. While doing the testing for it i have come across the following error:

ReferenceError: bot is not defined
    at Object.<anonymous> (C:\Users\johan\Desktop\Bruh bot\app.js:7:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

I am unsure what is wrong, but here is the coding for the app.js file:

var Discord = require("discord.js")
var DiscordClient = require('discord.io')
var Discord = require('discord.io')

(This is where the cmd is having issues ->) bot.on('message', message => {

  //variables
  var sender = message.author;
  var msg = message.content.toUpperCase(); 
  var prefix = '?'

  if (msg === prefix + 'ping') {
      message.channel.send('Pong!') // Sends a message to the channel, with the contents: "pong!"
  }

  if (message.channel.id === ' ') { 
      if (isNaN(message.content)) { 
          message.delete()
          message.author.send('please only post the number and not any other text in this channel, Thank You!') 
  }

};

// Listener Event: Bot Launched
bot.on('ready', () => {
    console.log('Bot Launched and ready!') 

   

bot.login('My token') 

});

});

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
