### ISSUE TITLE
Bot silently "half"-disconnects

### ISSUE THREAD

**Issue by copygirl** [hydrabolt/discord.js#225]
Ever since I started using discord.js, my bot just randomly disconnects, or rather, appears offline in Discord. It stops _receiving_ messages, but is still able to _send_ messages to Discord just fine.

According to a friend, this doesn't send a disconnect event either (so no manual `discord.on("disconnect", reconnect);`), but I haven't tried it myself.

**Comment by khionu** [comment]
This sounds like a networking issue. If it can send it should be able to receive. Try adding this at the beginning of your main bot file
```js
var fs = require('fs');
var rawLog = fs.createWriteStream('rawLog.txt');
```
and this somewhere in the body, like you would have onMessage or onReady
```js
discord.on("raw", (rawObj) => {
    rawLog.write(rawObj);
});
```
After you get these issues again, see if you can find errors in your `rawLog.txt`

**Comment by meew0** [comment]
If it can send but not receive, it would mean the WS disconnects while the REST calls are still working fine. This would be a really strange situation because REST calls should only ever be executed in events, which are all triggered by the WS. Can you show the code you're using?

**Comment by copygirl** [comment]
@khionu Thanks, I'll see if I can find anything when it disconnects again.

@meew0 [Here.](https://github.com/copygirl/cord) Unfortunately, I had a thing for LiveScript when I wrote it. Also, it's quite outdated, but I have the same issue now as back then so I doubt it matters. It's a IRC-Discord bridge bot so I suppose that explains the ability to send messages without being online. Didn't think that should be possible before.

**Comment by meew0** [comment]
It being an IRC bridge would explain the sending outside of WS events. If it's an older project, what version of discord.js is it on, and does updating fix it?

**Comment by copygirl** [comment]
> what version of discord.js is it on, and does updating fix it?

I've recently updated to discord.js 6.1.0 and still seem to have the same issue.

**Comment by abalabahaha** [comment]
Can you try handling the `on('disconnect')` event

**Comment by copygirl** [comment]
At this point, I'm sure this would actually be fixed by just reconnecting on a disconnect. Since the disconnecting only happens randomly and I can't test it I'll just go ahead and rewrite my bot in JavaScript. I'll just redirect the attention to #216, close this issue and potentially reopen it if I still see an issue in the future.
