### ISSUE TITLE
this is not a function

### ISSUE THREAD

**Issue by FireController1847** [hydrabolt/discord.js#2253]
**Please describe the problem you are having in as much detail as possible:**
One of my shards (out of ten) is thinking any "this" in any broadcastEval is _not_ a function. Error below.
```
7|Pandora  | [Shard 6] { TypeError: this is not a function
7|Pandora  |     at eval (eval at _eval (/home/fire/bots/pandora/node_modules/discord.js/src/client/Client.js:409:12), <anonymous>:1:7)
7|Pandora  |     at Client._eval (/home/fire/bots/pandora/node_modules/discord.js/src/client/Client.js:409:12)
7|Pandora  |     at ShardClientUtil._handleMessage (/home/fire/bots/pandora/node_modules/discord.js/src/sharding/ShardClientUtil.js:131:76)
7|Pandora  |     at emitTwo (events.js:126:13)
7|Pandora  |     at process.emit (events.js:214:7)
7|Pandora  |     at emit (internal/child_process.js:772:12)
7|Pandora  |     at _combinedTickCallback (internal/process/next_tick.js:141:11)
7|Pandora  |     at process._tickCallback (internal/process/next_tick.js:180:9) name: 'TypeError' }
```

**Include a reproducible code sample here, if possible:**
```js
bot.shard.broadcastEval("this").then(res => {
  console.los(res);
}).catch(console.error);
```
This also has the same error.
```js
P!eval bot.shard.broadcastEval("this.shard.id").then(res => {
  console.los(res);
}).catch(console.error);
```

**Further details:**

- discord.js version: 352bd13e6f590e12d5e2e3be0cf836e929cef74b
- node.js version: v8.9.4
- Operating system: Windows 10 x64 v1709 (Fall Creators)
- Priority this issue should have – please be realistic and elaborate if possible: High -- Huge issue with sharding, disallows to get any global values.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 352bd13e6f590e12d5e2e3be0cf836e929cef74b

**Comment by SpaceEEC** [comment]
Likely related to #2248
