### ISSUE TITLE
.send() not working.

### ISSUE THREAD

**Issue by FHGDev** [hydrabolt/discord.js#2258]
# .send() Not working.

Hey, sup. 
So today I was trying to send a message to all the guilds my [bot](https://bot.hulkbot.ml/home) is in. So, in the ready event, I put 
```js
bot.guilds.forEach((guild) => {
   guild.channels.find('name', 'general').send('message')
   guild.channels.find('name', 'chat').send('message')
})```

So, I ran the bot, and I got this error.
```
 TypeError: Cannot read property 'send' of null
```

If I could get an explanation for this, and how to fix it, it'd be great.

## Node Version: 
   9.4.0
## Discord.js Version:
   11.3.0
## Hosted on GitHub with Heroku

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by FHGDev** [comment]
Welp, this isn't a question! It's a bug.

**Comment by Lewdcario** [comment]
That is not a bug, if you bothered to research what `find` returns, you will discover it returns `null` if whatr you sought was not found. Again, this is not a bug.

**Comment by FHGDev** [comment]
It has ALWAYS worked in the past, so I would know if it isn't meant to be used how I'm using it.

**Comment by FHGDev** [comment]
It just hasn't been working since 11.3.0.

**Comment by kyranet** [comment]
Please be aware some of us get notifications here as well as we have a webhook to get the latest updates from this repository. The issue you have is not a discord.js issue, and as @Lewdcario stated, please use Discord instead, we'll help you there.
