### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by zhiyan114** [hydrabolt/discord.js#2261]
**Please describe the problem you are having in as much detail as possible:**
Hi so im getting a memory leak problem everytime when the bot is restarted and some command is being used
Error code:
`(node:6001) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 guildMemberAdd listeners added. Use emitter.setMaxListeners() to increase limit`

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- discord.js version: 9 (latest i think)
- node.js version: 9.4
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devdutchy** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:

https://discord.gg/bRCvFy9

This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
