### ISSUE TITLE
bot.voiceConnection.playFile bug

### ISSUE THREAD

**Issue by ic3w0lf22** [hydrabolt/discord.js#227]
Everytime I try to test the voice commands in discord with my bot, it says 

> TypeError: Cannot assign to read only property 'volume' of false

My code is `'tv': function(mybot, message) {
		try {
			bot.voiceConnection.stopPlaying();
			bot.voiceConnection.playFile("./test.mp3");
		} catch (err) {
			bot.reply(message, err);
		}
	}`

test.mp3 also exists in the directory of the bot, http://puu.sh/nMD1u/71c5d7e6d1.png

**Comment by abalabahaha** [comment]
Already known bug, fixed in development branch. For now, do `bot.voiceConnection.playFile("./test.mp3", {});`
