### ISSUE TITLE
CPU at 100%

### ISSUE THREAD

**Issue by dustinblackman** [hydrabolt/discord.js#232]
With Discordjs `6.1.0` there seems an issue with a CPU core fixed at 100%  when dealing with accounts that have many servers (mine for example is currently connected to 3000, with over 70k users). This happens right on boot without executing any special discordjs methods, just listening for new messages.

CPU remained at 100% for 15 minutes before I gave up and downgraded again back to `6.0.0`.

**Comment by abalabahaha** [comment]
If you're still up for it, can you try installing off indev(`npm install hydrabolt/discord.js#indev`)? That's a known issue, and will be fixed in an upcoming release. Sorry for the inconvenience.

**Comment by brussell98** [comment]
I had this issue and can confirm that it is fixed in indev

**Comment by dustinblackman** [comment]
Can confirm it's fixed on `indev`. Thanks! Looking forward to the next release.
