### ISSUE TITLE
Add to server

### ISSUE THREAD

**Issue by AnnoyingDog87** [hydrabolt/discord.js#233]
So, i was messing with Discord.js, and i tried to add my bot to another server.

Every command was working, but the bot didn't send any message when i used the function Bot.sendMessage()

Please, help!

**Comment by meew0** [comment]
Can you show the code you're using?

**Comment by AnnoyingDog87** [comment]
That's weird.
I added a callback function and it started working

**Comment by abalabahaha** [comment]
If you're talking about accepting an invite through discord.js, that doesn't happen instantly, so putting code in the callback ensures it will only execute _after the bot has successfully finished joining the server_.
