### ISSUE TITLE
Are there any details about Role Resolvables?

### ISSUE THREAD

**Issue by touchandswipe** [hydrabolt/discord.js#235]
Trying to use memberHasRole(member, role) but seem to run into problem specifying what is resolvable for role. docs doesnt have details too. pls help tyvm and great work overall!

**Comment by abalabahaha** [comment]
Role object or Role ID, [as stated in the docs](http://discordjs.readthedocs.org/en/latest/docs_resolvables.html#role-resolvable)

**Comment by touchandswipe** [comment]
Thanks mate. found it. couldn't find that in the doc prior.
