### ISSUE TITLE
.sendMessage() not sending anything

### ISSUE THREAD

**Issue by mfoulks3200** [hydrabolt/discord.js#239]
I've been scratching my head at this for over an hour now, I'm trying to get my bot to send something into a certain text channel with this code:
`console.log('!play https://youtube.com/watch?v='+youtube.items[0].id.videoId);
          mybot.sendMessage(164917313387233280,'!play https://youtube.com/watch?v='+youtube.items[0].id.videoId);`
(I know it's not a problem with variables or anything because the console.log() has no trouble producing the output) I've put the channel id in the first parameter, but it still doesn't work. I think the channel id fits under the umbrella of "channel resolvable", right? I feel like I'm missing something really obvious, so if I am, please enlighten me.

Thanks

**Comment by Denocle** [comment]
Try using the channel ID as a string, instead of an integer.
```
mybot.sendMessage('164917313387233280', '!play https://youtube.com/watch?v='+youtube.items[0].id.videoId);
```

**Comment by abalabahaha** [comment]
ID numbers are too big, they will lose precision in Javascript. Use `"164917313387233280"` instead of `164917313387233280`

**Comment by mfoulks3200** [comment]
wow, ok, I'm stupid XD, thanks for the help, you guys are fast!

**Comment by ModalSeoul** [comment]
Can we do this without hardcoding channel id...?

**Comment by GusCaplan** [comment]
@ModalSeoul join [our discord server](https://discord.gg/bRCvFy9) and we can assist you further.

**Comment by muscaiu** [comment]
> 
> 
> wow, ok, I'm stupid XD, thanks for the help, you guys are fast!

No you're not stupid at all. And joining the discord server and asking questions didn't help me either.
