### ISSUE TITLE
setAvatar: Error: Internal Server Error

### ISSUE THREAD

**Issue by Xstasy** [hydrabolt/discord.js#241]
I got 4 bots running same codebase, same commit version of discord.js, on the same system.
3 of them can set avatar, one just receives `Error: Internal Server Error` from the setAvatar callback.

Debug does not output anything :\

**Comment by meew0** [comment]
Does the one where it doesn't work happen to be a bot account?

**Comment by Xstasy** [comment]
TL;DR I'm a noob.
