### ISSUE TITLE
forceFetchUsers not working

### ISSUE THREAD

**Issue by BitQuote** [hydrabolt/discord.js#246]
Even when using `bot.forceFetchUsers()`, many members of large servers are not in the members list.

**Comment by abalabahaha** [comment]
Was this resolved?

**Comment by BitQuote** [comment]
I suppose so...I restarted my bot and it mysteriously started working.

**Comment by BitQuote** [comment]
This issue has come up again. Despite using `forceFetchUsers`, the members list is still incomplete.

**Comment by abalabahaha** [comment]
forceFetchUsers() takes time to complete. If your code depends on the complete member list, make sure you're either:
1. Manually calling forceFetchUsers() and putting code in the promise/callback
2. Passing forceFetchUsers as an option in the Client constructor (this also delays the on("ready") event until after force fetch completes) (`var client = new Discord.Client({forceFetchUsers: true});`)

**Comment by BitQuote** [comment]
Even with `var client = new Discord.Client({forceFetchUsers: true});`, it doesn't work...

**Comment by meew0** [comment]
Can you maybe show your full code?

**Comment by abalabahaha** [comment]
I think we discussed, this seems to fail on his OpenShift instance but works in local testing. Doesn't appear to be a library bug though.

**Comment by BitQuote** [comment]
Yes, the issue turned out to be on OpenShift's end

**Comment by Daijobou** [comment]
@abalabahaha 
You wrote 

> Manually calling forceFetchUsers() and putting code in the promise/callback

You are sure that this function exists? I get a error

> TypeError: bot.forceFetchUsers is not a function

I search a way too, to get all members for a statistik, but get always only a small part of all userdatas.
See https://stackoverflow.com/questions/48886454/discordjs-forcefetchusers-not-working

_I have discordjs 11.3.0 installed_

**Comment by iCrawl** [comment]
Please look at the date this issue was posted and possibly open a new one before reviving old threads.
