### ISSUE TITLE
No sound / data sent from "bot.voiceConnection.playFile"

### ISSUE THREAD

**Issue by XNBlank** [hydrabolt/discord.js#248]
I've updated to the most recent dev branch, but now when I try to get the bot to play an audio file through `bot.voiceConnection.playFile(file)` nothing happens. No sound. Discord's voice debug says no data is being sent from the bot. I'm lost.

Was there a change that I'm not aware of that requires the code to be a little different?

```javascript
if(messageLow.startsWith(prefix + "playaudio")){
	var temp = messageRaw.split(" ")[1];
	var path = "./sounds/";
	mybot.voiceConnection.stopPlaying();
	if(temp.startsWith("http")){
		console.log("Playing sound : " + temp);
		 mybot.voiceConnection.playFile(temp);
	}else{
		console.log("Playing sound : " + path + temp);
		mybot.voiceConnection.playFile(path + temp);
	}
}
```

![](http://i.imgur.com/OyNoRpw.png)

**Comment by macdja38** [comment]
I don't know what could cause the issue, and their have been changes to audio stuff over the past few days, but could you test a few versions and see which ones work or don't?

**Comment by robbix1206** [comment]
Have you the circle of the bot speaking with that or not ?
