### ISSUE TITLE
Issuing multiple addMemberToRole on the same user causes silent fail

### ISSUE THREAD

**Issue by occurr** [hydrabolt/discord.js#249]
Issuing more than one `addMemberToRole` to the same user without waiting for the last `addMemberToRole`'s callback causes a failure without an error (silent fail).

**Comment by brussell98** [comment]
This is not a library issue. You are creating a race condition by sending multiple requests at the same time, meaning that the last one to arrive will overwrite the others.
You have to wait for the callback.

**Comment by occurr** [comment]
Why would adding a user role overwrite another user role? Is state being saved at the time of request?

**Comment by brussell98** [comment]
Adding a member to a role updates the server member's role value to be a new array of roles. It doesn't just the the server to add one.
This means that It will overwrite whatever was there before.

**Comment by occurr** [comment]
Ah, I see. It would be a nice bit of functionality to be able to update more than one user role at once considering the limitation .

**Comment by brussell98** [comment]
You can pass it an array of roles and it will add all of them at once

**Comment by occurr** [comment]
Oh, fantastic. I would suggest adding that to the docs :D 

Anywho, closed
