### ISSUE TITLE
.playFile() doesn't exist?

### ISSUE THREAD

**Issue by mfoulks3200** [hydrabolt/discord.js#252]
I've been trying to use the .playFile() function, and no matter what I try, nodejs refuses to aknowlage its existance, with the error:

mybot.playFile('./music/'+musicQueue[0].title+'.mp3');
        ^
TypeError: mybot.playFile is not a function

I've even tried using mybot.voiceConnection.playFile('./music/'+musicQueue[0].title+'.mp3');, but that doesn't work either. what am I doing wrong?

**Comment by abalabahaha** [comment]
If you read the docs correctly, `mybot.voiceConnection.playFile('./music/'+musicQueue[0].title+'.mp3')` is the way to go. What issue did you have with that?

**Comment by mfoulks3200** [comment]
I put in the second part of my question that I tried that as well, but I can provide the specific error I get

mybot.voiceConnection.playFile('./music/'+musicQueue[0].title+'.mp3');
                       ^
TypeError: Cannot read property 'playFile' of null

**Comment by abalabahaha** [comment]
Yes, because you need to join a voice channel first.
