### ISSUE TITLE
The Client.logout has been broken.

### ISSUE THREAD

**Issue by robbix1206** [hydrabolt/discord.js#255]
The Client.logout() function has been broken.
What i will say is when i use it in this script.

`var discord = require('discord.js');
var bot=new discord.Client;
bot.login("username","password",function (err,token) {
  if(err!=null)
  {
    console.log(err);
    process.exit;
  }
});
bot.on("ready",function () {
  setTimeout(function () {
    bot.logout();
  },10000)
})
bot.on("message",function (message) {
  console.log(message);
});`

The Bot connect to Discord and have to disconnect after 10s but after 10s node close properly because for discord.js all the connection are closed but for discord the bot still show online for something like 2min (before certainly the timeout).
This problems occurs from Today for me.
Yesterday it was working correctly but today it look likes has it has been broken.

(Sorry for my bad English)

Edit: the problem occur in the web version of discord too.
Edit 2: Mobile app for android is not touch by the bug.

**Comment by abalabahaha** [comment]
Fixed in indev branch, either use that or wait for the next release
