### ISSUE TITLE
Receiving inconsistent number of serverCreated after ready packet

### ISSUE THREAD

**Issue by aequasi** [hydrabolt/discord.js#257]
Using the following code, on a bot account, that has more than 100 servers, i'm getting an inconsistent number of serverCreated events, and more than what can be explained by servers already contained in the ready packet.

Specifically tested with DSL, have gotten:
* 867
* 1270 (which i believe is the closest to what it should be. This is what it was close to before the gateway change)
* 1351
* 1514
* 1487
* 1509
* 740
* 2124
* 1706
* 2698
* 1724

Its never been the same

```javascript
const Client = require('discord.js').Client;

var client = new Client({forceFetchUsers: true});

client.loginWithToken('token');

client.on('debug', (message) => console.log(message));
client.on('error', console.error);
client.on('disconnect', () => console.info("Bot has disconnected"));

var count = 0;
client.on('serverCreated', () => {
  count++;
  console.log(count);
});

```

**Comment by aequasi** [comment]
Happens with or without `forceFetchUsers: true`

**Comment by meew0** [comment]
`serverCreated` isn't supposed to be emitted there anyway, that's a bug. Can you check whether the total number of servers on the client after all the servers have loaded (`client.servers.length`) is at least consistent?

**Comment by aequasi** [comment]
What do you mean its not supposed to be emitted there?

**Comment by abalabahaha** [comment]
thought it was until we figure out better wait-for logic
