### ISSUE TITLE
Can't set bot account avatar

### ISSUE THREAD

**Issue by Omegaxis8009** [hydrabolt/discord.js#260]
trying to set a bot account avatar with `updateDetails` and `setAvatar` (Not at the same time)

and both of them give

`if (!this.user.bot && !(this.email || data.email)) throw new Error("Must provide email since a token was used to login");`

A few people have said that this should be working, so I am unsure as to what is happening.

**Comment by abalabahaha** [comment]
6.1.0 doesn't support bot accounts yet, but the indev branch does. You'll have to either wait for the next release or attempt to use the indev branch (get help w/ this in the discord.js Discord channel).

**Comment by Omegaxis8009** [comment]
I got the indev branch after asking on discord but its giving me the same error

**Comment by abalabahaha** [comment]
Are you doing this in the ready event handler?
