### ISSUE TITLE
[INDEV] Crash on bot.voiceConnections[0].stopPlaying();

### ISSUE THREAD

**Issue by Trismirite** [hydrabolt/discord.js#262]
Using playRawStream to play youtube songs and when .stopPlaying(); is triggered it results with the error 

`events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: write after end
`

**Comment by Trismirite** [comment]
Works fine on ytdl-core@0.7.9
https://www.versioneye.com/nodejs/ytdl-core/0.7.9

**Comment by abalabahaha** [comment]
ytdl thing, not too much can be done
