### ISSUE TITLE
voiceConnection.PlayXYZ doesn't work on ubuntu 14.04

### ISSUE THREAD

**Issue by Razzile** [hydrabolt/discord.js#265]
I've been trying to get my bot to play sound. On windows, the following code works fine but on ubuntu 14.04 with ffmpeg installed the bot just doesn't play anything.

```
"memes" : {
        name : "memes",
        usage : "!memes",
        command : function(bot, message) {
            bot.joinVoiceChannel(message.author.voiceChannel, function(error, voice) {
                voice.playFile("./res/meme.mp3", {"volume":1.0}, function(error, intent) {
                    if (error) console.log(error.stack);
                    intent.on("end", function() {
                        bot.leaveVoiceChannel();
                    });
                });
            });
        }
    },
```

the error variable is always null too in the above example.

the mp3 at ./res/meme.mp3 definitely exists and i've tried accessing it by direct path too.

I've also tried using libav-tools instead of ffmpeg too to no avail.

here is the info on the ffmpeg I have installed
```
Package: ffmpeg
Priority: optional
Section: video
Installed-Size: 106 MB
Maintainer: Doug McMahon <mc631man@gmail.com>
Version: 7:3.0.0+git1~trusty
Depends: libasound2 (>= 1.0.16), libass5 (>= 0.13.0), libbz2-1.0, libc6 (>= 2.17), libfdk-aac0 (>= 0.1.1), libfreetype6 (>= 2.2.1), libgnutls26 (>= 2.12.17-0), libmp3lame0, libopencore-amrnb0, libopencore-amrwb0, libopus0 (>= 1.0.3), libpulse0 (>= 1:0.99.1), libsdl1.2debian (>= 1.2.11), libsoxr0 (>= 0.1.0), libspeex1 (>= 1.2~beta3-1), libva1 (>> 1.3.0~), libvdpau1 (>= 0.2), libvidstab1.0, libvorbis0a (>= 1.1.2), libvorbisenc2 (>= 1.1.2), libx11-6, libx264-148, libx265-79, libxcb-shape0, libxcb-shm0, libxcb-xfixes0, libxcb1, libxext6, libxv1, libxvidcore4 (>= 1.2.2), zlib1g (>= 1:1.2.0.2)
Download-Size: 31.7 MB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/ trusty/main amd64 Packages
Description: Multimedia player, server, encoder and transcoder
```

**Comment by zoton2** [comment]
I had a similar/same issue with libav-tools on my Raspberry Pi 2; turns out that it doesn't support the `-hide_banner` parameter that the module puts in so it just errors out and ends the stream instantly. Does your `end` listener fire just after you attempt to play the MP3 as well?

Apparently `-hide_banner` is needed so it doesn't error out, but I removed it and it works just fine, even on a version of FFmpeg that *does* accept the parameter.

**Comment by Razzile** [comment]
yea that's exactly what happens

**Comment by zoton2** [comment]
If you want to test if this is your issue, go to `lib/Voice/AudioEncoder.js` and remove the parameter from the array on [this line](https://github.com/hydrabolt/discord.js/blob/master/lib/Voice/AudioEncoder.js#L131) (for playFile) and see if it works then.

**Comment by Razzile** [comment]
doesn't seem to be working :/

**Comment by Razzile** [comment]
Update: This fixed it!!! thanks @zoton2 .
I'll leave this issue open so the devs can see it

**Comment by abalabahaha** [comment]
seen it :+1:

**Comment by zoton2** [comment]
@abalabahaha was the one who helped me figure out this was the issue so they deserve the credit really.
