### ISSUE TITLE
sendFile with Text

### ISSUE THREAD

**Issue by hsiw** [hydrabolt/discord.js#269]
Currently in discord.js you are unable to send a file with content using the sendFile(); function. With a semi-recent update you've been able to do this in the Discord client but not using discord.js yet. Could this please be added in the future as it would help with multi-message spamming.

**Comment by Programmix** [comment]
Doesn't that feature of the Discord client just send a message and subsequently the file?

**Comment by uniquoooo** [comment]
@abalabahaha you should add the `tts` option as well. Just send `tts` as `true` in multipart.

**Comment by hsiw** [comment]
After testing the changes in the commit that abalalalalalala its still not showing the content using the following format:
`bot.sendFile(msg, "http://i.imgur.com/czx5YDq.gif", null, "TEST");`

**Comment by abalabahaha** [comment]
Now on indev and verified by testers
