### ISSUE TITLE
Bot kinda just dies

### ISSUE THREAD

**Issue by hsiw** [hydrabolt/discord.js#270]
For the past few weeks I've been having an issue where my bot kinda just dies. Any function using the discordjs stops working and the bot disconnects. The on disconnect event doesn't fire when this happens. I haven't noticed what exactly happens to cause it to die because it seems random. Sometimes I have 40hrs+ of uptime before it happens others I have less than 5hrs of uptime. I've thrown in a on warn and on error and neither of these show anything. I'm really sorry that I can't be more specific for whats causing this.

**Comment by aequasi** [comment]
Getting this too, actually

**Comment by Lord-Ptolemy** [comment]
I've have had this for months. Like @hsiw said, can be a couple hours to 40+ hours of uptime. I've usually only encounter in when I've left the bot on for 24hrs+.

**Comment by khionu** [comment]
TechniKhitty has been crashing every few hours, and my eval bot hasn't been doing any better

**Comment by abalabahaha** [comment]
Cloudflare occasionally cuts websockets, and discord.js isn't detecting this.

**Comment by occurr** [comment]
Yeah, i'm having the same issue

**Comment by abalabahaha** [comment]
[The testers said this worked, so I pushed it](http://discordjs.readthedocs.org/en/latest/docs_client.html#autoreconnect)
