### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by chadrien** [hydrabolt/discord.js#272]
Hi,

I'm using `discord.js` for a bot project of mine written in TypeScript. For now I've made my own typings file (not great/complete) and I was wondering if you're going to provide an official (i.e. made by the contributors of this project) one in the mid/long term?

**Comment by abalabahaha** [comment]
Debatable... I think we won't be providing one, but still waiting on _other contributors' input_

**Comment by chadrien** [comment]
Alright, as I started one I might as well try to complete it and open a PR :smiley:

**Comment by GexoXYZ** [comment]
@chadrien Any progess on this? If you already have something, someone could continue on it if you stopped.

**Comment by chadrien** [comment]
Hi @GexoXYZ: I was absorbed by other things and completely forgot this, sorry! I have something already but it's not perfect and far from complete: https://github.com/chadrien/cycle-discord/blob/master/src/custom-typings/discord.d.ts
Feel free to go ahead from this as I may not have the time to continue working on this in the time being.

**Comment by Falconerd** [comment]
Unless someone else is working on this, I'm going to take a stab at it. I'll post any updates here.

**Comment by Falconerd** [comment]
I've started writing the definition file. So far it seems functional, however I'm worried that it's not correct. Can anyone take a look and tell me if it looks okay?

https://github.com/Falconerd/discord.js-td/blob/master/index.d.ts

**Comment by Falconerd** [comment]
Okay, I've completed an initial version. I haven't written tests for it yet as I'm out of time. When it's all testing properly I'll see if I can submit it to definitely-typed.

https://github.com/Falconerd/discord.js-td/blob/master/index.d.ts

**Comment by GexoXYZ** [comment]
https://github.com/nicholastay/discord.js.d.ts

**Comment by Falconerd** [comment]
Sweet, I'll remove mine as one is better

**Comment by hydrabolt** [comment]
As of 9.0.2, the typescript definition would be out-of-date. It'd be great if someone could update it!

**Comment by hydrabolt** [comment]
Doesn't look like this is going to happen ;(

**Comment by meew0** [comment]
Why close it? Somebody may attempt it in the future if it stays open.

**Comment by chadrien** [comment]
I'll do it!

**Comment by ItsDizzy** [comment]
Made a litte start already: https://gist.github.com/ItsDizzy/b3852392ee9dc0e4f092411bf8176eb2

**Comment by oorooroot** [comment]
Generated this template 99% automatically from docs.json https://gist.github.com/oorooroot/091e392cdc45a995b2fade876980c0cd
Need some review on it, please. Creating typings first time.

**Comment by ItsDizzy** [comment]
@oorooroot how did you do that?

**Comment by jaimehrubiks** [comment]
@oorooroot good job.

**Comment by ItsDizzy** [comment]
@oorooroot and thank you very much, I really needed this haha

**Comment by chadrien** [comment]
@oorooroot: Looks really good 👍
The comments might be removed though? Looks like it's just a plain copy of code comments, so it might not be necessary in the definition file and it's also "code" (well not really, they're comments) duplication.
But appart from that, nice job! Maybe you could open a PR with this and a modified `package.json` adding a `scripts` entry to generate it the way you did so the `discord.js` team could automate it when they make changes/new releases.

**Comment by oorooroot** [comment]
@chadrien i think that comments are necessary for class, member and argumet description, when using definitions in any IDE. I will refactor my script in few days, polishing some things, including better comments. 

Im still not sure if it is such good idea, to generate typings from docs. During parsing the docs i found some argument or member types, that are not defined by docs.json or any javascript code in the project(you can found this type definitions at the end of my .d.ts file, `VerificationLevel` or `RoleData` for example, all of them typed as `any`).

There are also some documetation-described types that looks strange for me. As example `@returns {Promise<Invite, Error>}` here https://github.com/hydrabolt/discord.js/blob/indev/src/client/Client.js#L197
or `@returns {Object<string, boolean>}` here https://github.com/hydrabolt/discord.js/blob/indev/src/structures/EvaluatedPermissions.js#L24 not sure if `Object<string, boolean>` is correct definition in js, but in typescript definitions i just replaced with `{[K:string]: boolean}`(such cases are hardcoded in my script so it is pretty ugly for now). 

So there are some "special requirements" to documentation, if we wsnt to get all the things typed 100% automaticaly.

**Comment by ItsDizzy** [comment]
The , mean it can return 2 types. `Promise<Invite, Error>` means it will either return a Promise with a Invite type or one with an Error type, the corrent way of defining this would be `Promise<Invite | Error>`

**Comment by Mischala** [comment]
@chadrien I came here to offer to do this also, because I'm in almost the exact same situation, want to convert my bot to TS, need a def file.

Just wanted to point out that the way users acquire typing files has changed in Typescript 2.0
[See here for more info](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/)
This means publishing a Scoped NPM package (@types/discord.js)

if you need any help, give me a bell, really keen to give back to this project.

**Comment by Lichthagel** [comment]
@Mischala I would also like an @types package

**Comment by GusCaplan** [comment]
someone might want to take a look at https://github.com/englercj/tsd-jsdoc. it generates typescript definitions from jsdoc, and we have the entire client documented with jsdoc :)

**Comment by Lichthagel** [comment]
I thinks that is what @oorooroot did

**Comment by ItsDizzy** [comment]
@GusCaplan good call, will have to check if @hydrabolt 's jsdocs are read correctly by that tool

**Comment by iCrawl** [comment]
@GusCaplan you are a fool.
Full typings for d.js are available here btw: https://github.com/acdenisSK/discord.js-typings

**Comment by Mischala** [comment]
@iCrawl Is there a reason this can't be maintained as part of the original project? 
especially with these improvements to the Typescript's typing's acquisition.

**Comment by iCrawl** [comment]
0 at all. There was just no PR yet. I will have a talk with him so it will probably be included in indev.
