### ISSUE TITLE
Immediately fires the disconnect event (Bot acc)

### ISSUE THREAD

**Issue by OneMansGlory** [hydrabolt/discord.js#274]
Yesterday, I switched STAR_BOT to a bot account, and moved to the token login method, and it worked fine for the first few minutes. Then the problems began. As soon as I tried to start the bot, the disconnect event fired. This keeps happening, and it's pretty frustrating :P This might be a bug with my code, but it happened for my other bots for a while as well.

**Comment by OneMansGlory** [comment]
Upon further inspection, the bot logs in, then is immediately disconnected.

**Comment by abalabahaha** [comment]
Either your token is incorrect, or your code is causing it to silently fail/disconnect.
