### ISSUE TITLE
Use of client.logout() with autoReconnect looping disconnected event and not working for long disconnects

### ISSUE THREAD

**Issue by BrunoMoreira991** [hydrabolt/discord.js#276]
After using `client.logout()` with `autoReconnect` as **true** the `disconnected` event will keep firing and loop forever.
![disconnected loop](https://cloud.githubusercontent.com/assets/16598818/14585162/62ad4f84-0462-11e6-8cf0-da76ed1681c6.png)

---
**EDIT**: After further testing I confirmed that `autoReconnect` is only working for really short timeouts.
```Javascript
//I made this little console.logs to make sure.
if (autoReconnect) {
    this.autoReconnectInterval = Math.min(this.autoReconnectInterval * (Math.random() + 1), 60000);
    console.log("autoReconnectInterval is " + this.autoReconnectInterval);
    setTimeout(function () {
        console.log("I got here");
        _this2.setup();

        // Check whether the email is set (if not, only a token has been used for login)
        if (_this2.email) {
            _this2.login(_this2.email, _this2.password);
        } else {
            _this2.loginWithToken(_this2.token);
        }
    }, this.autoReconnectInterval);
}
```
![autoreconnect issue](https://cloud.githubusercontent.com/assets/16598818/14589423/f5c35224-04d9-11e6-81ac-cce430c4d4f2.png)

> First disconnect is a really short timeout (Internet came back almost at the same time the disconnected event was fired) and the second disconnect was a longer one.

1. Bot Disconnects (Internet goes down or whatever)
2. Tries to login (autoReconnect)
3. Fails because there is no Internet yet or whatever.
4. Doesn't retry.

---
1. client.logout()
2. Tries to login (autoReconnect)
3. Fails because there are no credentials due to logout()
4. Keeps trying.

The "papers" are inversed. lol

**Comment by abalabahaha** [comment]
Should be fixed in indev
