### ISSUE TITLE
Insta disconnect + Indev error

### ISSUE THREAD

**Issue by Appa2015** [hydrabolt/discord.js#279]
Ok, so, when I open up my bot using loginWithToken, it just logs in for a second then instantly disconnects. And I get a bunch of errors while using _npm install hydrabolt/discord.js#indev_ which are:
http://puu.sh/olF9z/6bf537bf45.png
http://puu.sh/olFah/490a9c2229.png

**Comment by TehSeph** [comment]
Not sure about the first issue, but the second one is that you need git installed to pull indev using npm.

**Comment by brussell98** [comment]
Mine is also disconnecting instantly.
I'm using `loginWithToken`

**Comment by Appa2015** [comment]
I have git installed... :/

**Comment by brussell98** [comment]
If you were getting instant disconnects before it should be fixed now. Was related to an internal server error for me.
