### ISSUE TITLE
How do I make the bot join a voice channel?

### ISSUE THREAD

**Issue by Ventivian** [hydrabolt/discord.js#281]
So there's 2 voice channels in my discord general and Music and I want the bot to join Music but my current code it doesn't seem to work

[Script](http://hastebin.com/isecezilom.coffee)

**Comment by Lord-Ptolemy** [comment]
http://discordjs.readthedocs.org/en/indev/docs_client.html#voiceconnections

**Comment by Lord-Ptolemy** [comment]
`.joinVoiceChannel` requires a channel resolvable. Not a string.
http://discordjs.readthedocs.org/en/indev/docs_client.html#voiceconnections

**Comment by Ventivian** [comment]
What does that mean exactly?

**Comment by Caraxi** [comment]
A Resolvable for a channel is the channel ID
http://discordjs.readthedocs.org/en/rewrite-docs/docs_resolvables.html#voice-channel-resolvable

**Comment by MaTriXTheCow** [comment]
`sad`
