### ISSUE TITLE
request is not defined?

### ISSUE THREAD

**Issue by Ventivian** [hydrabolt/discord.js#282]
So  my music bot will join the channel but if I try doing the play command it throws this error 

[error in CMD](https://i.gyazo.com/8150ec4ce044276c965d96a3f4749d4f.png)

[script](http://hastebin.com/jixozimefa.coffee)

I tried doing _!play_ https://www.youtube.com/watch?v=jfFTT3iz740

and then it threw the error from above and I don't know why

**Comment by brussell98** [comment]
You need `npm i request` and then require it at the top like with discord
This is not a discord.js issue.

**Comment by Ventivian** [comment]
npm i request?

**Comment by Lord-Ptolemy** [comment]
I think these will be of use to you:
https://www.codecademy.com/
https://developer.mozilla.org/en-US/docs/Web/JavaScript
https://nodejs.org/api/
http://tobyho.com/2011/06/08/the-javascript-stacktrace-blog/

annnnnddd
http://google.com
