### ISSUE TITLE
client.setAvatar() doesn't work

### ISSUE THREAD

**Issue by Medallyon** [hydrabolt/discord.js#284]
I just created a new bot-account and need to change this Avatar.
`client.setAvatar("URL", callback())` always returns success, but the Avatar does not update.

**Comment by acdenisSK** [comment]
You need to use a base64 string

**Comment by Lord-Ptolemy** [comment]
`.setAvatar` doesn't use a url. You need to use a base64 string or buffer.

Read the docs.
http://discordjs.readthedocs.org/en/indev/docs_client.html#setavatar-avatar-callback

**Comment by GoBJIuH** [comment]
Look at the docs again. It shouldn't be URL, it should be base64.
https://discordjs.readthedocs.org/en/latest/docs_client.html#setavatar-avatar-callback
https://discordjs.readthedocs.org/en/latest/docs_resolvables.html#id7

**Comment by TehSeph** [comment]
100% UN-Tested, but you could try something like so:
```
var request = require("request").defaults({ "encoding" : null });

request("URL", function (err, res, body) {
    if (!err && res.statusCode === 200) {
        var data = "data:" + res.headers["content-type"] + ";base64," + new Buffer(body).toString("base64");
        client.setAvatar(data, callback());
    }
});
```
