### ISSUE TITLE
playFile causing error: spawn help ENOENT

### ISSUE THREAD

**Issue by nfell2009** [hydrabolt/discord.js#286]
Hihi,

So I've just started using discord.js as it was the easiest to install. However, have been having a problem with trying to play a sound. Here is my code:

```javascript
var Discord = require("discord.js");
var bot = new Discord.Client();

bot.on("ready", function(message) {
	bot.joinVoiceChannel(bot.channels.get("name", "General"), function(){
		console.log("Joining #General");
	});
	setTimeout(function(){bot.voiceConnection.playFile("./TeaParty.mp3");}, 2000); 
});
```

`

The file TeaParty.mp3 exists and is in the same directory as the script that's being ran. It's a valid .mp3 file (works on my computer) and no other files work either. I saw that @meew0 said you need ffmpeg, so I installed that (npm install fluent-ffmpeg), while in the same directory as the script, but it still isn't working.

Any help would be very much appreciated!

Thank you :)

**Comment by meew0** [comment]
You don't need fluent-ffmpeg, you need the actual [FFmpeg program](https://www.ffmpeg.org/download.html) installed and somewhere in your PATH.

**Comment by nfell2009** [comment]
Thanks for your help @meew0! I'm just a bit lost on how to add ffmpeg to my path. I'm new to this whole Linux thing... (running Ubuntu 14.04 LTS if that's any help?).

**Comment by abalabahaha** [comment]
`sudo add-apt-repository ppa:mc3man/trusty-media && sudo apt-get update && sudo apt-get install ffmpeg`

**Comment by nfell2009** [comment]
Ran that and says I'm running the latest version. I get
stream.pipe is not a function
