### ISSUE TITLE
client.user.game vs msg.author.game

### ISSUE THREAD

**Issue by hsiw** [hydrabolt/discord.js#287]
`client.user.game` returns a string with the game name whereas `msg.author.game` returns an object with a name property. This is likely legacy code from when games also had an id assigned to them.

**Comment by TehSeph** [comment]
Games should be objects. This isn't legacy code, but rather just a mistake of someone setting `client.user.game` from `data.game.name` instead of setting it to the entire object.

**Comment by hsiw** [comment]
Only reason I was thinking it may be legacy code sort of stuff was because games used to be by both ID and Name but who knows.

**Comment by TehSeph** [comment]
Nah, games went from ID to Object. They've never been strings. :smiley:

**Comment by abalabahaha** [comment]
But we have perfect consistency /s
