### ISSUE TITLE
Unused client option: revive

### ISSUE THREAD

**Issue by ekmartin** [hydrabolt/discord.js#289]
Looks like it's been renamed to autoReconnect, but there's still some code left: 
https://github.com/hydrabolt/discord.js/blob/master/src%2FClient%2FClient.js#L49
https://github.com/hydrabolt/discord.js/blob/27a0361afcee2ffa5506d3cec534d3137c040f92/src/index.js#L15

If I'm not misunderstanding something?

**Comment by abalabahaha** [comment]
whoops
