### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by sig333** [hydrabolt/discord.js#291]
I followed the [instructions](http://discordjs.readthedocs.org/en/latest/installing.html) for installing this, but I don't know how I'm supposed to start editing a file. Do I just open a basic file in python/javascript or is there something in the discord.js file I have to open?

**Comment by Lord-Ptolemy** [comment]
I think you're better of by visiting these links first:

**Learn Javascript:**
https://www.codecademy.com/
https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Learn how to use Node.js:**
https://nodejs.org/dist/latest-v5.x/docs/api/

**Read Discord.js's docs:**
http://discordjs.readthedocs.org/en/indev/docs_client.html
