### ISSUE TITLE
messageUpdated event does not fire if message is not in cache

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#294]
as a possible enhancement the messageUpdate event could fire if the old message is not in the cach, and just supply the new message. This would increase consistency with the messageDeleted event and be usefull in my bot for filtering of messages are being updated but were sent before the bot was started.

**Comment by michaelowens** [comment]
I'm still having this issue in 9.3.0. Updating messages that were created before the bot connected will not fire `messageUpdate`

**Comment by Slamakans** [comment]
I can't seem to tell from my phone, but I think the changes were applied to indev, so check which branch you are using @michaelowens

**Comment by Gawdl3y** [comment]
This is an ancient change from pre-v9. Please create a new issue to request this feature.
