### ISSUE TITLE
have member update supply old user object as well.

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#296]
if http://discordjs.readthedocs.org/en/latest/docs_client.html#servermemberupdated were to supply the old user object as well as the new one it would save users having to cach the old user objects in order to detect changes simplifiying the bot development proccess.

**Comment by GexoXYZ** [comment]
Added with 9700f8577b4df08156e782af8d27020211cadb67

**Comment by macdja38** [comment]
Can confirm functioning though accedentaly deployed :+1:
