### ISSUE TITLE
removing avatar does not trigger presence update

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#297]
A user removing their avatar does not trigger a presence update.

**Comment by nfell2009** [comment]
Does a user changing their avatar trigger one?

**Comment by macdja38** [comment]
@nfell2009 yes it does. and to add to the issue the oldUser when the user add's their avatar back still contains the old avatar from before the user removed it. This should demo the issue.
https://cdn.discordapp.com/attachments/81385020756865024/174085441429962753/unknown.png

**Comment by macdja38** [comment]
issue may not be a lack of presence update being triggered, but a lack of change in the user object my code was being passed, which then caused it to not log an update (presence updates are spammy so I did not have them all being logged). Nexerq # pointed out that this line of code could be the issue.
https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1810

**Comment by macdja38** [comment]
Can Confirm it's fixed in 873f78b02a30157f49726009d7fdbb5d3496f178
