### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by lampmeorelse** [hydrabolt/discord.js#298]
Hello, I was wondering how I would be able to detect what people say, and create commands like ">ban <mention someone>" that would output <mention someone> to a variable, and it would trigger an if statement, such as banning the mentioned user.

**Comment by GexoXYZ** [comment]
uh. look at the docs? Do you know javascript?

**Comment by Lord-Ptolemy** [comment]
I think you're better of by visiting these links first:

**Learn Javascript:**
https://www.codecademy.com/
https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Learn how to use Node.js:**
https://nodejs.org/dist/latest-v5.x/docs/api/

**Read Discord.js's docs & Examples:**
http://discordjs.readthedocs.org/en/indev/docs_client.html
https://github.com/hydrabolt/discord.js/tree/master/examples

After you've got the basics down. You can then proceed to use this library to program a bot. Such issues as yours aren't a problem with the library, but your lack of knowledge on how to use it. Which the above links should help.
