### ISSUE TITLE
serverMemberRemoved only sends server.name and user.name

### ISSUE THREAD

**Issue by jnovack** [hydrabolt/discord.js#302]
The `serverMemberRemoved` emit does not emit a `Server` and `User` object as documented.

It currently only emits the `Server.name` and `User.name` strings.

**Comment by Programmix** [comment]
I can't confirm this; and I checked the library's code. It looks like everything's fine. Are you positive this is an issue with the library and not a user-error?

**Comment by jnovack** [comment]
`indev` branch is NOT doing this.
