### ISSUE TITLE
on presence Status seems reversed

### ISSUE THREAD

**Issue by Coffee4cr** [hydrabolt/discord.js#303]
```js
bot.on("presence", (usr) => {
    var now =  Date().toLocaleString()
    if (usr.status == 'offline'){
        console.log(usr.username + ' is now offline ['+now+']');
    } else if (usr.status == 'online') {
        console.log(usr.username + ' is now online ['+now+']');
    }
});
```
Every time I disconnect, I see the online message, and when I connect, I see the offline message.

**Comment by BrunoMoreira991** [comment]
Maybe you should read the docs. http://discordjs.readthedocs.io/en/latest/docs_client.html

> Supplies 2 User objects, the first being the old user, the second being the new, updated user.

**Comment by Coffee4cr** [comment]
Thanks @BrunoMoreira991 
My bad
