### ISSUE TITLE
Per Server Nickname support

### ISSUE THREAD

**Issue by TheDoctorsLife** [hydrabolt/discord.js#305]
As of https://blog.discordapp.com/2016-4-29-change-log/ Discord now supports per server nicknames.

**Comment by GexoXYZ** [comment]
see https://github.com/hydrabolt/discord.js/commit/b47540d6eb552ae331514299ce20427e2fb5ff00

**Comment by abalabahaha** [comment]
Implemented in indev, NPM release soon:tm:
