### ISSUE TITLE
Add new 'serverNickUpdated' event

### ISSUE THREAD

**Issue by brussell98** [hydrabolt/discord.js#306]
Currently there is no way to track when a user changes their nickname, as `serverMemberUpdated` only supplies the new user object and not the old one.

I'd like to hear people's opinions on adding an event for this.

**Comment by BrunoMoreira991** [comment]
I think there's no need for a new event, instead it could be passed/integrated on the user object and then we could just compare the old nickname with the new nickname to check for a change.

**Comment by Lord-Ptolemy** [comment]
http://discordjs.readthedocs.io/en/indev/docs_client.html#servermemberupdated
Is probably the event that will have it if it does not already.

**Comment by macdja38** [comment]
I think my issue https://github.com/hydrabolt/discord.js/issues/296 could solve this as well.
