### ISSUE TITLE
joined Server is undefined

### ISSUE THREAD

**Issue by MRVDOG** [hydrabolt/discord.js#309]
I am trying to get access to the server roles, but the second console log returns "undefined"

![image](https://cloud.githubusercontent.com/assets/4422624/14942278/ccd36df0-0faf-11e6-9e40-5af737cdcff4.png)

![image](https://cloud.githubusercontent.com/assets/4422624/14942290/2676abf6-0fb0-11e6-98ed-d8a26c50c83b.png)

I noticed in the documentation that it says "This will not work for OAuth bot accounts", is there a way to access this information using an OAuth Bot, I really need to access the server's roles

**Comment by hsiw** [comment]
The `serverCreated` event does exactly this.

**Comment by MRVDOG** [comment]
doesn't that only fire when a server is created?

**Comment by Lord-Ptolemy** [comment]
Yes.

**Comment by hsiw** [comment]
When you join a server it fires the `serverCreated` event

**Comment by MRVDOG** [comment]
ahhhh, okay, I thought it was if the bot created a server
![image](https://cloud.githubusercontent.com/assets/4422624/14942389/966a4438-0fb3-11e6-987f-d306f8cdfe6a.png)

**Comment by hsiw** [comment]
http://discordjs.readthedocs.io/en/latest/docs_client.html#servercreated is what you're looking for. `createServer` isnt an event `serverCreated` is.

**Comment by MRVDOG** [comment]
I know, I assumed the `createServer()` function fired the `serverCreated` event, not the `joinServer()` function

**Comment by MRVDOG** [comment]
anyways, thank you for your help :smile:
