### ISSUE TITLE
When a bot using a token receives a friend request, it crashes discord.js

### ISSUE THREAD

**Issue by Gorialis** [hydrabolt/discord.js#310]
Error happens at /lib/Client/InternalClient.js at line 87 and causes a "cannot read property 'add' of null" TypeError.

This is annoying because it means that people can intentionally crash your bot by sending it a friend request.

**Comment by hsiw** [comment]
Because you're not using a bot account and only logging in with a token I'd recommend you just login with the email/password associated with it, it *should* prevent that issue from happen.

**Comment by Gorialis** [comment]
I have two bots, one that does use a bot account, and one that doesn't. I experience this bug on both.
I can change the one that doesn't use a bot account to an email/password combination and that does remove the issue, but this still leaves the other one vulnerable to crashes at any time.

**Comment by hsiw** [comment]
I'd suggest updating to the latest `indev` build because I believe that this was recently fixed.

**Comment by Lord-Ptolemy** [comment]
@Gorialis What version of the library are you using? I reported this issue weeks ago and it was fixed.

**Comment by Gorialis** [comment]
Updating to the latest `indev` build seems to have fixed the issue, so it seems like the issue is only present on the `master` branch. Thanks for the help!
