### ISSUE TITLE
msg.author.bot reverts to false after a period of time

### ISSUE THREAD

**Issue by davidlimjh** [hydrabolt/discord.js#312]
Hello,

I have a bot that logs messages. I use msg.author.bot to ignore bots.
msg.author.bot initially returns a TRUE when a bot message is detected. However after a short period of time it will start returning a false even if it is a bot that sends the message.

**Comment by Programmix** [comment]
I don't see anywhere in the code where the `bot` property of User changes aside from when it's first initialized. Am I missing something? I think I've experienced this bug as well and I'm trying to figure out what the cause might be.
