### ISSUE TITLE
Rewrite Progress

### ISSUE THREAD

**Issue by hydrabolt** [hydrabolt/discord.js#313]
# About
As you may know, discord.js is being rewritten. This issue is to track the progress of the rewrite.

# Progress
## Guilds
* [x] Observe WebSocket Events
* [x] Creation
* [x] Leaving
* [x] Deletion
* [x] Kicking Members bbf0b0683a9ac1a8f509bf91a8c4e380dfb1d380
* [x] Banning Members
* [x] Unbanning Members
* [x] Getting Bans
* [x] Modifying Server Details (e.g. name) ab1737524821d2ad4a2176a7184ffbe1d68ae404
* [x] Create Invites
* [x] Delete Invites
* [x] Fetching All Members
* [x] Emojis

## Roles
* [x] Observe WebSocket Events
* [x] Creating Roles 849b8df2dad8ccc5196130418e010df200f76f3f
* [x] Deleting Roles 3cd91a19aae83082e9b3db0572ef16ce7ed8c067
* [x] Updating Roles 0d53afe3cec95bd4f4df51d186b860468d349cd6
* [x] Applying Roles to Members

## Channels
* [x] Observe WebSocket Events
* [x] Creation
* [x] Deletion
* [x] Modifying Channel Details (e.g. name, topic, bitrate)
* [x] Typing Simulation
* [x] Creating Channel Overwrites
* [x] Deleting Channel Overwrites
* [x] Updating Channel Overwrites
* [x] Track Users that are Typing
* [x] Track Users that are Speaking
* [x] Deafen/Mute Members
* [x] Move Members

## Client User
* [x] Observe WebSocket Events
* [x] Modify Details (e.g. Username, Avatar)
* [x] Set Nickname in Guilds
* [x] Emit Presence Updates

## Users
* [x] Observe WebSocket Events
* [x] Send DMs bc443df11dde22f20c0628d7409279e0cc4bc027
* [x] Delete DMs bc443df11dde22f20c0628d7409279e0cc4bc027
* [ ] Private calls

## Messages
* [x] Observe WebSocket Events
* [x] Creation
* [x] Editing
* [x] Deletion
* [x] Track Mentions
* [x] Send Files

## Voice Channels
* [x] Send Audio
* [x] Receive Audio
* [x] Join Channels

## Documentation
* [x] Inline Documentation
* [x] Example-Based Documentation

**Comment by Whipgit** [comment]
Has this been put on hold?

**Comment by GexoXYZ** [comment]
hydrabolt just wasn't here for quite some time, he probably doesn't have the time for it atm

**Comment by hydrabolt** [comment]
Starting up work on this again

**Comment by developerCodex** [comment]
Awesome I cannot wait for these awesome updates, when do you think you'll finish rewriting the code? 
@hydrabolt ?

- devCodex
discord.js user

**Comment by hydrabolt** [comment]
@developerCodex not making any promises, but hopefully in 4-5 weeks

**Comment by developerCodex** [comment]
Alright, thanks for replying so fast. Now will the website documentation be updated too?

**Comment by hydrabolt** [comment]
@developerCodex the readthedocs documentation should be replaced with JSDocs and inline documentation.

**Comment by developerCodex** [comment]
@hydrabolt Alright, thanks for telling me/notifying me I appreciate the feedback and quick response time(s).

**Comment by hydrabolt** [comment]
Rewrite has been published!
