### ISSUE TITLE
voiceConnection.stopPlaying() throws Error: write EPIPE

### ISSUE THREAD

**Issue by Farami** [hydrabolt/discord.js#314]
Hi. For some reason voiceConnection.destroy() as well as stopPlaying() both throw

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at Socket._writeGeneric (net.js:681:26)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at clearBuffer (_stream_writable.js:404:7)
    at onwrite (_stream_writable.js:340:7)
    at Socket.stream.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:781:12)
```

I am calling it like this:
```javascript
      this.discordClient.voiceConnection.stopPlaying();
```

**Comment by Farami** [comment]
The error gets thrown by `this.streamProc.stdin` in stopPlaying.
Hooking the error event onto it will prevent the entire process from crashing.

**Comment by abalabahaha** [comment]
what are you passing to playXXX()?

**Comment by Farami** [comment]
```javascript
that.discordClient.voiceConnection.playRawStream(stream, { volume: that.currentVolume });
```

Stream is a raw stream from another library called node-spotify-web. The playback is working perfectly.

**Comment by abalabahaha** [comment]
Possibly similar to the ytdl error, where the stream still tries to send data to discord.js after discord.js closed its receiving stream.
