### ISSUE TITLE
mybot.voiceConnection.playRawStream not sending data

### ISSUE THREAD

**Issue by MRVDOG** [hydrabolt/discord.js#316]
HI, I am trying to get my bot to stream music over Voice, my bot is joining VC, but nothing comes through, I have checked voice debugging and it seems something happens as the "last packet received" resets
![image](https://cloud.githubusercontent.com/assets/4422624/14963039/bbf55f62-1099-11e6-8348-5c6505f68354.png)

could this be a problem with the bot running on a windows machine? I haven't got a linux machine to test this on, I updated my discord.js to #indev in hopes this would fix the issue, but it hasn't, anyone got any ideas?

here is the code I have:
![image](https://cloud.githubusercontent.com/assets/4422624/14963153/4a86937c-109a-11e6-861e-3f9fad8c8bc6.png)

it is getting through the code as it's sending a message to the chat
![image](https://cloud.githubusercontent.com/assets/4422624/14963198/73f7b5ba-109a-11e6-9d0e-33e984097f4f.png)

**Comment by abalabahaha** [comment]
Can you hop on the discord.js Discord channel? It's easier to help from there

**Comment by MRVDOG** [comment]
sure, I don't have mic hooked up at the moment though, as in the process if moving things around

**Comment by abalabahaha** [comment]
Its a text channel

**Comment by MRVDOG** [comment]
ahh yeah, I assume it's #node_discord-js? if so I'm there :grin:
