### ISSUE TITLE
'Symbol' is undefined error in IE11

### ISSUE THREAD

**Issue by lyze237** [hydrabolt/discord.js#318]
Dear Developers,

I can't get the example on your website and a self written version of it with the newest version of the "web-dist" version to work.

It always gives me a 'Symbol' is undefined error when I load up the page.

Clicking on the button "Run" on your demo page results then into a "'Discord' is undefined" error: http://i.imgur.com/zUCQ9PA.png

**Comment by meew0** [comment]
`Symbol` is an ES6 thing that IE11 doesn't support. You'll have to use a different browser.

**Comment by lyze237** [comment]
Ah alright. That's stupid :v

I'm basically trying to create a website which is mobile friendly so a couple friends of mine, which use windows phone (uses windows 11 mobile), can also write "on the go" with us in discord.

**Comment by hydrabolt** [comment]
You could always add [es6-symbols](https://github.com/medikoo/es6-symbol) to polyfill the Symbol ;)

**Comment by lyze237** [comment]
Ahh thanks for the info!
