### ISSUE TITLE
Using notes.

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#327]
Ability to read and modify notes would be great. It would allow us to record thing's about people, use eval commands or whatever in notes. and idk what else. maybe a database system?

**Comment by meew0** [comment]
Notes are client side only though, so the benefit would be limited

**Comment by abalabahaha** [comment]
Still useful

**Comment by Programmix** [comment]
Has Discord released an API for note reading/writing?

**Comment by abalabahaha** [comment]
If the client can do notes, there must be an endpoint somewhere

**Comment by Programmix** [comment]
Update on this: talked to Jake.
He told me that notes are disabled for bot accounts. Only non-OAuth accounts can use it. So, this feature unfortunately wouldn't be very useful at all. :/

**Comment by abalabahaha** [comment]
Still going to add it

**Comment by GexoXYZ** [comment]
Added in https://github.com/hydrabolt/discord.js/pull/423
