### ISSUE TITLE
Issue with invisible error on voiceConnection.playFile()

### ISSUE THREAD

**Issue by Numil** [hydrabolt/discord.js#330]
Here's my code: 

`bot.voiceConnection.playFile("http://s1download-universal-soundbank.com/mp3/sounds/3672.mp3",{volume:0.5});`
bot being: 
`var bot = new Discord.Client();`
Can someone help me ?

**Comment by GexoXYZ** [comment]
We can help you on the API server https://discord.gg/0SBTUU1wZTV8g9iI
It's mostly a problem with ffmpeg or node-opus
