### ISSUE TITLE
Long-running bot disconnects

### ISSUE THREAD

**Issue by ryanfl** [hydrabolt/discord.js#335]
I'm finding that my bot seems to disconnect after running for a long period (~12hrs+), yet no logs or errors are thrown. Is this on behalf of rate limiting or something? Right now, it's just a listening bot however.

**Comment by GexoXYZ** [comment]
Are you using the autoReconnect option on your client object? 
It's not unusual that bots disconnect.

**Comment by abalabahaha** [comment]
Cloudflare drops connections after a while, try turning autoReconnect on
