### ISSUE TITLE
CheckQueue

### ISSUE THREAD

**Issue by Deukhoofd** [hydrabolt/discord.js#34]
Noticed you removed the CheckQueue function from the client scripts, but are still calling it in updateMessage, sendFile and sendMessage functions. This breaks these functions. Is there a solution to this other than manually copying the old checkqueue function back in the client scripts?

**Comment by hydrabolt** [comment]
Hi, adding the queue convoluted the code quite a bit, so I don't think I'll be adding it back anytime soon.

However, you can add the code back yourself or you can make a helper function in your own code, sorry about that!
