### ISSUE TITLE
bot.setStatus won't display the game on discord

### ISSUE THREAD

**Issue by kjuy86t** [hydrabolt/discord.js#340]
process: function(bot, msg) {
        bot.setStatus("online", "potato")
    
},

**Comment by ThePsionic** [comment]
Setting the game happens with the method `bot.setPlayingGame(String)`, e.g. `bot.setPlayingGame(potato)`.

**Comment by kjuy86t** [comment]
Still doesn't work.

**Comment by abalabahaha** [comment]
Make sure you are checking from another account, Not the bot user account.

Also make sure you are setting it after the ready event, not before.

**Comment by kjuy86t** [comment]
this crashes the bot D:

**Comment by abalabahaha** [comment]
@kjuy86t o.o what error?

**Comment by kjuy86t** [comment]
2016-05-11T22:02:56.926401+00:00 app[worker.1]: treating !games from <@105747712481173504> as command
2016-05-11T22:02:57.795927+00:00 heroku[worker.1]: Process exited with status 1

**Comment by kjuy86t** [comment]
nothing helpfull

**Comment by abalabahaha** [comment]
[Can we work this out on the Discord channel](https://discord.gg/0SBTUU1wZTYd2XyW)

**Comment by dylanh724** [comment]
> For future people, check to make sure you aren't using a 3 month old version of discord.js

This is probably because any guides googled go to an obsolete docs site at the very top, that is apparently represented by official discord.js team --

![image](https://cloud.githubusercontent.com/assets/8840024/26237707/ddf59dde-3ca8-11e7-996d-9a963c8ebb08.png)


Should probably get someone to post a note at the top that these docs are old. Or hell, take the site down.

**Comment by iCrawl** [comment]
>May 12, 2016

Don't necro please.

**Comment by CyberiumShadow** [comment]
But he just wants the reddit karma

**Comment by Kalazbb** [comment]
Use : 
```js
client.setGame("GAME");
```
is works at me

**Comment by Lewdcario** [comment]
@Kalazbb, please check dates before posting. The first message was on `May 11, 2016`.
