### ISSUE TITLE
Expose the server username of a User

### ISSUE THREAD

**Issue by ThePsionic** [hydrabolt/discord.js#341]
I'm not too well versed in the Discord API so I don't know whether this is actually possible, but it would be great if we could get the username of a certain User in a certain Server.

**Comment by abalabahaha** [comment]
server.members is a list of Users in the server

What would you identify users by? That is, what would differentiate the user you want from other users in the server?

**Comment by ThePsionic** [comment]
It's rather easy to get an User object from a Message, the Users would remain to be differentiated by their snowflakes.

**Comment by macdja38** [comment]
how would you want to get the user?

**Comment by abalabahaha** [comment]
would `server.members.get("id", "INSERT SNOWFLAKE HERE")` work

**Comment by ThePsionic** [comment]
Not sure why eg. `message.author.getNickname(message.channel.server)` wouldn't work.

**Comment by abalabahaha** [comment]
ohh we're talking about nicknames...

message.channel.server.detailsOf(message.author).nick

**Comment by ThePsionic** [comment]
Doesn't seem to work, returns `undefined`. It's also not included in the docs: http://discordjs.readthedocs.io/en/latest/docs_server.html#detailsofuser-user

**Comment by macdja38** [comment]
use indev http://discordjs.readthedocs.io/en/indev/docs_server.html#detailsofuser-user

**Comment by abalabahaha** [comment]
oh yeah it hasn't made it to stable/NPM yet

**Comment by ThePsionic** [comment]
Ah. Any ETA on this? It's not exactly critical but it'd be nice to have ASAP.

**Comment by macdja38** [comment]
you can use indev, change the version in your package.json from from 7.0.1 or whatever to hydrabolt/discord.js#indev and then use npm install again.

**Comment by ThePsionic** [comment]
Hm, on indev `message.channel.server.detailsOf(message.author).nick` returns `null`.

**Comment by brussell98** [comment]
That means the user has no username

**Comment by ThePsionic** [comment]
Yeah I realised that after the fact :P Nothing a simple if-statement can't fix. Thanks for the help all, I got it working now :+1:

**Comment by ThePsionic** [comment]
One small thing I noticed: if the user has reset their username (at least with /nick, haven't tested through the interface), the `nick` field remains filled with the last known nickname of the User.

**Comment by abalabahaha** [comment]
0e5a1d2 should fix that
