### ISSUE TITLE
Using "setPlayingGame" gives me an error.

### ISSUE THREAD

**Issue by Jumpman204** [hydrabolt/discord.js#348]
When using setPlayingGame in my bot, I get this error: " TypeError: Cannot set property 'status' of undefined. "  Is there any way I can fix this? 
(My code is below, I'm 99% sure there are no errors in terms of syntax and how I'm the function.)
```js
bot.setPlayingGame("Use |help for a list of commands!")

**Comment by GexoXYZ** [comment]
You need to call it after the bot is ready.
eg on the ready event
`client.on('ready' () => {
//here
});`
