### ISSUE TITLE
Circular JSON Structure Error (Related to Roles)

### ISSUE THREAD

**Issue by Programmix** [hydrabolt/discord.js#349]
I recently encountered this error when trying to add / remove roles from users. My best guess is that it was caused by the role resolving update (https://github.com/hydrabolt/discord.js/commit/e7882a38ee144fc2c3528bf929937aa9655ed28f)

Reverting to the commit before that one fixed the issue.

![screen shot 2016-05-15 at 8 48 16 am](https://cloud.githubusercontent.com/assets/13167687/15275240/dd6b0dd2-1a7a-11e6-933d-31bc124bcb6d.png)

**Comment by GexoXYZ** [comment]
Someone else was getting this error aswell. So confirmed i guess

**Comment by abalabahaha** [comment]
are you logging the roles? @Programmix

**Comment by Programmix** [comment]
@abalabahaha This is my code. The error occurs for both addMemberToRole and removeMemberFromRole.

![screen shot 2016-05-15 at 10 08 08 am](https://cloud.githubusercontent.com/assets/13167687/15275601/02a2fe34-1a85-11e6-8866-81fa36c83e04.png)

**Comment by abalabahaha** [comment]
Hmm... Can someone give steps to reproduce?

**Comment by abalabahaha** [comment]
Fixed with 9015bb8
