### ISSUE TITLE
.playFile() not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by GoldenChrysus** [hydrabolt/discord.js#352]
Here is the relevant code:

```
voiceConnection.playFile("./music.mp3", { volume: 0.5 }, function (error, streamIntent) {
	streamIntent.on("error", function (error) {
		console.log("error " + error);
	});

	streamIntent.on("time", function (time) {
		console.log("time " + time);
	});

	streamIntent.on("end", function () {
		console.log("end");
	});
});
```

I have verified this works on Windows, but I cannot get it to work on Ubuntu 14.04. I have CHMODed the music file to add read, write, and execute privileges. ffmpeg and avconv are both installed and can be executed through terminal with their respective commands. Path to ffmpeg is /usr/bin/ffmpeg as it should be.

I suspect there is some sort of ffmpeg error (because I also had ffmpeg issues on Windows) but I don't know what it could be. The bot does not crash, but the console output from the above code is just "end" meaning the end-of-file flag has triggered.

**Comment by GexoXYZ** [comment]
Can you come on the [Discord API server](https://discord.gg/0SBTUU1wZTVboNjO)? This is mostly easily resolved

**Comment by GoldenChrysus** [comment]
Followed the instructions provided in the chat:

> novoice: Some questions to consider:
> Did you install Python 2.7.x correctly? If not, install it correctly and try reinstalling. Windows see https://python.org/downloads/. Linux and OSX should have this already, but if not, use the OS's package manager.
> 
> Did you install FFMPEG correctly? If not, install it correctly and try reinstalling. Windows users, try http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/. Linux, use your OS's package manager (apt-get/yum/pacman) (If Ubuntu 14.04, install https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/). OSX, use brew to install it.
> 
> Did you install Visual Studio with C/C++ (Windows), build-essential (Linux), or Xcode CLI tools (OSX)? If not, install the corresponding program, then try reinstalling discord.js: npm install --save discord.js
> 
> Did discord.js install correctly? If not, or not sure, try reinstalling discord.js: 
> npm cache clean
> npm install --save discord.js
> 
> Did node-opus install correctly? If not, or not sure: 
> npm cache clean
> npm install node-opus
> 
> Are you using the latest version of discord.js and other dependencies? npm update --save discord.js
> 
> Also, are you reading the docs? http://discordjs.rtfd.org/

- Ensured Python 2.7.x is installed
- Installed build-essential
- Installed node-opus
- Reinstalled discord.js
- ffmpeg and avconv both are recognized

Doing all of this seemed to resolve the reading of the file. The console outputs the current time of the file's playhead, so it does seem to be playing the file. That said, there is still no actual audio playing in the voice channel (whereas I ensured again that the exact same code works on Windows).

**Comment by briantanner** [comment]
This sounds like it could be an issue with ffmpeg either not being installed correctly, or not in path.

**Comment by GoldenChrysus** [comment]
Unsure how to determine if it is an ffmpeg issue. I installed using the instructions [here.](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) 

I can execute commands like
`ffmpeg -i ~/music.mp3 -acodec libopus -b:a 100000 -vbr on -compression_level 10 ~/music.opus`
without issue. But still no audio in the voice connection.
