### ISSUE TITLE
dgram throws 'Not running'

### ISSUE THREAD

**Issue by GexoXYZ** [hydrabolt/discord.js#353]
![eyj1cmwioijodhrwoi8vas5pbwd1ci5jb20vctg3zvb6zs5wbmcifq xa0o9assjfukfxbmhf_guxacbam](https://cloud.githubusercontent.com/assets/13241270/15377656/a8432802-1d5d-11e6-926c-e7fc7c2b9c9c.png)

so dsyelxic just got this after disconnecting the bot while playing a song

**Comment by briantanner** [comment]
This error occurs after every `connection.destroy()` for me as well

**Comment by abalabahaha** [comment]
Fixed with 3fa3b02
