### ISSUE TITLE
[Quesiton] Reply messages with mention and without and private messages

### ISSUE THREAD

**Issue by Lukkez** [hydrabolt/discord.js#355]
how to make the bot reply messages without mention and make them reply private messages, and if u guys know, make a command like ~calc (math calc) just like ~calc 29 * 2 ~calc 28 + 88

**Comment by Lord-Ptolemy** [comment]
I think you're better of by visiting these links first:

**Learn Javascript:**
https://www.codecademy.com/
https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Learn how to use Node.js:**
https://nodejs.org/dist/latest-v5.x/docs/api/

**Read Discord.js's docs & Examples:**
http://discordjs.readthedocs.org/en/indev/docs_client.html
https://github.com/hydrabolt/discord.js/tree/master/examples

After you've got the basics down. You can then proceed to use this library to program a bot. Such issues as yours aren't a problem with the library, but your lack of knowledge on how to use it. Which the above links should help.

**Comment by Banderi** [comment]
I would like to know this as well, as it's not a knowledge issue, rather a question regarding the library's functions. The docs do not mention if you must use RegEx to split the mentions from the messages (which is a hassle to learn anyways, and therefore should not be treated as common knowledge) or if there's a command to return the clean message content.

**Comment by frank1iu** [comment]
Can't you just override `Discord.Message.prototype.reply`?

**Comment by Banderi** [comment]
I don't think rewriting a method in a module is much easier than using RegEx. Really, the best way would be to have simple member like a `Message.InnerContent` separate from the main `Message.Content`, or have a `Message.Content.NoMentions` submember.
