### ISSUE TITLE
"Connections" such as Twitch and future services

### ISSUE THREAD

**Issue by macharborguy** [hydrabolt/discord.js#36]
are any of the new 'Connections' features that Discord just implemented coming thru the API as of yet?  as of right now, only Twitch is supported, but others will be made available in the future.

I hope to tie our Twitch IRC bot into Discord as well using Discord.js, and am rewriting the bot to make use of both independently, as well as a user manager.   I am going to add in a way for users to in effect link their accounts at the bot level, but if any of the Twitch information is passed along via their API, and thru Discord.js, that could save quite a bit of time.

**Comment by hydrabolt** [comment]
I'll look into it, but probably not :(

I just don't want the API getting bloated

**Comment by hydrabolt** [comment]
Yeah, unfortunately this probably isn't going to happen. The API is mainly meant to be lightweight, and I don't think that everyone using the API would want to use Twitch with it. So unfortunately, you'll have to be able to add it in by yourself
