### ISSUE TITLE
User.voiceChannel sometimes undefined

### ISSUE THREAD

**Issue by Programmix** [hydrabolt/discord.js#360]
I've noticed that occasionally, discord.js won't have the VoiceChannel of a user cached, even if they're in one. A few people I know have confirmed that this issue occurs for them as well.

**Comment by abalabahaha** [comment]
Might be that the lib doesn't parse the voice_state sent during guild create/ready

**Comment by macdja38** [comment]
That's probably it, having the user rejoining works.

**Comment by Programmix** [comment]
Yeah. Whenever people tell me that it isn't detecting users being in voice channels, I tell them to rejoin, and that fixes it.

**Comment by macdja38** [comment]
That's actually my bot's thing when it can't tell what voice channel people are it. it seems to only happen recently after the bot is restarted.

**Comment by Programmix** [comment]
Just checked the code; the lib does seem to parse voice_states on READY/GUILD_CREATE. Perhaps there's some issue with how it's being parsed?

**Comment by abalabahaha** [comment]
Still unable to reproduce on latest indev, reproduction instructions would be nice

**Comment by macdja38** [comment]
1) have user join a voice channel
2) turn on bot
3) check the user's voice channel, this will sometimes fail.

**Comment by GexoXYZ** [comment]
(Probably) fixed with https://github.com/hydrabolt/discord.js/commit/f49f1ab3c8d0354e5021d7ff8eb721196e96020f
