### ISSUE TITLE
loginWithToken doesn't show any errors?

### ISSUE THREAD

**Issue by unlucky4ever** [hydrabolt/discord.js#361]
I seemed to have noticed that when I do the callback for loginWithToken to get the errors and stuff, it returns nothing at all.

I purposely put in a wrong token to force it to throw the errors that it's supposed to throw.

When installing the npm I used `hydrabolt/discord.js#indev`

Here is my code.
```javascript
console.log("Logging in...");
bot.loginWithToken(process.env.TOKEN, (err, token) => {
  if (err) {
    console.log(err);
    setTimeout(() => {
      process.exit(1);
    }, 2000);
  }

  if (!token) {
    console.log(cWarn(" WARN ") + " failed to connect");
    setTimeout(() => {
      process.exit(0);
    }, 2000);
  }
});
bot.on("disconnected", () => {
  console.log(cRed("Disconnected") + " from Discord");
});
```

This is literally all that shows in my console...
![screenshot from 2016-05-22 02-05-25](https://cloud.githubusercontent.com/assets/974995/15452813/b03997d8-1fc1-11e6-8ce9-91da3430464c.png)

**Comment by briantanner** [comment]
It wasn't an error but a disconnect from discord. you can handle that by enabling autoReconnect such as...

```js
var bot = new Discord.Client({autoReconnect: true});
```

**Comment by abalabahaha** [comment]
loginWithToken will not validate your token
