### ISSUE TITLE
channel.permissionsOf(user) should support role objects as well

### ISSUE THREAD

**Issue by clydejallorina** [hydrabolt/discord.js#362]
This should make our lives much easier.

Upd8: Check comment below.

**Comment by abalabahaha** [comment]
You could get the role permission overwrite by looking in channel.permissionOverwrites for an overwrite with the same ID as the role...

Or do you also want the calculated server-level role permissions?

**Comment by clydejallorina** [comment]
I want the calculated server role perms.

Which makes this wrong so I guess this can be closed?
