### ISSUE TITLE
Mentions not properly parsed for custom server usernames

### ISSUE THREAD

**Issue by pezcode** [hydrabolt/discord.js#364]
You can change [usernames per server](https://support.discordapp.com/hc/en-us/articles/219070107-Server-Nicknames):
Without a custom username mentions appear like `<@198251925>  hello` but if you change the bot's name you'll get `<@!198251925> hello` (note the `!`).
Discord.js doesn't seem to parse the latter version, and `message.mentions` ends up being empty and `message.isMentioned` returns `false`.

**Comment by GexoXYZ** [comment]
Are you on the latest indev?

**Comment by pezcode** [comment]
No, I'm on 7.0.1 from npm. Is this fixed on indev?

**Comment by hsiw** [comment]
Yes

**Comment by pezcode** [comment]
Alright, I guess this can be closed then.
Thanks for the fast replies!
