### ISSUE TITLE
Random bot crashing... don't have any clue what it means.

### ISSUE THREAD

**Issue by Appa2015** [hydrabolt/discord.js#365]
My bot randomly crashed and left me with: 
https://gyazo.com/ca7ab11fbb523f74d62e5edfb809efc6
I don't know what it means :/

**Comment by BrunoMoreira991** [comment]
Is this still happening? It looks like a network problem to be honest. But could be your code... probably.

**Comment by abalabahaha** [comment]
Feels like a DNS issue
