### ISSUE TITLE
getInvite not returning valid Invite Object

### ISSUE THREAD

**Issue by tankerkiller125** [hydrabolt/discord.js#370]
I am putting the invite URL in correctly however the returned Invite Object incorrect. I have also tried using just the Invite Code without the URL portion and get the same results. I have also experimented with infinite and timed invites and both return the same basic Object.

```js
Invite {
  maxAge: undefined,
  code: '0qwPf0WZWbvq6Qmg',
  channel: { type: 'text', id: '152871118972256256', name: 'general' },
  server: 
   { splash_hash: null,
     id: '152871118972256256',
     name: 'Tankerkiller125' },
  revoked: undefined,
  createdAt: NaN,
  temporary: undefined,
  uses: undefined,
  maxUses: undefined,
  xkcd: null }
```

Is it a possibility that I'm not using it correctly? Or maybe `joinServer()` is not correct is some way?

**Comment by Programmix** [comment]
Quick question -- Is the account you're experiencing the bug on an OAuth accounts?
OAuth accounts are unable to accept invitations.

**Comment by tankerkiller125** [comment]
I have tried it with standard login as well.

**Comment by Programmix** [comment]
No, but is your account an OAuth account? Doesn't matter how you're logging in.

**Comment by abalabahaha** [comment]
Seems valid for a basic invite object. Does your bot have Manage Channel permissions in that channel?
