### ISSUE TITLE
FFMPEG process pileup

### ISSUE THREAD

**Issue by Programmix** [hydrabolt/discord.js#372]
This could be a question or a bug; I'm honestly not sure. Basically, through the course of my music bot running, it generally accumulates large sums of FFMPEG processes that never die and use up a fair bit of RAM. AFAIK, I am stopping the audio correctly. Any idea why this might occur?

**Comment by macdja38** [comment]
I seem to be having the same issue with imortal FFMPEG processes.

**Comment by Programmix** [comment]
Not sure how to fix this issue. I tried modifying AudioEncoder to terminate the FFMPEG encoding process when it finishes. However, processes still end up not being terminated. Can't seem to figure out why.

**Comment by Programmix** [comment]
Should be solved by #390! :D
