### ISSUE TITLE
Integrate API Error codes

### ISSUE THREAD

**Issue by GexoXYZ** [hydrabolt/discord.js#377]
https://github.com/hammerandchisel/discord-api-docs/issues/61

**Comment by abalabahaha** [comment]
How would this be "integrated"?

**Comment by GexoXYZ** [comment]
Thought this was something else when I first saw it. My bad.

**Comment by meew0** [comment]
It could still be useful to implement so errors thrown by, say, a bot trying to do something without permission, are more descriptive than just the HTTP errors superagent throws

**Comment by GexoXYZ** [comment]
But in the end the error codes just correspond to a message, which we already get (?)
