### ISSUE TITLE
Cannot iteratively remove roles from a user

### ISSUE THREAD

**Issue by Medallyon** [hydrabolt/discord.js#378]
See http://pastebin.com/Nq8q4dng

I try to iteratively remove roles from a user, but it will only ever remove a single role, instead of all of them. I thought it was a rate-limiting issue at first (hence the timeout), but that doesn't seem to be the problem. I also tried `console.log`ing and it turns out it iterates over all roles (and doesn't stop at the first one), but simply doesn't remove them.

**Comment by GexoXYZ** [comment]
Note that you can pass an array of roles to removeMemberFromRole

**Comment by Medallyon** [comment]
No way, I'll try that immediately.

**Comment by Medallyon** [comment]
That works.
