### ISSUE TITLE
Bot fails silently if message sent is over 2000 characters

### ISSUE THREAD

**Issue by ammuench** [hydrabolt/discord.js#379]
Right now the bot will fail silently if the sendMessage or reply commands are used with messages greater than 2000 characters

**Comment by GexoXYZ** [comment]
Cannot comfirm, it throws provides an error in the callback

**Comment by ammuench** [comment]
Running:
```javascript
bot.sendMessage(channel, "Message with 2000 characters...");
```

Doesn't output any indication that it failed.  Just tested.  Even a console output saying "failed to send message due to character limit" would be helpful

**Comment by Samutz** [comment]
Try
```
bot.sendMessage(channel, "Message with 2000 characters...", function(error){
    if (error) console.log(error);
});
```

Most discord.js function have callbacks that provide error objects if an error occurred.

**Comment by abalabahaha** [comment]
It's really up to you to listen for errors, which are returned in both the callback and Promise.catch forms, and handle them however you want
