### ISSUE TITLE
User.bot not working correctly

### ISSUE THREAD

**Issue by BitQuote** [hydrabolt/discord.js#389]
Returns false for many bots that show the "BOT" tag in the app.

**Comment by abalabahaha** [comment]
any more data for this? like under what circumstances this happens?

**Comment by BitQuote** [comment]
I'm not really sure. It seems to be random, even for the same bot. It changes between restarts.

**Comment by Medallyon** [comment]
Can confirm: http://i.imgur.com/how4PWM.png

Although this doesn't fix for me when restarting. Still says false for the same bots.

**Comment by abalabahaha** [comment]
Can you check if this happens under each condition:
* The user was online before the bot started
* The user went offline => online after the bot started
* A server member was edited (roles, nickname) before coming online

**Comment by hydrabolt** [comment]
Should be fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)
