### ISSUE TITLE
voiceLeave user voiceChannel broken?

### ISSUE THREAD

**Issue by ChrisTalman** [hydrabolt/discord.js#398]
Is it intended behaviour that the `voiceLeave` event supplies a `user` object with a `voiceChannel` property that is always `null`?

I have recently updated discord.js to what I assume is the master branch. Previously, the `voiceChannel` property could be accessed on a `user` object supplied by a `voiceLeave` event to determine whether the user has disconnected from voice, or switched to another channel. This is no longer possible in the version that I am now using.

**Comment by Programmix** [comment]
Try switching to the `indev` branch instead of the `master` branch and see if that solves your issue.

**Comment by ChrisTalman** [comment]
@Programmix Upon your advice I tried `indev`. The problem appears to remain there.

**Comment by abalabahaha** [comment]
can you hop on the [discord.js channel](https://discord.gg/0SBTUU1wZTYd2XyW)

**Comment by GexoXYZ** [comment]
voiceLeave's callback passes voiceChannel and user. Just use the voiceChannel instead.

**Comment by ChrisTalman** [comment]
@GexoXYZ The `voiceChannel` passed to the callback is the channel that the user has left. I am seeking the channel that they are now in, if at all. Before I updated to a newer version of discord.js recently, I was able to rely upon `user.voiceChannel` to determine whether the user has switched to another channel or simply disconnected. This was a reliable method which worked every time. In the new version of discord.js, this method no longer works. I would like to know whether this is an intentional change, or a bug.

**Comment by abalabahaha** [comment]
Intentional. Maybe a voiceSwitch event should be added...

**Comment by abalabahaha** [comment]
Added convenience `voiceSwitch` event to indev, `on("voiceSwitch", (oldChannel, newChannel, user) => {})`

Also it appears user.voiceChannel could have been updated earlier, so I think your method should work again (again, change is on indev branch)
