### ISSUE TITLE
Add timeout option to client.awaitResponse

### ISSUE THREAD

**Issue by brussell98** [hydrabolt/discord.js#401]
Something like
`client.awaitResponse(msg, 'Please reply in 10 seconds...', {timeout: 10000}).then...`

This will prevent the client from being stuck waiting for a user to send a message.

**Comment by staentomic** [comment]
Yea this would be really helpful

**Comment by rocket0191** [comment]
Yes, please!

**Comment by hydrabolt** [comment]
Rewritten in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2), it's now known as [`client.awaitMessages`](http://hydrabolt.github.io/discord.js/index.html#!/docs/tag/master/class/TextChannel?scrollto=awaitMessages) and has support for timeout and many other features.
