### ISSUE TITLE
bot.logout doesn't work with promise

### ISSUE THREAD

**Issue by mees-** [hydrabolt/discord.js#406]
I was testing the time certain actions take when i encoutered an error:
this code works fine
```javascript
bot.logout(() => {
        console.timeEnd("logout");
        process.exit(0);
      });
```

but this code never triggers the `console.timeEnd("logout");`
```javascript
  bot.logout()
      .then(() => {
        console.timeEnd("logout");
        process.exit(0);
      });
```

i thought all the functions that support callback should also support promises

**Comment by GexoXYZ** [comment]
Can't reproduce, works perfectly fine for me, no matter what indentation or anything.

**Comment by abalabahaha** [comment]
On second thought, probably linked to #409
