### ISSUE TITLE
logout() does not seem to be working.

### ISSUE THREAD

**Issue by MarioGraceZ22** [hydrabolt/discord.js#409]
The function logout() seems to have unexpectedly stopped working recehently in my bot, which is rather odd to me since it had never responded this way. It is very likely that I am doing something wrong with my coding or perhaps the way I setup things. I am currently using loginWithToken to get the client to log in, but whenever logout is called, it returns the "Error: Forbidden."

This is the login code:
`var auth = require("./auth.json");`
`bot.loginWithToken(auth.token, function (error, token) {`
  `  if (error) {`
    `    console.log(error);`
`    }`
  `  else {`
      `  console.log("Successfully logged in.")`
   ` }`
`})`

This is the logout code:
`bot.logout(function (error) {`
                           ` if (error) {`
                                `console.log(error);`
                                `bot.sendMessage(msg.channel, "Woops, errors! " + error);`
                          `  }`
`});`

Any help is appreciated! Sorry if I'm making a dumb mistake.

**Comment by abalabahaha** [comment]
Logout is intended for user accounts (with email and password login), and does nothing for bot accounts. If you want to terminate the gateway connection, use bot.disconnect() instead.

**Comment by abalabahaha** [comment]
Actually, I lied, apparently disconnect() does not exist in this lib...
