### ISSUE TITLE
playFile(); mp3 file not working

### ISSUE THREAD

**Issue by kylonx** [hydrabolt/discord.js#415]
Hey guys!
I'm trying to play a MP3-File in a voice channel, but it's not working.

```
bot.on('message', (msg) => {
  if(msg.content == 'join') {
    video.pipe(fs.createWriteStream('current.mp3'));
		bot.reply('joined');
		bot.joinVoiceChannel('174428230890160129');
  }

  if(msg.content == 'play') {
    //audio not playing
    console.log('play now');
    bot.voiceConnection.playFile('current.mp3', {});
  }
});
```

I don't know what I doing wrong, but I hope you can help me.
Best Regards

**Comment by BrunoMoreira991** [comment]
What is not working, does it join the voice channel? More details would be helpful. I don't know exactly what you're trying to do on line 3, but anyway...

If you're trying to play a mp3 file named `current.mp3` on line `bot.voiceConnection.playFile('current.mp3', {});` and it is located on the root of your project then it should be `bot.voiceConnection.playFile('./current.mp3');`

If after this "fix" it still doesn't work the issue is most likely ffmpeg and other dependencies missing:

**Please follow this instructions:**

> novoice: Some questions to consider:
> Did you install Python 2.7.x correctly? If not, install it correctly and try reinstalling. Windows see https://python.org/downloads/. Linux and OSX should have this already, but if not, use the OS's package manager.
> 
> Did you install FFMPEG correctly? If not, install it correctly and try reinstalling. Windows users, try http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/. Linux, use your OS's package manager (apt-get/yum/pacman) (If Ubuntu 14.04, install https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/). OSX, use brew to install it.
> 
> Did you install Visual Studio with C/C++ (Windows), build-essential (Linux), or Xcode CLI tools (OSX)? If not, install the corresponding program, then try reinstalling discord.js: npm install --save discord.js
> 
> Did discord.js install correctly? If not, or not sure, try reinstalling discord.js: 
> npm cache clean
> npm install --save discord.js
> 
> Did node-opus install correctly? If not, or not sure: 
> npm cache clean
> npm install node-opus
> 
> Are you using the latest version of discord.js and other dependencies? npm update --save discord.js
> 
> Also, are you reading the docs? http://discordjs.rtfd.org/

**Comment by abalabahaha** [comment]
Also hop on the [discord.js Discord channel](https://discord.gg/0SBTUU1wZTYd2XyW)

**Comment by kylonx** [comment]
@abalabahaha Write me on Discord, I'm Kylon

**Comment by Avon1** [comment]
i have the same problem when i run my bot in the linux vpn but it's ok in windows how to resolve this

**Comment by hydrabolt** [comment]
You'll need to install FFmpeg binaries, the easiest way is `npm install ffmpeg-binaries`.

Please try to avoid posting on really old issues next time!

**Comment by Avon1** [comment]
no its a problem with the new update 4.0.0 i still like the 3.2.2-3

**Comment by Avon1** [comment]
"discord.js": "^11.3.2",
    "ffmpeg-binaries": "^3.2.2-3",
    "opusscript": "0.0.6" 
installed these packages but throws a errors
https://media.discordapp.net/attachments/222081003253006336/465867011801612298/unknown.png?width=960&height=251

**Comment by ItsJust4You** [comment]
install ffmpeg
