### ISSUE TITLE
WebSocket handler is too volatile

### ISSUE THREAD

**Issue by Programmix** [hydrabolt/discord.js#416]
One annoying issue I've noticed with discord.js is that the message handler for the websocket is very volatile. If an error occurs anywhere while parsing and handling the websocket event, the entire handler will simply break. This should not be the case. The library should be able to continue receiving events, even after some error happens to occur.

**Comment by hydrabolt** [comment]
The WebSocket handler will now just emit an error on invalid packets rather than breaking as of [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)
