### ISSUE TITLE
server.members.length != Discord Members Length

### ISSUE THREAD

**Issue by Medallyon** [hydrabolt/discord.js#419]
When I `eval server.members.length`, I get `298` [(image)](http://i.imgur.com/Tv4aS9w.png)
When I go to `Discord's Server Settings`, it says `305` [(image)](http://i.imgur.com/OHz9A4H.png)

This doesn't block any functionality (so far), it's just somewhat bothering me.

**Comment by GexoXYZ** [comment]
Are you using the `forceFetchUser` parameter for your client object?

**Comment by Medallyon** [comment]
No.
