### ISSUE TITLE
`presence` event does not trigger game status updates

### ISSUE THREAD

**Issue by eslachance** [hydrabolt/discord.js#420]
Discord version: 8.0.0
NPM: 2.15.5
Node: 4.4.5

Issue: `client.on('presence', (olduser, newuser) =>` not triggered on game update.

Description: The following code should presumably trigger whenever a user starts playing a game, but it does not in the current version: 

```
bot.on("presence", (userold, usernew) => {
	console.log("Presence Changed!");
});
```

As a workaround, it's possible to capture the `raw` event instead, check for `event.t == "PRESENCE_UPDATE"` and go from there. Unfortunately this does not provide the "old" object for comparison, which is sad.

**Comment by Kogs** [comment]
This is happening again for me. Workaround still works.
