### ISSUE TITLE
playFile end event emitted early

### ISSUE THREAD

**Issue by Deixel** [hydrabolt/discord.js#422]
I'm trying to have my bot connect to a voice channel, play a file, then disconnect once it's finished, but the bot keeps disconnecting much earlier than expected.
```javascript
mybot.joinVoiceChannel(message.author.voiceChannel, function(error, voiceConnection)
		{
			if(error)
			{
				console.error(error);
			}
			voiceConnection.playFile("sound.mp3", function(error, intent)
			{
				if(error)
				{
					console.error(error);
				}
				intent.once("end", playbackFinished());
			});
		});
```
```javascript
function playbackFinished()
{
	setTimeout(function(){mybot.leaveVoiceChannel(myUser.voiceChannel)}, 5000);
}
```

Based on the docs, I'd expect the outcome to be
1. Join channel
2. Playback starts
3. Playback ends
4. 5 second wait
5. Leave channel.
But what actually happens is
1. Join channel
2. Playback starts
3. 5 seconds later, leave channel mid playback.

If I remove the 5 second wait, it leaves the channel immediately after joining. With a console.log at the start of playbackFinished, it seems it's being called as soon as playback starts.

**Comment by GexoXYZ** [comment]
How long is your mp3? You may need to set an offset:

```The end event is emitted once playback ends. Depending on various factors, it may be emitted a couple seconds earlier than the actual stream ending, you may have to add an offset if necessary.```
as found [in here](http://discordjs.readthedocs.io/en/indev/docs_voiceconnection.html#playfile-path-options-callback)

**Comment by Deixel** [comment]
It's 15 seconds long.

**Comment by GexoXYZ** [comment]
Can you hop on the [Discord.js channel](https://discord.gg/0SBTUU1wZTYd2XyW)

**Comment by GexoXYZ** [comment]
For anyone interested, it was caused by this line `intent.once("end", playbackFinished());`.

It's a function **call** not a **signature**, hence fixed by this: `intent.once("end", playbackFinished)`
