### ISSUE TITLE
Details found in `server.detailsOfUser()` should be found in `server.members` Cache

### ISSUE THREAD

**Issue by eslachance** [hydrabolt/discord.js#425]
At the moment, with the `server.detailsOfUser()` implementation, it's possible to get the Nickname of a User, through `msg.server.detailsOfUser(user).nick` . However, it's impossible to obtain a User object from a Nickname. 

User Details in relation to a server should be added to the user cache if possible, meaning it would be possible to search a user by those details. For example, `server.members.get("nick", "LuckyEvie")` 

While we're at it, having access to the `mute`, `selfMute`, `deaf` and `selfDeaf` could be useful as a list filter.

**Comment by abalabahaha** [comment]
Not a worthwhile change IMO
