### ISSUE TITLE
Error when joining voice channel

### ISSUE THREAD

**Issue by bokisa12** [hydrabolt/discord.js#429]
So this is what I have so far: 

	Bot.on('ready', () => {
		let voiceChannelId = Bot.channels[1].id;
		Bot.joinVoiceChannel(voiceChannelId, (error, voiceConnection) => {
			if(!error) console.log(`Connected to voice channel`)
			else console.error(error);
			voiceConnection.playFile('./file.mp3');
		});
	});
	Bot.login(botDetails.mail, botDetails.pass);

The bot successfully joins the voice channel (I can see it), but in the console I get this error: 

    events.js:160
          throw er; // Unhandled 'error' event
          ^

    Error: spawn help ENOENT
        at exports._errnoException (util.js:949:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
        at onErrorNT (internal/child_process.js:348:16)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)

The path for the file is right and the file is not corrupt. What's the problem here? Thanks.

**Comment by GexoXYZ** [comment]
https://github.com/hydrabolt/discord.js/issues/418

**Comment by bokisa12** [comment]
@GexoXYZ I didn't even had ffmpeg installed. Thanks.

**Comment by bokisa12** [comment]
@GexoXYZ Just installed ffmpeg, still not working. Same error. Ffmpeg is working correctly in the command line.

**Comment by bokisa12** [comment]
@GexoXYZ Alright, now I don't get any errors, but the sound is simply not playing. I'm in the same voice channel as the bot, he's not muted, but nothing is coming through.

**Comment by GexoXYZ** [comment]
Do you get any errors when installing d.js?

**Comment by bokisa12** [comment]
@GexoXYZ Nope, the bot itself works perfectly (text messages, etc.), it's just that the audio for some reason doesn't play.

**Comment by GexoXYZ** [comment]
Can you do
 ```js
voiceConnection.playFile('./file.mp3', (err, intent) => {
    console.log(err);
});

**Comment by bokisa12** [comment]
@GexoXYZ Null, no error.

**Comment by bokisa12** [comment]
@GexoXYZ No error means that it should be playing, right? The strange thing is that if it was playing there should be a green circle around the bot's icon (under the voice channel). There's no green circle around the icon.

**Comment by GexoXYZ** [comment]
This sounds like opus didn't compile properly. Errors in installation don't mean that it won't work. Can you recheck?

**Comment by bokisa12** [comment]
@GexoXYZ So when I installed discord.js I didn't have XCode CLI Tools installed so opus didn't compile at all. Now I reinstalled it (this time opus did compile), tried again, but still no luck, same as before. Although I did get a warning while installing discord.js: 

    ../src/node-opus.cc:41:1: warning: 'OpusEncoder' defined as a class here but previously declared as a              
    struct [-Wmismatched-tags]
    class OpusEncoder : public ObjectWrap {
    ^
    ../src/../deps/opus/include/opus.h:164:9: note: did you mean class here?
    typedef struct OpusEncoder OpusEncoder;
            ^~~~~~
            class
    1 warning generated.

**Comment by bokisa12** [comment]
@GexoXYZ I want to kill myself right now. I've been using the wrong filename for the .mp3 file. I'm so fucking done.

**Comment by bokisa12** [comment]
@GexoXYZ Anyways, it works. Thanks for the help!

**Comment by GexoXYZ** [comment]
ayy lmao
