### ISSUE TITLE
users remain in voice channel members list after leaving.

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#430]
Users seem to remain in my bot's voiceChannel members cach even after they have disconnected from the voice channel. Tested using my eval command.

To replicate:
1) Have a few people join a voice channel, my bot was also in the voice channel, not sure if that's important.
2) Have them leave.
3) Test that they remained in the cach, I ran the code:
```javascript
bot.voiceConnections.filter((connection)=>{return connection.server.id == 77176186148499456})[0].voiceChannel.members
```
with the number being the server id. this returns a list of username's if printed you should see users that have left the voice channel, assuming you are also effected by the bug.

**Comment by eslachance** [comment]
I have a very similar issue which I was about to start troubleshooting (great timing, Mac!). In my case I'm filtering the list of voice channels and getting the total number of channels with between 1 and 5 members. This becomes wrong quickly, as the result increments itself as time goes by (I'm not doing reduce or keeping this result - I evaluate it every 15 minutes). So yes it does seem like the cache does not update when a user leaves a voice channel. 

My code: 

```js
let voiceChans = server.channels.filter(c => c instanceof Discord.VoiceChannel&&c.name!="AFK");
query.full_groups = voiceChans.filter(c=>c.members.length > 5).length;
query.partial_groups = voiceChans.filter(c=>c.members.length<6&&c.members.length>0).length;
```

Right now that says 8 partial, 1 complete. There are only 3 partials and 1 complete.

**Comment by macdja38** [comment]
not sure if they were leaving or moving to a different voice channel, just to add to that.

**Comment by macdja38** [comment]
I can confirm this issue is still happening 
http://i.imgur.com/BWP0F6B.png
