### ISSUE TITLE
TypeError: Cannot read property 'roles' of undefined

### ISSUE THREAD

**Issue by TheRealKev1n** [hydrabolt/discord.js#435]
Hello, I keep getting this error while setting a role for a user. Can someone help me?

TypeError: Cannot read property 'roles' of undefined

Thanks,
Kevin

**Comment by GexoXYZ** [comment]
Whats your code around line 32 and what discord.js version are you using?

**Comment by TheRealKev1n** [comment]
Im using the example to test it didnt change anything but the login and the role

Line 32: var role = msg.server.roles.get("name", "VIP");

**Comment by GexoXYZ** [comment]
msg.server does only exist in discord.js 8.0.0+
Update it.

Otherwise it'll also error if you're trying to set a role in a dm.

(Also your email+pass is exposed)

**Comment by TheRealKev1n** [comment]
Where is the email + password exposed? Just using the example

**Comment by GexoXYZ** [comment]
Will delete this post in 10min
http://test.futurisonline.nl/examples/permissions/adminbot.js

**Comment by TheRealKev1n** [comment]
@GexoXYZ ah yeah i see need to fix that then im new to this so im just testing, And yes could you delete it please
