### ISSUE TITLE
Bot message next line

### ISSUE THREAD

**Issue by TheRealKev1n** [hydrabolt/discord.js#439]
Hello, 

Is it possilbe for the bot to go to the next line within the same message? 
Now i'm doing this:

```
 bot.sendMessage(msg.channel, "Online users:");
 bot.sendMessage(msg.channel, "user 1");
 bot.sendMessage(msg.channel, "user 2:");
```

but sometimes the order is incorrect

would be nice if i could do something like this:
` bot.sendMessage(msg.channel, "Online users:" + '<br>' + "user 1" + '<br>' + "user 2" );`

Thanks,
kevin

**Comment by GexoXYZ** [comment]
`"Line 1 \n Line 2"`

**Comment by AndrewWalla** [comment]
use `\n` to create a new line, is like `<br>`

**Comment by Dev-Yukine** [comment]
could people stop responding to old and already solved/closed issues, jeez,

**Comment by iranathan** [comment]
lol
