### ISSUE TITLE
[Request] Don't uglify code for npm

### ISSUE THREAD

**Issue by smitetierlist** [hydrabolt/discord.js#44]
There is no real benefit in uglifying code before shipping it.

It just makes life worse for me when investigating into the source code.

**Comment by TehSeph** [comment]
@smitetierlist m8 pls. https://github.com/hydrabolt/discord.js/tree/master/src

**Comment by abalabahaha** [comment]
NPM is for shipping production versions, not for development. If you want source, [source folder](https://github.com/hydrabolt/discord.js/tree/master/src)

**Comment by hydrabolt** [comment]
As it's in NPM and being shipped for production, I won't stop uglifying code - it minifies it for production to reduce the overall size of your application. If you want the source code, please see the links @TehSeph and @abalabahaha have posted.

Please also know that the API is going under a rewrite, so if you want to see the latest developments please check the rewrite branch.

**Comment by Pepperrika** [comment]
We like ugly code ;)

**Comment by smitetierlist** [comment]
Okay, I'll accept that. 

Anyway: what is the benefit of uglifying the code? It's a very small code base.
When one really wants to run uglified code on a server (I don't see any benefit here) they could implement it easily in their deploy script.

Rewrite branch: Do you have planned / expect massive breaking changes? I'm just starting my new project.

**Comment by abalabahaha** [comment]
@smitetierlist I believe from Discord chats that there will be a major stability overhaul in the coming 5.x rewrite, so probably breaking changes.

You could ask the dev and other programmer people questions on the [Discord API server](https://discord.gg/0SBTUU1wZTYd2XyW) linked in the README, probably will get a faster response.

**Comment by hydrabolt** [comment]
@smiteteirlist there are general breaking changes all around, but most will only take a few minutes to fix so I'd say your safe to start with the master branch as it has docs etc

**Comment by hydrabolt** [comment]
@smitetierlist ^^
