### ISSUE TITLE
Bot won't recognise everyone's games

### ISSUE THREAD

**Issue by Medallyon** [hydrabolt/discord.js#442]
I've tried catching all my games via the presence event, but since the update, it only catches some users' games.

Upon evaling `msg.author.game.name` while playing any game, it presents me with the message `TypeError: Cannot read property 'name' of null`. The same applies to *some* other members of the server, but not all.

Side Note, How do I properly check if someone's playing a game via `presence`? I always do `if (newMember.game !== null) {...}`

**Comment by abalabahaha** [comment]
The check is right.
Hmm...

**Comment by SPMNJ** [comment]
I think we should just make `user.game` a string instead of an object so that it won't cause this error

**Comment by hydrabolt** [comment]
Fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2). `user.game` is an object as it can contain streaming data.
