### ISSUE TITLE
How to use awaitResponse function

### ISSUE THREAD

**Issue by donnes** [hydrabolt/discord.js#447]
Hi, if this is not the place for it.

I don't know exactly how use the function awaitResponse, someone can send a practical example?

Thanks

**Comment by GexoXYZ** [comment]
This should be a nice example:
```js
if(msg.content === "quiz") {
	bot.awaitResponse(msg, "What color is the sky?")
	.then(nextMessage => {
		if(nextMessage.content.toLowerCase() === "blue") {
			bot.sendMessage(msg, "Correct :tada:");
		} else {
			bot.sendMessage(msg, "Wrong!!");
		}
	});
}
```

For smaller questions like these people will help on https://discordapp.com/invite/0SBTUU1wZTYd2XyW
