### ISSUE TITLE
'presence.game.type - TypeError' Checking if streaming.

### ISSUE THREAD

**Issue by BobDodoBird** [hydrabolt/discord.js#448]
_Apologies if this is a duplicate, I am extremely new to GitHub._

I am _trying_ to check oldPresence.game.type vs. newPresence.game.type, originally ["presence"](http://discordjs.readthedocs.io/en/latest/docs_client.html#presence) didn't work at all until **I added the fix from indev #421**.

_An idea of what I am trying to do..._

```
1> bot.on("presence", (oldPresence, newPresence) => {
2> 	  if(newPresence.game.type){
3> 	      console.log("[PRESENCE UPDATE] - STREAMING - ", newPresence.game);
4> 	  }else{
5> 	      // Other stuff...
6> 	  }
7> });
```

The **error occurs when a presence update's game property is empty.**
_(newPresence or oldPresence)_ 
`game.type` / `game.name`
> TypeError: Cannot read property 'type' of null
TypeError: Cannot read property 'name' of null

Although correctly returns **null** when not specifying a property of a presence update not playing a `game`; no errors.

I have tried:
```
JSON.stringify(newPresence.game.type)
list.newPresence.game.type
newPresence.game.type != undefined
newPresence.game.type == undefined
newPresence.game.type != null
newPresence.game.type == null
```
If anyone can offer a different way of checking if `game.type` is null/undefined.  Unless this is a bug/error that is going to have to wait until its fixed.  _I understand this whole "presence" is a current bug in-itself, but if the indev fix was supposed to fix this?_

**P.S. -** _I am extremely new to Javascript and NodeJS; just recently diving into it with a friend _(headfirst)_.  Trying to go on my experience from Java, C# & C++._

**Comment by abalabahaha** [comment]
presence.game has the potential to be null if the user isn't playing a game. Thus, you get this error when you do presence.game.type (null.type), since null has no properties. Check if presence.game is null before checking its properties
