### ISSUE TITLE
Grabbing the ID of message from bot.sendMessage

### ISSUE THREAD

**Issue by gaarb** [hydrabolt/discord.js#450]
How can I do this?

**Comment by eslachance** [comment]
In the callback, you have access to the new message: 

```js
bot.sendMessage(msg, "This is a message", function(error, newmsg) {
  console.log(newmsg.id);
}
```
For smaller questions you'll get quick help on [Discord API#node_discord.js](For smaller questions you'll get quick help on Discord API#node_discord.js)

**Comment by gaarb** [comment]
Alright cool, thanks :)

**Comment by gaarb** [comment]
Also, I'm trying to get it to add to a json file. I've tried everything like: 
```json
db["messages"].push({"id": newmsg.id});
&&
db["messages"]["id"] = newmsg.id;
```

Can I have some help? or look somewhere else...

**Comment by eslachance** [comment]
Please, just join the Discord API server it will make this much easier (and won't spam our channel with github update notifications, as well as 3 ppl's emails)

**Comment by gaarb** [comment]
Okay.

**Comment by eslachance** [comment]
I literally did that in my first reply though.
