### ISSUE TITLE
Issue with memberHasRole

### ISSUE THREAD

**Issue by pro8lot** [hydrabolt/discord.js#451]
I'm doing a check to see if someone has the "Owner" role that I made, but whenever I attempt this, I get Error: Invalid role. Here is my code: 
var ownercheck = bot.memberHasRole(message.author, "Owner");

**Comment by dbkynd** [comment]
Try 
``var ownercheck = (message.author.id === message.server.owner.id);``

**Comment by pro8lot** [comment]
Thank you so much! I finally accomplished what i wanted!

**Comment by GexoXYZ** [comment]
The above code will only check for the actual server owner though. For
others looking at this issue in the future, a role name is not a role
Resolvable. To get a role object from a name use
`message.server.roles.get("name", "Owner")`. You can use that object in the
memberHasRole function.

**Comment by pro8lot** [comment]
@GexoXYZ I would like to do that to allow my moderators to have the perms, but I am completely lost on how to do so with memberHasRole
