### ISSUE TITLE
Make role command

### ISSUE THREAD

**Issue by Lukkez** [hydrabolt/discord.js#453]
How to make a command to make a role like "!role create "name of role" #000000" (!role create test #000000) and to delete roles using !role delete "name of role", i am having problems, and if someone can help, how to create a variable who can be changed typing because i am looking to make some custom commands to my bot

**Comment by GexoXYZ** [comment]
Take a look at [`client.createRole`](http://discordjs.readthedocs.io/en/indev/docs_client.html#createrole-server-data-callback) and [`client.deleteRole`](http://discordjs.readthedocs.io/en/indev/docs_client.html#deleterole-role-callback).

To find a role by its name you can use the Cache helper function [`get`](http://discordjs.readthedocs.io/en/indev/docs_cache.html#get-key-value)
For example `server.roles.get('name', 'ROLENAME')`

**Comment by Lukkez** [comment]
Thanks

**Comment by EdemPlayzPC** [comment]
that doesn't exist???

**Comment by dragonfire535** [comment]
Look at the date on this issue.

**Comment by HorizonTM** [comment]
Nice meme 👌
