### ISSUE TITLE
Setting a channel topic a 2nd time throws server error.

### ISSUE THREAD

**Issue by msudol** [hydrabolt/discord.js#455]
I'm trying to have my bot set a channel topic as a regular task with some information and it has been crashing, so I wrote a test command to trigger it manually, and it continues to crash.  Oddly, the first time I tell the bot to set the channel topic it runs flawlessly.  However if I have the bot set a channel topic a 2nd time I get this:

```
2016-07-05T21:48:11.389Z WARN Channel Topic Set Error
2016-07-05T21:48:11.425Z WARN
{ message: 'Internal Server Error',
  stack: 'Error: Internal Server Error\n
  at Request.callback (/home/discordbot/node_modules/discord.js/node_modules/superagent/lib/node/index.js:698:17)\n    
  at IncomingMessage.<anonymous> (/home/discordbot/node_modules/discord.js/node_modules/superagent/lib/node/index.js:922:12)\n
  at emitNone (events.js:72:20)\n
  at IncomingMessage.emit (events.js:166:7)\n    
  at endReadableNT (_stream_readable.js:913:12)\n    
  at nextTickCallbackWith2Args (node.js:442:9)\n    
  at process._tickCallback (node.js:35617)',
  original: null,
  response:
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: [Object],
     request: [Object],
     req: [Object],
     links: {},
     text: '{"code": 0, "message": "int() argument must be a string or a number, not \'NoneType\'"}',
     body: [Object],
     files: {},
     buffered: true,
     headers: [Object],
     header: [Object],
     statusCode: 500,
     status: 500,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error: [Object],
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 500 }
```

This is my code:

```
			var checkChan = null;
			var chanList = this.bot.channels;
			if ((opts !== undefined) && (opts !== null)) {
				var jopts = config.tryJSON(opts);  // makes sure is valid json
				if (jopts !== false) {
					checkChan = chanList.get("name", jopts.name);
					
					this.bot.setChannelTopic(checkChan.id, jopts.msg, function(error) {
						if ((error !== undefined) && (error !== null))  {
							logger.warn("Channel Topic Set Error");
							logger.warn(error);
						}
						else {
							logger.info("setChannelTopic: " + checkChan.id + " " + jopts.msg);
						}
					});
				}
				else {
					logger.warn("setChannelTopic options are not valid JSON");
				}
			}
			else {
				logger.warn("setChannelTopic failed to execute, did you do it right?");
			}
```

Even if I sent the bot an invalid channel or topic message (which i'm not doing), it should still fail gracefully should it not?  Instead the bot crashes, and I really can't make sense of that error trace.  Any suggestions or is this a possible bug?

**Comment by GexoXYZ** [comment]
That's an error from the discord api, `int() argument must be a string or a number, not 'NoneType'`. 
So either you or the lib is fucking up, Try updateChannel and report back

**Comment by msudol** [comment]
I did updateChannel with basically the same code, first topic update is successful, subsequent attempts to do channel topic update fail with same error, I'm going to add a log message to make sure I'm not somehow passing a null or undefined value to the command - not sure how to explain how it's working on the first attempt and then failing.  Will report back with my findings with more logging / sanity checking.

**Comment by abalabahaha** [comment]
Might be missing `color`

**Comment by GexoXYZ** [comment]
Channels don't have colors :eyes:

**Comment by msudol** [comment]
From the docs - no need for position on setChannelTopic

```
setChannelTopic(channel, topic, callback)
Sets the topic of a channel
    channel - A Channel Resolvable
    topic - A String
    callback - function taking the following:
            error - error if any occurred
```

For update channel note the usage of the word **any**, for which is would seem that position would be optional..  I'll add position to the updateChannel call but, that still won't help with setTopic. 

```
updateChannel(channel, data, callback)
Updates the settings of a channel
    channel - A Channel Resolvable
    details - object containing **any** of the following:
            name - String, the new name of channel
            topic - String, the new topic of the channel (TextChannel only)
            position - Number, the new position of the channel
            userLimit - Number, the new user limit of the channel (VoiceChannel only)
            bitrate - Number, the new bitrate (in kb/s) of the channel (VoiceChannel only)
    callback - function taking the following:
            error - error if any occurred
```

**Comment by msudol** [comment]
Update - I did a very basic debug test with no variables. The bot listens for doTopic1 and doTopic2 and tries to set the topic of the channel with the ID hardcoded.  doTopic1 succeeeds, doTopic2 fails with the same error as above

```
		case "doTopic1":
			this.bot.setChannelTopic("178570760615362561", "test1", function(error) {
				if ((error !== undefined) && (error !== null))  {
					logger.error(error);
				}
			});
			break;
			
		case "doTopic2":
			this.bot.setChannelTopic("178570760615362561", "test2", function(error) {
				if ((error !== undefined) && (error !== null))  {
					logger.error(error);
				}
			});
			break;
```

Some digging at the code for discord.js I think the problem relates to the use of the superagent library in internalclient.js (since it works once then fails on a second call, something must be getting held over from the first call and not being cleared, seems like superagent is expecting a request length to be sent.....)   - I just haven't had the time to really dig into the code yet, I made a fork and will work on it and make a PR if I can I just don't have a lot of time...

**Comment by GexoXYZ** [comment]
Found the problem :tada:
I think I don't have to add a lot more to this:
```js
{ name: 'general',
  topic: 'test1',
  position: 0,
  user_limit: undefined,
  bitrate: undefined }
// Second call
{ name: 'general',
  topic: 'test2',
  position: 0,
  user_limit: undefined,
  bitrate: NaN }
```

Gonna try to fix and PR

**Comment by GexoXYZ** [comment]
oh and also: https://github.com/hydrabolt/discord.js/issues/404

**Comment by abalabahaha** [comment]
Can someone confirm

**Comment by msudol** [comment]
I can confirm that this fix works, tested it out and I am able to set the channel topic multiple times now.
