### ISSUE TITLE
Pinned Message Support

### ISSUE THREAD

**Issue by bdistin** [hydrabolt/discord.js#457]
I understand pinned messages are a new feature to discord, but could support be added to the api to view/manage pinned tweets? 

It appears that discord supports it in their api/communication w/e. https://discordapp.com/developers/docs/resources/channel But I would have no idea where to look to fork/ push a patch back...

**Comment by GexoXYZ** [comment]
It's added on indev

**Comment by bdistin** [comment]
Opps, I see that now, sorry for this...
