### ISSUE TITLE
Create Commands with Arguments? Example: kick

### ISSUE THREAD

**Issue by Bluethefurry** [hydrabolt/discord.js#458]
Hello, i'm fairly new to Discord.js, and i havent figured out how to make a kick command that works like this: 
`kick @User231` 
i know how to make commands and such, but not with arguments like Players.

**Comment by jaimehrubiks** [comment]
There are many ways to do this
*The easiest one:
You test your string against the command
`if (message.content.startsWith("kick") )`
then you can split it by spaces: `var words = message.content.split(' ');`
and then you retrieve 
```
let usertokick;
if( words.length > 1 ) usertokick = words[1]
```
*Another approach:
You create a regular expression with groups:
`var kick = /^kick (.+)$/;
`Then you test it
```
if ( kick.test( message.content ) )
let username = kick.exec( message.content ).match[1];
```

**Comment by Bluethefurry** [comment]
Thanks for the Reply, i'm running into an issue when trying to kick a User, i always get the Error 
`TypeError: Cannot read property 'id' of null`
Here's my code:
`			if (m.content.startsWith("c:kick") )
				var words = m.content.split(' ');
			
			console.log("Kick command executed")
			channel = m.channel
			server = m.server
			var user_permissions = channel.permissionsOf(m.sender);
			var kickPermission = user_permissions.hasPermission("kickMembers");
			if(kickPermission) {
				let usertokick;
				if( words.length > 1 ) usertokick = words[1]
			console.log(usertokick+ " has been kicked")
			server.kickMember(usertokick)}}`

**Comment by TeeSeal** [comment]
Well, in your code "words[1]" would be a string (something like "<@1234567890>") while in order to kick someone you need a user object. You can get the user object from a mention in a message like: `m.mentions[0]` (gets the user object for the first mention in the message). Here's a code snippet that could work for you:

`
if (m.content.split(' ')]0] == "c:kick") {
  if (m.channel.permissionsOf(m.sender).hasPermission("kickMembers") {
    bot.kickMember( m.mentions[0], m.server, function(err) {
      if (err) console.log(err);
      console.log("Kicked " + m.mentions[0].username + ".);
      bot.sendMessage(m.channel, "User kicked.");
    });
  } else {
    bot.sendMessage(m.channel, "You don't have permission to kick.");
  }
}

`

**Comment by Bluethefurry** [comment]
@TeeSeal 
after alot of debugging of your code i ended up with this error upon kicking:

`    error:
      { Error: cannot DELETE /api/guilds/178890089374547979/members/199461099999854592 (403)
          at Response.toError (/usr/lib/node_modules/discord.js/node_modules/superagent/lib/node/response.js:106:13)
          at Response.setStatusProperties (/usr/lib/node_modules/discord.js/node_modules/superagent/lib/node/response.js:183:12)
          at new Response (/usr/lib/node_modules/discord.js/node_modules/superagent/lib/node/response.js:42:8)
          at Stream.<anonymous> (/usr/lib/node_modules/discord.js/node_modules/superagent/lib/node/index.js:918:22)
          at emitNone (events.js:91:20)
          at Stream.emit (events.js:185:7)
          at Unzip.<anonymous> (/usr/lib/node_modules/discord.js/node_modules/superagent/lib/node/utils.js:108:12)
          at emitNone (events.js:91:20)
          at Unzip.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:973:12)
        status: 403,
        text: '{"code": 0, "message": "Privilege is too low..."}',
        method: 'DELETE',
        path: '/api/guilds/178890089374547979/members/199461099999854592' },
`

code:

`			if (m.content.split(' ')[0] == "c:kick") {
				if (m.channel.permissionsOf(m.sender).hasPermission("kickMembers")) {
				c.kickMember( m.mentions[0], m.server, function(err) {
					if (err) console.log(err);
					console.log("Kicked " + m.mentions[0].username + ".");
					c.sendMessage(m.channel, "User kicked.");
				}) } else {
			c.sendMessage(m.channel, "You don't have permission to kick.");
			}
			}		`

**Comment by Bluethefurry** [comment]
Update: Resolved, bot group wasn't Ordered right, Thanks for the help everyone!
