### ISSUE TITLE
How to get bots to use discord commands?

### ISSUE THREAD

**Issue by PastaAdventures** [hydrabolt/discord.js#46]
i want my bot to be able to use /tts and @

**Comment by khionu** [comment]
Using commands? Idk about.

Mentioning people? Here
```js
var target = bot.getUser("username", stringWithUsername);
var response = target.mention + ", your message.";
bot.sendMessage(message.channel, response);
```

**Comment by PastaAdventures** [comment]
I'm getting this error now

http://i.imgur.com/aKIHSvE.png

**Comment by khionu** [comment]
..... replace "stringWithUsername" so that it is a variable that has the username in in...

**Comment by hydrabolt** [comment]
You can also make a message TTS by specifying the option parameter, check
the docs for Client.sendMessage for an example of this.

**Comment by khionu** [comment]
Good to know, re TTS

**Comment by PastaAdventures** [comment]
so msg.sender.username?

**Comment by hydrabolt** [comment]
If you want to mention them, no. If you just want their username, yep.

To mention do: msg.sender.mention() OR do msg.sender + ""

**Comment by khionu** [comment]
Or, if you want to mention the sender at the beginning `bot.reply(message, "what you want to tell them");

**Comment by PastaAdventures** [comment]
so this is suppose to send a tts msg?
if (msg.content === "!notice") {
bot.sendMessage(msg.channel, "Hey " + msg.sender.username + "!", true)
}

**Comment by khionu** [comment]
1) Learn JS
2) Read the Discord.JS documentation
3) Read what we said above.

**Comment by PastaAdventures** [comment]
i don't know what i'm suppose to specify it as, true and tts don't work

**Comment by khionu** [comment]
That's not what. "msg.sender.username" is just going to give you the string. That's not what I showed you to Mention them.

**Comment by PastaAdventures** [comment]
yeah, for this on i just want the string, but wan the bot to tts the whole msg

**Comment by hydrabolt** [comment]
Options is an object, not just true. You need to use:

{
    tts:true
}

**Comment by FredyTek** [comment]
hi @khionu what do you mean by replacing "stringWithUsername" as a variable, I am new to discord.js so could you kindly show men how you can do this in javascript, 

Thanks in advance!

**Comment by Azoy** [comment]
@FredyTek are you trying to send a message that mentions someone?

**Comment by abalabahaha** [comment]
Please don't revive old issues... Make a new one if you have a question

**Comment by FredyTek** [comment]
Yes @Azoy 
 I will @abalabahaha

**Comment by ChlckenWings** [comment]
can someone help me? what im trying to do is so if someone types "@botname hi" the bot will say whatever back but how do you get teh prefix to be the bots @?

**Comment by saysora** [comment]
@ChlckenWings I got that to work by simply watching the message.content to include client.user which is my bot.

So, for example:
`if(message.content.includes(client.user)){
message.channel.send('Yes?');
}`

Hope that helps.
