### ISSUE TITLE
client.updateChannel() does not properly update other channel position attributes

### ISSUE THREAD

**Issue by Brayzure** [hydrabolt/discord.js#466]
When using `client.updateChannel()` to set a channel's position, it does not increment the positions of any channels that are supposed to come after it, causing channels of the same type to have the same position attribute. Manually moving channels properly increments other channels, which leads me to assume this is a bug.

**Comment by hydrabolt** [comment]
Fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)
