### ISSUE TITLE
client.UpdateChannel(); updates only once.

### ISSUE THREAD

**Issue by Equinoxbig** [hydrabolt/discord.js#467]
So yeah here is my code : 

if (input.startsWith("TOPIC")) {
    text = message.content.split(" ")[1];
    bot.UpdateChannel(message, {topic: text});
}

(input is message.content.toUpperCase();)

and when I use the command it updates once then can't update anymore.

**Comment by GexoXYZ** [comment]
Should be fixed on indev

**Comment by abalabahaha** [comment]
Dupe of #455
