### ISSUE TITLE
playFile isn't sending audio

### ISSUE THREAD

**Issue by Aetylus** [hydrabolt/discord.js#469]
I have a fairly simple command that uses `VoiceConnection.playFile`. After everything is set up, it calls a function that contains the following:

    var file = '/library/sample.mp3';
    console.log('[Debug: Playing file ' + file + '... ]');
    console.log('[Debug: Status: ' + this.bot.voiceConnection.playing + ']');
    this.bot.voiceConnection.playFile(file, (err, intent) => {
       if (err) console.log(err);
       console.log('[Debug: Playing file ' + file + ']');
       console.log('[Debug: Status: ' + this.bot.voiceConnection.playing + ']');
       console.log('[Debug: Server: ' + this.bot.voiceConnection.server + ']');
       console.log('[Debug: Encoder: ' + JSON.stringify(this.bot.voiceConnection.encoder) + ']');
    });

Nothing appears to be going wrong, and the logging I put it also seems to support this:

>     [Debug: Playing file /library/sample.mp3... ]
    [Debug: Status: false]
    [Debug: Playing file /library/sample.mp3]
    [Debug: Status: true]
    [Debug: Server: MyServer]
    [Debug: Encoder: {"choice":"ffmpeg","volume":{"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":[{"type":"Buffer","data":[0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,255,255,1,0,255,255,0,0,255,255,0,0,1,0,0,0,1,0,0,0,0,0,1,0,255,255,0,0,1,0,255,255,1,0,255,255,254,255,1,0,255,255,1,0,0,0,0,0,0,0,0,0,1,0,255,255,1,0,0,0,0,0,255,255,255,255,0,0,255,255,1,0,0,0,1,0,255,255,1,0,0,0,255,255,0,0,0,0,0,0,255,255,255,255,1,0,0,0,1,0,1,0,255,255,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]}],"length":136,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":true,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{"end":[null,null,null],"error":[null,null],"close":[null,null]},"_eventsCount":7,"_writableState":{"objectMode":false,"highWaterMark":16384,"needDrain":false,"ending":false,"ended":false,"finished":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":true,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":"buffer"},"_volume":1}}]

However, it doesn't seem to output any audio. The bot has joined both the server and voice channel without any issues, but there's no green audio indicator and no sound from the Discord client side.

I'm currently running this in a nodejs Docker instance and everything else about the bot seems to work without issues. It's recognizing messages, performing any other non-playback related functions, and outputting all the correct text.

**Comment by abalabahaha** [comment]
Probably better if you joined [the Discord channel](https://discord.gg/0SBTUU1wZTYd2XyW), as there are a multitude of potential reasons for this.

**Comment by Aetylus** [comment]
Looks like I just had to update my node. Was using `FROM node:argon` in my `Dockerfile` - changed that to just be `FROM node` to pull the latest version and everything worked flawlessly after that.
