### ISSUE TITLE
Message author sometimes null

### ISSUE THREAD

**Issue by hydrabolt** [hydrabolt/discord.js#47]
This will be fixed in version 5.0.0, where caching and other things are heavily improved. It is also a breaking change so I do not recommend updating to it immediately when it is released.

**Comment by khionu** [comment]
Not only Author. It's either the Member or User object, but I'm not sure which. I get it sometimes from mentions.

**Comment by abalabahaha** [comment]
@khionu [message.author **is** a Member/User](http://discordjs.readthedocs.org/en/latest/docs_message.html#author)

And to add on to this issue, multiple people on Discord reported http://pastebin.com/f34V5bcc (crashed on boot).

**Comment by khionu** [comment]
I understand that. It's like saying one branch of a tree is infected, but actually it's farther up the branch.

**Comment by hydrabolt** [comment]
Fixed in v5
