### ISSUE TITLE
discord.js not found

### ISSUE THREAD

**Issue by GyllieGyllie** [hydrabolt/discord.js#471]
Hey,

I've tried to install discord.js today but I can't seem to get it to work.
I've reinstalled node.js 2 times, installed discord.js with the commands on the documentation but when i run the bot it says it can't find discord.js

So I asked a friend to do it and for him it works fine so no clue what's wrong on my end.

**Comment by eslachance** [comment]
Please read https://eslachance.gitbooks.io/discord-js-bot-guide/content/getting-started/the-long-version.html and follow each step.

**Comment by eslachance** [comment]
If you need further help join us on Discord: https://discord.gg/xfp8kqk

**Comment by GyllieGyllie** [comment]
Hey, that helped indeed. Thanks!
