### ISSUE TITLE
Granting, then removing roles from users removes both/all roles involved.

### ISSUE THREAD

**Issue by AlecGW** [hydrabolt/discord.js#472]
Whenever I try to add and then remove a role within the same execution, it grants the new role, then removes both roles. It also happens the other way around, but grants both instead.
I have no idea if this is something I'm doing, but I have no idea what could be causing it.

**Comment by abalabahaha** [comment]
Put one inside the callback of the other. As they are async requests, they may arrive in the wrong order.

**Comment by AlecGW** [comment]
Works like a charm! Thanks!
