### ISSUE TITLE
Audio streams occasionally randomly end

### ISSUE THREAD

**Issue by Programmix** [hydrabolt/discord.js#475]
No precise repro. Occasionally, streams will just end randomly. In my case, it occurs when playing a stream from ytdl-core.

**Comment by developerCodex** [comment]
Strange.

**Comment by Trismirite** [comment]
I have the same issue, very rare for me though.

**Comment by developerCodex** [comment]
@Trismirite @Programmix Do both of you have the updated verison of npm, git, node and discord.js? And do you have indev or just the regular?

**Comment by Programmix** [comment]
Using latest npm, node v6.3.1, latest git, discord.js#indev

**Comment by jaimehrubiks** [comment]
I'm not sure if you refer to the same bug that occasionally ends streams earlier than sound track, which has been there for a long time without solution.

**Comment by Programmix** [comment]
The timing of the cutoff seems to be mostly random. Always happens at different points in the song, anywhere from the beginning, to the middle, to the end.

**Comment by Rinsworth** [comment]
This seems to happen a lot to me. It seems moreover that music that is longer than 5 minutes have this issue. Also, the beginning of music that is played gets a little bit unstable, but improves after around 10 seconds.

**Comment by Programmix** [comment]
Would like to add something to this discussion. I've noticed that what happens in my case is that about half of all audio streams on a particular shard will end at once. Unsure what causes the issue.

**Comment by developerCodex** [comment]
Hm, is there any error code you have gotten in your console, do you have sharding? Also, it could be that there is to many music being played at once and people are spamming it. Check all that out and mention me with a reply. @Programmix

**Comment by Trismirite** [comment]
My bot is on one server and it still happens to me... >_>

**Comment by Hyper-Coder** [comment]
I've been having this happen a ton to me. It occasionally just stops playing within a second of starting.

**Comment by hydrabolt** [comment]
Should be fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2) - voice is a lot more stable

**Comment by fbagjug** [comment]
Years down the line this happens to me. No errors no nothing so I am not too sure, the audio stream just randomly ends without saying anything after a few minutes of the song.

**Comment by transGirl-alice** [comment]
> Years down the line this happens to me. No errors no nothing so I am not too sure, the audio stream just randomly ends without saying anything after a few minutes of the song.

this, I'm having the same issue, but in a bot thats only in 2 servers, one of which is dead

**Comment by transGirl-alice** [comment]
I think the issue should be reopened
