### ISSUE TITLE
[Question] How do i return all of the servers someone is in?

### ISSUE THREAD

**Issue by TrueXPixels** [hydrabolt/discord.js#478]
Hello ;

I was wondering how I would go about grabbing all of the servers that a user is in using their ID.

Where i am at now:

I have their ID, but i just need the list of servers they are in.

**Comment by macdja38** [comment]
well, assuming your not sharded you have two options.. do you want ALL the servers they are in, or do you want all the servers they and your bot are in? the first requires a bunch of complicated oauth2 stuff, the 2nd you should loop though each server, and check if server.members.has("id", "the memberss id") if that's true they are in that server.
