### ISSUE TITLE
Playing sound files

### ISSUE THREAD

**Issue by PastaAdventures** [hydrabolt/discord.js#48]
I want to have a file that upon command, plays through my VLC. Any ideas?

**Comment by TehSeph** [comment]
Voice is planned, but not for a while. Check out [discordie](https://github.com/qeled/discordie) if you're in immediate need of a NodeJS library with voice support (as it is currently the only NodeJS lib with it.)

**Comment by izy521** [comment]
Excuse you, @TehSeph :(

**Comment by TehSeph** [comment]
Whoops! Apparently [discord.io](https://github.com/izy521/discord.io) has voice support too!
@hydrabolt you gotta step up your game! ;)

**Comment by PastaAdventures** [comment]
i don't see it anywhere in documentation

**Comment by hydrabolt** [comment]
"Voice is planned, but not for a while."
