### ISSUE TITLE
Cannot access Constants.Permissions object

### ISSUE THREAD

**Issue by hkwu** [hydrabolt/discord.js#480]
I can't access the permissions constants like the documentation states.
```javascript
import Discord from 'discord.js';

console.log(Discord.Constants.Permissions); // TypeError: Cannot read property 'Permissions' of undefined
```
Most likely due to this line in `index.js`,
```javascript
import Constants from "./Constants";
```
since the constants module doesn't have a default export.

**Comment by abalabahaha** [comment]
#431 fixed this, will be in next release
