### ISSUE TITLE
Role Throttling?

### ISSUE THREAD

**Issue by TheScree** [hydrabolt/discord.js#481]
When Executing the following series of command in sequence...

```
bot.removeMemberFromRole(user, message.server.rolesOfUser(user), function(err) {
  if (err) console.log(err);
  bot.addMemberToRole(user, theRole, function(err) {
    if (err) console.log(err);
  });
});
```

The code is _supposed_ to remove all roles from a user, then add back a single role.

Sometimes only one of these commands properly executes. It is intermittent and not consistent (sometimes this works correctly). I have witnessed several executions where a user ends up with a role, ends up without a role being removed and in some cases the role is both properly added and a different role is removed.

Should be fairly easy to replicate. I do not run this pair of commands multiple times, usually once in a long while. I.E: I am not running the above sequence chained together to hit a rate limit.

**Comment by TheScree** [comment]
Note, #472 and #476 weren't attempting to implement the above commands nested properly for async behavior.

I have attempted to structure the code in numerous ways to work around this issue, but at this point its either a problem with the Discord API (likely) or the library in question.

**Comment by macdja38** [comment]
I can confirm removing multiple roles at the same time from one user does not work as intended, though I have not tried in the last month. What I think you have to do to "fix" this though it's probably a lib issue is remove the roles one after another, in the callback.
Bassically the easiest way to do that would be an async recursive function, that removes a random roll, then calls itself till their are no roles left. it would have to return a promise. An example implementation with psudo code would be.
```javascript
function removeAllRoles(user, server) {
    return new Promise((resolve, reject)=>{ 
    removeARandomRole(user, server).then(()=>{
        if(remainingRoles > 0) {
            resolve(removeAllRoles(user, server));
        } else {
            resolve(true);
    })
}
```
If that makes any sense.

**Comment by hydrabolt** [comment]
Both requests are trying to over write each other, you need to give one request time to be executed (@macdja38's solution fixes this)
