### ISSUE TITLE
How to use autoReconnect?

### ISSUE THREAD

**Issue by BlackWolfff** [hydrabolt/discord.js#483]
Hello.
My bot is randomly disconnecting without any error or message, I guess it loses connection or something.
I know there is a autoReconnect feature but I don't know how to use it.
In discord.js documentation says it autoreconnect after losing connection, but nothing about how to use it.
Can someone show me example how to use this feature?
Thanks.
(I know my english is not perfect, sorry about that.)

**Comment by MergHQ** [comment]
````var cli = new Discord.Client({autoReconnect:true});````

**Comment by staentomic** [comment]
Don't ask it in here -_-, there is a server for that...

**Comment by SgtPunishment** [comment]
What those guys said!

**Comment by xori** [comment]
It might be something you should add to the documentation (maybe [here](https://discordjs.readthedocs.io/en/latest/docs_client.html#disconnected)), or make it more prominent then, because I couldn't find this information either. So +1 @BlackWolfff.

**Comment by xori** [comment]
and of course, right after I say that
https://discordjs.readthedocs.io/en/latest/docs_client.html#autoreconnect

**Comment by Nexuist** [comment]
Hi,

I know that the given answer was to use autoReconnect but that doesn't appear to be included to be included in the docs anymore (I checked https://discord.js.org/#/docs/main/stable/typedef/ClientOptions). Am I missing something? My bot is also going down at random time intervals without an error message.

**Comment by GusCaplan** [comment]
autoreconnect is always enabled now, if your bot is going down you might want to look into internet stability issues.
