### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by DavidWalkerFish** [hydrabolt/discord.js#485]
`C:\WINDOWS\system32>npm install discord.js
-
> ref@1.3.2 install C:\WINDOWS\system32\node_modules\discord.js\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref
> node-gyp rebuild

C:\WINDOWS\system32\node_modules\discord.js\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\discord.js\node_modules\node-opus\node_modules\ogg-packet\node_modules\ref-struct\node_modules\ref
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing node-opus@0.2.1
discord.js@8.0.0 node_modules\discord.js
├── unpipe@1.0.0
├── tweetnacl@0.14.3
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
└── superagent@1.8.3 (component-emitter@1.2.1, methods@1.1.2, cookiejar@2.0.6, reduce-component@1.0.1, extend@3.0.0, mime@1.3.4, formidable@1.0.17, qs@2.3.3, readable-stream@1.0.27-1, debug@2.2.0, form-data@1.0.0-rc3)`

**Comment by developerCodex** [comment]
Is this resloved, also did you install Git, node, npm?

**Comment by abalabahaha** [comment]
@developerCodex notice how the issue was closed
