### ISSUE TITLE
Upgrading from node 5.7.0 to node 6.3.0 breaks the playFile function

### ISSUE THREAD

**Issue by GenjitsuGame** [hydrabolt/discord.js#486]
Hello,

After upgrading node, my bot was not able to play audio anymore through the playFile function.

Everything seemed to work as I was getting the intent and no error from the callback and the end event was triggered as the correct moment, but there was no audio whatsoever coming from the bot.

**Comment by Programmix** [comment]
I'm using node v6.3.1 and I don't experience this issue. Are you sure you properly installed and built node-opus?

**Comment by abalabahaha** [comment]
Try removing node_modules and reinstalling all the packages. Voice also works fine for me on Node 6

**Comment by GenjitsuGame** [comment]
I went back to node 5.7 for now.

What I've tried so far was reinstalling node, npm, ffmpeg and discordjs. Basically done every things I had done in order to get it to work the first time. I will try reinstalling node-opus I guess.
