### ISSUE TITLE
Can't use behind proxy

### ISSUE THREAD

**Issue by verebelyin** [hydrabolt/discord.js#489]
Hi,

I tried to set up the proxy through environment variables (HTTP_PROXY, HTTPS_PROXY, PROXY), but neither of them worked. I couldn't find any mentioning about this in the docs.

Is there any possiblity to use the bot behind a proxy?

**Comment by abalabahaha** [comment]
The library uses your system network settings, so you would have to change those. Also, I don't believe many proxies support WebSockets, so keep that in mind.

**Comment by GusCaplan** [comment]
node websockets and proxies aren't very good friends. There are some specific hacks you can do, but that's more of a case-by-case thing

**Comment by hydrabolt** [comment]
Doesn't seem like something we can implement, sorry.
