### ISSUE TITLE
HELP PLEASE ERROR!

### ISSUE THREAD

**Issue by FaNNboii** [hydrabolt/discord.js#491]
![ba9f8d6f9f23242664f50f9](https://cloud.githubusercontent.com/assets/16906122/17330054/9635d1d4-58c5-11e6-9b40-25464ef0912d.jpg)

Everytime i try to start it -.-

**Comment by Bluethefurry** [comment]
not a discord.js bug

**Comment by FaNNboii** [comment]
what else?

**Comment by eslachance** [comment]
Please join us on Discord, as github spams the channel with ticket updates anyway and we'd rather not. 
Click this: [https://discord.gg/xfp8kqk](https://discord.gg/xfp8kqk)
