### ISSUE TITLE
bot.memberHasRole() - Should be Boolean?

### ISSUE THREAD

**Issue by Hyper-Coder** [hydrabolt/discord.js#494]
While using the `bot.memberHasRole()` function, it would make sense for it to be a Boolean of true or false if the user has a role. Instead, if the user has the role, it'll return the role; where if the user doesn't have the role, it'll return a TypeError.

![image](https://images.typicalbot.com/i/57a17f6fcac6d.png)

**Comment by Programmix** [comment]
Using 8.1.0 stable branch. This doesn't occur for me... perhaps you're doing something wrong?

**Comment by Hyper-Coder** [comment]
It isn't throwing an error because the if statement checks true/false or something/null, as you know...but doing this is either the role or null/undefined. Where I would think it should be true/false that the member has the role.

**Comment by eslachance** [comment]
I think what he means is that in 8.1.0 this has changed. Proof:
https://i.imgur.com/VcPzsZh.png

**Comment by Hyper-Coder** [comment]
Not for me.
![](https://images.typicalbot.com/i/57a7f4f42de09.png)

**Comment by GexoXYZ** [comment]
It's on indev
