### ISSUE TITLE
user.Speaking

### ISSUE THREAD

**Issue by YourMCGeek** [hydrabolt/discord.js#498]
user.Speaking does not work as a Boolean. Instead of returning "True" or "False" it returns undefined.

**Comment by GexoXYZ** [comment]
JavaScript is a case-sensitive language. 
It's 
`<user>.speaking`

[Documentation reference](http://discordjs.readthedocs.io/en/indev/docs_user.html#speakingl)

**Comment by YourMCGeek** [comment]
I tried to change it to user.speaking and it still returns undefined.

**Comment by GexoXYZ** [comment]
Can you get on the [Discord API server](https://discord.gg/6nGhwh8)?

**Comment by YourMCGeek** [comment]
Already on it, thats where I brought it up. Mention me: @Tucker#1692. Currently in nodejs channel.

**Comment by GexoXYZ** [comment]
**Resolved**
