### ISSUE TITLE
Voice Connection & Heroku 

### ISSUE THREAD

**Issue by Skuaaa** [hydrabolt/discord.js#500]
I'm desperately looking for a fix to an issue which I'm currently experiencing. When trying to run the code below:
`bot.voiceConnection.playFile("./Ahri.attack1.ogg");`

I get the following error:
`Error: spawn help ENOENT`

I've installed FFmpeg on my Heroku server using `npm install ffmpeg`, but was just looking for some advice on how I can fix this issue. I don't believe that my path is wrong, I think it's just the way in which I have installed FFmpeg.

**Comment by GexoXYZ** [comment]
http://discordjs.readthedocs.io/en/indev/troubleshooting.html

**Comment by Skuaaa** [comment]
@GexoXYZ Sorry, my bad. I accidentally posted the issue before writing a description. I've updated it now however...

**Comment by GexoXYZ** [comment]
That's not how you install ffmpeg.

Take a look at this https://github.com/shunjikonishi/heroku-buildpack-ffmpeg

**Comment by Skuaaa** [comment]
@GexoXYZ Thank you so much! It's working perfectly now. I really appreciate your help, since I couldn't find a solution anywhere. You were also very quick to respond ^^
