### ISSUE TITLE
Problems assigning roles to mobile users

### ISSUE THREAD

**Issue by funcdoor** [hydrabolt/discord.js#514]
I have a bot which lets users assign certain roles to themselves, but sometimes assigning a role errors with "Role does not exist on same server as member". This only happens with mobile users.

**Comment by macdja38** [comment]
Try enabling the client option [forceFetchUsers](https://discordjs.readthedocs.io/en/latest/docs_client.html#forcefetchusers). Their is a decent chance the client simply does not have the role cached and that's confusing it.

**Comment by funcdoor** [comment]
I haven't seen the error come up since I added that option, so I'm gonna close this. Thank you very much!
