### ISSUE TITLE
Does Client.users not update on its own with respect to User.game?

### ISSUE THREAD

**Issue by JaronOrchard** [hydrabolt/discord.js#515]
I wrote some sample code to print out the games of all the users in my channel using the bot's users cache, but the games don't update when they change (although the cache seems to update when users go online/offline).  Is this intended?  I know that the presence event exists, but I didn't know if it was as easy as calling bot.users.update(presenceVar1, presenceVar2) and if that was even necessary.

Thanks!  Keep up the great work. :)

**Comment by briantanner** [comment]
what version of discord.js?

**Comment by JaronOrchard** [comment]
package.json says 8.0.0.

**Comment by abalabahaha** [comment]
Latest is 8.1.0, try that

**Comment by JaronOrchard** [comment]
Upgrading to 8.1.0 did fix the issue!  Apologies, I should have tried that first.  Thank you for your help!
