### ISSUE TITLE
setNickname(server, nickname, user) not changing nickname

### ISSUE THREAD

**Issue by razorrider7** [hydrabolt/discord.js#518]
I have been trying to change a nickname with my bot however 
`client.setNickname(message.server, 'nickname', message.author);`
has no effect.

I **have** got the bot to respond to users, this is the only thing that isn't working.
I am using the latest version of node (v6.3.1) and have installed discord.js.

**Comment by GexoXYZ** [comment]
Note that there are two different permissions for changing nicknames: `changeNickname` for the client's nick and `manageNicknames` for everyone else's. Are you sure your bot has these permissions?

**Comment by razorrider7** [comment]
The bot has both permissions, however the .catch(console.log) error is "Privilege is too low..." it says forbidden: true,

Is it something to do with my being the server admin?

**Comment by abalabahaha** [comment]
Yes. If the bot's highest role is lower or the same as your highest role, you guys can't do stuff to each other.

**Comment by razorrider7** [comment]
Ok. Thanks for the help.
