### ISSUE TITLE
warn: channel doesn't exist even though SPEAKING expects them to

### ISSUE THREAD

**Issue by briantanner** [hydrabolt/discord.js#520]
I'm getting this all day, every day. It's coming from #452 

So, `user.voiceChannel` is undefined.

![image](https://cloud.githubusercontent.com/assets/3637408/17681571/be380494-6370-11e6-91c9-f2ac4639d447.png)

**Comment by hydrabolt** [comment]
Fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)
