### ISSUE TITLE
Please help! 

### ISSUE THREAD

**Issue by Sonnixable** [hydrabolt/discord.js#526]
I'm completely new to the world of Discord bots and currently have something I'm trying to do but I cannot work it out. I'm trying to add permission to a command.

e.g If an Administrator uses the command ^clear the chat will clear however if the user is not an Administrator the command will not run and the bot would reply with "Error you do not have permission for that command". 

Any help is really appreciated!!

**Comment by AlphaYus** [comment]
This isn't the place to be reporting issues. Just come into the Discord API discord and into the js_discord-js channel

**Comment by briantanner** [comment]
It's literally named "Issues"

**Comment by AlphaYus** [comment]
Mental typo, I edited it.
