### ISSUE TITLE
autoReconnect tries to reconnect exponentially faster, not slower: causing a crash

### ISSUE THREAD

**Issue by bdistin** [hydrabolt/discord.js#527]
![node disconnect test](https://cloud.githubusercontent.com/assets/18535830/17838784/b3d06b6c-679a-11e6-99af-912eb3e3120a.gif)

From looking at the source code, the math seems to check out. But for some unknown (to me) reason, it doesn't slow down as it should.

**Comment by hydrabolt** [comment]
Fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)
