### ISSUE TITLE
client.loginWithToken() issue

### ISSUE THREAD

**Issue by rzsx97** [hydrabolt/discord.js#530]
**Hello there**

I'm developing a kind of Bot Framework, and i can see when i got an error in the login callback, the parameter "error" doesnt return anything, just handle the "error" event can i see the error.

**Comment by abalabahaha** [comment]
There isn't really a good way to validate the token you pass. The library only knows when a token is bad when attempting to make a request or connecting to the gateway, which is where the error event comes from.

**Comment by rzsx97** [comment]
But i tried given a bad token, and still the error returns null.

**Comment by MergHQ** [comment]
loginWithToken doesn't check if the token is valid. The library will emit an error event when if the ws handshake fails. That way you can see if the token is invalid.

Also, you could just check this yourself. Make a request with that token and see if it returns invalid token.

**Comment by hydrabolt** [comment]
loginWithToken has been removed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2) in favour of a unified `login` method
