### ISSUE TITLE
Voice Audio Output Doesn't Work for Me

### ISSUE THREAD

**Issue by Tromino** [hydrabolt/discord.js#531]
Sorry if this isn't the correct place to ask about problems specific to myself, I couldn't find anywhere else I could post this. I also checked issues with similar problems, and I didn't find any answers.

So I'm trying to make a music bot using this module, and I have a command to play audio with `client.voiceConnection.playRawStream()`. The problem is, no audio is being output to the voice channel. There is no green circle around the avatar, and using `setSpeaking(true)` doesn't add it.

It seems to be reading the stream correctly. Using `playing` returns true, `streamTime` looks like the correct time, and the intent "end" even gets triggered at the correct time. Audio also doesn't work when using `playFile()`.

The server this is running on has Node.js v4.5.0 and FFmpeg 2.4.3. The module version is 8.1.0. It's also running on Ubuntu 14.04.5 LTS.

**Comment by GexoXYZ** [comment]
To **identify** the problem:

**1.)** Go to your console and type ffmpeg -version. Does it recognize ffmpeg?

**2.)** Go to your console and type python --version Everything above 2.x.x is not supported

**3.)** Go to your project folder and reinstall discord.js. Do you get any errors? node-gyp errors are related to missing C++ build tools.

**4.)** If all this doesn't fail and you still don't get sound make sure your bot has permissions to speak and is not muted.



To **solve** the problem: 
windows: If you are having issues while installing discord.js with voice support on Windows, or trouble with audio, please follow these instructions.

- **Python 2.7.x** should be installed, and available in path. To verify, click start, run, type python and it should open it). If not, download from https://python.org/downloads/.
- **FFMPEG** must be installed properly, instructions are on http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/
- If you have Visual Studio 2013 or 2015, make sure C++ Build Tools are installed. Simply create a new Empty C++ project. If prompted to install the C++ files, do so. 
- **Alternatively**, you can install only the Visual C++ Build Tools as a standalone: http://landinghub.visualstudio.com/visual-cpp-build-tools
- Some users have reported that installing VLC helps with codec dependencies, so try that. 

Run the following commands to re-install discord.js

`npm cache clean` (to remove any cached versions of discord or its dependencies)
`npm install -g npm` (this will update NPM, and fixed it for some users!)
`npm install --save --msvs_version=2015 discord.js` (change version to 2013 if using VS2013)

If any errors show, attempt to re-install node-opus manually: 

`npm cache clean`
`npm install node-opus`

(thanks LuckyEvie)


Note that there's a new npm package that installs **Python** and the **C++ Build tools** automatically for you, you might want to look into this: `npm install --global --production windows-build-tools`. It should work, but if not, fall back to the steps described above,

**Comment by Tromino** [comment]
FFmpeg works fine, and is the version I gave in the issue.
The Python version installed is 2.7.6.
I reinstalled npm and the module, there were no errors, and audio still doesn't work.
The bot account isn't muted on either the server or my Discord client, the volume is high, and the bot has permissions to speak.
Installing VLC didn't help.
This is an Ubuntu server, by the way.

**Comment by arya-s** [comment]
Having the same issue, works on my mac but not on my ubuntu 14.04.3 LTS.

I got ffmpeg version N-80901-gfebc862 though.

**Comment by abalabahaha** [comment]
Sounds like a discord.js/node-opus issue. Try clearing the `node_modules` folder, then clearing the npm cache (`npm cache clean`), then reinstalling all modules. Make sure you're installing the latest versions (discord.js @ 8.1.0, node-opus @ 0.2.1).

**Comment by Otokiru** [comment]
+1 for this same issue on my new Ubuntu server 14.04 TLS.
It was playing fine on my old Ubuntu server. And it was running discord.js v6.1.0
After I update it to v8.1.0, it doesn't play anymore.
So i tried to install discord.js v6.1.0 on my new Ubuntu server, it plays fine.

**Comment by arya-s** [comment]
@abalabahaha I followed your steps but the outcome is the same. There is no error thrown either.

**Comment by abalabahaha** [comment]
Can you guys hop on [the Discord channel](https://discord.gg/V5RRnpt)

**Comment by arya-s** [comment]
Turns out the path to my audio file was just wrong. It works now..
