### ISSUE TITLE
How can I PM a user?

### ISSUE THREAD

**Issue by Simon-Chase** [hydrabolt/discord.js#537]

**Comment by bdistin** [comment]
sendMessage(channel, content, options, callback);

Where channel is [user resolvable](http://discordjs.readthedocs.io/en/indev/docs_resolvables.html#user-resolvable)

**Comment by Simon-Chase** [comment]
What is user resolvable? How do I find out what it is?

**Comment by abalabahaha** [comment]
Try clicking his link and scrolling down

**Comment by Kalazbb** [comment]
You ca use this : 
`msg.author.send("Content of message")`

**Comment by mpskierbg** [comment]
thats just to the sender of the message. he wants to send to a specific person. bdid you find an answer?

**Comment by HorizonTM** [comment]
Please look at the date of the issue next time. Its over a year old.

**Comment by Addoie** [comment]
> Please look at the date of the issue next time. Its over a year old.

Who are you to tell anyone what to do "Big boi who likes to code and play games."
