### ISSUE TITLE
Name to User ID

### ISSUE THREAD

**Issue by Simon-Chase** [hydrabolt/discord.js#539]
How can I get a user id by their name?

**Comment by GusCaplan** [comment]
....

**Comment by FrankenMan** [comment]
Bruh

**Comment by GexoXYZ** [comment]
It depends where you're at. If you have access to a message, the best would be
`message.server.members.get("name", "USERNAMEHERE").id;`
otherwise you can also get it globally
`client.users.get("name", "USERNAMEHERE").id;`

**Comment by AS2xD** [comment]
does this still work??? if it does how i dont understand :<

**Comment by ImRodry** [comment]
This issue is more than 5 years old so obviously not. Please don't necropost on issues, you can ask your questions on the [Discord server](discord.gg/djs)
