### ISSUE TITLE
Channel Mention

### ISSUE THREAD

**Issue by khionu** [hydrabolt/discord.js#54]
Embedding a Channel Object in a message produces the channel name as a string, not a ChannelMention.

**Comment by khionu** [comment]
@abalabahaha :P

**Comment by TehSeph** [comment]
@abalabahaha @hydrabolt Pssst, Same might need to be done for Server objects? :)

**Comment by abalabahaha** [comment]
@TehSeph one does not simply mention server objects

**Comment by TehSeph** [comment]
facepalm.jpg

It's 3am I'm not sure what I was thinking...

**Comment by khionu** [comment]
._. oh dear

**Comment by hydrabolt** [comment]
Added in 0fdcf827d079b70c41fb651d552895c1b9e7689a :+1:
