### ISSUE TITLE
Make bot @mention user on user's first time joining

### ISSUE THREAD

**Issue by razorrider7** [hydrabolt/discord.js#575]
How would I make a bot do something (like send a message) when a user first joins the a discord server?
I've been looking all over for a hint as to how to do that...

**Comment by Bluethefurry** [comment]
```
c.on('serverNewMember',(x,y)=>{
	if(x === c.servers.get('id',"SERVERID"))
		c.sendMessage(x.channels.get('name','general'),"Welcome to my Server "+y.mention()+"!")
})
```

**Comment by FrankenMan** [comment]
pls

**https://eslachance.gitbooks.io/discord-js-bot-guide/content/samples/welcome_message_every_x_users.html
**
