### ISSUE TITLE
Send message to PM

### ISSUE THREAD

**Issue by AmazingGamerBoy** [hydrabolt/discord.js#577]
Hi, if I ask the bot for help on a main server channel, how to I program it to send the help to my PM? Thanks, I can't seem to find the right function to do it.

**Comment by YorkAARGH** [comment]
That's not an issue, that's a question, this is the wrong place for it, go to discordapi's #js_discord.'s

**Comment by AmazingGamerBoy** [comment]
@YorkAARGH Link Please?

**Comment by hydrabolt** [comment]
Documentation relevant to your question:
* https://discordjs.readthedocs.io/en/latest/docs_client.html#sendmessage-channel-content-options-callback
* http://discordjs.readthedocs.io/en/indev/docs_resolvables.html#id6
A guide to using discord.js: https://eslachance.gitbooks.io/discord-js-bot-guide/content/
Help Channel: https://discord.gg/JcXmf
