### ISSUE TITLE
Error: Invalid session

### ISSUE THREAD

**Issue by logandark** [hydrabolt/discord.js#580]
```
Error: Invalid session
    at WebSocket.websocket.onclose ([censored]/node_modules/discord.js/lib/Client/InternalClient.js:93:1566)
    at WebSocket.onClose ([censored]node_modules/ws/lib/WebSocket.js:446:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at WebSocket.cleanupWebsocketResources ([censored]/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
This error happens when you log into 2 different bots using the same script.
```js
bot.loginWithToken(token)
user.loginWithToken(user_token)
```
This error does not happen when logging into the user or the bot individually.
How do I fix this?

**Comment by eslachance** [comment]
Short version: You can't.
Long version: You just can't.

**Comment by logandark** [comment]
I believe I can. I have a theoretical solution that may work:

* Require discord.js twice

**Comment by eslachance** [comment]
You can't. It's the same code. Internal session caches can't support 2 separate login sessions. Possibly, duplicating the discord.js folder inside node_modules *might* work but then one won't update properly anyway.

The **Proper** way to do this is to look into IPC, if you want to transfer information between two separate bots. Same way people share information between shards.

**Comment by logandark** [comment]
IPC?
_is confused_

**Comment by hydrabolt** [comment]
Can you try logging into the second bot 6 seconds after the first one and see if that makes a difference?

**Comment by hydrabolt** [comment]
Should be fixed in [9.0.2](https://github.com/hydrabolt/discord.js)

**Comment by logandark** [comment]
@hydrabolt Don't close an issue without knowing it's solved:
```
/etc/.b/.njsbot/node_modules/discord.js/src/client/Client.js:17
class Client extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/etc/.b/.njsbot/node_modules/discord.js/src/index.js:1:78)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by GexoXYZ** [comment]
@logandark update node, version 6 is required.

**Comment by logandark** [comment]
Oh, okay

**Comment by Tyler0130** [comment]
@logandark How about not commenting on a closed issue unless there's actually a problem? ;P

**Comment by logandark** [comment]
There actually is a problem, there are no apt-get updates for node.

**Comment by iCrawl** [comment]
Pls use google https://nodejs.org/en/download/package-manager/

**Comment by logandark** [comment]
```
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
```

**Comment by FrankenMan** [comment]
have you tried installing node 6

**Comment by briantanner** [comment]
You should use nodesource for installing node. linux package managers are forever outdated.
https://github.com/nodesource/distributions

**Comment by Hackzzila** [comment]
https://nodejs.org/en/download/package-manager/ will also work, I installed 6.4 with it

**Comment by hydrabolt** [comment]
smh

**Comment by briantanner** [comment]
@logandark https://github.com/nodesource/distributions, also the package-manager page above also uses nodesource distributions.

**Comment by logandark** [comment]
I came across [this](http://askubuntu.com/questions/786272/why-does-installing-node-6-x-on-ubuntu-16-04-actually-install-node-4-2-6) and now `nodejs --version` shows `v6.5.0`. Thanks for your help!

**Comment by logandark** [comment]
Unfortunately, I am now getting a `TypeError: bot.loginWithToken is not a function`.

**Comment by Hackzzila** [comment]
Because it isn't a function, read the new docs

**Comment by logandark** [comment]
Oh, okay.

Thanks!

**Comment by Hackzzila** [comment]
The rewrite is completely different

**Comment by FrankenMan** [comment]
rewrite m8. read the new docs http://hydrabolt.github.io/discord.js/#!/docs/tag/master/file/general/Updating%20your%20code

**Comment by logandark** [comment]
Ayy lmao
