### ISSUE TITLE
Cannot read property `detailsOfUser` of undefined

### ISSUE THREAD

**Issue by MRVDOG** [hydrabolt/discord.js#585]
Hi, as the title states, I am having an issue

I am using the following code
`message.server.detailsOfUser(user.id)`

I read that for message.server to work I require discord.js 8.0.0 or higher, but I have discord.js 8.1.0

![image](https://cloud.githubusercontent.com/assets/4422624/18225520/c49a9ee4-71eb-11e6-8b58-c92776d2ba72.png)

![image](https://cloud.githubusercontent.com/assets/4422624/18225514/75605b16-71eb-11e6-8755-08b6589eb1cf.png)

does anyone have any ideas, I just spent a good 6hrs rewriting my bot and don't really fancy reverting back and wasting all that time

Thanks, MrV

**Comment by Hyper-Coder** [comment]
By rewriting, do you mean into the D.JS Rewrite?

**Comment by GexoXYZ** [comment]
Are you sure your bot didn't get DM'd ?

**Comment by MRVDOG** [comment]
@Hyper-Coder I coded a bot using an earlier version of Discord.JS and I am now rewriting it using 8.1.0

@GexoXYZ absolutely positive, it's when I send a command in my Servers default channel, it crashes the bot with this error

![image](https://cloud.githubusercontent.com/assets/4422624/18225615/8d9cefe8-71ee-11e6-8d9c-1f79a12cba6e.png)


![image](https://cloud.githubusercontent.com/assets/4422624/18225575/a97dd78c-71ed-11e6-88a3-05f7a6fa0009.png)

![image](https://cloud.githubusercontent.com/assets/4422624/18225624/cee1ff66-71ee-11e6-8349-a591f329179d.png)


```
data = botVariables(message.server, user, reply, message);
if( data != "" ) {
	mybot.sendMessage(to, data);
}
```

**Comment by eslachance** [comment]
The line your error points to is missing `message.` at the beginning. `server` is not used as-is in a message handler. So `message.server.detailsOfUser()`

**Comment by MRVDOG** [comment]
the line the error points to is in a function which passes message.server as server

**Comment by eslachance** [comment]
No it points to a line attempting to assign user details to a var, but clearly indicates that `server` is **undefined**. Which means it's not being passed correctly to the function. Or not properly defined before the function is called.

**Comment by MRVDOG** [comment]
ohhh, I see what you mean, I know the Message object is being passed to the function correctly, as I never had an issue with that in the past, I will see if I can figure something out from that, I technically don't even need to pass the server into the function if it is also defined in the message object, I will do some debugging and will be back either, if I solve the issue, of am still having problems xD

Thanks MrV

**Comment by MRVDOG** [comment]
okay so I got it working, reduced the amount of arguments the function requires, but had to add some code to get the Server object, but it all works again now

![image](https://cloud.githubusercontent.com/assets/4422624/18227435/345aff8c-721c-11e6-9a8b-f154158e4ffa.png)

![image](https://cloud.githubusercontent.com/assets/4422624/18227441/5894a98e-721c-11e6-8133-8ed3dbf616cf.png)

Thanks for your help, turns out there is nothing wrong with Discord.js, just me being an idiot haha

**Comment by hydrabolt** [comment]
Glad that it's fixed!
