### ISSUE TITLE
updateRole clears out all permissions 

### ISSUE THREAD

**Issue by Deukhoofd** [hydrabolt/discord.js#59]
Doing some fairly simple code:

    hexcode_ = contentsplit[contentlength - 1].toString();
    hexcode= parseInt(hexcode_, 16)
    bot.updateRole(role1, {
         color: hexcode,
     })

Sets all permissions for that role to false. Name and hoist are unaffected, color is changed as supposed

**Comment by dodekeract** [comment]
I think that's the intended behavior. Just try to get the permissions of `role1` and update the color, then call `updateRole`.

**Comment by Deukhoofd** [comment]
Well, seeing as how the documentation states "all attrs optional", I'd assume that if you keep permissions empty, it should not change its permissions.

**Comment by abalabahaha** [comment]
Makes sense, it's probably unintended then. I've pushed a (hopefully working) fix to Github (not the NPM version, the Github repo). It still needs testing, though, and only hydra can add updates to NPM.

**Comment by hydrabolt** [comment]
Thanks @abalabahaha and @Deukhoofd! I'm unable to check it as of yet, but I will try my best to get round to this issue.

**Comment by hydrabolt** [comment]
whoops didn't mean to close haha
