### ISSUE TITLE
README.md "Examples" 404

### ISSUE THREAD

**Issue by zikeji** [hydrabolt/discord.js#604]

**Comment by briantanner** [comment]
Could you comment on what this issue is about?

**Comment by hydrabolt** [comment]
Fixed in indev, will become active in master on next release.

**Comment by zikeji** [comment]
Sweet.

@briantanner Sorry, I thought the title was enough. Just a simple broken link. Not overly important.

**Comment by zikeji** [comment]
@hydrabolt Sorry, shoulda checked the other branch.

**Comment by hydrabolt** [comment]
It's fine haha

**Comment by zikeji** [comment]
@hydrabolt I just finished my basic bot and now I'm going to have to update it to 9.0. The feels xD. Nice job on the API though.

**Comment by hydrabolt** [comment]
Thanks @zikeji :+1:
