### ISSUE TITLE
Stream returned by playRawStream does not terminate properly

### ISSUE THREAD

**Issue by SimonSchick** [hydrabolt/discord.js#61]
The problem roots from here: https://github.com/hydrabolt/discord.js/blob/master/src/Voice/VoiceConnection.js#L99

When the stream ended stream.read will always return null, therefor it will keep calling the send function via setTimeout.

Furthermore the condition `buffer.length !== 1920` will never be satisfied as stream.read will return null if the request amount of bytes was not supplied.

Instead you may want to listen to the end event of the input stream and terminate your stream accordingly.

Generally it might be worth simply attaching a data listener to the input stream rather than manually polling the input stream.

**Comment by SimonSchick** [comment]
So I played around with this a little and it seems that using this instead seems to fix it:

````
				var buffer = stream.read(1920);

				if (!buffer) {
					if (onWarning) {
						retStream.emit("end");
						self.setSpeaking(false);
						return;
					} else {
						onWarning = true;
						setTimeout(send, length * 10); // give chance for some data in 200ms to appear
						return;
					}
				}

				if(buffer.length !== 1920) {
					var newBuffer = new Buffer(1920).fill(0);
					buffer.copy(newBuffer);
					buffer = newBuffer
				}
```

**Comment by hydrabolt** [comment]
Ok, thanks I will take a look at it

**Comment by koriwi** [comment]
Tested and working
