### ISSUE TITLE
.setRoles won't accept single Role object

### ISSUE THREAD

**Issue by Meowbeast** [hydrabolt/discord.js#611]
After doing guild.roles.get(), which returns a Role, and you pass that single Role into member.setRoles(), it fails expecting an Array.  

It would make sense to be able to pass a Role without pushing a single Role into an Array.

**Comment by Meowbeast** [comment]
Current workaround is to push the single Role into an array...but I feel you should be able to pass a single Role without first pushing to an Array.

**Comment by zikeji** [comment]
It is documented as accepting a single role and not an array: http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/GuildMember?scrollto=setRoles

So it should be that way.

**Comment by Gawdl3y** [comment]
It's not documented as accepting a single role. It accepts either `Collection<string, Role>` or `Role[]`.

**Comment by Meowbeast** [comment]
It appears to be documented correctly, but I would assume passing a single Role should work without the extra work pushing the Role into an Array.

UNLESS, `member.setRoles()` will totally overwrite all roles.  In such case, you would prob want to get current roles first, and add the new role to the array before setting.

Which, if it does totally overwrite all roles, then we need a `member.setRole()` method.

**Comment by zikeji** [comment]
Sorry @Gawdl3y I was thinking of passing a `Collection<string, Role>` with a single role being the issue here. Didn't read OP clearly enough.

**Comment by Gawdl3y** [comment]
Confirmed that `setRoles` overwrites existing roles. I will be making a PR with an `addRole` method.

**Comment by Meowbeast** [comment]
Closed by #615

**Comment by PictureGamer** [comment]
Just ran into this problem too, had to get the current array of roles and push the new role before setting the roles again. Would be a great help if like previous versions we had dedicated `addRole` and `removeRole` methods

**Comment by Gawdl3y** [comment]
Already in indev.
