### ISSUE TITLE
user.bot property not accurate

### ISSUE THREAD

**Issue by Meowbeast** [hydrabolt/discord.js#612]
I've added a few bots to my server and user.bot is flagged false.  
I've confirmed other libs recognize the same accounts as bots.

**Comment by Meowbeast** [comment]
Can confirm this is not persistent.

Kicking and re-adding the bot will sometimes report `user.bot = true`.  Other times (most times), it's reported `false`.

Once user is in the Guild and you do a user check, it seems to report as a bot.  It's specifically in the `guildMemberAdd` event where bot is incorrectly reported false on `member.user.bot`

**Comment by hydrabolt** [comment]
_Potentially_ fixed, please take a look and close if it is.

**Comment by Meowbeast** [comment]
Issue persists.

**Comment by hydrabolt** [comment]
Fixed in f0a9a1353fad6e46add1664f9f7c73e69ac868d8
