### ISSUE TITLE
Allow message.edit() to accept Arrays like the recent change to .sendMessage()

### ISSUE THREAD

**Issue by Meowbeast** [hydrabolt/discord.js#624]
A recent PR allowed for `.sendMessage()` to accept an Array.

For consistency, can we have `message.edit()` accept Arrays?

**Comment by YorkAARGH** [comment]
That's actually a good idea

**Comment by Programmix** [comment]
This issue should be closed.

**Comment by Meowbeast** [comment]
Closed by #630
