### ISSUE TITLE
Add support for .sendCode()

### ISSUE THREAD

**Issue by Meowbeast** [hydrabolt/discord.js#625]
Feature request for a `.sendMessage()` clone that will send contents as a code block.

`channel.sendCode(content | Array, format)`

E.g.  `channel.sendCode('Hello World', 'xl');`

**Comment by datitisev** [comment]
I imagine this will also split the message greater than 2000 chars into multiples. All messages then should be wrapped around the same codeblock, so we don't get plain text and bad formatting.
Code could be split into multiple messages by line and not mid-sentence.

---

```xl
Code greater than 2k chars... first message
```
```xl
Second message, hopefully split by lines and not mid-sentence
```

**Comment by hkwu** [comment]
@datitisev would that be necessary since `sendMessage()` doesn't do that?

**Comment by datitisev** [comment]
I mean... sendMessage doesn't wrap your message in a code block either 😛 
If we don't need the former, we don't need the latter either.
Would be useful, though.

**Comment by Gawdl3y** [comment]
Message splitting is now supported in indev. Is `sendCode()` useful/helpful enough to include? It would automatically add the split prepend and append properties, if splitting is enabled for it.

**Comment by Hyper-Coder** [comment]
I do not believe it has a bit enough use. If people want this, they could make their own. Most bots using code blocks don't have blocks over 2k and they usually how more than just the block such as how my boy TypicalBot has server stats, stats, etc.

**Comment by Gawdl3y** [comment]
After a nice long discussion in Discord, added in 7ff9ac2bccaaadef9bee57daafffe9ef89bb982f.
