### ISSUE TITLE
TypeError: Discord.MessageCollector() is not a constructor

### ISSUE THREAD

**Issue by timhwang21** [hydrabolt/discord.js#626]
Error message:

```
[12:51]timothy~/Github/RickBot-master->node index.js
/Users/timothy/Github/RickBot/index.js:28
const TestCollector = new Discord.MessageCollector(bot.channels[6], () => true, SECOND * 10);
                      ^

TypeError: Discord.MessageCollector is not a constructor
    at Object.<anonymous> (/Users/timothy/Github/RickBot/index.js:28:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

My code:

```javascript
const TestCollector = new Discord.MessageCollector(bot.channels[6], () => true, SECOND * 10);

TestCollector.on('end', (collection, reason) => {
  collection.deleteAll();
});
```

I looked in the source and could only find a reference to MessageCollector [here](https://github.com/hydrabolt/discord.js/blob/2762c1d4397f8abba3d28d1a6d804cff2031d80f/src/structures/interface/TextBasedChannel.js). Is this feature not in master yet? Thanks!

**Comment by hkwu** [comment]
That class isn't exported, so you can't access it.

**Comment by timhwang21** [comment]
Thanks. How can I create and access a MessageCollector? Only though `TextChannel.createCollector()`? Thanks.

**Comment by GexoXYZ** [comment]
yes

**Comment by Gawdl3y** [comment]
Yep, you must use `.createCollector()`. Is there a reason you would need to make one yourself? The class could be exported if there's a use for it.

**Comment by timhwang21** [comment]
I guess there isn't. I was confused by the documentation because I assumed all the classes could be initialized. Thanks, all!
