### ISSUE TITLE
Client.fetchUser should add guild members to the caches as well

### ISSUE THREAD

**Issue by Gawdl3y** [hydrabolt/discord.js#629]
`Client.fetchUser` should add the user to the guilds' member caches in addition to the regular user cache.
As it is now, there is no way to run guild-specific functions on a fetched user.

Additionally, manually fetching a user like this may prevent it from ever being added to guild member caches as it is right now, I think?

**Comment by Gawdl3y** [comment]
There may need to be a `.guilds` property on `User`s, so that these can be iterated through when fetching the user.

**Comment by Programmix** [comment]
I disagree with this. In order to add the fetched user to the guild member caches you'd have to iterate through all guilds and request to fetch the guild member. If you want the member, you should use Client.fetchUser, and then subsequently Guild.fetchMember on all/specific guilds.

**Comment by Gawdl3y** [comment]
Yep, I meant to close this when I added `Guild.fetchMember` earlier. Forgot.
