### ISSUE TITLE
Long delay after playing another song

### ISSUE THREAD

**Issue by Trismirite** [hydrabolt/discord.js#632]
I have a queue system, and when I call the dispatcher to end the song and play the next one, it takes sometimes up to a minute to start playing the next song, the time varies randomly. Here's my code (not full code) 

```js
function queuePlay(message){
	message.channel.sendMessage("`Resolving...`").then(sentMessage => {
		bot.channels.get(queue[0].channelid).join().then(vconnection => {
			if(queue[0].type === "YouTube"){
				connection = bot.voiceConnections.find("channel", vconnection.channel.id).playStream(yt(queue[0].stream, {audioonly: true}));
				sentMessage.edit("Playing `" + queue[0].title + "` (" + queue[0].duration + ", requested by " + queue[0].nickname + ")")
				bot.user.setStatus("online", "► " + queue[0].title);
				connection.once("end", () => {
					queue.shift();
					if(queue.length === 0){
						bot.user.setStatus("online", "v" + config.version);
						connection.end();
						vconnection.disconnect();
						message.channel.sendMessage("Queue concluded");
					} else {
						queuePlay(message);
					}
				});```

**Comment by MikaalSky** [comment]
There's a lot of problems with slowness in the new voice system. This is something I've observed in my code as well.

**Comment by Programmix** [comment]
I feel like this is more related to the slowness of ytdl than anything else. Fetching YouTube stream URLs is a time-consuming process. Perhaps you'd benefit from caching them in the background before they're needed.

**Comment by DasWolke** [comment]
The Delay also occurres when using local mp3 files with a size of roughly 3mb, as i got a 6mbit/s upload that should not be a problem, but i also got a Delay. I installed node-opus too.

**Comment by aister** [comment]
the delay doesn't happen when I downgrade to v8 tho

**Comment by hydrabolt** [comment]
Fixed in https://github.com/hydrabolt/discord.js/commit/f192d16b5bf1da0303e5cca367fe6c961dcd51c9 :smile:
