### ISSUE TITLE
Instantiate a TextChannel

### ISSUE THREAD

**Issue by pxly** [hydrabolt/discord.js#633]
After upgrading to 9.x I read that the channel identifier that was used as a parameter inside the .sendMessage function was removed and that .sendMessage had to be called from a TextChannel.

I'd like to call .sendMessage out of the blue, how do I instantiate a TextChannel so I can call .sendMessage on it?

**Comment by eslachance** [comment]
you can search for the channel in the `bot.channels` or `guild.channels` Collections. For instance `bot.channels.get("channelid").sendMessage("test")` works fine. 

For further help please join us on the [Discord.js Official](https://discord.gg/bRCvFy9) server.

**Comment by pxly** [comment]
Awesome, thanks for the quick reply. I was aware of `bot.channels`, but since it was a `Cache` type, I didn't think much of it. I'll use `bot.channels.get('id')` from now on.
