### ISSUE TITLE
presenceUpdate issues

### ISSUE THREAD

**Issue by Lombra** [hydrabolt/discord.js#634]
Experiencing some inconsistencies with the presenceUpdate event.

All regarding a regular user that is not the bot.

- Starting from not playing anything and launching a game seems to work as intended.
- Exit game, new user object still has user.game data as if nothing changed.
- Launch same game again, presenceUpdate does not fire at all.
- Exit game, again seems like oldUser == newUser.

The native Discord client properly reflects these events, and the old _presence_ event from v8 worked fine.

**Comment by Programmix** [comment]
Users don't receive their own presence updates. I think this is what you're experiencing here.

**Comment by Lombra** [comment]
I'm trying with a user that is unrelated to the bot, and the same seems to hold true for other users on the server. I have never seen an update where oldUser has a game and newUser is null since I moved to v9.

**Comment by Gawdl3y** [comment]
#666 describes the issue you're having.
