### ISSUE TITLE
Remove lib and web-dist from the repo

### ISSUE THREAD

**Issue by SimonSchick** [hydrabolt/discord.js#64]
Compiled code shouldn't be on the repo.

Anyone can build these running `npm install` and `grunt` or `grunt dist` easily.

**Comment by hydrabolt** [comment]
I think it's fine as it is there, it's easier and faster for people who are cloning the repo ;)

**Comment by abalabahaha** [comment]
Per discussion on Discord server, I think lib is being removed.

**Comment by TehSeph** [comment]
@abalabahaha can you not re-open it? :P

**Comment by abalabahaha** [comment]
@TehSeph I never opened it... I'm just providing an update for outdated info should someone stumble upon this issue.

**Comment by TehSeph** [comment]
Right, I was asking if you had permissions to re-open it, since clearly this went from resolved to debated again.

**Comment by abalabahaha** [comment]
@TehSeph we resolved it over Discord. Lib is being removed.
