### ISSUE TITLE
Add globalCache Client constructor option

### ISSUE THREAD

**Issue by Sven65** [hydrabolt/discord.js#640]
Instead of having to use IPCs to communicate the cached data between shards, add support for it natively, so that you can use for example ``bot.users.get("id", "1234567890")`` on all shards instead of just one.

**Comment by Gawdl3y** [comment]
That would be *very* slow, and would be unnecessary under most circumstances. If it were to be added, it'd have to be a separate method.

**Comment by Programmix** [comment]
As much as I'd enjoy having this as a feature, this really is something for the user to implement... not the lib.

**Comment by macdja38** [comment]
With the new shard manager thing this kinda makes sense. But it should definitaly be a seporate method.

**Comment by hydrabolt** [comment]
It shouldn't be possible even with the Shard Manager, it would be incredibly slow. Use IPC to send only the data you need, if we were sending thousands of objects over IPC a second the lib would slow to a halt.
