### ISSUE TITLE
ECONNRESET every time after using dispatcher.end()

### ISSUE THREAD

**Issue by aister** [hydrabolt/discord.js#650]
when I use dispatcher.end I got an ECONNRESET every single time which crash my app without fail. I've done a few researches and it seems it's an error that happens a lot especially on linux servers. My test bot running on window executed dispatcher.end() normally when my actual bot running on heroku's server didn't.

Also, when I switch from dispatcher.end() to stream.destroy(), the bot continues to play for around 10s, and then normally end. So I believe the problem lies at how linux deals with how the stream got cut before being destroyed properly.

**Comment by Gawdl3y** [comment]
Please check if this is still occurring on the latest `indev`.

**Comment by R3alCl0ud** [comment]
this issue is still occurring on latest indev build

**Comment by gsmit1996** [comment]
I got the error as well. What I did:

1. Played a stream from YTDL
2. While still playing from the stream, called
```
stream.destroy();
dispatcher.end();
```
3. Played a new YTDL stream directly after it.

This worked in Windows, but throwed the `ECONNRESET` on Linux.

**Comment by hydrabolt** [comment]
Fixed in 77e83fb85af09d2e2cd767ae04aa9dad348e5c5f :smile:

**Comment by hydrabolt** [comment]
_ECONNRESET strikes again_

**Comment by hydrabolt** [comment]
**finally** fixed
