### ISSUE TITLE
Feature Request: `<Guild>.membersWithRole(role)`

### ISSUE THREAD

**Issue by eslachance** [hydrabolt/discord.js#654]
membersWithRole should return a collection of all users with the specified role resolvable.

Equivalent to something like:
```js
msg.guild.members.filter(m=> m.roles.has("216219836957720576"))
```

(would have to work with role resolvables of course)

**Comment by Programmix** [comment]
I think that this definitely should be a user-defined function, not a builtin function for the library, as it is a rare use-case.

**Comment by Gawdl3y** [comment]
I'm not sure this should be added either, as it's trivial to do yourself - and will come with the gotcha that you'll have to fetch all guild members first, which is generally something to avoid as much as possible.

**Comment by hydrabolt** [comment]
Agree, this should not be core, it's too specific and can easily be implemented.
