### ISSUE TITLE
'presence' event not firing on join/leave game

### ISSUE THREAD

**Issue by acverhulst** [hydrabolt/discord.js#66]
Howdy. Not sure if the Client's 'presence' event is firing properly.

```
client.on('presence', (user, status, gameId) => {
  console.log('presence', user, status, gameId);
});
```

This event fires when a user logs in, but does not seem to fire when joining or leaving a game. 

If I manually log the 'raw' event when joining or leaving a game, I do see a 'PRESENCE_UPDATE' value in the message:
```
client.on('raw', (thing) => {
  console.log(thing);
});
```

Both script and test user both running from same machine, using Win10 with the nov 6th release of Discord (not sure how to find version info with the app?) and Node v5.1.0

**Comment by TehSeph** [comment]
@acverhulst You can always do `npm list` to see what modules (and versions) you have installed locally. :)

**Comment by abalabahaha** [comment]
@acverhulst this issue has been fixed recently, but the update is only on Github at the moment. The fix will be included in the next NPM update (should be soon).

Disclaimer: Upgrading from v4.x to v5.x (released about a week ago) will [introduce some breaking changes](http://discordjs.readthedocs.org/en/latest/migrating.html), but if you have trouble with it, we're happy to help on the [Discord API server](https://discord.gg/0SBTUU1wZTUBoYKx).
