### ISSUE TITLE
Client.users' games are not properly turning off again

### ISSUE THREAD

**Issue by JaronOrchard** [hydrabolt/discord.js#666]
I'm running version 9.0.2.  I once had a similar issue in https://github.com/hydrabolt/discord.js/issues/515 which was solved by moving from 8.0 to 8.1, but I think a regression has occurred.  It changes games properly but does not STOP playing them.

Reproduction steps:
1) Play a game
2) Grab user with Client.users.find("id", "123456etc");
3) user's game.name is correct
4) Stop playing game
5) Grab user with Client.users.find("id", "123456etc");
6) user's game.name is still the same as it was in step 3 even though I'm not playing it anymore

Any suggestions on a fix?  Thanks for your hard work on discord.js!

**Comment by hydrabolt** [comment]
Should be fixed in dbaaa8dc93673c3a41920daa367d8cb7ed4f2ab1.
