### ISSUE TITLE
Events "guildMemberAdd" & "guildCreate" fire upon new server join

### ISSUE THREAD

**Issue by Medallyon** [hydrabolt/discord.js#668]
version: tested on 9.0.2 & 9.1.0

description: client fires events `guildMemberAdd` and `guildCreate` when it joins a new guild. `guildMemberAdd` should not fire upon guild join.

recreation steps:

1. Invite bot using Discord oAuth2 link

```
client.on("guildCreate", (guild) => {

    console.log(client.user.username + " was invited to and joined " + guild.name);
});
client.on("guildMemberAdd", (guild, member) => {

    console.log(member.user.username + " joined " + guild.name);
});
```

The snippet above produces the code shown in the screenshot http://i.imgur.com/9OwiUkI.png

**Comment by Medallyon** [comment]
"When joining a server, a `guildMemberAdd` event triggers for each user on that server, and that shouldn't happen" - evie

**Comment by eslachance** [comment]
Additionally, `guildMemberAdd` is **also** triggered when a user **leaves** the server.

**Comment by aister** [comment]
in 9.0.2 guildMemberAdd isn't triggered when a user leaves the server. However it triggers for every single  members in the guild whenever the bot is online (or reset).
