### ISSUE TITLE
Version 8 hotfix

### ISSUE THREAD

**Issue by appellation** [hydrabolt/discord.js#669]
I'd like to discuss the possibility of merging an update for version 8.1.0 that fixes occasional `401 Unauthorized` errors that came with Discord requiring the `Bot` prefix on their authorization headers.

I realize that you're probably not inclined to support v8 now that v9 is released and going strong.  Further, I can't really see a way to do this short of making a separate branch from the 8.1.0 release for this patch; I would hope/expect that you could delete the branch after tagging it, but I've never had to deal with this before so I'm not exactly sure how that works.

However, since I've patched it for myself ([appellation/discord.js#v8.1.0_patch](https://github.com/appellation/discord.js/tree/v8.1.0_patch)) as I move towards upgrading to v9, I thought I would bring up the possibility of making it available to others.

**Comment by briantanner** [comment]
Please see the indev-old branch, it has the patch and others already

**Comment by appellation** [comment]
Oh.  I guess I should poke around a bit more.  Thanks.
