### ISSUE TITLE
dispatcher.pause() / dispatcher.resume() speeds up after a few seconds.

### ISSUE THREAD

**Issue by Trismirite** [hydrabolt/discord.js#672]
If you pause a song, wait nearly 20 seconds, then resume it, the song will fast-foward very quickly until it either ends the song or it will continue to go normal speed after a while. The longer you have it paused usually the longer it lasts. Abal managed to fix this in his Eris library but now the issue has arised to Discord.js.

**Comment by hydrabolt** [comment]
Fixed in 0d417b643232be81ccbdd1ea23f09f05f418a6f2

**Comment by JerryFunHouse** [comment]
Well its happening again, any ideas?
