### ISSUE TITLE
"content" argument in TextChannel.sendFile() not sending with attachment

### ISSUE THREAD

**Issue by emyarod** [hydrabolt/discord.js#675]
In version 9.1.0, only the text message to send with the file attachment appears to be missing from the response.

for example

`message.channel.sendFile('http://i.imgur.com/6CbxaPc.jpg', 'Kappa.jpg', 'testmessage');`

returns the image and renames the file, but does not include `testmessage` in the response

**Comment by hydrabolt** [comment]
Fixed in latest indev :smile:
