### ISSUE TITLE
serverNewMember and serverMemberRemoved events not present anymore

### ISSUE THREAD

**Issue by squalx** [hydrabolt/discord.js#676]
I have the feeling those have been removed. I can't figure out where those went to and how to get that kind of functionality back for my bot. I was using an older version of discord.js to avoid dealing with this, but seems like Discord deprecated something because my bot does not welcome users that join a server anymore.

Sorry I have to ask this here, but I can't find much info about discord.js outside of Github and your documentation.

If you think posting this here is not appropriate, you can close it, but I would appreciate it if someone would point me on the right direction or tell me if this is not supported anymore. 

BTW, I'm using version 9.1.1

Thanks.

**Comment by hydrabolt** [comment]
What exact version of discord.js are you running on?

**Comment by Gawdl3y** [comment]
[`guildMemberAdd`](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/Client?scrollto=guildMemberAdd) and [`guildMemberRemove`](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/Client?scrollto=guildMemberRemove)
