### ISSUE TITLE
<EvaluatedPermissions>.permissions isn't shown on the docs site

### ISSUE THREAD

**Issue by Hyper-Coder** [hydrabolt/discord.js#682]
http://hydrabolt.github.io/discord.js/#!/docs/tag/indev/class/EvaluatedPermissions

It only shows <EvaluatedPermissions>.member, permissions isn't listed.

@Gawdl3y Probably just needs a doc rebuild?

**Comment by Gawdl3y** [comment]
It's marked as private - but I don't see why it can't be public.

**Comment by Hyper-Coder** [comment]
Oh. It should be public, though. As some people use the bit number for it.

**Comment by Gawdl3y** [comment]
Renamed and made public in 68879777d8854425a46c781a63b9b1e4e2d0f9e1.
