### ISSUE TITLE
guildMemberAdd continuously triggers after bot goes online. 

### ISSUE THREAD

**Issue by 1Computer1** [hydrabolt/discord.js#684]
Screenshot: https://u.pomf.is/uasifp.png
(on indev)

The code is just this:
`mybot.on("guildMemberAdd", (guild, member) => {
	guild.defaultChannel.sendMessage("Welcome to " + guild.name + ", " + member.user  + "!");
});`

No one joins or anything, it just triggers like that.

**Comment by hydrabolt** [comment]
Is this a bot on a user account?

**Comment by hydrabolt** [comment]
Fixed in af33b2b5bbedb3d73084d6930638af4de3b972ca
