### ISSUE TITLE
Bot wont reply

### ISSUE THREAD

**Issue by tomgie** [hydrabolt/discord.js#685]
With the example just recently my bot wont reply or do anything but events.

**Comment by zounce** [comment]
Error?

**Comment by eslachance** [comment]
@tomgie if you're still on 8.1 this is normal, a change in the API caused an issue. See my first comment on #683 for a fix.

**Comment by Gawdl3y** [comment]
Please visit the [official Discord server](https://discord.gg/bRCvFy9) for general support. Make sure to provide any pertinent information when asking for help, like errors that are occurring. Don't just say, "It doesn't work", as we can't really do anything to help you without any details.
