### ISSUE TITLE
msg.author.bot is undefined

### ISSUE THREAD

**Issue by a09hopper** [hydrabolt/discord.js#686]
`if(input === "AVATAR"){
	msg.reply('here is your URL to the avatar');
	msg.reply(msg.author.bot)
	}` whenever I try this msg.author.bot tells me in discord it is undefined, so there are no errors with the code, I juts obviously typed something wrong.

**Comment by FrankenMan** [comment]
putting message.author.bot in that kind context would always return undefined

**Comment by a09hopper** [comment]
soooo.... what context do I need? as on the website of the docs it just says .bot

**Comment by FrankenMan** [comment]
lets say you don't want the bot to reply to itself. It would be ```if (message.author.bot) return;```

**Comment by a09hopper** [comment]
But how would I print it to the chat?

**Comment by Hyper-Coder** [comment]
Only occurs when bot is not true. If it's true, it'll show true.

**Comment by hydrabolt** [comment]
should be fixed in f0a9a1353fad6e46add1664f9f7c73e69ac868d8 where it is forced to be false
