### ISSUE TITLE
Some audio files are sped up when playing them.

### ISSUE THREAD

**Issue by 1Computer1** [hydrabolt/discord.js#689]
[This](https://u.pomf.is/xoemqi.mp3) and [this](https://u.pomf.is/vlndya.mp3).

It might be a problem with the audio files itself, but I don't know enough about that to confirm.

~~Sorry for weeb audio files~~

**Comment by GusCaplan** [comment]
i believe this is fixed in 0d417b643232be81ccbdd1ea23f09f05f418a6f2, as a response to #672

**Comment by 1Computer1** [comment]
Updated to indev just now, problem persists.

**Comment by GusCaplan** [comment]
@Hyper-Coder when you get a chance could you add a bug label to this 👍
