### ISSUE TITLE
Add method to stop VoiceReceiver

### ISSUE THREAD

**Issue by eslachance** [hydrabolt/discord.js#693]
A the moment there is no way to control the VoiceReceiver. It should have a `stop` or `close` or `end` event, in order to stop the receiver and any streams it's currently receiving. 

Some possible reference: https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname

**Comment by hydrabolt** [comment]
Addressed in 95369b0a89f6dd616203c55e9d31a804869788dd, but untested, if this fails please re-open the issue.
