### ISSUE TITLE
ClientUser.setAvatar() does not work on selfbots (needs email)

### ISSUE THREAD

**Issue by eslachance** [hydrabolt/discord.js#697]
When attempting to use setAvatar on a selfbot/userbot, the response from the API is 400, with the specific message:

`text: '{"email": ["This field is required."]}',`

Since selfbots are in the proper oauth2 scope, the email is available through ClientUser.email. This could be used directly as needed in the setAvatar call to the API.

**Comment by hydrabolt** [comment]
Fixed in https://github.com/hydrabolt/discord.js/commit/fbcea236c53ab19bb74928933d0d144141403312 install from indev to get fixes will be released with 9.2.1
