### ISSUE TITLE
User.equals() does not equal

### ISSUE THREAD

**Issue by SnazzyPine25** [hydrabolt/discord.js#701]
![uogkkwq](https://cloud.githubusercontent.com/assets/7025343/18494906/f714239a-79de-11e6-9bd5-0531bd910b85.png)

**Comment by Gawdl3y** [comment]
Don't use `.equals`, just compare IDs. `.equals` compares *all* properties, not just the ID. It's much slower, and unnecessary for most use-cases. It's primarily for internal use.
That being said, it seems like this usage of it should be `true`.
