### ISSUE TITLE
`bot.channels` includes users that have properties of channels but methods of users?????!!!!!!!

### ISSUE THREAD

**Issue by datitisev** [hydrabolt/discord.js#704]
<img width="840" alt="captura de pantalla 2016-09-14 a las 8 46 35 pm" src="https://cloud.githubusercontent.com/assets/6401250/18534744/696b831a-7abc-11e6-8004-ebf3a1c3eb27.png">
<img width="846" alt="captura de pantalla 2016-09-14 a las 8 46 59 pm" src="https://cloud.githubusercontent.com/assets/6401250/18534745/696b889c-7abc-11e6-87d9-716d2db4799b.png">
![](https://cdn.discordapp.com/attachments/222079895583457280/225778287912288256/Captura_de_pantalla_2016-09-14_a_las_8.42.09_PM.png)

**Comment by GusCaplan** [comment]
![omg](http://i.imgur.com/oitQcz0.png "OMG")

**Comment by GusCaplan** [comment]
we should note this is just with client.channels, not guild.channels

**Comment by datitisev** [comment]
More screenies:

<img width="847" alt="captura de pantalla 2016-09-14 a las 8 55 55 pm" src="https://cloud.githubusercontent.com/assets/6401250/18534907/ae3b5b86-7abd-11e6-9ad3-256e0d49f740.png">

**Comment by datitisev** [comment]
NEVER MIND!!! _facepalms_

Those were DMs... yeah

**Comment by abalabahaha** [comment]
We need a PEBKAC label...

**Comment by GusCaplan** [comment]
+1
