### ISSUE TITLE
C9 debugger causes music to be delayed

### ISSUE THREAD

**Issue by Youtubrer** [hydrabolt/discord.js#710]
C9 debugger and music incompatible.
Also when playing music without debugger, it jumps the first 5 seconds of the song

**Comment by Gawdl3y** [comment]
This is not an issue with the library. C9's debugger will likely slow everything down, and voice streaming is relatively intensive.

**Comment by Youtubrer** [comment]
Sorry, i forgot to add that this wasnt an issue in previous versions. :/ whatever ill just disable the debugger when testing the audio.
