### ISSUE TITLE
Cant use voiceChannel.join()

### ISSUE THREAD

**Issue by 5oClutch** [hydrabolt/discord.js#711]
client.voiceChannel.join().then(connection => console.log('Connected!'))
                       ^

TypeError: Cannot read property 'join' of undefined
    at Client.client.on.message (D:\node\discord\test.js:11:24)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (D:\node\discord\node_modules\discord.js\src\
client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\node\discord\node_modules\discord.js\sr
c\client\websocket\packets\WebSocketPacketManager.js:93:65)
    at WebSocketManager.eventMessage (D:\node\discord\node_modules\discord.js\sr
c\client\websocket\WebSocketManager.js:182:31)
    at WebSocket.ws.onmessage (D:\node\discord\node_modules\discord.js\src\clien
t\websocket\WebSocketManager.js:65:37)
    at WebSocket.onMessage (D:\node\discord\node_modules\discord.js\node_modules
\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)

D:\node\discord>

**Comment by GexoXYZ** [comment]
`client.voiceChannel` is not a thing. As the error says, it's undefined. Imagine being on 50 guilds, how would it know what voiceChannel to refer to?

**If you always want the client to join the same channel:** 
```js
const Discord = require('discord.js');

const client = new Discord.Client();

// Joins the voice channel as soon as the client starts up
client.on('ready', () => {
  // Get the channel via ID
  let channel = client.channels.get('81385020756865024');
  // Or via name (less persistent)
  channel = client.channels.find('name', 'Music');

  channel.join()
  .then(connection => console.log('Connected'))
  .catch(console.error);
});

client.on('message', message => {
  //...
});

client.login('token');
```

**or if you always want it to join a messages authors voice channel:**
```js
const Discord = require('discord.js');

const client = new Discord.Client();

client.on('ready', () => {
  console.log('Ready!');
});

client.on('message', message => {
  if (message.content === '!play') {
    // Note that this will only work if the message was sent in a guild
    // and the author is actually in a voice channel.
    // You might want to check for all that stuff first
    const channel = message.member.voiceChannel;

    channel.join()
    .then(connection => console.log('Connected!'))
    .catch(console.error);
  }
});

client.login('token');
```

**Comment by BeaRZiwe** [comment]
(function (exports, require, module, __filename, __dirname) { import { connect } from "http2";
                                                              ^^^^^^

SyntaxError: Unexpected token import, this is my error what do i do? 
its not even written in my code should i import this "import"or what pls help

**Comment by robflop** [comment]
Could you check your node.js version (using ``node -v`` in a terminal) and tell me what branch of discord.js you are using -- stable or master?

**Comment by YoungCurlin** [comment]
I'm having a similar problem as ghost

**Comment by lloti** [comment]
@YoungCurlin
1) This is a 6+ month old issue that's already been closed
2) Ghost is just a fake user; click on its profile for more info
3) Just delete the line, it was probably auto added by VS Code

**Comment by YoungCurlin** [comment]
darn, thanks
