### ISSUE TITLE
guildMemberAvailable event not working

### ISSUE THREAD

**Issue by desvandev** [hydrabolt/discord.js#715]
`bot.on('guildMemberAvailable', (guild, member) => {
    console.log(member);
});`
It should work whenever a user comes online right?

**Comment by GusCaplan** [comment]
i think guildMemberAvailable is for when a guild member is "shown" to the client by the api if it's needed, as a way of saving bandwidth on large guilds.

**Comment by Gawdl3y** [comment]
That's how I understand it, as well.
