### ISSUE TITLE
ClientDataResolver.resolveFile doesn't handle inexistent files

### ISSUE THREAD

**Issue by KetchupGirl** [hydrabolt/discord.js#717]
There's an error while attempting to send a nonexistent file.
Example code: `msg.channel.sendFile('nothing').catch((e) => console.log(e));`

This error is thrown in `ClientDataResolver.js` 
```javascript
/home/ketche/node_modules/discord.js/src/client/ClientDataResolver.js:226
            if (!stats.isFile()) throw new Error(`The file could not be found: ${file}`);
                      ^

TypeError: Cannot read property 'isFile' of undefined
    at fs.stat (/home/ketche/node_modules/discord.js/src/client/ClientDataResolver.js:226:23)
    at FSReqWrap.oncomplete (fs.js:123:15)
```
`stats` is **undefined** if the file doesn't exist, so **isFile** can't be called.
Besides, this error terminates the execution of the program.

**Comment by Gawdl3y** [comment]
Fixed in latest indev. (a2778d4a969266bb53bdd3cdd96b26be93b499b2)
