### ISSUE TITLE
playConvertedStream() doesn't work

### ISSUE THREAD

**Issue by Substance12** [hydrabolt/discord.js#719]
After converting audio to 16-bit PCM, 48000hz I try to play it over playConvertedStream but it doesn't do anything. It doesn't give me an error either, it just doesn't do anything. playStream gives me an unknown error instead

Am I compressing the audio in a wrong way? It's done with fluent-ffmpeg using the same settings specified in the docs. Or could it be something else?

**Comment by Gawdl3y** [comment]
See #708.

**Comment by Substance12** [comment]
Yep, changing that line made it work.
