### ISSUE TITLE
Mention

### ISSUE THREAD

**Issue by duotor0** [hydrabolt/discord.js#722]
How bot can mention command **sender**? Example: !ping Bot: @(username) pong!

**Comment by Gawdl3y** [comment]
Using [`message.reply('pong!');`](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/Message?scrollto=reply) or simply concatenating the user object to the string, like ``message.channel.sendMessage(`${message.author} pong!`);``

**Comment by Gawdl3y** [comment]
In the future, please use the [official Discord server](https://discord.gg/bRCvFy9) for questions like these.
