### ISSUE TITLE
Mocking Discord JS for Unit Testing

### ISSUE THREAD

**Issue by BrandonCookeDev** [hydrabolt/discord.js#727]
is it possible to mock discord.js for unit testing?

**Comment by hydrabolt** [comment]
at the moment it's not possible, we'd have to replicate a discord server which seems like an awful lot of hassle

**Comment by SyedAman** [comment]
Any update on this? Can we test the bots for replying properly to user messages?

**Comment by Lewdcario** [comment]
Please check the date of the last post before posting in a dead thread.

**Comment by piggyzoidberg** [comment]
very ded
