### ISSUE TITLE
login returns Bad Request

### ISSUE THREAD

**Issue by ErmanSayin** [hydrabolt/discord.js#750]
Hello, I wanted to create a selfbot, but I get this error when I attempt to log in using email and password:

```
(node:4400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Bad Request
```

The code is basically:

```
var Discord = require("discord.js");
var api = new Discord.Client();
api.login('<email>', '<password>');
```

**Comment by ErmanSayin** [comment]
After using catch looks like it "detected a new login location", so that's why it wouldn't let me in, my bad

**Comment by CornerOfTheOval** [comment]
How did you end up resolving this? im having the same issue

**Comment by ErmanSayin** [comment]
@CornerOfTheOval I used tokens instead of username/password, because using tokens bypasses the location detector. You can get the token of an user account by logging in through the web client, then putting `javascript:prompt("", localStorage.token)` into the address bar

**Comment by GusCaplan** [comment]
@CornerOfTheOval @ErmanSayin just for the future, we are removing the ability for the lib to login using an email and password, and only allowing tokens (see #963)
