### ISSUE TITLE
issue sending messages from bot

### ISSUE THREAD

**Issue by MRVDOG** [hydrabolt/discord.js#752]
Hi, for some strange reason, sendMessage all of a sudden stopped sending messages to my server, and I have no idea why, all I did was restart my bot, and now messages don't come through, I did some debugging to see if things were working properly, but I can't see an issue, I even added a console log to the sendMessage function, and it seems to be getting that far

![image](https://cloud.githubusercontent.com/assets/4422624/18895756/f72d1e14-8513-11e6-888f-faf2964c6e7b.png)

![image](https://cloud.githubusercontent.com/assets/4422624/18895765/1301cef0-8514-11e6-8dd6-108d956807a1.png)

I just can't figure out what is wrong, and have spent 3 days trying to fix it, which is why I have come here for assistance

**Comment by Gawdl3y** [comment]
You must do `npm install hydrabolt/discord.js#indev-old` in order to continue using v8. This will solve your issue.
