### ISSUE TITLE
bot failed to resolve 3 messages in 4000

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#753]
out of 4000 sendMessages discord.js v9 failed to resolve the promises for 3 messages completely.

**Comment by Gawdl3y** [comment]
https://puu.sh/rqk6a/8310574ceb.png

**Comment by macdja38** [comment]
Not sure if it was burst or sequential, just whatever the lib is calibrated for by default.

**Comment by iCrawl** [comment]
Not sure if this is related, but could be.
Out of 34 messages, 33 were sent and one threw me an error.
http://a.pomf.cat/ktpvnv.png

apiRequestMethod: 'burst'; latest indev.
the messages were I sent close to the ratelimit.

**Comment by Lykaksparsz** [comment]
4000? hmmh.. i think of.. a max messages!
