### ISSUE TITLE
Setting Mentionable for a Role

### ISSUE THREAD

**Issue by demipixel** [hydrabolt/discord.js#754]
```js
guild.createRole({ name: match[1], mentionable: true }).then(role => {
  console.log(role.mentionable);
  role.edit({ mentionable: true })
    .then(r => console.log(r.mentionable))
    .catch(console.error);

  ...
});
```

Outputs

```
false
false
```

Am I setting "mentionable" incorrectly or is this a bug?

**Comment by hydrabolt** [comment]
Works locally, what version of discord.js are you running? (`npm list discord.js`)

**Comment by Gawdl3y** [comment]
This is fixed in indev. Previously, `mentionable` was not passed along to the API request.
