### ISSUE TITLE
Browser?

### ISSUE THREAD

**Issue by Matthew2D** [hydrabolt/discord.js#76]
How do you get this in the browser like the website?

**Comment by hydrabolt** [comment]
In the repo there is a folder called web dists, it has js files containing a browserified discord.js.

**Comment by Matthew2D** [comment]
Can you give me your HTML file?

**Comment by abalabahaha** [comment]
@Matthew2D https://github.com/hydrabolt/discord.js/blob/gh-pages/browser.html

**Comment by Matthew2D** [comment]
Thanks! Not exactly easy to get to.

**Comment by abalabahaha** [comment]
The website itself is on Github Pages (*.github.io). The way Github Pages works, all the website source files are in the gh-pages branch. Now you know :P

**Comment by Matthew2D** [comment]
Yeah I never knew that.

**Comment by Matthew2D** [comment]
Wait the bot works uploading it to through the FTP right? I dont have to have a program running in the background in a VPN or anything?

I could just  upload these files (https://github.com/hydrabolt/discord.js/tree/gh-pages) and it will work?

**Comment by hydrabolt** [comment]
Should do, the bot will stay running as long as the user viewing the page
keeps it open.

**Comment by maxh65000** [comment]
The `dists` folder is no longer there. How can I do this now?

**Comment by devsnek** [comment]
all our webpack builds are available here: https://github.com/hydrabolt/discord.js/tree/webpack

**Comment by EntropicBlackhole** [comment]
Henlo, where would you end up having them now? I know it has been 8 years since this has been opened, but it would be very useful knowing

**Comment by Jiralite** [comment]
Discord no longer supports running Discord bots in a browser.

You can ask further questions in the [Discord server](https://discord.com/invite/djs).
