### ISSUE TITLE
Setgame function

### ISSUE THREAD

**Issue by developerCodex** [hydrabolt/discord.js#760]
In V9, does it allow you to put your bot's setgame to do not disturb?

**Comment by datitisev** [comment]
One can set the bot's game to anything you want, but to set its status to Do Not Disturb, use `client.user.setStatus('dnd')`. That changes its status, not its game.
To set its game, use `client.user.setStatus(<INSERT_STATUS_HERE>, 'Do Not Disturb');`

**Comment by hydrabolt** [comment]
DND and invisible are not available in v9 on npm, check indev branch

**Comment by datitisev** [comment]
Sorry, I forgot to mention it was on `indev` ATM. :/
