### ISSUE TITLE
Support for Discord Webhooks

### ISSUE THREAD

**Issue by kurisubrooks** [hydrabolt/discord.js#772]
I'd personally love this feature, because it allows me to better stylise my bot's responses.
Hope you consider it.

https://github.com/hammerandchisel/discord-api-docs/blob/feature/webhooks/docs/resources/Webhook.md

How they look in-client:
![image](https://cloud.githubusercontent.com/assets/6291467/19099081/c88d1a00-8afe-11e6-97d5-b793d3388667.png)

**Comment by macdja38** [comment]
Their is currently some debate over if this should be added to the lib or not... 
https://github.com/hydrabolt/discord.js/pull/768
Not really sure why... and discordie, discord.js v8 and eris have it. I'd suggest taking a look at that and implementing it yourself in your code, or using Gus's external web-hook tool that he is either working on or done.

**Comment by kurisubrooks** [comment]
No worries. It's really not hard for me to do in my own code, but I thought
it should also be implemented into the module, just to be as feature
complete as possible. Given other modules are working on implementing it
aswell.

**Comment by macdja38** [comment]
@kurisubrooks not working on it... they implemented it a while ago. It's definitely something I think we should see in the lib... it's a discord api call like any other... that said, hydrabolt is the one to talk to about this... and if we see rich embeds for bot messages 3 days from now their is not too much of a point.

**Comment by kurisubrooks** [comment]
Jeez, that's disappointing. 
I don't like the way Discord.io handles things, and the API is not great to use, but if I didn't have the knowledge to implement webhooks myself, i'd have switched to a different library by now. 

That PR's been open for 2 days, which in github terms is still quite short, but given this is a hyper-active project with work being committed almost every week, it's a bit of an annoyance to see @hydrabolt hasn't taken action against the pull request so far.

Hopefully we'll see webhooks feature complete in a future update of discord.js

**Comment by macdja38** [comment]
*discord.js and https://github.com/hydrabolt/discord.js/pull/757

**Comment by GusCaplan** [comment]
It is currently implemented in #768 which should be merged soon

**Comment by hydrabolt** [comment]
the PR was merged
