### ISSUE TITLE
messageUpdate does not fire on messages created before connection is established

### ISSUE THREAD

**Issue by michaelowens** [hydrabolt/discord.js#773]
Like the old issue #294 , messages created before the bot connects won't fire the `messageUpdate` event upon updating the messages.

**Steps to reproduce:**
- Create message in channel
- Connect with discord.js (bind `messageUpdate` on client)
- Update message

No event will be fired.

**Comment by hydrabolt** [comment]
There's not much we can do, discord.js ensures update only fires if it was aware of the previous state of the message. To get around this you can fetch an entire channels logs or listen to raw events.
