### ISSUE TITLE
Client.guildMemberAdd

### ISSUE THREAD

**Issue by 5Five5** [hydrabolt/discord.js#776]
On production and indev 9.3, I am receiving an issue where this is being sent for every member that is already in my server.

My code:
`Client.on('guildMemberAdd', (guild, member) => {`
`	guild.channels.get("123456").sendMessage("Welcome, " + member);`
`});``

On 9.3, this will send this message with every member in my server.
I reverted to 9.2 and it only sends the message when a new member joins my server.

**Comment by hydrabolt** [comment]
Is this a user/bot account?

**Comment by 5Five5** [comment]
It occurred on both.

**Comment by hydrabolt** [comment]
can't reproduce

**Comment by Gawdl3y** [comment]
@hydrabolt Probably because you already claimed to have fixed it in the last commit, dingus.
