### ISSUE TITLE
Yeoman generator for discord.js

### ISSUE THREAD

**Issue by MeLlamoPablo** [hydrabolt/discord.js#780]
Hi there! I made a yeoman generator for discord bots using discord.js. I made it for myself, to make it easy to create bots and to experiment with yeoman, but I figured that I might as well share it with you guys, just in case you wanted to reference it somewhere in the README, because it'd make the process of getting started a lot easier for beginners.

Here it is: https://github.com/MeLlamoPablo/generator-discordbot

**Comment by Gawdl3y** [comment]
Added a link to the readme in ca4e9549a0be09077069d2db6beb0d5c641c3674.
