### ISSUE TITLE
Client.muteMember() no longer working

### ISSUE THREAD

**Issue by dayxhep** [hydrabolt/discord.js#781]
I already checked the permissions of the bot, a client.muteMember(user, server) no longer mutes the user.
No error returned in console, the user and the server are resolvable and are OK.

It seems working, no promises in waiting but the user can continue to type in text channels

**Comment by datitisev** [comment]
I'm pretty sure `.muteMember` is for **voice**, and not typing, as another method close to it is `.deafen` (voice).

**Comment by dayxhep** [comment]
I finally just did it :

```JS
client.muteUser = function (user, channel, callback) {
	var object = {"readMessages": false, "sendMessages": false};
	self.bot.overwritePermissions(channel, user, object, callback);
}

client.unmuteUser = function (user, channel, callback) {
	var object = {"readMessages": true, "sendMessages": true};
	self.bot.overwritePermissions(channel, user, object, callback);
}
```

**Comment by datitisev** [comment]
@dayxhep Don't do that! You are removing the ability to mute and unmute users in a voice channel server-wide!
Make your own function instead, or use `client.removeWritePerms` or something.

**Comment by dayxhep** [comment]
muteUser() does not override muteMember() in my case ^^

**Comment by datitisev** [comment]
Right, sorry about that. I misread it.
