### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by MRVDOG** [hydrabolt/discord.js#782]
Hey, for some strange reason I'm getting `Error: Unauthorized` when trying to send a message, I am using normal user Credentials to login, as I don't want to turn my account into a bot, I am trying to make it so when I send a command it replies and removes the original message (sort of like /shrug), but it's not working 😢 

![image](https://cloud.githubusercontent.com/assets/4422624/19221076/c65760f0-8e33-11e6-99c6-5b2233c55b1d.png)

any help would be greatly appreciated

**Comment by iCrawl** [comment]
Is that a selfbot, like running on your account?
Or a bot that is running another account that isn't a bot account?

**Comment by MRVDOG** [comment]
Selfbot on my account

**Comment by GexoXYZ** [comment]
Login with a token instead of your email/pass, also you might wanna use an up-to-date version of d.js. In certain older versions you had to instantiate the client using `new Client({ bot: false });` for user accounts.

**Comment by MRVDOG** [comment]
I'm using 8.2.0, `new Client({ bot: false });` worked, thanks Gexo
