### ISSUE TITLE
Search functionality on documentation

### ISSUE THREAD

**Issue by fu012343210** [hydrabolt/discord.js#793]
This is probably not the correct place to put this but I see no where else to ask... Can we please get a search function on the documentation website?

**Comment by GusCaplan** [comment]
this is already planned.

**Comment by fu012343210** [comment]
Perfect. The documentation is great, but that will be a great addition.

**Comment by GusCaplan** [comment]
@fu012343210 If your question/issue was answered/resolved (respectively) please make sure you close the issue!

**Comment by iCrawl** [comment]
Actually no, keep it open, and we should tag it as "enhancement", so hydra really doesn't forget.

**Comment by Gawdl3y** [comment]
See #799.
