### ISSUE TITLE
Documentation site improvements

### ISSUE THREAD

**Issue by Gawdl3y** [hydrabolt/discord.js#799]
## New stuff
- [x] Indicate that a method is static
- [x] Display return descriptions for methods
- [x] Indicate that a property is readonly
- [ ] ~~Indicate that a property is a getter/setter~~ (not currently possible)
- [ ] ~~Show nullability on types~~ (not currently possible)

## Old stuff
- [x] Add a search bar
- [x] Add display for default values on typedefs and method parameters (see [SplitOptions](http://hydrabolt.github.io/discord.js/#!/docs/tag/indev/typedef/SplitOptions))
- [x] Fix blank page when clicking the Docs button in the header while already viewing the docs
- [x] Fix commit/release selection
- [x] Fix constructor with object + properties params (see [ShardingManager](http://hydrabolt.github.io/discord.js/#!/docs/tag/indev/class/ShardingManager))
- [x] Fix clicking on a property/method to jump to it not working when it was already scrolled to
- [x] Hide `v8`, `gh-pages`, `gh-pages-dev` from branch selection
- [x] Make the list of classes/typedefs/etc actual links, so you can right-click -> open in new tab, or middle click
- [x] Fix the built-in JS type links
- [x] Fix awful browser history behaviour
- [x] Make the "extends ClassNameHere" link to the type
- [x] Make types and methods/properties/events actual links

**Comment by Toshimonster** [comment]
How about adding a section on what permissions are required for each command? eg; Fetchmessages = readmessages etc
