### ISSUE TITLE
User VoiceConnection from Message is Null

### ISSUE THREAD

**Issue by koo04** [hydrabolt/discord.js#80]
It seems when I get a user from a message, who is connected to a voice channel, I get null when using:

```
message.author.voiceConnection
```

I was going to fork and see if I can find out why, but figured I would submit a bug first to see if it is just me.

**Comment by hydrabolt** [comment]
users objects don't have a voiceConnection, it's only `client.voiceConnection`

**Comment by abalabahaha** [comment]
How are you supposed to get the connection of another user?... If that was allowed you could just stalk people...

**Comment by koo04** [comment]
Isn't the voiceConncetion the voice channel they are on? I am trying to see what voice channel a user, who just sent a message, is on.

**Comment by hydrabolt** [comment]
Ah, that's not possible at the moment, however it will be in the next version. I'll make another comment on this issue when it's available ;)

For now, only the logged in client has access to the voice connection, it doesn't know about any other users.

**Comment by koo04** [comment]
Okay, that makes sense. I will wait for a reply.

Until then, I assume that I just use a Channel resolvable object to join a Voice Channel?

**Comment by hydrabolt** [comment]
Yep ;)
