### ISSUE TITLE
Voice playback stops for listeners in a voice channel until they disconnect/reconnect when the bot finishes streaming in a different guild

### ISSUE THREAD

**Issue by Tyler0130** [hydrabolt/discord.js#801]
So, I've been playing around with my music bot and trying to play music with it on multiple guilds. One thing I've noticed is that when the song is over and the dispatcher comes to an end, the audio for the listeners in the other guilds cuts off. However, if you leave the voice channel and connect again, the audio plays like nothing ever happened.

After @Hyper-Coder experienced the same issue with his bot (which is undoubtedly coded differently than mine) and having no reasonable explanation for the issue within my code, I've come to the conclusion that something is possibly buggy in v9 of the library, as v8 doesn't have this issue, to my knowledge.

**Comment by Maurdekye** [comment]
Having same issue here, after ending one dispatch all others stop for people currently connected. They have to disconnect and reconnect to the voice servers in order to keep listening.

**Comment by hydrabolt** [comment]
Fixed in the backwards-compatible voice rewrite which is available in the indev branch. Will be released with v10 soon.
