### ISSUE TITLE
bot.joinVoiceChannel?

### ISSUE THREAD

**Issue by Jwiggiff** [hydrabolt/discord.js#803]
bot.joinVoiceChannel doesn't work.

    var Discord = require("discord.js");
    var bot = new Discord.Client();

    bot.on("message", msg => {

      let prefix = "jarvis ";

      if(!msg.content.startsWith(prefix)) return;
      if(msg.author.bot) return;
      var User = msg.author
        if (msg.content.startsWith(prefix + "help")) {
            msg.channel.sendMessage("I sent a list of commands to you, " + User);
            User.sendCode("", "Commands:\nhelp    Displays commands\nping    Pong!");
        }

        if (msg.content.startsWith(prefix + "ping")) {
          msg.channel.sendMessage("Pong!");
        }

        if (msg.content.startsWith(prefix + "voice")) {
          msg.channel.sendMessage("Joining...");
          var channel = msg.author.voiceChannel;
          bot.joinVoiceChannel(channel).catch(error);
    		}
    });

**Comment by GusCaplan** [comment]
@Jwiggiff if you [join the discord.js help server](https://discord.gg/bRCvFy9) we can assist you there
