### ISSUE TITLE
GuildMember.ban(days) \ Guild.ban(member, days) fails to purge

### ISSUE THREAD

**Issue by Hyper-Coder** [hydrabolt/discord.js#804]
The deleteDays isn't working to purge messages. I've tried both GuildMember.ban and Guild.ban, and neither work to purge a users messages. The number **is** a number.

**Comment by Tyler0130** [comment]
Hmm, this is interesting. I've been having this issue too.

**Comment by hydrabolt** [comment]
Fixed as of 21533eec5b142f3ff166db190477de88a1a70645
