### ISSUE TITLE
bot.user.setStatus('online', 'status') crashes bot

### ISSUE THREAD

**Issue by DoctorDarkMagic** [hydrabolt/discord.js#806]
I have been having these issues a lot.

https://gyazo.com/f834e3e2b2092851d95558c48ff76d38

**Comment by Hyper-Coder** [comment]
It's now bot.user.setPlaying('game')

**Comment by DoctorDarkMagic** [comment]
Not on dev

**Comment by Gawdl3y** [comment]
http://hydrabolt.github.io/discord.js/#!/docs/tag/indev/class/ClientUser?scrollto=setGame on indev
