### ISSUE TITLE
TextChannel is not defined. Please help

### ISSUE THREAD

**Issue by kinggamer1235** [hydrabolt/discord.js#808]
I am trying to make the bot simple post a message when it is ready but for some reason it wont work. I have followed the documentation but for me it just doesn't work. Help would be greatly appreciated.

```
var Discord = require("discord.js");

var bot = new Discord.Client();

bot.on('ready', () =>
{
	TextChannel.sendMessage("Hello!")
});
```

error:
 TextChannel.sendMessage("Hello!")
        ^

ReferenceError: TextChannel is not defined

**Comment by Tyler0130** [comment]
This isn't an issue.

By opening this issue, I'm going to guess that you are new to JavaScript, you haven't read the documentation very well, or both.

If you are having trouble, you can join the official Discord.JS support server here: https://discord.gg/bRCvFy9.

**Comment by R3alCl0ud** [comment]
What you want to do is this
```js
bot.on('ready', () => {
    bot.channels.get("ID of channel").sendMessage("Hello!");
});
```
