### ISSUE TITLE
Event Enter Voice Channel

### ISSUE THREAD

**Issue by qlaffont** [hydrabolt/discord.js#811]
Hi,
I didn't found in documentation but it is possible to have an event where a guildmember go to voice channel. With this event we can have channel and member.
Thanks.
Quentin

**Comment by qlaffont** [comment]
Same With Disconnect from voice channel

**Comment by Tyler0130** [comment]
There's an event called "voiceStateUpdate", which I believe is what you are looking for.

**Comment by qlaffont** [comment]
And after that i need to check newMember.voiceChannel ?

**Comment by Tyler0130** [comment]
Yep.

**Comment by qlaffont** [comment]
Thanks ^^

**Comment by qlaffont** [comment]
If you can create a dedicated page for Event in documentation is better ;)

**Comment by Tyler0130** [comment]
http://hydrabolt.github.io/discord.js/#!/docs/tag/indev/class/Client?scrollto=voiceStateUpdate
