### ISSUE TITLE
fetchMessage does not fetch a message that was sent before a D.JS client is rebooted

### ISSUE THREAD

**Issue by CyberiumShadow** [hydrabolt/discord.js#813]
Essentially,

Running `message.channel.fetchMessage(id)` after a bot reboot will return a pending promise, however when attempting to access a property of that promise ie. Message ID, it does not return anything.

![image](https://cloud.githubusercontent.com/assets/4259904/19519389/8ee0c194-9657-11e6-8ff8-1443f760fcb3.png)

**Comment by CyberiumShadow** [comment]
UPDATE: Just ran the eval on my legacy bot (pure D.JS)

I got a forbidden error and was unable to obtain message ID after a reboot.

**Comment by CyberiumShadow** [comment]
Resolved: Only Bot Accounts can use this endpoint,

Suggestion: **Update the documentation for fetchMessage** saying that only Bot accounts can use that method.

**Comment by Gawdl3y** [comment]
This will be documented.
