### ISSUE TITLE
VoiceReceiver PCM output

### ISSUE THREAD

**Issue by appellation** [hydrabolt/discord.js#814]
I've been testing the output of `VoiceReceiver.createPCMStream()` and found that it outputs 32-bit PCM rather than the 16-bit PCM as stated in the [docs](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/VoiceReceiver?scrollto=createPCMStream).

To find this, I used `fluent-ffmpeg` and encoded it with an input format of `s16le` into an mp3 file.  This produced a hilariously distorted but not very helpful recording.  Trying this again with `s32le` worked perfectly.

**Comment by Gawdl3y** [comment]
Fixed in 4e693e2e390149694c0a070f4620b8a255510ef6.

**Comment by winneon** [comment]
@appellation Might I ask how you piped to `fluent-ffmpeg`? When I try to directly output to a writable stream, the PCM file is an invalid file when I run it through ffmpeg and it doesn't play anything.

**Comment by appellation** [comment]
I used the below code to pipe it to a stream that accepts only 16-bit LE audio although I'm pretty sure I was able to test this code by changing the output to a `mp3` file.  The only part that's relevant to D.js is the first two lines; the rest is me formatting to the specifications I need.

```js
ffmpeg(VoiceReceiver.createPCMStream(user))
	.inputFormat('s32le')
	.audioFrequency(16000)
	.audioChannels(1)
	.audioCodec('pcm_s16le')
	.format('s16le')
	.on('error', reject)
	.pipe(out);
```

**Comment by winneon** [comment]
Thank you! I assume `out` is a writable stream, perhaps created with `fs.createWriteStream`?

**Comment by appellation** [comment]
Sorry.  `out` is actually streaming to an API endpoint, although I doubt it would behave significantly different from a stream created by `fs`.
