### ISSUE TITLE
discord.js v9.3.0 bot.reply not working.

### ISSUE THREAD

**Issue by tomgie** [hydrabolt/discord.js#817]
Trying to reply to a message gives me this error.
http://pastebin.com/a2jxmPHZ

**Comment by Tyler0130** [comment]
Because `bot.reply()` isn't a function. In v9, it's `Message.reply()`. So, assuming the message is "message", use `message.reply("reply message");`.

For further support, please join [this Discord server](https://discord.gg/bRCvFy9).

**Comment by appellation** [comment]
Since you have two parameters in your function call, I would assume that you're trying to upgrade from v8?  If so, check out [these docs](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/file/general/Updating%20your%20code).
