### ISSUE TITLE
Stream playback is slow

### ISSUE THREAD

**Issue by koo04** [hydrabolt/discord.js#82]
I am streaming music to the room but the BPM is like 10. Is that because of my decoding or because how Discord.js is putting out to the server?

Here is the code:
```javascript
            Icy.get(settings.radioCast, function (res) {

              var dec = res.pipe(new Lame.Decoder());
              room.playStream(dec, function(err, str) {
                if(err) console.log(err);
                console.log(str)
              });

            });
```

**Comment by hydrabolt** [comment]
Out if interest, is it a mono stream and if so are you using discord.js from npm, master branch or indev branch? The indev branch has some changes to stereo which might cause it.

If its master or npm it would just be the stream you are passing in.

**Comment by koo04** [comment]
I believe the stream is stereo. I am streaming it FROM VirtualDJ TO my ShoutCAST server. Then the bot grabs it from there. The ShoutCAST and VirtualDJ settings seems to be stereo.

I am using Discord.js from NPM.

Then it sounds like it may be the decoder. I will see about getting some answers from Lame. Since there is not a lot of documentation on it. I will report back and close this when I have something.

**Comment by meew0** [comment]
You shouldn't need Lame, discord.js should be able to decode the stream itself if you use `playRawStream` instead of `playStream`.

**Comment by koo04** [comment]
I attempted that. It would just play a split second of static and the bot would stop.

Though, now I think about it. I was not piping the stream. I will go try a couple things and see what happens.

**Comment by koo04** [comment]
It crashes at: 
```
_stream_readable.js:495
   dest.on('unpipe', onunpipe);
```

The code:
```javascript
Icy.get(settings.radioCast, function (res) {
//var dec = res.pipe(new Lame.Decoder());
  var dec = res.pipe();
  room.playRawStream(dec, function(err, str) {
    if(err) console.log(err);
    console.log(str)
  });
});
```

**Comment by meew0** [comment]
`pipe` with no arguments shouldn't work (or not do anything) as it just pipes one's stream output into another's input. Try it without the `pipe`, like `room.playRawStream(res, ...)`

**Comment by koo04** [comment]
I figured that would be an issue.

I had tried that. It comes out with the same error.

**Comment by hydrabolt** [comment]
Can you try adding your own `end` `close` and `error` event handlers that just console.log when they occur to the stream? I want to see if it's an issue with the stream. Also try adding a `data` handler. Thanks

**Comment by hydrabolt** [comment]
Any updates on the situation? I'm assuming it's fixed now

**Comment by koo04** [comment]
I have not gotten time to do it. My code is public if you need it tested sooner than later. I apologize for the messy code, if you do go take a look.
