### ISSUE TITLE
How do you Send A Message without an @?

### ISSUE THREAD

**Issue by SharkFinPro** [hydrabolt/discord.js#822]
I have read the docs but cant find out how

**Comment by SharkFinPro** [comment]
EDIT: How do you send it while not going off of a message?

**Comment by Gawdl3y** [comment]
[User.username](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/User?scrollto=username) and [User.discriminator](http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/User?scrollto=discriminator).
Please use our [official Discord server](https://discord.gg/bRCvFy9) for help like this.
