### ISSUE TITLE
The official playfile/playStream example in the documentation does not work

### ISSUE THREAD

**Issue by Dewiter** [hydrabolt/discord.js#823]
Hi,

since 2days, i'm trying to get the PlayStream method working, i'm following all the steps and did all well, but the only thing i see is :
-it works if the youtube video is < ~5sec
-I see the bot green voice indicator blinking for 0.1sec if its > 5sec.

I have no errors in any .catch :/ 

here's my snippet : 

```Js
const Discord       = require('discord.js');
const credential    = require('./credential.json');
const ytdl          = require('ytdl-core');

const streamOptions = { seek : 0, volume : 1}
const bot           = new Discord.Client();

//-----------------------------------

bot.on('ready', function()
{
    console.log("Connected !");
    bot.channels.find('id','235930131280035842').sendMessage('Connected !')
    bot.channels.find('id', '236934801817468932').join()
    .then(function(connection)
    {
        const stream = ytdl('https://www.youtube.com/watch?v=XAWgeLF9EVQ', {filter : 'audioonly'});
        const dispatcher = connection.playStream(stream, streamOptions);

        // ytdl.getInfo('https://www.youtube.com/watch?v=kfoJUeyMsOE',['-q', '--no-warnings', '--force-ipv4'], function(err,video)
        // {
        //     connection.playStream(request(video.url));
        // });

        connection.on('error', (err) =>
        {
            console.log("err : ", err);
        });
        connection.on('disconnected', (err) =>
        {
            console.log("err : ", err);
        });
    })
    .catch(function(e)
    {
        console.log("err : ",e);
    });
});

bot.login(credential.token);
```

hope it helps.

node -v :
`v6.8.0`

discord.js version :
`^9.3.0`

ytdl-core version:
`^0.7.18`

avconv:
`9.18-6:9.18-0ubuntu0.14.04.1`

EDIT: I found somehing, its not working on my setup because i'm using the native "bash for windows10". I tryied on my linux and its all ok.

**Comment by CyberiumShadow** [comment]
Here's an optImisation point

You don't need to use find for ids

Just use .get

**Comment by FOG-Yamato** [comment]
Could be unstable internet, that often causes the dispatcher to crash with the ERRCONRESET message

**Comment by IanMitchell** [comment]
I'm also struggling with this. I'm a little confused on the playFile API documentation as well - some examples have it as a promise, and others don't.

Promise syntax: http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/StreamDispatcher
Non-promise: http://hydrabolt.github.io/discord.js/#!/docs/tag/master/class/VoiceConnection?scrollto=playFile

**Comment by appellation** [comment]
I'm a little confused about what you're asking here, but I'll break it down as I understand it and hopefully that will help.

## A description of what happens:

You've got yourself a `VoiceChannel` and so you connect to it using `join()`.  This gives you a promise that resolves with a `VoiceConnection`.  You take that connection and execute `playFile(file)` which returns a promise that resolves with the `StreamDispatcher` which is an `EventEmitter` (not a promise).  You use this dispatcher to monitor and control the state of the audio stream generated by the `playFile` function.

## An example of what happens:

I figure that I could take this opportunity to combine the examples in the docs.

```js
voiceChannel.join()
.then(connection => {
  return connection.playFile('C:/Users/Discord/Desktop/music.mp3');
 })
.then(dispatcher => {
  dispatcher.on('error', console.error);
  // You can also do things like dispatcher.pause() and dispatcher.end() here.
}).catch(console.error);

**Comment by hydrabolt** [comment]
above should fix your issue ^
