### ISSUE TITLE
<Guild>.emojis does not update

### ISSUE THREAD

**Issue by DarylPinto** [hydrabolt/discord.js#825]
`<Guild>.emojis` does not update when an emoji's name is changed in the server settings.

To recreate this issue:

1. Create a custom guild emoji
2. `console.log(<Guild>.emojis.array().map(emoji=>emoji.name));`
3. Change the name of the custom emoji in the server settings
4. Run the `console.log` statement again to see that the array has not changed

In order for to actually log the change, the bot must be restarted.

**Comment by Gawdl3y** [comment]
Fixed in #826.
