### ISSUE TITLE
trying for the prefix to be the bots@

### ISSUE THREAD

**Issue by ChlckenWings** [hydrabolt/discord.js#827]
can someone help me? what im trying to do is so if someone types "@botname hi" the bot will say whatever back but how do you get teh prefix to be the bots @?

**Comment by Gawdl3y** [comment]
The prefix would be `<@BOT'S USER ID HERE>` or `<@&BOT'S USER ID HERE>`.
Please us our [official Discord server](https://discord.gg/bRCvFy9) for questions like these in the future.
