### ISSUE TITLE
Using GuildMember.ban/kick returns 403, Guild.banMember succeeds

### ISSUE THREAD

**Issue by joelfi** [hydrabolt/discord.js#829]
This works:

```js
// message received from client.on("message", message => {....
message.member.guild.banMember(message.author, 5); // bans member + deletes messages in 5 days
```

But this doesn't:

```js
// message received from client.on("message", message => {....
message.member.ban(5); // bans member + deletes messages in 5 days
```

Catching the error from `ban` (formatted):
```
Error: cannot PUT /api/v6/guilds/[guild_id]/bans/[member_id] (403)
status: 403,
text: '{"code": 0, "message": "Privilege is too low..."}',
```

I have double-checked that the bot has ban/kick permissions and the person to be banned/kicked is in a lower role than the bot. Can't kick with any method, since there is no `guild.kickMember`. Any reason why `GuildMember.ban` and `Guild.banMember` require different privileges/permissions?

**Comment by hydrabolt** [comment]
Guild.banMember isn't a feature in 9.x.x, are you using an outdated version of discord.js?

**Comment by joelfi** [comment]
Package.json says that I'm using 9.3.0:

```"discord.js": "^9.3.0"```

**Comment by DarkN-exus** [comment]
`message.guild.ban(message.mentions.users.first(), "days");` Should work

**Comment by joelfi** [comment]
Turns out the code was trying to ban/kick the wrong member. Thanks!
