### ISSUE TITLE
[Minor - NonIssue] nodei.co url in README.md

### ISSUE THREAD

**Issue by khionu** [hydrabolt/discord.js#83]
*Might* want to remove that...

**Comment by nicholastay** [comment]
It seems that nodei.co is down, I think possible alternatives could be shields.io or badge.fury.io for the version badge.

**Comment by abalabahaha** [comment]
@khionu It should be showing up as a blank image, not a URL...
And nodei.co is just temporarily down, not much point in removing it and putting it back later. 

@nicholastay Those are badge sites, but there is a difference between version badges and nodei.co badges.

**Comment by khionu** [comment]
It is showing. Had no idea it was temporary, never really took notice given the important stuff is in the docs. A friend pointed it out.
