### ISSUE TITLE
message.reply not taking split:true

### ISSUE THREAD

**Issue by aister** [hydrabolt/discord.js#837]
if the split option in message.reply is not an object, the split option will be changed into an empty object, which means no split.

the issue can be found at line 374 in src/structures/Message.js

**Comment by hydrabolt** [comment]
Fixed in add52ce62d24a03e127b5c2deee5812fd9b0ad0d, will be released in v10

**Comment by iCrawl** [comment]
@aister an empty object is still truthy and it will still work.

https://u.pomf.is/tnobya.png
https://u.pomf.is/pwktxf.png
