### ISSUE TITLE
disableEveryone fails when using double-at-signs (@@everyone)

### ISSUE THREAD

**Issue by Cat-who-loves-bots** [hydrabolt/discord.js#838]
So my friend tried to brake message option disable everyone with say command and he managed to do it by adding another @ that shouldn't work ![](http://i.imgur.com/MpxDkMi.jpg)

**Comment by iCrawl** [comment]
I don't believe you.

**Comment by Cat-who-loves-bots** [comment]
hmm seems updating to latest indev fixed it :eyes: problem doesn't exist anymore
