### ISSUE TITLE
2k characters

### ISSUE THREAD

**Issue by appellation** [hydrabolt/discord.js#856]
I'm not sure how important this is, but attempting to send a message over 2000 characters rejects the promise with a `Bad Request` error from the Discord API.  I remember this issue was addressed in #653, but it seems to have been reverted with the v10 update.

**Comment by iCrawl** [comment]
https://discord.js.org/#!/docs/tag/master/class/TextChannel?scrollto=sendMessage
https://discord.js.org/#!/docs/tag/master/typedef/MessageOptions
https://discord.js.org/#!/docs/tag/master/typedef/SplitOptions

`.sendMessage()` and `.sendCode()` both can be passed the option split with a variety of settings.
This was not reverted.

**Comment by appellation** [comment]
Although I'm curious what the situation would be in which you'd specifically not want your message split or why it wouldn't be default.

**Comment by iCrawl** [comment]
Why do you think it should be default?

And if you dont want it to split and it is above 2k characters you can trim the message yourself.

**Comment by appellation** [comment]
I suppose there aren't enough variable-length messages that could reach the size where it would be a problem.  I was just thinking that wanting a split message rather than an error would be preferable to most people, so in the instances where the bot might generate a 2k+ character message, defaulting to that would be better.

But, it is a rather rare situation, so I can see how the explicit statement is fine.

**Comment by iCrawl** [comment]
I hope you know what that means if you scrape a website and don't know how many characters you will get back right?
It could be 10k, 50k, 100k.
Defaulting it would result in you spamming the shit out of a channel and even get ratelimited.

**Comment by appellation** [comment]
Never considered that people do that with bots. Fair point.



On Thu, Oct 27, 2016 at 9:24 PM -0700, "Crawl" <notifications@github.com<mailto:notifications@github.com>> wrote:


I hope you know what that means if you scrape a website and don't know how many characters you will get back right?
It could be 10k, 50k, 100k.
Defaulting it would result in you spamming the shit out of a channel and even get ratelimited.

-

**Comment by GusCaplan** [comment]
that's a nice auth token there, it would be a shame if someone got their hands on it...

**Comment by appellation** [comment]
wtf.  the message at the bottom said i could just reply 😢
