### ISSUE TITLE
node-opus is easily built on Windows but README states otherwise

### ISSUE THREAD

**Issue by Luminess** [hydrabolt/discord.js#863]
In [the README](https://github.com/hydrabolt/discord.js#installation), it's stated:

> getting node-opus to build [on Windows] can be a bit of a challenge

That's incorrect. Satisfying all of the prerequisites for building native node modules on Windows is as easy as entering `npm install --global --production windows-build-tools` in cmd. It's even recommended in the [node-gyp README](https://github.com/nodejs/node-gyp/blob/master/README.md#installation).

**Comment by meew0** [comment]
That section is from the time when you had to manually install Visual Studio etc. to get it to build. I haven't personally tried the new process but if it really is that easy it should definitely be changed.

**Comment by Gawdl3y** [comment]
Updated docs in 2a50dad852bba37a860deae5ca9b530f5327c2cd.
