### ISSUE TITLE
role.setPosition()/guild.setRolePosition()

### ISSUE THREAD

**Issue by firynth** [hydrabolt/discord.js#864]
Will not reorder the positions of roles to reflect roles being deleted out. Position numbers go missing as you add more. See list below. New roles are being set to position 7 as they are created. FF00FF was a newly created role.

Also, these functions will hang and return a response code of 400 "Bad request" if positions get corrupted in some fashion so that the position of a role is higher than what the highest role position should be.

Ex:
Role: @everyone   Position: 0
**Role: Mod   Position: 11** _Highest role_
Role: Firy Specials   Position: 5
Role: Reg   Position: 6
Role: Po'Dawgs   Position: 16
Role: lemon   Position: 15
Role: MasterOverwatch   Position: 4
Role: Nightbot   Position: 3
Role: BetterTTV   Position: 2
Role: Timeout   Position: 1
Role: #0066FF   Position: 14
Role: #FF00FF   Position: 1

I am unable to use setPosition or setRolePosition after this occurs. I believe that this occurs when the async calls try to set the position for a role as another role is being deleted. Due to the nature of async calls, I don't know exactly what is happening  on the back end exactly.

**Comment by Gawdl3y** [comment]
The behavior of the reordering is on Discord's end, and is intentional.

**Comment by firynth** [comment]
No, the behavior of deleting and not changing role positions is on Discord's end, and is "intentional". However, the Discord app changes the positions of **_ALL_** roles when you change the position of a role by dragging a role to the appropriate spot. These function calls do not. It continues to ignore the positions that were deleted out and increases the positions of all other positions by 1, regardless of what number they had before. Hell, even creating a multiple roles can all share the same position of 1 until you update their positions with code.

So the behavior of breaking the positions so that you can't make calls until you manually fix it, is not "intentional". And also the main thing I was trying to report. If this is also on Discord's end, then so be it. I mentioned role numbers not being updated on deletion because, without more information, I have no clue if this is what's causing the lockout for setting role positions. The act of deleting and creating a new role is causing this API to break eventually. And before you ask, I use promises to ensure the delete is done before a new role is created, but since it's async, two calls could be issued near the same time and possibly cause the corruption.

**Comment by hydrabolt** [comment]
_Should be fixed in https://github.com/hydrabolt/discord.js/commit/e63432c18e380afe27c19c89f67e1dac9d78650a in indev
