### ISSUE TITLE
How to edit a message by id? Or, how to construct our own Message by its id?

### ISSUE THREAD

**Issue by MeLlamoPablo** [hydrabolt/discord.js#865]
Hi! I've been wondering how to edit a message knowing its id. As stated on the docs, this previously was:

```js
Client.updateMessage(message, "New content");
```

but it got changed to:

```js
Message.edit("New Content")
```

I understand the logic behind the change, but I can't figure out how to edit a message knowing only its id.

The discord API requires both the channel id and the msg id to edit the message, so I figured that I could get the messages from the chanel object, wich I do have. I tried the following:

```js
var channel = bot.channels.get("my_channel_id"); // this does work
var message = channel.messages.get("my_msg_id"); // this returns undefined
```

I've realized that the `channel.messages` collection only shows one message (while my channel has much more than that). To confirm that, I tried:

```js
channel.messages.forEach((val, key, mapObj) => {
    console.log(val.id);
});
```

And that only logged the channel's last message's id, which is not the one I want.

So, could I get some insight on what I'm doing wrong? Thanks in advance!

On a side note, while I understand that this is logical and structured:

```js
var channel = bot.channels.get("my_channel_id");
var message = channel.messages.get("my_msg_id");
message.edit("New content");
```

IMHO this would be way more convenient and be as logical and structured than the previous version:

```js
var message = new Discord.Message("my_msg_id");
message.edit("New content");
```

But I don't think that's possible, or at least, it's not documented.

**Comment by hydrabolt** [comment]
If your channel only stores 1 message, you've manually set that yourself as we default to 1,000 messages per server ([see messageMaxCacheSize](https://discord.js.org/#!/docs/tag/master/typedef/ClientOptions)).

But yes, you would have to do `channel.messages.get()` once this is resolved, or to force an ID to be cached on a bot account you can run `TextBasedChannel.fetchMessage()`

**Comment by meew0** [comment]
Alternatively, if you want to skip the resolution step over performance considerations or such, you can invoke `client.rest.methods.updateMessage` manually with a constructed `Message` object, given the channel and message IDs:

```js
message = {
  channel: { id: 12345 },
  id: 23456
};

client.rest.methods.updateMessage(message, "My new content");
```

**Comment by MeLlamoPablo** [comment]
@hydrabolt actually, I haven't touched that setting, so I don't know what it's causing the issue. I can provide any further information if you want. I could even give you access to my repo if you want, but that would be me asking you to do the debugging, so probably not. Thanks for the quick answer anyways.

@meew0 thanks, I'll try that if what hydrabolt suggests doesn't work from me.

**Comment by hydrabolt** [comment]
I'd be happy to debug it if you can give me access 🙂

**Comment by Gawdl3y** [comment]
We default to 200 messages per channel, not 1000 messages per server.

**Comment by MeLlamoPablo** [comment]
@hydrabolt thanks for your offer! However I've already solved it :)

I was expecting `channel.messages.get()` to have every message on the channel, but it only contains messages that were sent since the bot was running. Therefore, if I try to get a message that was sent before a bot restart, it would return undefined. As you pointed out, the soulution would be:

```javascript
TextChannel.fetchMessage(msgId).then(console.log);
```

Thank you all for your help!

**Comment by hydrabolt** [comment]
No problem, glad you could get it working! 😄
