### ISSUE TITLE
Problem with user status updates.

### ISSUE THREAD

**Issue by richmoj3** [hydrabolt/discord.js#87]
I was having an issue with users Online/Offline status not being updated in the member's cache. I added the following line in InternalClient.js under case PacketType.PRESENCE_UPDATE and it seems to have fixed the issue.

    data.user.status = data.user.status || user.status;

I'm not sure if this was the correct way to go about fixing it.

**Comment by TehSeph** [comment]
If you mean https://github.com/hydrabolt/discord.js/blob/master/src/Client/InternalClient.js#L1262 then yup that looks like the place to add it. :+1:

**Comment by TehSeph** [comment]
Eh, actually. That's wrong. The issue looks like it should be
`user.status = data.user.status;` instead of `user.status = data.status;`
on https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1391
Same with the line after it, dealing with game_id.

**Comment by abalabahaha** [comment]
I think if we actually updated the user presence _before_ emitting the presence event, it should work.

**Comment by TehSeph** [comment]
OH lol, didn't see that. Yep that ordering. rip.

**Comment by hydrabolt** [comment]
Potentially fixed in d9b9d1d0a3c7627bc0eeac49d1dcf39523aeabe8, you can test and if it works close the issue, otherwise please say and I'll have another look
