### ISSUE TITLE
user.fetchProfile => Bots cannot use this endpoint

### ISSUE THREAD

**Issue by cobaltway** [hydrabolt/discord.js#870]
I'm experiencing a code 20001 error (403 forbidden) "Bots cannot use this endpoint" when using the user.fetchProfile() method.

Not sure if I should post it here or on the discord-api github (I don't know if the request used in the library is a wrong one, or a right one but not working on discord side). You tell me.

**Comment by iCrawl** [comment]
Correct, its only for Userbots.

**Comment by CyberiumShadow** [comment]
*cough* **_selfbot_**
