### ISSUE TITLE
Error: Couldn't find an Opus engine

### ISSUE THREAD

**Issue by Fisherswamp** [hydrabolt/discord.js#872]
This is the code I am running to play a sound. 
```js
var ch = message.member.voiceChannel;
//console.log(ch);
if(ch != null){
	//message.channel.sendMessage("This command is currently under construction, sorry.");
	ch.join().catch(console.error).then(connection => {
		console.log("Bot: " + bot.guild);
		bot.guilds[0].voiceConnection.playFile("path + dotamatch.mp3",
			function(err){
				if(err){
					console.log(err);
				}
			}
		);
	});
}
```
However I get "Error: Couldn't find an Opus engine."

I am not sure why I am getting this error.

**Comment by hydrabolt** [comment]
Can you make sure you have either `node-opus` or `opusscript` installed as dependencies? You can check with `npm list`.

**Comment by Fisherswamp** [comment]
Thank you so much, I will add those as dependencies, and get back to you!

**Comment by Fisherswamp** [comment]
I now have opusscript installed as a dependency, and added `var opus = require('opusscript');` to my code. I still get the same error.

**Comment by hydrabolt** [comment]
What version of discord.js are you running?

**Comment by Fisherswamp** [comment]
The readme doc links to http://discord.js.org/#!/docs. So I would assume version 10.

**Comment by Fisherswamp** [comment]
I reinstalled opusscript, and npm and now the problem is resolved.

**Comment by RageCrezz** [comment]
How did you reinstall Opus? I still get the same error. Tried to solve the problem as you did.

**Comment by Fisherswamp** [comment]
I reinstalled NPM actually

**Comment by RageCrezz** [comment]
"Could not install typings files for JavaScript language features. Please ensure that NPM is installed and is in your PATH"

After installing FFMPEG as PATH, I get this error.
Before restarting Visual Studio, I got the Engine error. I don't really know what to do now..

How did you reinstall NPM?
Can you give me an instruction?
I don't even understand, how I set NPM as PATH again now. I set it as PATH, but still get the error in the beginning of my comment.

**Comment by FaultyX2** [comment]
reinstall nodejs
