### ISSUE TITLE
Remove preceding comma from message.reply()

### ISSUE THREAD

**Issue by MrSp33dy123** [hydrabolt/discord.js#876]
Apologies if I'm overlooking something here, however I personally find it irritating how message.reply() puts a comma after the @mention automatically for me-- I'd rather do it myself, when I want to.

Would it be possible for this to be changed, and/or could somebody point me in the direction of what piece of code to edit if I want to change this for myself?

EDIT: I believe I have found the _guilty_ line of code; line 394 of Message.js if I'm not mistaken :P

**Comment by iCrawl** [comment]
You know you could just do:
```
message.channel.sendMessage(`${message.author} blabla`);
```
to achieve the same thing.

**Comment by hydrabolt** [comment]
message.reply has always had the comma, there is no point changing it now. I would use Crawl's suggestion.

**Comment by hydrabolt** [comment]
As a side note, the documentation link in the readme always links to the latest release's documentation; you'll have to specify which documentation you want to see after loading the page.

**Comment by MrSp33dy123** [comment]
> message.reply has always had the comma, there is no point changing it now. I would use Crawl's suggestion.

No point changing it because of backwards-compatibility issues? The only thing is that Crawl's suggestion, in my opinion, negates the whole point of having a `.reply()` shortcut; it's just a bit bulky. That's exactly why I've been using `.reply()` in the first place.

If you don't want to remove the comma because it would affect pre-existing code depending on this module then that's fine, and I don't want to cause a fuss about that. But if that's not the case, then I don't see what the harm would be in removing it. I've forked my own version of discord.js to use with my bot, so in all honesty this isn't too much of a big deal for me.
