### ISSUE TITLE
messageReactionAdd event doesn't check messages from before client launch

### ISSUE THREAD

**Issue by MrYurihi** [hydrabolt/discord.js#877]
When a bot is launched, if it has the "messageReactionAdd" event, any reactions added to earlier posts won't trigger the event

If you use this code:
```JavaScript
bot.on('messageReactionAdd', (reaction, user) => {
  console.log("reaction added");
});
```
run the bot, and then add a reaction to a message sent earlier than the bot launch, it wont log "reaction added"

**Comment by Programmix** [comment]
This behavior is intended. Events are intended for things that happen after the bot is connected. You wouldn't want the message event to be triggered for all previously-sent messages, would you? If you want to get reactions for a previous message, you'll have to use something like `fetchMessages` and then read the reactions from the resulting message(s).

**Comment by hydrabolt** [comment]
@Programmix's answer is correct; messages before the client launches are not known by the client, so it means the event wouldn't be able to give you the actual message the reaction refers to.

`fetchMessages` would work, as Programmix said, but make sure you set up a large maximum cache size in your client options.
