### ISSUE TITLE
Volume setting for voice encoding

### ISSUE THREAD

**Issue by nicholastay** [hydrabolt/discord.js#88]
Would like to request for a volume setting for ffmpeg/avconv encoding for the voice section. By default it can be very loud, so a volume setting could be nice so new members to a voice chat don't get their ears blasted. I've located a `volume=1` and this could be changed to allow a variable setting in a func such as `setVolume()`.

Edit: https://github.com/hydrabolt/discord.js/blob/master/src/Voice/AudioEncoder.js#L51 location of code
Edit2: https://github.com/hydrabolt/discord.js/blob/master/src/Voice/AudioEncoder.js#L90 oh and of course the encodeFile

**Comment by hydrabolt** [comment]
Ok I'll add this to the next version!

**Comment by hydrabolt** [comment]
Added in d66b765933f9c077b9dc8fd83e2720ec9c56e4a1
