### ISSUE TITLE
Catch the updated voiceConnection 

### ISSUE THREAD

**Issue by dayxhep** [hydrabolt/discord.js#884]
Hello hello,
I saw that `ClientVoiceManager` has the function :
```js
  /**
   * Upgrades this Pending Connection to a full Voice Connection
   * @returns {VoiceConnection}
   */
  upgrade() {
    return new VoiceConnection(this);
  }
```
Could i use it to retrieve the voiceConnection anywhere by : 
```js
var botVc = bot.voice.upgrade();
```
Or is it a wrong practice ?

Because i was trying to access bot.voiceConnection but this is never updated and/or never created.

**Comment by GusCaplan** [comment]
`client.voiceConnection` isn't a property, but `client.voiceConnections` is, **as a collection mapped from guild id to voice connection**. also `client.voice` does not exist.

**Comment by hydrabolt** [comment]
`.upgrade` just means that the potential voice connection has enough data to be used, it should not be used externally at all. Gus's comment above should help you 😄

**Comment by dayxhep** [comment]
Thanks guys for the answers, is there a way to determine the current used VoiceConnection in the collection ?
