### ISSUE TITLE
Message.attachments is empty

### ISSUE THREAD

**Issue by darkson95** [hydrabolt/discord.js#885]
Hi everyone,
I am very happy with your powerful library, but I have an issue. I want to implement a bot for my mathematic-prof. and I need to catch the attachment in the message the user will send.
I saw you implemented the property attachment in the Class Message, but the property is everytime the same:
```
{
  "_array": null,
  "_keyArray": null
}
```

This is the view in Discord (The text is the 'optional' comment):
![](http://i.imgur.com/ggX1YGG.png)

This is my Code:

```
var Discord = require("discord.js");
var bot = new Discord.Client();

bot.login("*******************************************");

bot.on('ready', () => {
	console.log('I am ready!');
});

bot.on("message", msg => {
	var prefix = "!";
	var args = stringArgv.parseArgsStringToArgv(msg.content);
	var cmd = args[0] || "";
	args = args.filter(a => a !== cmd);

	if (msg.author.bot) return;
	if (!msg.content.startsWith(prefix)) return;

	if(cmd.startsWith(prefix + "att")){
		console.log(JSON.stringify(msg.attachments, null, 2));
	}
});
```

darkson95

**Comment by FastDeath** [comment]
https://discord.js.org/#!/docs/tag/master/class/Message?scrollto=embeds

**Comment by darkson95** [comment]
The Property embeds is unfortunately an empty Array.

**Comment by GusCaplan** [comment]
i believe this should answer your question
![](https://i.imgur.com/kINkSaH.png)

**Comment by hydrabolt** [comment]
To expand on Gus's comment, `message.attachments` is a collection mapped by attachment ID. Because attachments can be circular, it can be hard to use `JSON.stringify` on them, I suggest grabbing the values you need from an attachment and `JSON.stringify`ing them instead.
