### ISSUE TITLE
Adding roles on guildMemberAdd: Doesn't work if member has a bot role

### ISSUE THREAD

**Issue by PgBiel** [hydrabolt/discord.js#887]
![Image of the code](http://i.imgur.com/pv4ESfr.png)

This code works just fine. A member enters, and the code looks in the serverroles variable (which is a require of a json file) to see if the guild stored the id of a role to be given on join. And if it does, it gives said role.
Like I said, it works just fine. Except... if the member joining comes with a bot role (you know, the kind of role that cannot be deleted, removed from anyone or added to anyone: they come with bots).
It doesn't give the role, and logs this at console:

![](http://i.imgur.com/QNaqBJ0.png)

That error generally happens if the client doesn't have permissions to do something, and this made me think about it being the fact that it has a bot role and, as it cannot be removed/added, trying to add role would be trying to modify their whole role list and therefore somehow interfering with the bot role... But then the interesting part: Outside of the guildMemberAdd event, such as when sending message, I can run the same add role code without a problem, even with the bot role. So I don't really know what's wrong... Is this a bug? Or am I doing something wrong?

**Comment by GusCaplan** [comment]
can you try
```js
if (member.roles.has(serverroles[member.guild.id])) return;
member.addRole(serverroles[member.guild.id]).catch(console.error);
```
note the `.catch`, which will spit out some actual information about the error
also, you can shorten that line to
```js
console.log(member.user.username)
```

**Comment by PgBiel** [comment]
@GusCaplan Wow okay... That catch really filled console with a big bunch of information. And at some places it says "Missing Permissions", at others it says "Forbidden". However, it's clear that the bot has permissions (its role has administrator perm). Like I stated in the post, I managed to add the same role to, in this case, for testing, Mee6 (a bot), inside the message event. And it worked, using the same code, same situation: with bot role. But at join it says forbidden...
The full patch I'll put on pastebin:
http://pastebin.com/cxNuswtW
...and in case you need this information, I use a Mac.
(quick note that I'm going to go in 1 hour as the time of writing and will be back in around 6 hours after that, in case you wonder why I don't reply)

**Comment by GusCaplan** [comment]
@PgBiel your bot token is in that paste, you should reset it

**Comment by PgBiel** [comment]
@GusCaplan Thanks for pointing that out 👍

**Comment by hydrabolt** [comment]
I'll take a look into it today :)

**Comment by hydrabolt** [comment]
Looks like it can't be fixed by discord.js, you'll have to wait until appropriate roles are applied to the bot member after it joins (a timeout of ~3 seconds should suffice if you don't want to make event listeners)

**Comment by PgBiel** [comment]
Ok thanks
