### ISSUE TITLE
TextChannel.lastMessageID provides invalid "last message id"

### ISSUE THREAD

**Issue by Trismirite** [hydrabolt/discord.js#892]
It continued to get the message above my message, no idea why. I switched to `TextChannel.fetchMessages({limit: 1}).then(messages => {` and it worked fine. not sure if this is a faulty on my part, or a bug, but somebody else had an issue with it also.

**Comment by GusCaplan** [comment]
lastMessageID can't get the id of the message it's sent in, obviously, since the message doesn't exist yet. This is most likely a product of an eval command.

**Comment by appellation** [comment]
Although I tested this using an `eval` command, I ran the command about 5 or 10 times and the result was the exact same message ID.  I tested this over the span of a couple minutes.

**Comment by GusCaplan** [comment]
can repo, will fix

**Comment by GusCaplan** [comment]
fixed in #898
