### ISSUE TITLE
Object.prototype.function not compatible with discord.js

### ISSUE THREAD

**Issue by Toshimonster** [hydrabolt/discord.js#893]
Steps;
1. Import Discord.js
2. Define Object.prototype.function (literally anything)
3. Create Discord client.
4. client.login, Events dont proc.
5. Throws : ```(node:4392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: The header content contains invalid characters
(node:4392) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
6. Wonder why this is happening.
7. Logic is not logical.
8. reinstall Discord.js
9. Flip table...
10. Think about what you did to deserve this error.

But seriously, this makes no sense. IDK if its my system, or if anyone else can repro.

**Comment by Toshimonster** [comment]
- note that client and login is all valid.

**Comment by Gawdl3y** [comment]
??

**Comment by hydrabolt** [comment]
I am confused about what you are asking

**Comment by GusCaplan** [comment]
i think he literally means ```js
Object.prototype.xyz = function somefunction () {}

const client = new Discord.Client();

// where's my client.xyz() ?
```

obviously this won't work as expected

**Comment by Toshimonster** [comment]
Well, In actual fact what i ment, was ```js
const discord = require('discord.js')
object.prototype.xyz = function fun() {}
const client = new discord.Client();
client.login('token') // returns the promise errors, and seems to terminate. (it is a valid token)
```
I DONT call client.xyz. Object != Client.

**Comment by GusCaplan** [comment]
did you read the promise error? it usually says something useful
