### ISSUE TITLE
MessageEmbed.footer property missing

### ISSUE THREAD

**Issue by HyperCoder2975** [hydrabolt/discord.js#896]
https://discordapp.com/developers/docs/resources/channel#embed-object
https://discord.js.org/index.html#!/docs/tag/indev/class/MessageEmbed
https://i.typicalbot.com/d65f04
https://i.typicalbot.com/395312

**Comment by iCrawl** [comment]
https://discordapp.com/developers/docs/resources/channel#embed-object

**Comment by GusCaplan** [comment]
fixed in #898
