### ISSUE TITLE
.on("guildMemberUpdate", (old, new) => {...}) returns the Guild for the first parameter into the function ("old")

### ISSUE THREAD

**Issue by threetran** [hydrabolt/discord.js#900]
The [docs](https://discord.js.org/#!/docs/tag/master/class/Client?scrollto=guildMemberUpdate) say that I should pass `(oldMember, newMember) => {...}` into `.on("guildMemberUpdate"`, but `oldMember` is actually `newMember.guild`.

**Comment by Gawdl3y** [comment]
Ensure you're on v10.
