### ISSUE TITLE
[enhancement] Add "messageReaction" event

### ISSUE THREAD

**Issue by antoinebeaumont** [hydrabolt/discord.js#903]
It would be great to have this event!
As this Python API : wait_for_reaction
http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.wait_for_reaction

client.on('messageReaction', (Message message, Reaction reaction) => {  });
In this case message must contains a list of all its reactions, and reaction must be the last one.

**Comment by CyberiumShadow** [comment]
There...l already is one...

**Comment by antoinebeaumont** [comment]
I found this issue report [#877](https://github.com/hydrabolt/discord.js/issues/877) but I can't found this in the doc or the source code. Can you help?

**Comment by antoinebeaumont** [comment]
Ok, missread the #877 ... I have to use `fetchMessages` ...

**Comment by Slamakans** [comment]
You only have to use fetchMessage(s) to get reactions of old messages.

The events triggered by reactions are messageReactionAdd and messageReactionRemove, but they are undocumented.

**Comment by antoinebeaumont** [comment]
Thanks @Slamakans !
So in which cases do these events work?

1. Bot join
2. Message by Xyz
3. Abc add reaction to message
4. messageReactionAdd was triggered ?
