### ISSUE TITLE
[Enhancement] Collection.findAll

### ISSUE THREAD

**Issue by Toshimonster** [hydrabolt/discord.js#908]
It would be great if inside of
Collection.findAll()
it was possible to use a function, and not just strings & values.
For instance,
```js
messages = messages.findAll('author.id', id); //WONT WORK
```
~ you would have to use a very inefficient forEach bunch of code.

**Comment by Toshimonster** [comment]
~ Just added a pull request for a minor update to the Collections Class, which allows propOrFn

**Comment by Gawdl3y** [comment]
See Collection.filter().
