### ISSUE TITLE
User bot guildMemberAdd on reconnect

### ISSUE THREAD

**Issue by meishuu** [hydrabolt/discord.js#910]
On 10.0.1 if the net connection goes down, comes back up, and the user bot reconnects, guildMemberAdd will fire for all members in the guild. Possibly related to #684 and #776.

Let me know if I should try to repro on indev.

**Comment by iCrawl** [comment]
You probably should try to reproduce in indev.

**Comment by meishuu** [comment]
Still happens in indev.

**Comment by hydrabolt** [comment]
@meishuu do these events fire before or after `READY`?

**Comment by meishuu** [comment]
@hydrabolt Yes.

I've built a minimal test case and I believe this to be related to `sync`.

```js
const Discord = require('discord.js');
const bot = new Discord.Client({ fetchAllMembers: true, sync: true });

bot.on('ready', () => { console.log('ready'); });
bot.on('disconnect', () => { console.log('disconnect'); });
bot.on('reconnecting', () => { console.log('reconnecting'); });

bot.on('guildMemberAdd', (member) => { console.log(`add: ${member}`); });

bot.login('<email>', '<pass>');
```

will produce

```
ready
disconnect
reconnecting
reconnecting
reconnecting
------------
reconnecting
reconnecting
reconnecting
ready
add: <@170798412784992251>
add: <@119926795708530683>
add: <@118918383587557375>
```

after waiting long enough for the (user)bot to no longer show as online, which is presumably longer than the sync interval.

**I do not think this happens without `sync: true`** but I will try again now that I have successfully reproduced it.

**Comment by meishuu** [comment]
My suspicions are correct. This does not happen if I leave `sync` at the default `false`.

**Comment by hydrabolt** [comment]
Can you try out commit https://github.com/hydrabolt/discord.js/commit/b3358245701280120cc5e892d38cb03c498bce30 and see if the issue still occurs?

**Comment by meishuu** [comment]
The event flow with both b335824 and 1933451 appears to be

    ready
    disconnect
    reconnecting
    disconnect

at which point it completely gives up and stops attempting to reconnect, so I'm not sure how else to test it.

**Comment by hydrabolt** [comment]
It should be fixed in that commit for sure, now the only other place that guild member add event would fire is if the WebSocket sent the `GUILD_MEMBER_ADD` event.
