### ISSUE TITLE
Error downloading discord.js on Windows using npm

### ISSUE THREAD

**Issue by TnkC** [hydrabolt/discord.js#913]
I have node js installed on my PC and I've tried installing discord.js but I always get errors.

this is what it says in cmd.

http://prntscr.com/da6rdc

after I try running the bot script this is what shows up.

http://prntscr.com/da6ro2

Please help. I really want to make a bot :(

**Comment by Gawdl3y** [comment]
1. Your NPM is out of date.
2. Your Node is out of date. Node 6.0.0 or newer is required.

Updating Node will also update NPM.

**Comment by TnkC** [comment]
Thanks, I'l try now <3
