### ISSUE TITLE
Question about embed in messages

### ISSUE THREAD

**Issue by PgBiel** [hydrabolt/discord.js#915]
Is it possible to edit the embed of a message you are sending? Because I've seen bots send completely customized ones. Look this example:
![](http://i.imgur.com/A9Z4s06.png)
And when you click it, it redirects to an url that...is not actually an url: "!!!!".
![](http://i.imgur.com/YUOt5tT.png)
Is there any way that this is implemented to discord.js.....or that it ***can*** be implemented...?
I'm pretty sure (not 100%) that that bot uses code different from discord.js.

**Comment by GusCaplan** [comment]
embeds are implemented in discord.js indev branch. to set the url that the embed has, set the `url` property of the embed object.

**Comment by PgBiel** [comment]
Thanks for the quick answer! 👍  I'm going to try out the indev then.
