### ISSUE TITLE
Docs, typeDef: wsEventResolvable

### ISSUE THREAD

**Issue by AoDude** [hydrabolt/discord.js#919]
Took me a while digging through the source to find the wsEvents as strings possible for the disabledEvents client option. It would be nice to have it type defined like permissionResolveables, however I couldn't figure out where that was done to pr myself.

**Comment by AoDude** [comment]
It also appears like there might be a couple duplicated events? I suppose these might have different uses, but bringing it to attention just in case.

  FRIEND_ADD: 'RELATIONSHIP_ADD',
  FRIEND_REMOVE: 'RELATIONSHIP_REMOVE',
  RELATIONSHIP_ADD: 'RELATIONSHIP_ADD',
  RELATIONSHIP_REMOVE: 'RELATIONSHIP_REMOVE',

**Comment by hydrabolt** [comment]
Added in https://github.com/hydrabolt/discord.js/commit/0d574a0678153260852fc83556bbc0157295e388 as `WSEventType` typedef
