### ISSUE TITLE
how I can read member by member from an array?

### ISSUE THREAD

**Issue by HWSKY** [hydrabolt/discord.js#920]
the idea is catch all users from a determined `roleID` and then remove all this members to this role
`let membersWithRole = message.guild.members.filter(m=> m.roles.has(roleID));`
how i can catch the information from de `membersWithRole` and do that?

dumb idea
```
for(int i = 0; i < membersWithRole.size; i++)
{
    membersWithRole[i].removeRole(role.ID);
}
```

**Comment by AoDude** [comment]
`message.guild.members.filter(m=> m.roles.has(roleID)).forEach(m => m.removeRole(roleID));`

But for future questions like this, please join the official Discord.JS guild to ask. https://discord.gg/bRCvFy9

**Comment by HWSKY** [comment]
thanks a lot! @AoDude
