### ISSUE TITLE
Obtaining all messages from a channel

### ISSUE THREAD

**Issue by ir-g** [hydrabolt/discord.js#926]
Is there a way of obtaining all messages from a channel for storage to a text file?

**Comment by hydrabolt** [comment]
You could start by fetching the last 100 messages (the API limits us to 100) with `TextBasedChannel.fetchMessages({ limit: 100 })`. Then you could keep repeating this and passing in a `before` property based on the oldest message fetched each time. Eventually, you would have a list of all the messages that could be written to a text file. Relevant [discord.js documentation](https://discord.js.org/#/docs/main/master/class/TextChannel?scrollTo=fetchMessages) and [discord developer documentation.](https://discordapp.com/developers/docs/resources/channel#get-channel-messages)

In future, please ask for help in our [official server](https://discordapp.com/invite/bRCvFy9) for queries such as this one ;)
