### ISSUE TITLE
Voice stream playback sometimes cuts off after about ten minutes

### ISSUE THREAD

**Issue by meew0** [hydrabolt/discord.js#93]
As multiple people have reported, when playing a stream back over voice, it sometimes cuts off after approximately 10 minutes of playback. This happens with streams got over ytdl (using [Lethe](https://github.com/meew0/Lethe)), and apparently Icy and Soundcloud streams too.

**Comment by hydrabolt** [comment]
Fixed in f280349f0c5ceb5c9e2433e37297daffd6a03aa3

**Comment by hydrabolt** [comment]
Actually, fixed in e02028730731a03317dd1d2cbd30be69cbb502e7 and d8af1a49ae78292269fbb1e0c24213e010f395a1
