### ISSUE TITLE
Where to ban-appeal? (discord.js discord server)

### ISSUE THREAD

**Issue by XWhatevs** [hydrabolt/discord.js#933]
I was banned a while ago but I can't find a place to appeal anywhere.

**Comment by YorkAARGH** [comment]
This is not the place to post appeals, this is for issues with the library

**Comment by XWhatevs** [comment]
That's exactly why Im posting this here. Because I cannot find a place to appeal....

**Comment by GusCaplan** [comment]
if i remember your case correctly, you aren't getting unbanned any time soon, so just stop posting here.

**Comment by YorkAARGH** [comment]
To put it bluntly no, responding Selfbots are a bannable offence to start
with, and yours was responding with homophobic remarks. You will not be
unbanned.

**Comment by coder580** [comment]
i was sleep deprived and i said a bunch of stuff i shouldnt have

**Comment by coder580** [comment]
or most of it i was sleep deprived

**Comment by coder580** [comment]
half the stuff i was saying was at like 2-3 am
