### ISSUE TITLE
How to cancel guild member fetching when receiving error message "Already fetching guild members in ${this.id}."?

### ISSUE THREAD

**Issue by bamboo3250** [hydrabolt/discord.js#934]
As the title, when I run this line of code:
```
message.guild.fetchMembers().then(guild => {
     //my stuff
}).catch(err => {
    console.log(err);
});
```
I received `Already fetching guild members in ${this.id}.` but the member list never came. And as a result, the next call of `guild.fetchMembers()` also didn't work and got the same error. So I want to ask if there is any way to cancel the call/fetching or not.

**Comment by GusCaplan** [comment]
it automatically times out after 120 seconds

**Comment by hydrabolt** [comment]
See Gus' answer
