### ISSUE TITLE
Unable to install discord.js using npm

### ISSUE THREAD

**Issue by LegendsLyfe** [hydrabolt/discord.js#936]
I have tried the "npm install discord.js" after installing node.js the latest version.
But I recieve an error:
+-- discord.js@10.0.1
+-- UNMET PEER DEPENDENCY node-opus@^0.2.1
`-- UNMET PEER DEPENDENCY opusscript@^0.0.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\System32\package.json'
npm WARN discord.js@10.0.1 requires a peer of node-opus@^0.2.1 but none was installed.
npm WARN discord.js@10.0.1 requires a peer of opusscript@^0.0.1 but none was installed.
npm WARN System32 No description
npm WARN System32 No repository field.
npm WARN System32 No README data
npm WARN System32 No license field.

I have tried to get node-opus, I have no idea how to get oppusscript. I used npm install node-opus command then I recieve another error:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-opus"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log

I have recieved the error shown on top when doing "npm install discord.js" but fixed after installing the latest version. But now its again not working, please help me!

**Comment by appellation** [comment]
That's not an error.  Don't worry about it unless you need voice.  Also, you seem to be trying to install discord.js in `System32` which is inadvisable.  Make a directory for your project, `npm init`, and try again.

P.S. `node-opus` is harder to install on Windows than `opusscript`.
