### ISSUE TITLE
Errors trying to install discord.js.

### ISSUE THREAD

**Issue by FatRagdoll** [hydrabolt/discord.js#940]
When writing the command "npm install --save discord.js" following errors occur:

```
-- UNMET PEER DEPENDENCY node-opus@^0.2.1

npm WARN discord.js@10.0.1 requires a peer of node-opus@^0.2.1 but none was installed.
npm WARN c@1.0.0 No description
npm WARN c@1.0.0 No repository field.
```
So that means that there is something wrong with node-opus, but when I write the command "npm install node-opus --save --unsafe-perm" multiple errors show:

```
C:\Users\Daniel\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\Daniel\AppData\Local\Programs\Python\Python35\python.EXE" is v3.5.1, which is not supported by gyp.
```

This suggests that there might be something wrong with my python version, which is weird since I've tried to re-install multiple different versions of python. 
I've no idea what to do from here so any ideas are more than welcome.

**Comment by GusCaplan** [comment]
`UNMET PEER DEPENDENCY` isn't an error, it's a warning, as well as the lines with `WARN`. If you aren't using voice you can just ignore all this.

As to your second error, i suggest you try reading.
`gyp ERR! stack Error: Python executable "python.EXE" is v3.5.1, which is not supported by gyp.`

**Comment by FatRagdoll** [comment]
Well when trying to run the bot this error comes up:

```
C:\Users\Daniel>node F:\Users\Daniel\Downloads\Rainbow-Rank-for-Discord-master\rainbowrank.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'discord.js'
```

**Comment by GusCaplan** [comment]
can you join [our help server](https://discord.gg/bRCvFy9)

**Comment by FatRagdoll** [comment]
I just did, my name is Jabbathefrukt :)

**Comment by cydh** [comment]
@FatRagdoll did you get the solution for https://github.com/hydrabolt/discord.js/issues/940#issuecomment-264323911 ?

**Comment by hydrabolt** [comment]
@cydh make sure discord.js is correctly installed, there's a page detailing installation [here](https://hydrabolt.gitbooks.io/using-discord-js/content/getting-started/installing-discordjs-windows.html)
