### ISSUE TITLE
Node-opus install fail

### ISSUE THREAD

**Issue by TheDom102** [hydrabolt/discord.js#941]
When I do `npm install node-opus`, it ends up with this error:

fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory.
..\src\binding.cc(1): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory.

I'm using Node v7.2.0, Node-gyp v3.4.0, NPM v3.10.9 and Discord.js v10.0.0.

**Comment by MellisaFireyMelon** [comment]
It is harder to install node-opus and I did try it was harder than expected. Do you have a bot on multiple servers? If not use oppusscript.

**Comment by TheDom102** [comment]
I usually have my bot on multiple servers. But I can try on one for now as I haven't released my bot publicly yet.
