### ISSUE TITLE
With every new sound being streamed, a new FFMPEG process is made.

### ISSUE THREAD

**Issue by XNBlank** [hydrabolt/discord.js#95]
Everytime playFile() is called, a new process for FFMPEG is created, and old ones are not destroyed.

**Comment by hydrabolt** [comment]
Should be fixed in 4d438672061f1a9202418c740e5a86d7f2769622

**Comment by hydrabolt** [comment]
Was actually fixed in https://github.com/hydrabolt/discord.js/commit/c2cf1badfdf2d88e90e7b0e59bf684bd913627c0
