### ISSUE TITLE
message.guild.channels not returning array properly.

### ISSUE THREAD

**Issue by tomgie** [hydrabolt/discord.js#951]
running console.log(message.guild.channels.array.length); inside of the client.on("message",function(message) function just returns 0 / null. Not sure what is happening.

**Comment by GusCaplan** [comment]
array is a function not a property.

**Comment by iCrawl** [comment]
Or you could just use `message.guild.channels.size`

**Comment by Gawdl3y** [comment]
[Collection#array](https://discord.js.org/#/docs/main/master/class/Collection?scrollTo=array) is a method, not a property. You don't need to use that, though. Instead, use `message.guild.channels.size`.
