### ISSUE TITLE
[SOLVED] `bot.setStatus()` not working?

### ISSUE THREAD

**Issue by GlitchMasta47** [hydrabolt/discord.js#953]
I have a basic discord.js bot that uses the `setStatus()` command to display how many servers it is in and the command to receive the list of commands. I put this inside a `bot.on("ready")` handler, just in case that is important. Here is a screenshot of the console error:
![image](https://cloud.githubusercontent.com/assets/17860556/20906852/d67514d8-bb0f-11e6-9d37-0bd9f2a05f62.png)

**Comment by iCrawl** [comment]
https://discord.js.org/#/docs/main/master/class/ClientUser?scrollTo=setStatus

`bot.user.setStatus()`

**Comment by GlitchMasta47** [comment]
Thanks, now solved.
Surprisingly couldn't find it in the Google index, usually does.

**Comment by iCrawl** [comment]
Oh, you might also wanna check for

`bot.user.setGame()`

if its solved close your issue please! 👍

**Comment by Realsupersaiyan** [comment]
How did you fix it ?

**Comment by ickerio** [comment]
This is over 6 months old!? Are you trying to set your bot to playing a game or set it to a status (dnd, online, idle etc)
Both are on the docs here https://discord.js.org/#/docs/main/stable/class/ClientUser

**Comment by Realsupersaiyan** [comment]
I can't seem to get the "bot.guilds.size" working.

**Comment by CyberiumShadow** [comment]
@Realsupersaiyan head over to our official discord server at https://discord.gg/bRCvFy9 and ask your question there.

**Comment by kaidiscord** [comment]
> I can't seem to get the "bot.guilds.size" working.

bot.guilds.size does not work anymore. 

This works for me: bot.guilds.cache.size
