### ISSUE TITLE
Issue streaming audio

### ISSUE THREAD

**Issue by ErikMartensson** [hydrabolt/discord.js#96]
Hello.

For the last week I've tried my best getting any kind of sound to be transmitted over a voice channel with this node module.

I've tried both with Windows, 32-bit and 64-bit and also with Ubuntu on my Raspberry Pi 2. Both Node v4 and v0.12.
I had some errors when running `npm install` on my Windows machine that I never got past, so that's why I switched to Ubuntu. But I still experience problems.

I have avconv and opus installed (I think..) ffmpeg seems to be impossible to install on Ubuntu 14.03, or at least for me.

I've tried the `playFile` and `playRawStream`, trying both an MP3 file and a different WAV file. The avatar on my bot lights up green for a brief moment, as if audio is sent, but it disappears before I can hear anything.
Then I tried with a Shoutcast stream instead, to see if it was just some problems with the files. With the Shoutcast stream I get maybe half a second of really loud white noise before it just goes quiet again.

So, what am I missing? I feel really stupid because I've waited for someone else to report the same kind of problems that I'm experiencing, but I haven't seen anyone with the same issue as me.

**Comment by hydrabolt** [comment]
Hi,

audio support _is_ really buggy at the moment. This has happened to me so many times. The `indev` branch has a lot of voice fixes, so if you try using that temporarily (`npm i hydrabolt/discord.js#indev`) and could you see if this branch works for you?

**Comment by ErikMartensson** [comment]
Yes, that branch did work, at least for playing files which was what I originally wanted, so thank you!

I did however stumble upon two other problems, the first was that I no longer could do a `client.channels.get('id', somechannelid);`. There might be something in the Cache class that's broken.

And when I tried the Shoutcast stream again I got this error:
```
node: ../../nan/nan.h:679: Nan::MaybeLocal<v8::Object> Nan::CopyBuffer(const char*, uint32_t): Assertion `size <= imp::kMaxLength && "too large buffer"' failed.
Aborted
```

These issues probably needs to go into two separate Github issues. The last one I'm not so interested in but I think the first one might be a problem for lots of people.

**Comment by hydrabolt** [comment]
`client.channels.get()` is working fine for me on the latest commits, are you sure that the `somechannelid` you are passing in is a String and not a Number? Turning it into a number makes it inaccurate.

**Comment by ErikMartensson** [comment]
You are absolutely correct! It needed to be a string, when I had it as an integer.

Also, about the second problem, I solved that by switching from `playStream`to `playRawStream` and now I can torture everyone with both sound files and audio streams.

Thanks again.

**Comment by hydrabolt** [comment]
Haha no problem!
