### ISSUE TITLE
Client not reconnecting 1/10 times

### ISSUE THREAD

**Issue by iCrawl** [hydrabolt/discord.js#965]
![osaact](https://cloud.githubusercontent.com/assets/20760160/21066200/a977532e-bea7-11e6-8195-53a802da7a87.png)

Thats what it looks like if the library is reconnecting automatically.

But sometimes it just does:
![xyaary](https://cloud.githubusercontent.com/assets/20760160/21066209/baae28c0-bea7-11e6-8427-1cda54de905c.png)

It disconnected and forced me to restart the bot.
Which is where the "Connection has been established successfully" comes from because it reconnected to the postgreSQL Database, which it only does on process restart.

@Gawdl3y can confirm it happening.

**Comment by Cat-who-loves-bots** [comment]
same for me it happens sometimes and forces to restart my bot

**Comment by zajrik** [comment]
Can also confirm this happening. 👌 It's pretty rare, but when it happens it's generally more than one of my bots as well.

**Comment by hydrabolt** [comment]
Fixed in latest indev commits
