### ISSUE TITLE
Incorrect login details were provided.

### ISSUE THREAD

**Issue by LamboCreeper** [hydrabolt/discord.js#974]
Hi,

When ever I try to load my bot i'm getting the error: `(node:12113) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.`. I thought this would be a problem with the token being incorrect so I reset it and tried that, but this seems to not have fixed it. I've also tried reinstalling node, npm and discord.js and also failed to fix my issue.

If anyone knows how I can fix this it would be much appreciated.

**Comment by Slamakans** [comment]
Come join the [Discord.js Official](https://discord.gg/bRCvFy9) help server

**Comment by gt-c** [comment]
same thing happening to me. kind of sucks and it's not related to the token at all ;-;

**Comment by Lewdcario** [comment]
This issue is almost two years old. Please check dates before necro posting.

**Comment by HagRetek** [comment]
Just for anyone who has the same issue, note that the image by @Slamakans is not available.

You need the bot's token ("Bot" tab in the application settings), not the client ID or the token in "General Information". You can check if it is the correct one as the bot token you need is longer than the general application token.
