### ISSUE TITLE
Can't install or run "npm install discord.js"

### ISSUE THREAD

**Issue by zekromslayer** [hydrabolt/discord.js#976]
Hey guys. So I am having some trouble trying to create a personal discord bot because when I run the cmd prompt and do "npm install discord.js" I get some errors. 

+-- UNMET PEER DEPENDENCY node-opus@^0.2.1
`-- UNMET PEER DEPENDENCY opusscript@^0.0.1

npm WARN discord.js@10.0.1 requires a peer of node-opus@^0.2.1 but none was installed.
npm WARN discord.js@10.0.1 requires a peer of opusscript@^0.0.1 but none was installed.
npm WARN diana@1.0.0 No repository field.

I've tried googling this and looking at articles but nothing seems to do anything. I did "npm init" and "npm i --save discord.js --no-optional" but it didn't do anything and I couldn't run it. Halp!

**Comment by macdja38** [comment]
if you don't need music these can be safely ignored.

**Comment by zekromslayer** [comment]
I would like to use music.

**Comment by GusCaplan** [comment]
just run
```
npm i discord.js opusscript
npm i -g ffmpeg-binaries
```

**Comment by dylanh724** [comment]
These dependencies take almost no storage -- why wouldn't these just be included?

**Comment by hydrabolt** [comment]
We're planning on changing this. 👍

**Comment by CaptanHamm** [comment]
any update on this?
