### ISSUE TITLE
Create custom embed

### ISSUE THREAD

**Issue by DerAtrox** [hydrabolt/discord.js#977]
Hey, how can I create custom embeds like this one?

![exmaple](https://img.deratrox.de/XHvBF.png)

I couldn't find anything about this in the docs.

**Comment by iCrawl** [comment]
You can either send an embed object or use the builder for rich embeds.

```js
msg.channel.sendMessage("", {embed: {
  color: 3447003,
  author: {
    name: bot.user.username,
    icon_url: bot.user.avatarURL
  },
  title: 'This is an embed',
  url: 'http://google.com',
  description: 'This is a test embed to showcase what they look like and what they can do.',
  fields: [
    {
      name: 'Fields',
      value: 'They can have different fields with small headlines.'
    },
    {
      name: 'Masked links',
      value: 'You can put [masked links](http://google.com) inside of rich embeds.'
    },
    {
      name: 'Markdown',
      value: 'You can put all the *usual* **__Markdown__** inside of them.'
    }
  ],
  timestamp: new Date(),
  footer: {
    icon_url: bot.user.avatarURL,
    text: '© Example'
  }
}});
```

https://discord.js.org/#/docs/main/indev/class/RichEmbed

If you have any further questions please come to the [official server](https://discord.gg/bRCvFy9) instead of opening issues.

**Comment by DerAtrox** [comment]
Oh sorry... I have to be blind or something.. Totally overlooked this class. Thank you for the fast response!
