### ISSUE TITLE
[Question] Is there a way to add reaction to a message?

### ISSUE THREAD

**Issue by vxcvbzn** [hydrabolt/discord.js#980]
I don't see anything about that in the docs...

**Comment by Sowce** [comment]
https://discord.js.org/#/docs/main/indev/class/Message?scrollTo=react

Actually only available in indev branch

**Comment by IanMitchell** [comment]
Seems to be a bit buggy still. I'm not able to add :hash: or 🇹 as reactions, despite being able to manually

**Comment by GusCaplan** [comment]
this has nothing to do with our code. it has to do with how your system represents regional indicators.

**Comment by IanMitchell** [comment]
Might be worth a mention in the documentation that not all emoji will work then (and clarification that `string` means raw emoji instead of `:regional_indicator_t:`)

**Comment by iCrawl** [comment]
Not sure if thats worth the mention, considering thats just the "discord" way to display emojis.
String means Unicode character in that case.

**Comment by IanMitchell** [comment]
Using the wrong string results in a thrown Error - I think that's worth an explanation. If you try an unsupported Emoji and get a Bad Request Error, the next logical step is to try to throw the discord representation of it at the discord API.

Saying not all emoji are supported by the API might achieve the same end - either way, I think a bit of clarification would be helpful
