### ISSUE TITLE
Array.from(Discord.Collection) should have a prototype representative.

### ISSUE THREAD

**Issue by Toshimonster** [hydrabolt/discord.js#981]
Due to the fact that
```
    Discord.Collection.array()
    (Array.from(Discord.Collection.values))
```
and
```
    Discord.Collection.keyArray() 
    (Array.from(Discord.Collection.keys))
```
exists, surely a 
`    Array.form(Discord.Collection)`
should exist?

**Comment by Toshimonster** [comment]
_Please label as enhancement ^^_

**Comment by Gawdl3y** [comment]
It already does exist. `Array.from(someCollection)` will produce an array of arrays with key-value pairs. This is inherent to ES6 Maps in general, not just Collections. That's also where the `keys()` and `values()` methods come from.
