### ISSUE TITLE
notify when promise couldn't be held due to permission

### ISSUE THREAD

**Issue by mishugashu** [hydrabolt/discord.js#989]
I've been trying to do `guildMember.addRole(roleId).then((gM) => { console.log(gM); });`, but it's been failing silently. Turns out, the bot didn't have any permissions to set roles on the server. So, the failure was correct.

But, it'd be nice to know in some sort of response (maybe a second return value error string?) if something had failed. The code above produces absolutely nothing. The only way I know it failed is that the role didn't get added.

**Comment by Gawdl3y** [comment]
Use the [`catch()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) method.

**Comment by mishugashu** [comment]
Thanks for the suggestion. I actually had tried it before (I do know a couple things about javascript), but after taking a second look at it since you stated it should work, it looks like I was running an older version of Node that didn't support it properly (it wouldn't pass the resolved promise to the `then` next in the chain). Serves me right for using new versions of things piled on top of old versions of things.
