### ISSUE TITLE
[SelfBot] client.destroy() cannot make an authenticated logout api request

### ISSUE THREAD

**Issue by bdistin** [hydrabolt/discord.js#992]
http://puu.sh/sQXZe/c108f21616.png

client.destroy() on a self bot nulls out the token, closes the websocket, and then attempts to make an authenticated api request to logout. D.JS throws an error that the token is not available when trying to make the logout request.

**Comment by GusCaplan** [comment]
it should be noted that if you eval client.destroy(), your code will probably try to send the result of that, which will happen *after* you log out, resulting in token errors, as you have logged out at that point.
