### ISSUE TITLE
Unexpected token )?

### ISSUE THREAD

**Issue by epic8009** [hydrabolt/discord.js#995]
http://pastebin.com/9WG4u1WD
^^
code

In line 65, apparently the ) is an unexpected token... Any help? It wasnt unexpected until i put the let swearwords in and the for loops in...

**Comment by hkwu** [comment]
Check your brackets, and indent your blocks properly cause I wouldn't even want to read that fam

**Comment by PgBiel** [comment]
![image](https://cloud.githubusercontent.com/assets/9021226/21267525/dd577914-c391-11e6-9080-76608a002683.png)

4 brackets, not 3.

**Comment by GusCaplan** [comment]
please don't use these issues for these kind of questions, only open them for specific issues found in discord.js

**Comment by Gawdl3y** [comment]
This is not the place for such questions.
